### ISSUE TITLE
Help with publications setup

### ISSUE THREAD

**Issue by felipegb94** [alshedivat/al-folio#1]
Hi,

First of all, thank you very much for this template! It was extremely easy to setup and with basic html and jekyll knowledge it is pretty straightforward to customize.

I am trying to setup my publication template in a similar way as yours (https://www.cs.cmu.edu/~mshediva/publications/). The main thing I am having trouble automating with jekyll scholar is having the publication venue/conference on the left and also having links to the paper  pdf, poster, and abstract. Do you add those links manually? 

Thanks!
Felipe

**Comment by alshedivat** [comment]
Hi! I'm glad you found the template helpful.

The template for the publications page is locate in `_layouts/bib.html`. You can see [here](https://github.com/alshedivat/al-folio/blob/master/_layouts/bib.html#L65-L87) how the links are generated. Basically, you need to add fields such as `pdf`, `arxiv`, etc. to your bib-entries in `_bibliography/papers.bib`. Here is an example of a bib-entry from my homepage:

```bibtex
 @inproceedings{cisse2016adios,
   title={ADIOS: Architectures Deep In Output Space},
   author={Ciss\'e, M. and Al-Shedivat, M. and Bengio, S.},
   abstract={<long text of the abstract>},
   booktitle={Proceedings of The 33rd International Conference on Machine Learning,},
   year={2016},

   abbr={ICML},
   code={https://github.com/alshedivat/adios},
   pdf={adios-icml16.pdf},
   supp={adios-icml16-supp.pdf},
   poster={adios-icml16-poster.pdf},
}
```

As you notice `abbr`, `code, `pdf`, `supp` and `poster` are custom bibtex fields.

**Comment by felipegb94** [comment]
Sweet! That was an easy fix. Thank you very much!
