### ISSUE TITLE
Add Mastodon to social integration

### ISSUE THREAD

**Issue by alpinho** [alshedivat/al-folio#1015]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Integrate a similar feature for Mastodon personal profile as implemented for the other social platforms.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by alpinho** [comment]
I just realized that there is already an issue (#918) opened asking for this feature. The proposed solution in the thread works for me, as well!

**Comment by alshedivat** [comment]
mastodon social link was also added in #974
