### ISSUE TITLE
Blog not detecting new posts

### ISSUE THREAD

**Issue by udion** [alshedivat/al-folio#103]
Hi, 

I recently forked the repo and I am trying to add new blog posts by creating new posts in `_posts/` but it does not get updated in the blog (running it locally haven't deployed it yet). Even if the new post is a copy of an old post with only the date being different, the same thing happens.

Any clues?

**Comment by alshedivat** [comment]
Could you please provide more details for me to be able to diagnose/reproduce the issue?

E.g., you can post here the name and the contents of the file that contains a new post that doesn't get displayed; or you can create a new branch in your fork that reproduces this issue and link it here. Thanks.

**Comment by udion** [comment]
Steps I followed:
- forked this repo
- changed basic information
- updated publications and projects (working)
- created a new post (the content of the post below). The post is named as `post1.md` and is saved under `al-folio/_posts/`
- now when running `bundle exec jekyll serve` I don't see the new post, but I do see all the old posts that came by default.

post1.md
```
ayout: distill
title: yolo like blog
description: 

date: 2020-12-22

authors:
  - name: Uddeshya Upadhyay

bibliography: 2018-12-22-distill.bib

# Below is an example of injecting additional post-specific styles.
# If you use this post as a template, delete this _styles block.
_styles: >
  .fake-img {
    background: #bbb;
    border: 1px solid rgba(0, 0, 0, 0.1);
    box-shadow: 0 0px 4px rgba(0, 0, 0, 0.1);
    margin-bottom: 12px;
  }
  .fake-img p {
    font-family: monospace;
    color: white;
    text-align: left;
    margin: 12px 0;
    text-align: center;
    font-size: 16px;
  }

---

hello.
```

**Comment by alshedivat** [comment]
The name of the file that contains the post must be in the format `yyyy-mm-dd-<post_name>.md`. Also, the date `yyyy-mm-dd` must be either a current or past date, not a future date.

**Comment by udion** [comment]
@alshedivat Yes, I tried that as well earlier (it so happens that it the date in the name and the date inside markdown should match).  Now it's fixed. Thanks for your prompt response!
