### ISSUE TITLE
Build process randomly breaks when building AI-folio site:  request.rb  "path=" bad argument

### ISSUE THREAD

**Issue by NickvashKani** [alshedivat/al-folio#1043]
This has happened twice when I've tried to build a AI-folio site. I am able to build and install fine the first time. I make a few modifications to the _config.yml file, everything seems to go fine. Then I leave the project and when I return and try to build AI-folio again I get the following error message: 

`
Configuration file: /Users/nvk/Google Drive/Websites/personal_website/_config.yml
            Source: /Users/nvk/Google Drive/Websites/personal_website
       Destination: /Users/nvk/Google Drive/Websites/personal_website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
"Fetching external posts from :"
                    ------------------------------------------------
      Jekyll 4.3.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/Users/nvk/.rvm/gems/ruby-3.0.0/gems/httparty-0.20.0/lib/httparty/request.rb:83:in `path=': bad argument (expected URI object or URI string) (ArgumentError)
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/httparty-0.20.0/lib/httparty/request.rb:71:in `initialize'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/httparty-0.20.0/lib/httparty.rb:613:in `new'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/httparty-0.20.0/lib/httparty.rb:613:in `perform_request'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/httparty-0.20.0/lib/httparty.rb:527:in `get'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/httparty-0.20.0/lib/httparty.rb:646:in `get'
	from /Users/nvk/Google Drive/Websites/personal_website/_plugins/external-posts.rb:14:in `block in generate'
	from /Users/nvk/Google Drive/Websites/personal_website/_plugins/external-posts.rb:12:in `each'
	from /Users/nvk/Google Drive/Websites/personal_website/_plugins/external-posts.rb:12:in `generate'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:193:in `block in generate'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:191:in `each'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:191:in `generate'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:79:in `process'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/bin/jekyll:23:in `load'
	from /Users/nvk/.rvm/gems/ruby-3.0.0/bin/jekyll:23:in `<main>'
`

For the life of me I can't figure out what I'm doing wrong. I'm also not versed in Ruby and so I don't know if there is some trick that I'm simply unfamiliar with. Does anyone have any ideas?

**Comment by pourmand1376** [comment]
Hi, This is from your error message. You have to do it unless you would have no information on how to solve this error

> Please append--traceto the build command  for any additional information or backtrace.

**Comment by Schiwo** [comment]
I have the exact same error. Suddenly, the deploy process breaks. Undoing all previous changes does not resolve the problem:

```
2s
4s
13s
9s
0s
2s
Run yes | bash bin/deploy --verbose  --src master --deploy gh-pages
+ shift
+ [[ 4 > 0 ]]
Deploying...
+ key=--src
+ case $key in
+ SRC_BRANCH=master
+ shift
+ shift
+ [[ 2 > 0 ]]
+ key=--deploy
+ case $key in
+ DEPLOY_BRANCH=gh-pages
+ shift
+ shift
+ [[ 0 > 0 ]]
+ set -e
+ echo Deploying...
+ echo 'Source branch: master'
Source branch: master
+ echo 'Deploy branch: gh-pages'
Deploy branch: gh-pages
+ read -r -p 'Do you want to proceed? [y/N] ' response
+ [[ ! y =~ ^([yY][eE][sS]|[yY])+$ ]]
+ git diff-index --quiet HEAD --
++ git ls-files --exclude-standard --others
+ test -z ''
++ git branch
++ tr ' ' '\n'
++ grep master
++ tail -[1](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:1)
+ '[' master ']'
+ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
++ git branch
++ grep gh-pages
+ '[' ']'
+ git checkout -b gh-pages
Switched to a new branch 'gh-pages'
+ export JEKYLL_ENV=production
+ JEKYLL_ENV=production
+ bundle exec jekyll build
Configuration file: /home/runner/work/schiwo.github.io/schiwo.github.io/_config.yml
            Source: /home/runner/work/schiwo.github.io/schiwo.github.io
       Destination: /home/runner/work/schiwo.github.io/schiwo.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
"Fetching external posts from :"
                    ------------------------------------------------
      Jekyll [4](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:5).3.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/httparty-0.20.0/lib/httparty/request.rb:83:in `path=': bad argument (expected URI object or URI string) (ArgumentError)
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/httparty-0.20.0/lib/httparty/request.rb:71:in `initialize'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/httparty-0.20.0/lib/httparty.rb:613:in `new'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/httparty-0.20.0/lib/httparty.rb:613:in `perform_request'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/httparty-0.20.0/lib/httparty.rb:[5](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:6)27:in `get'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/httparty-0.20.0/lib/httparty.rb:[6](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:7)46:in `get'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/_plugins/external-posts.rb:14:in `block in generate'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/_plugins/external-posts.rb:12:in `each'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/_plugins/external-posts.rb:12:in `generate'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:193:in `block in generate'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:191:in `each'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:191:in `generate'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:[7](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:8)9:in `process'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:2[8](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:9):in `process_site'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:[9](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:10)1:in `block in process_with_graceful_fail'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `load'
	from /home/runner/work/schiwo.github.io/schiwo.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli.rb:474:in `exec'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:[12](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:13)7:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.[22](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:23)/libexec/bundle:49:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:37:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:[23](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:24):in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x[64](https://github.com/Schiwo/schiwo.github.io/actions/runs/3782067433/jobs/6429488672#step:6:65)/bin/bundle:23:in `<main>'
yes: standard output: Broken pipe
Error: Process completed with exit code 1.
```

**Comment by pourmand1376** [comment]
Have you set your website url in config.yml correctly?

**Comment by Schiwo** [comment]
I've set it to:
`url: https://schiwo.github.io`

**Comment by Schiwo** [comment]
Alright, I solved the problem.
 I deleted in line 150 of the config file the rss_url.
Resetting it to
` rss_url: https://medium.com/@al-folio/feed`
solves it. It feels like this should be conditional, since I have no idea what medium.com actually is.

**Comment by NickvashKani** [comment]
Yup that was the issue. Thanks to @Schiwo for figuring it out. Jesus, it doesn't seem like that should have been an issue. Can someone with more Ruby/Jekyll knowledge figure out if a fix is doable?

**Comment by NickvashKani** [comment]
OK I figured it out. It's simply that if you include an external source item by saying:
`-name`
then the name and rss_url fields need to be populated. If you want to get rid of this, you need to comment out the whole line instead of leaving the name and rss_url fields empty like so: 
```
  # - name: medium.com
  #   rss_url: https://medium.com/@al-folio/feed
```
To be fair, most people will almost certainly want to get rid of it because if you don't it adds a external blog post to your blog. But I thought leaving the field empty would be fine since there are many other options that you leave empty to ignore. Either way, if anyone else is getting that error, this is the fix.
