### ISSUE TITLE
Medium.com blogposts are not shown after deployment

### ISSUE THREAD

**Issue by bestasoff** [alshedivat/al-folio#1044]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
I've provided the _config.yaml with my medium.com account RSS and when I run the jekyl locally I have my posts shown on the blog page. But after deployment my Blog page is empty. 

**Expected behavior**
My blog posts from Medium are being shown after deployment.

**Screenshots**

**System (please complete the following information):**
 - Browser (and its version) Yandex Browser
 - Jekyll version [e.g. 3.8.7]
- Ruby version [e.g. 2.6.5]

**Additional context**

**Comment by alshedivat** [comment]
thanks for reporting this issue. it looks like the blog page is generated correctly in the `gh-pages` branch (https://github.com/bestasoff/bestasoff.github.io/tree/gh-pages), so I suspect the settings for github pages are misconfigured. please make sure you followed this step:
> Finally, in the **Settings** of your repository, in the **Pages** section, set the branch to `gh-pages` (NOT to `master`).

**Comment by bestasoff** [comment]
@alshedivat Thank you for your response! I'll check it put ASAP.
