### ISSUE TITLE
adding a dark mode toggle button

### ISSUE THREAD

**Issue by ShreshthSaxena** [alshedivat/al-folio#105]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alshedivat** [comment]
I like the idea. If you know any other Jekyll-based themes or websites that have this feature, could you add links? Thanks.

**Comment by ShreshthSaxena** [comment]
yes, as an example check this one: https://github.com/piharpi/jekyll-klise
It has a toggle button on top left

**Comment by Jongwoo-Shim** [comment]
Created a pull request modifying code to add dark mode. Code was also modified to allow for easier changes to theme colors.

**Comment by Jongwoo-Shim** [comment]
Sorry for the inconvenience, moved PR to a different branch : https://github.com/alshedivat/al-folio/pull/119
