### ISSUE TITLE
Math equation display mode does not render

### ISSUE THREAD

**Issue by amir9ume** [alshedivat/al-folio#106]
My github page is working fine. But I was going through the guide section on Equation. And I did the exact same thing as recommended , to put equation in a new paragraph, within $$___ $$. The equation doesn't render properly. 
Even the tutorial example given in the guide doesn't render.
Here is a screenshot. 
![Screenshot 2020-08-15 at 6 39 27 PM](https://user-images.githubusercontent.com/7136378/90322830-1a871380-df27-11ea-93c8-a8a4f150ed7c.png)

Please help

**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Browser (and its version) [e.g. chrome, safari]
 - Jekyll version [e.g. 3.8.7]
- Ruby version [e.g. 2.6.5]

**Additional context**

**Comment by samfearn** [comment]
Hey, it looks like you’re using double dollars to start maths mode *as well* as using the `\(` and `\)` syntax for inline maths mode. Try removing the initial and closing slash parens and see if that fixes the problem.

**Comment by amir9ume** [comment]
Thanks @samfearn , but I found that my error was using $$. When I used $, it worked for me.

**Comment by khojir** [comment]
> Thanks @samfearn , but I found that my error was using $$. When I used $, it worked for me.

Thanks! I have had a similar problem. I'm amazed by how this solution works. To figure out, I have checked this address: [https://alshedivat.github.io/al-folio/blog/2018/distill](https://alshedivat.github.io/al-folio/blog/2018/distill)
The .md files are using $$ and everything works correctly. But I had to use $ instead of $$. It's odd. Possible bug or any other explanation?

**Comment by handorax** [comment]
Hi, I have the same issue. I just cloned the repo, and the KaTeX equations are not rendering. Even the https://alshedivat.github.io/al-folio/blog/2018/distill/ example does not render.

- OS: macOS Cataline
- Browser: Firefox 80.0.1 (64-bit)
- Jekyll version 4.1
- Ruby version 2.7
