### ISSUE TITLE
ERROR: Windows named pipe error: The pipe has been ended. (code: 109)

### ISSUE THREAD

**Issue by kennethahah** [alshedivat/al-folio#1076]
I forked this project to my own repository and cloned it to my local computer running Windows 10 22H2. Then I called "docker-compose up" command to set up it locally. However, the process ended by popping out the error message "ERROR: Windows named pipe error: The pipe has been ended. (code: 109)". 

![image](https://user-images.githubusercontent.com/36859303/210405470-bc62a407-451b-4e69-bc45-be8b250840e6.png)

I can neither start the docker image on Docker Desktop v4.12.0. It will start but then exit immediately.

My Docker Desktop is running on a WSL2 backend with an integration with my default WSL2 distribution, Ubuntu 20.04.5 LTS.

-----------------------------------------------------------------
After rerunning the "docker-compose up" command, I am getting the same error but with a different message.

![image](https://user-images.githubusercontent.com/36859303/210407518-ff1fbeac-2190-4401-997d-c3a1fad782a0.png)

**Comment by pourmand1376** [comment]
The easiest way to solve this issue would be to delete `2021-07-04-diagrams.md`. But, I want to see if this error is resolved with the new release of the docker image. 

Can you change the docker image to `amirpourmand/al-folio:v0.8.0` in `docker-compose.yml` to see if this fixes the problem?

**Comment by kennethahah** [comment]
> The easiest way to solve this issue would be to delete `2021-07-04-diagrams.md`. But, I want to see if this error is resolved with the new release of the docker image.
> 
> Can you change the docker image to `amirpourmand/al-folio:v0.8.0` in `docker-compose.yml` to see if this fixes the problem?

I changed the docker image to `amirpourmand/al-folio:v0.8.0` but got the same error.

So I deleted `2021-07-04-diagrams.md` and things are working well.
