### ISSUE TITLE
how could I generate a static html file? Thanks.

### ISSUE THREAD

**Issue by RenqinCai** [alshedivat/al-folio#108]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alshedivat** [comment]
Follow the installation instructions and run `bundle exec jekyll build`. The static website will appear in the folder `_site`.

Closing this issue. Please use [gitter chat](https://gitter.im/alshedivat/al-folio) for questions of this sort.
