### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by OUCyf** [alshedivat/al-folio#1080]
Greeting,
This is Fu. I got an error when I wanted to install this project using M1-max chip. I failed to install mini_racer, and I have check many approaches but it always failed. My configurations are: 
- gcc-12 (or clang arm64-apple-darwin22.2.0)
- Bundler version 2.4.2
- gem version 3.4.2

Error is:
```
...
/Users/yinfu/gems/gems/bundler-2.4.2/lib/bundler/worker.rb:90:in `block (2
levels) in create_threads'

An error occurred while installing mini_racer (0.6.3), and Bundler
cannot continue.

In Gemfile:
  mini_racer
```

Best,
Fu

**Comment by rohandebsarkar** [comment]
`mini_racer` might not be compatible with Apple chips. Would suggest you to create an issue in the upstream repository: https://github.com/rubyjs/mini_racer

In the mean time you can try using docker to compile your site. [Docker instructions](https://github.com/alshedivat/al-folio#local-setup-using-docker-recommended-on-windows).
