### ISSUE TITLE
Blog posts are not included in the Sitemap.xml 

### ISSUE THREAD

**Issue by amirivojdan** [alshedivat/al-folio#1092]
Hi there, 

First of all, thank you for your awesome work. 

Recently, I was wondering why my blog posts are not indexed in Google Search Console automatically, then I realized that the generated Sitemap.xml does not contain the blog posts I have written. 

Is there any workaround for this issue?

**Comment by rohandebsarkar** [comment]
Are you sure? I just checked it seems the blog posts are being included in the sitemap. For example check the demo site: https://alshedivat.github.io/al-folio/sitemap.xml
