### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by ChildishGiant** [alshedivat/al-folio#1098]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
[deploy action fails](https://github.com/ChildishGiant/childishgiant.github.io/actions/runs/3877664957/jobs/6612944294) with
```
remote: Permission to ChildishGiant/childishgiant.github.io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/ChildishGiant/childishgiant.github.io/': The requested URL returned error: 403
yes: standard output: Broken pipe
```

**To Reproduce**
I just pushed to my repo 🤷🏻‍♀️ 

**Expected behavior**
Should work without permissions issues.

**Comment by ChenChenGith** [comment]
![image](https://user-images.githubusercontent.com/45627234/211541496-39e983d9-05c1-4f90-a9ab-97652c2919be.png)
The same issue. The first time I submit it.

**Comment by rohandebsarkar** [comment]
@ChildishGiant it seems like [the push went through](https://github.com/ChildishGiant/childishgiant.github.io/commits/gh-pages) even that shows an error. Another thing I noticed, you are building your site from `master`. You are supposed to built the GitHub Pages site from the branch `gh-pages`.

**Comment by ChenChenGith** [comment]
@rohandebsarkar Yes, it should build from the gh-pages. The readme says that the branch gh-pages will be automatedly added after the first submit. However, the action failed, so I do not have a gh-pages branch. I have tied to create a new branch gh-pages manually, but it still not work.
![image](https://user-images.githubusercontent.com/45627234/211577936-7e941e24-17e7-4155-a74e-7529996a8b05.png)

**Comment by rohandebsarkar** [comment]
@ChildishGiant @ChenChenGith I think you need to update GitHub actions permissions to allow both read and write to the repository.

**Comment by ChenChenGith** [comment]
@rohandebsarkar How to update the GitHub actions permissions?

**Comment by angusbucknell** [comment]
> @rohandebsarkar How to update the GitHub actions permissions?

Within your repository, go to Settings > Actions > General. At the bottom of the page is the _Workflow permissions_ section, switch it from read to read & write. After saving that, make a small edit to the repository to trigger that automatic deploy action. Then the gh-pages branch.

**Comment by ChildishGiant** [comment]
That's fixed it for me!
