### ISSUE TITLE
Incorrectly handling last names with more than one word

### ISSUE THREAD

**Issue by mvdoc** [alshedivat/al-folio#110]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
Hi, first of all, thanks for making & sharing this awesome theme. I'm excited to use it for my own website.

I think that the changes introduced by #102 do not correctly parse last names with more than one word (like mine, made up by four words). Clearly, there is no general way to automatically parse a name into first, middle, last name in a way that generalizes to all possible names. I would think that adding explicit variables in the config file would solve the issue.

This is the first time I'm using jekyll, but I will address this issue (because I really want to use this theme!). It will take me a while most likely, but I'm happy to submit a PR when I solve it.

**EDIT**

Short example showing the problem. Changing the name in `_config.yml` to "You R. Long Last Name" renders as follows

![image](https://user-images.githubusercontent.com/6150554/91649106-05c97600-ea25-11ea-9eb7-59565d081fae.png)

**Comment by alshedivat** [comment]
Thanks for pointing this out! Agreed, having separate variables for the first and last names (and an optional variable for the middle name) should work much better than parsing. It would be great if you can address this issue. Thanks!
