### ISSUE TITLE
error message on repo page

### ISSUE THREAD

**Issue by sdaza** [alshedivat/al-folio#1109]
Hello, 
I am getting this error on the repo page. It was working days ago. I haven't changed anything. 

<img width="804" alt="repo" src="https://user-images.githubusercontent.com/2096246/212106840-3801d25d-a87d-4848-bd71-5f0e9e0c1888.png">

**Comment by miguelaledesma** [comment]
Can confirm also getting this error on my end. 

![Screen Shot 2023-01-12 at 12 48 08 PM](https://user-images.githubusercontent.com/90358616/212178086-770c23c9-e9cb-4e65-8814-abdfe0bd5c21.png)

**Comment by sdaza** [comment]
It's working now... (?)

**Comment by georgemilosh** [comment]
Same here

**Comment by rohandebsarkar** [comment]
https://github.com/anuraghazra/github-readme-stats/issues/2402#issuecomment-1381819055
