### ISSUE TITLE
[Deployment][gh-pages]Unable to create a website with url: "<username>.github.io" with gh-pages. The default link is always "<username>.github.io/<respository_name>"

### ISSUE THREAD

**Issue by adityajain93** [alshedivat/al-folio#1117]
**Describe the bug**
Due to the current CI/CD integrations with github actions, the website is always deployed from the branch "gh-pages" . This requirement makes the url be of the format "<username>.github.io/<respository_name>" instead of "<username>.github.io"  even if the user wants a Personal website.

**To Reproduce**
1. Follow the steps needed to deploy the website with base_url = "" in the _config.yml file

**Expected behavior**
1. The deployed website would be  "<username>.github.io"

**Screenshots**
<img width="1499" alt="Screen Shot 2023-01-15 at 6 38 21 PM" src="https://user-images.githubusercontent.com/5649466/212586764-880d36ac-9709-40dc-8b52-c30092a7fe31.png">

**System (please complete the following information):**
- Using the docker image as given

**Additional context**

**Comment by wamorkart** [comment]
+1

**Comment by wamorkart** [comment]
@adityajain93 Check the spelling error. 
![image](https://user-images.githubusercontent.com/19406570/213023826-ea3a4a3d-1c11-4dfe-ba37-b64f0bbc2d51.png)

**Comment by adityajain93** [comment]
Thanks, make sense. That worked. Closing the issue
