### ISSUE TITLE
Can't start Docker on Wins

### ISSUE THREAD

**Issue by fenqiling** [alshedivat/al-folio#1120]
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dfenqiwgithubio%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.

Please help me. Thank you!

**Comment by alshedivat** [comment]
are you able to use docker at all for anything else on your system? unfortunately, the error you posted does not have enough information for anyone to understand what's going on let alone reproduce.

**Comment by pourmand1376** [comment]
> error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dfenqiwgithubio%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
> 
> Please help me. Thank you!

It is clear that you haven't started your Docker Engine Successfully. Just open docker desktop then try.
