### ISSUE TITLE
Dark theme does not change the color of text in tables

### ISSUE THREAD

**Issue by aaamini** [alshedivat/al-folio#1134]
It seems that there is a bug perhaps in the Material Bootstrap (?) regarding the dark theme and the color of the text in tables. 

Specifically, the text remains black in tables when changing to dark theme making the text invisible. The setting seems to be in `_tables.scss` which is not included in al-folio. 

Here is what the table looks like before any modifications:

![before](https://user-images.githubusercontent.com/17173393/213937854-6accca62-b575-44f7-9a6d-0ce8532d683b.png)

Here is it is after manually changing the color to `var(--global-text-color);`  in the inspector:

![after](https://user-images.githubusercontent.com/17173393/213937898-beeb1e85-7a98-45f0-9622-55d3ea828fb3.png)

Is it possible to include `_tables.scss` so that this can be fixed?

**Comment by tostenzel** [comment]
I think the same holds for figure captions in the distill style blogposts

**Comment by george-gca** [comment]
Does #1283 fixes this?

**Comment by lancewilhelm** [comment]
The issue appears to lie with how the tables are styled when the page is dark. When dark mode is toggled, the tables are classed as `.table-dark`. However, upon loading of the page, the tables are classed as `.table`. The script `no_defer.js` appears to address this issue for tables upon page load, but it does not class tables in news or cards.

**Comment by george-gca** [comment]
Fixed this in #1424, but there's something bothering me. The background of the dark mode should also be transparent. Currently it is like this:

![image](https://github.com/alshedivat/al-folio/assets/31376482/941eadda-1ce2-4a63-9a25-82d5e7920e70)

while in light mode is like this:

![image](https://github.com/alshedivat/al-folio/assets/31376482/dfa72ea3-8c81-4b66-ab9f-42d49113e95c)

I'll try to fix this in the same branch.
