### ISSUE TITLE
build fail error with bibliography

### ISSUE THREAD

**Issue by kenkyusha** [alshedivat/al-folio#1140]
I tried to set up my own publications with bib file and etc, however saw that it did not work and the github build failed related to the bibliography tag.

https://github.com/kenkyusha/kenkyusha.github.io/actions/runs/4018037216/jobs/6903150436#step:4:36488

I ended up completely removing the jekyll scholar and bib functionality in the following commits and got it building:
https://github.com/kenkyusha/kenkyusha.github.io/commit/6af9017b00751f7b8696aa12bd5d0579111b3ed1
https://github.com/kenkyusha/kenkyusha.github.io/commit/e6c0a43469bcd24d09573d3fbf77178f55a3cd64
https://github.com/kenkyusha/kenkyusha.github.io/commit/303f1c4fa981bad32626b0ffb994bb43d9973a00
https://github.com/kenkyusha/kenkyusha.github.io/commit/3549bec3cee2402814fd99cb0f310114248bf6fa
https://github.com/kenkyusha/kenkyusha.github.io/commit/1a9a0f87eb4a97d71db3b149e645d1ce43bc0c39

Anyone else had this error or suggestions how to work with it? 
Locally the bib and publication thing just ran fine.

**Comment by mzh045** [comment]
I had exactly the same problem as you last week.
As stated in [CLAMS](https://checlams.github.io/blog/2022/deploytutorial/) and many issues, the error `Unknown tag 'bibliography'` inevitably occurs in automatic deployment, due to the conflict between the security setting of Github and `plugins: jekyll/scholar`.

It seems that manual deployment is the only solution:
```bash
$ ./bin/deploy
```
Use the `master` branch for the source code and deploys the webpage to `gh-pages`.

**Comment by ColeFeely6** [comment]
I remember I removed a bunch of the bibliography stuff that had dependencies

**Comment by mzh045** [comment]
If your website still use the plugin `plugins: jekyll/scholar`, its automatic deployment would be reject by Github.

**Comment by kenkyusha** [comment]
> I had exactly the same problem as you last week. As stated in [CLAMS](https://checlams.github.io/blog/2022/deploytutorial/) and many issues, the error `Unknown tag 'bibliography'` inevitably occurs in automatic deployment, due to the conflict between the security setting of Github and `plugins: jekyll/scholar`.
> 
> It seems that manual deployment is the only solution:
> 
> ```shell
> $ ./bin/deploy
> ```
> 
> Use the `master` branch for the source code and deploys the webpage to `gh-pages`.

as he mentioned, read the blog post, it explains quite well.
Myself, I will not do it but, closing the topic for now.

**Comment by ShaYito** [comment]
The batch file works only on linux, how to deal with this on Windows?
