### ISSUE TITLE
OSF profile social integration

### ISSUE THREAD

**Issue by annadoesscience** [alshedivat/al-folio#1158]
**Is your feature request related to a problem? Please describe.**
The current version of the al-folio does not support social integration of one's [OSF](https://osf.io/) profile. 

**Describe the solution you'd like**
Would there be a possibility of adding it, so it is as easy to configure as e.g., social integration of Twitter or LinkedIn?

**Describe alternatives you've considered**
One could probably add an OSF link manually. However, having a useful social integration config would be way better. 

**Additional context**
A link to someone's profile looks like this: https://osf.io/ezhqp/; the "ezhqp" could be the input in the al-folio social integration.

**Comment by annadoesscience** [comment]
@buerviper Hi, thank you a lot, it worked! :D Just one comment: in _includes/social.html in line 23 you have a typo - a single / instead of //. 

Best,

Anna

**Comment by buerviper** [comment]
@annadoesscience This should be fixed now.
