### ISSUE TITLE
Have preview and abbr in bibtex

### ISSUE THREAD

**Issue by dyumanaditya** [alshedivat/al-folio#1162]
**Is your feature request related to a problem? Please describe.**
I'm not able to display the venue `abbr` on the left of the publication when I have a `preview` in my papers.bib file.

**Describe the solution you'd like**
is there a way to display both the preview AND the venue??

**Comment by CheariX** [comment]
I think, you could change `elsif` to a simple `if` here:  https://github.com/alshedivat/al-folio/blob/9b14e422a3502178db0b75968c0a78e82901b20d/_layouts/bib.html#L16

**Comment by theodumont** [comment]
As mentioned by @CheariX, a workaround for now could be to slightly change the code in `_layouts/bib.html`, starting from `line 5`:
```html
        <div class="col-sm-2">
            {%- if entry.abbr -%}
            <div class="abbr">
                {%- if site.data.venues[entry.abbr] -%}
                {%- assign venue_style = nil -%}
                {%- if site.data.venues[entry.abbr].color != blank -%}
                {%- assign venue_style = site.data.venues[entry.abbr].color | prepend: 'style="background-color:' | append: '"' -%}
                {%- endif -%}
                <abbr class="badge" {% if venue_style %}{{venue_style}}{% endif %}><a href="{{site.data.venues[entry.abbr].url}}">{{entry.abbr}}</a></abbr>
                {%- else -%}
                <abbr class="badge">{{entry.abbr}}</abbr>
                {%- endif -%}
            </div>
            {%- endif -%}
            {%- if entry.preview -%}
            <div class="preview">
                {% if entry.preview contains '://' -%}
                <img class="preview z-depth-1 rounded" src="{{ entry.preview }}">
                {%- else -%}
                {%- assign entry_path = entry.preview | prepend: '/assets/img/publication_preview/' -%}
                {% include figure.html
                path=entry_path
                class="preview z-depth-1 rounded"
                alt=entry.preview -%}
                {%- endif -%}
            </div>
            {%- endif -%}
        </div>
```
May not be the cleanest way but seems to work.

**Comment by dyumanaditya** [comment]
Thanks! That worked

**Comment by CheariX** [comment]
I do not understand, why having both, `abbr` and `preview`, isn't possible in the current `bib.liquid`.
If anyone only wants one of them, the bibtex entry can be configured for this purpose.
In contrast, if anyone wants to use both of them, it is not possible (without changing the template).

Since `abbr` and `preview` are al-folio specific keys, or at least I don't know if they are used somewhere else, it would be easily controlable via the bibtex entry.

Therefore, I would suggest to allow both side by side in `bib.liquid`.
If this is okay, I can send a PR.

**Comment by george-gca** [comment]
It is fine for me, but how would this look like? Showing them side by side wouldn't break the layout too much?

**Comment by CheariX** [comment]
My suggestion would be to stack them. I used this on my own website ([example](https://christianmainka.de/publications/rank-s)).

If you like this stacking, I can send a PR.

**Comment by CheariX** [comment]
I think I *once* had *some* reason to put it this way, but I do not rember since it was a long time ago.

I can send a PR for this (with your proposed order).

**Comment by broadcreate** [comment]
The image displayed on small screen such as phone isn't correct.
