### ISSUE TITLE
Can't open any page after deploying the webpage but works fine locally

### ISSUE THREAD

**Issue by fenqiling** [alshedivat/al-folio#1163]
I'm not sure what I didn't wrong but I have followed all the steps and it works totally fine locally. Could you please help me identify the issue? The path seems very odd and the pictures are not loading. Thank you!

https://fenqiling.github.io/fenqiw.github.io/

**Comment by george-gca** [comment]
How are set the values of `url` and `baseurl` in your `_config.yml`?

If you set them like this:
```yaml
url: https://fenqiling.github.io # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
```

it should work like this: https://fenqiling.github.io/

**Comment by fenqiling** [comment]
Hi George,

Thank you for your quick reply! I followed your comment and changed it as you suggested and it works now. However, I can't open all other pages and it looks different from what I built locally.

Do you have any suggestions?

**Comment by george-gca** [comment]
What else have you changed from the original code? I recommend you do a diff between your code and the original, and see what else have you changed. Just did a new run with the al-folio, and everything worked fine, both local and online.

**Comment by fenqiling** [comment]
Should I fork the repo rather than copy it? I'm wondering if this is the cause.

**Comment by george-gca** [comment]
Either way should work. I previously did it with a fork, now I am creating from the template. Just tried your site, and everything seems to be working.

**Comment by fenqiling** [comment]
Thank you. I forked the repo and found that I added too many packages in the Gemfile, which caused the problem. It's working now. Thank you!
