### ISSUE TITLE
Error: Process completed with exit code 128.

### ISSUE THREAD

**Issue by timpurackal** [alshedivat/al-folio#1169]
I tried manual deployment but had repeated errors while doing "Bundle exec", I followed almost all steps mention in a discuccion but none of them was effective. So I took the automatic deployment process but even there issue seems to arise Pasting the errors below.:

+ git push -f -q origin gh-pages
remote: Permission to timpurackal/timsabu.github.io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/timpurackal/timsabu.github.io/': The requested URL returned error: 403
yes: standard output: Broken pipe
Error: Process completed with exit code 128.

**Comment by junchaoshi** [comment]
Get the same exit code 128. Folked the original template and only set the url to https://<your-github-username>.github.io and leave baseurl empty In _config.yml.
During the auto-deploy process, the error occurred at the "Deploy website" step and the log file is attached. 

[6_Deploy website.txt](https://github.com/alshedivat/al-folio/files/10704247/6_Deploy.website.txt)

**Comment by junchaoshi** [comment]
@timpurackal hi I solve the problem with two steps, at least it works for me.

1. Setting -> actions -> General -> Workflow permissions -> select 'Read and Write permissions' button.
2. After the auto-deploy, then the gh-pages branch will appear. Setting -> Pages -> Branch -> select 'gh-pages' in the Drop-down menu.

**Comment by george-gca** [comment]
As soon as you use this template and follow the [deployment](https://github.com/alshedivat/al-folio#deployment) instructions, the website should work just fine in your `username.github.io`. Have you tried this without further modifications?
