### ISSUE TITLE
Project cards grid

### ISSUE THREAD

**Issue by abojchevski** [alshedivat/al-folio#117]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
The list of projects are rendered vertically, with one project per row, even though there is plenty of room remaining.
The behavior persist across different browsers and window sizes. 

**To Reproduce**
1. Go to https://alshedivat.github.io/al-folio/projects/
2. See error

**Expected behavior**
Multiple project cards are shown per row.

**Screenshots**
![image](https://user-images.githubusercontent.com/8150330/94341378-1d3a5580-0009-11eb-9d67-9405cd7df66a.png)

**System (please complete the following information):**
 - OS: Windows 10, Ubuntu 20.04
 - Browser: Chrome Version 85.0.4183.121, Brave Version 1.14.84 Chromium: 85.0.4183.121, Firefox 81.0

**Comment by alshedivat** [comment]
Thanks for reporting. Must be fixed now.
