### ISSUE TITLE
Bugs in automated deployment

### ISSUE THREAD

**Issue by IntelligentInteractiveLab** [alshedivat/al-folio#1191]
**Acknowledge the following**
- [√] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [√ ] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [√] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
When I try to push my code to have GitHub deploy automatically, it tells me the following error message：
```
remote: Permission to IntelligentInteractiveLab/intelligentinteractivelab.github.io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/IntelligentInteractiveLab/intelligentinteractivelab.github.io/': The requested URL returned error: 403
yes: standard output: Broken pipe
Error: Process completed with exit code 128.

```
In addition, I added the Fix permission code to deploy.yml using the YouTube tutorial video you provided：

```
    - name: Fix Permission
      run: |
        chmod a+x bin/*
        git commit -am "add execute permission to bin/deploy"
```
But the error message became：

```
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
Error: Process completed with exit code 1.
```
When I delete the following code in fix permission：

```
 git commit -am "add execute permission to bin/deploy"
```
The error message says I need to complete the commit before deployment：
```
Please commit the changes before proceeding.
Aborting.
yes: standard output: Broken pipe
Error: Process completed with exit code 1.
```
This phenomenon confused me and I wondered how to fix it. Thanks.

Note: I can implement website deployment with manual deployment, only add Fix permission for the first time during manual deployment, and delete Fixpermission in subsequent manual deployments. But this is significantly less convenient than automated deployment.

**Expected behavior**

I was wondering how to fix this confusing bug ！！！

**Comment by ColeFeely6** [comment]
I believe you have to look at the permissions in settings. I may have ran into this issue when first starting, try this out. Look up your error # and github pages and see if you find anything else https://github.com/JamesIves/github-pages-deploy-action/issues/1110

**Comment by IntelligentInteractiveLab** [comment]
Well, maybe I ignore that.But for now, I have solved this issue. Thanks!
