### ISSUE TITLE
"Related Publications" list for posts/pages in style of bibliography

### ISSUE THREAD

**Issue by buerviper** [alshedivat/al-folio#1193]
**Is your feature request related to a problem? Please describe.**
Posts or pages (like project pages) should have an easy way to show related publications in the same style as in the bibliography list. For instance, if I write a small blog post about my newest publication or upcoming talk, I would like to have the relevant publication(s) easily addable to the post. Similarly, if I have a project page, I would like to have an easy way to add publications to the respective project.

**Describe the solution you'd like**
Issue #684 tried to implement this (somehow) by adding an attribute to the bib file. The user said it did not work on multiple pages/projects, and the issue never got resolved afaik. Also, I think changing something on the bib file is a lot of manual work (especially if you export a new bib file and have to categorize each and every item first).

I think an easier way would be to add the respective publication(s) to the header of a post file, e.g.
```
---
layout: post
title:  a post with related publication  
date: 2015-05-15 21:01:00
related_publications: einstein1956investigations, einstein1950meaning, einstein1905movement
---
```

The post would then show the three mentioned publications at the end of the file in the same style as in the bibliography.

**Describe alternatives you've considered**

You can add references separately, however, they are then formatted in a standard citation style, not in the style of the bibliography. I did this for instance for this project page: https://buerviper.github.io/projects/self-healing by manually adding
```
1. {% reference ahner_self-healing_2015 %}
2. {% reference ahner_thermally_2016 %}
etc.
```

at the end. I don't think this solution is ideal.

**Comment by buerviper** [comment]
I played around with it a bit. Manually, I could insert it like

```
## related publications
<div class="publications">
  {% bibliography -f papers -q @*[key=einstein1956investigations]* %}
  {% bibliography -f papers -q @*[key=einstein1950meaning]* %}
</div>
```
at the end of my blogposts which would be what I want. I couldn't input something like "page.related_publications" instead of the key, so I don't know if an "automated" solution would even work with Jekyll scholar?

**Comment by george-gca** [comment]
I believe this way works. Would you mind sending a PR with this @buerviper?

**Comment by buerviper** [comment]
I still think some kind of semi-automated way would work better, I'll see if I can work something out and, if not, would just add this bit on related publications to one of the sample posts of the template.

**Comment by shiranD** [comment]
The solution described by both having a related link as well as pointing to it through {% reference ahner_self-healing_2015 %} for instance worked well for me but I still have questions. 1) What if I'd like to refer to a paper I did not take part of (or does not appear on my papers.bib). My second question is 2) how can I can the citation style work similar to https://buerviper.github.io/projects/self-healing repo? Mine shows a long string concatenating the fields of bib. Finally, 3) even though I have in _confing.yaml scholar: first and scholar: last names written in square brackets it still does not highlight them as suggested. Happy for any solution to any of these questions. Shiran

**Comment by george-gca** [comment]
Since this issue is already closed and there are a lot of questions, these are better asked at the [Q&A section](https://github.com/alshedivat/al-folio/discussions/new?category=q-a).
