### ISSUE TITLE
My website shows no updates even though the .html source files have changed 

### ISSUE THREAD

**Issue by yxwangnju** [alshedivat/al-folio#1204]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
My website shows no updates even though the .html source files have changed in the repo. I checked the commit log and found in the `gh-pages` branch the comment of my commit has a `[ci skip]` side note. But I did not include "[ci skip]" in the comment in my `master` branch when committing and pushing.

I enabled the automatic deployment. So I just made changes in the `master` branch and pushed it. 

![image](https://user-images.githubusercontent.com/38092796/220658573-5f14d533-be26-456d-bedc-1f913c2583b6.png)

**System (please complete the following information):**
 - OS: Windows 11
 - Chrome Version 110.0.5481.104

This is my workflow file when deploying:
```
name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
    - name: Enable bundler cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install deps
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        npm install -g mermaid.cli
    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "::set-output name=SRC_BRANCH::${GITHUB_HEAD_REF}"
          echo "::set-output name=NO_PUSH::--no-push"
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "::set-output name=SRC_BRANCH::${GITHUB_REF#refs/heads/}"
        fi
        echo "::set-output name=DEPLOY_BRANCH::gh-pages"
    - name: Deploy website 
      run:  yes | bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }}
                    --src ${{ steps.setup.outputs.SRC_BRANCH }} 
                    --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }} 
```

**Comment by wr0124** [comment]
same here...

**Comment by george-gca** [comment]
Does your website work locally? Is the problem only when uploading to Github?

**Comment by wr0124** [comment]
Except for the publications section, the rest of the website works well
locally. I followed the standard procedure of git add/commit/push, and all
the files on GitHub are fully updated with the local folder.

**Comment by george-gca** [comment]
I mean, does it update when running locally? For example, [running like this](https://george-gca.github.io/blog/2022/running-local-al-folio/)?

If you followed everything in the [deployment](https://github.com/wr0124/wr0124.github.io#deployment) section, everything should work fine. I would recommend making small changes, one at a time, before commiting. This way, it is easier to find out where it breaks. Start by just changing the address in `_config.yml` to see if it is able to upload the template site to your github.io address.

**Comment by wr0124** [comment]
thanks for the help!

**Comment by casualcomputer** [comment]
I also ran into the same issue. OP is saying that the gh-pages branch won't get updated even though the master branch contains the correct index.html's. While one would expect that deploy.yml (after execution) automatically copies the most up-to-date codes from the master branch to the gh-pages branch, the reality is that gh-pages branch never gets updated after pushing new codes into master.

**Comment by george-gca** [comment]
Have you followed the section `To enable automatic deployment` in README carefully?
