### ISSUE TITLE
Github can't satisfy your Gemfile dependencies

### ISSUE THREAD

**Issue by huzama** [alshedivat/al-folio#1208]
I am trying to deploy this website which works fine on my computer. However, when I use GitHub pages it shows me a warning first in the *build with Jekyll section* and then an error which is shown below.

**Logs**:
...
...
10. Warning:  github-pages can't satisfy your Gemfile's dependencies.
...
...
...
...
25824. Globbed Scope Path: assets/bibliography/2018-12-22-distill.bib
25825.          Rendering: _posts/2020-09-28-twitter.md
25826.   Pre-Render Hooks: _posts/2020-09-28-twitter.md
25827.   Rendering Liquid: _posts/2020-09-28-twitter.md
25828. github-pages 228 | Error:  Liquid syntax error (line 5): Unknown tag 'twitter'

**Comment by yjw113080** [comment]
I'm experiencing the same issue

**Comment by Helenlam20** [comment]
> 5. Finally, in the Settings of your repository, in the Pages section, set the branch to gh-pages (NOT to master). For more details, see [Configuring a publishing source for your GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source).

I think you forgot step 5 of  "To enable automatic deployment".

**Comment by huzama** [comment]
I solved the problem by updating the GemFile to comment "gem 'mini_racer'" and then using step 5 of "To enable automatic deployment."

**Comment by labibvaiblog** [comment]
I am facing the same step. Can you tell me more details and in-point steps to solve this issue?

**Comment by Helenlam20** [comment]
I had the same problem but solved it by doing step 5 of "To enable automatic deployment" written in the README. You have to go to settings of your repo and set the branch to gh-pages in the Pages section.

**Comment by berteodosio** [comment]
Can confirm. Following Step 5 and ensuring Github Actions had the appropriate permissions (according to README.md) worked for me.

**Comment by tmcybers** [comment]
> I had the same problem but solved it by doing step 5 of "To enable automatic deployment" written in the README. You have to go to settings of your repo and set the branch to gh-pages in the Pages section. 

It works, thanks helen

**Comment by tmcybers** [comment]
> Can confirm. Following Step 5 and ensuring Github Actions had the appropriate permissions (according to README.md) worked for me.

Thanks that it, now all works.

**Comment by Pats-Chen** [comment]
I had the same problem just now and I solved it by folllowing step 5. Thank you @Helenlam20 !

**Comment by mokasha2020** [comment]
I am still having this issue. I am deploying from a branch according to step 5 in the Github help link "Under "Build and deployment", under "Source", select Deploy from a branch." I commented out gem 'mini_racer' but still having the same issue.

**Comment by mokasha2020** [comment]
It turned out that I was getting an error in project1.md  Error: could not read file /github/workspace/_projects/1_project.md: invalid byte sequence in UTF-8. It seems that i had a character that the interpreter didn't like so I deleted it and i was able to build and deploy. The "Github can't satisfy your Gemfile dependencies" is only a warning and while it's still there it didn't stop me from building and deploying.

**Comment by genie360s** [comment]
> I had the same problem but solved it by doing step 5 of "To enable automatic deployment" written in the README. You have to go to settings of your repo and set the branch to gh-pages in the Pages section.

I can't find the gh-pages branch ?

**Comment by genie360s** [comment]
I am sorry , If I complete step 5 , I automatically enable automatic deployment ?

**Comment by leopoldHuang** [comment]
> I had the same problem but solved it by doing step 5 of "To enable automatic deployment" written in the README. You have to go to settings of your repo and set the branch to gh-pages in the Pages section.

Sorry, but what is step 5 excectly? Can you give me the url of the README.md cuz I don't know where it is. Thank you very much.

**Comment by george-gca** [comment]
The README file changed a lot since then. To check our README simply go to the main page of our repository.

**Comment by leopoldHuang** [comment]
这是来自黄烈的自动回复邮件。没别的意思，就是告诉你你的邮件爷收到了~

**Comment by leopoldHuang** [comment]
> The README file changed a lot since then. To check our README simply go to the main page of our repository.

THANKS!! I 've found what I need in the new markdown files!

**Comment by LeoPtls** [comment]
I am not able to find gh-pages because the step 4 fails for me with this issue : 
I am not able to find what I need in the read me
![image](https://github.com/user-attachments/assets/d6967685-f2b7-47c3-8dc5-e519ca043af7)

**Comment by george-gca** [comment]
@LeoPtls what changes have you made to your repo? Have you made only the bare minimum to the `_config.yml`?

**Comment by LeoPtls** [comment]
I manage to make it work when I do "use template" and copy all the branch
Thanks for the prompt reply

**Comment by george-gca** [comment]
You should not copy all the branches. The only branch needed is the `master` branch. The other needed branch `gh-pages` is created automatically if you do all the minimum steps right.
