### ISSUE TITLE
Putting colon in title of the blog's post

### ISSUE THREAD

**Issue by khojir** [alshedivat/al-folio#124]
Hi,
In the title of the blog's post, I wanted to put a colon. For example, I want to put do something like this:

layout: post
title: Book: An introduction to human history

But when do it, the blog doesn't show the title at all.

Thanks.

**Comment by alshedivat** [comment]
@khojir, you should be able to do that by putting the title inside quotation marks like this:
```
layout: post
title: "Book: An introduction to human history"
```
Let me know here if that doesn't work.
