### ISSUE TITLE
Inline $\LaTeX$ in blog post title renders as display

### ISSUE THREAD

**Issue by ma-sadeghi** [alshedivat/al-folio#1252]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Inline LaTeX renders as display when used in blog post `title`.

**To Reproduce**
Make a blog post file whose title contains an inline latex, e.g.:
```md
...
title: $$\tau$$ is a greek letter
...
```

**Expected behavior**
The LaTeX in the title should render as inline.

**Screenshots**
![image](https://user-images.githubusercontent.com/14086031/224392917-e42bb416-f4a1-4f47-847f-37314f869baa.png)

**System (please complete the following information):**
 - OS: Ubuntun 20.04
 - Browser: Chrome Version 110.0.5481.177 (Official Build) (64-bit)
 - Jekyll version: 4.3.2
- Ruby version: 3.2.1

**Comment by ardianumam** [comment]
Hi,

I try to use an inline latex inside `<div>` block, but it is rendered as a display formula instead of an inline formula. For example, please see below:
```
<div style="text-align: center;">
This is my formula $$a=b+c$$
</div>
```
The above formula is rendered as a display. Any direction to make such a formula to be inline? 
Thanks!
