### ISSUE TITLE
How to move the social icons below the profile image?

### ISSUE THREAD

**Issue by jjiantong** [alshedivat/al-folio#1254]
Hi. Thanks for your wonderful work!

I am just wondering if I can move the social icons (i.e., email, google scholar, etc.) just below the profile image. If so, could you provide some instructions to me on how I can do this? 

BTW, where can I change the size (or may be the percentage?) of the profile image? I just want to let the profile image a little small.

Thanks in advance.

**Comment by jamesdemon923** [comment]
Hello, how did you implement this feature? Thanks!

**Comment by jjiantong** [comment]
> Hello, how did you implement this feature? Thanks!

Hello. You can find the code block from `/_layouts/about.html`:
```
          <!-- Social -->
          {%- if page.social %}
            <div class="social">
              <div class="contact-icons">
                {% include social.html %}
              </div>

              <div class="contact-note">
                {{ site.contact_note }}
              </div>

            </div>
          {%- endif %}
```
Trying to move it below the end of the `if page.profile.address` block within the `<div class="profile">` container should work. The modified code should look like this:
```
          <div class="profile float-{%- if page.profile.align == 'left' -%}left{%- else -%}right{%- endif -%}">
            ......
            {%- if page.profile.address %}
            <div class="address">
              {{ page.profile.address }}
            </div>
            {%- endif %}
            <!-- Social -->
            {%- if page.social %}
            <div class="social">
              <div class="contact-icons">
                {% include social.html %}
              </div>
            </div>
            {%- endif %}
          </div>
```

**Comment by jjiantong** [comment]
Regarding the size of the profile image, you can change it on line 142 on `/_sass/_base.scss` by changing the percentage of the width.

I hope this helps!

**Comment by jamesdemon923** [comment]
Thanks so much!
