### ISSUE TITLE
Add a `Copy` button to code blocks

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#1262]
**Is your feature request related to a problem? Please describe.**
It would be really useful to have a Copy button appear in code blocks (preferably only when on hover).

**Describe the solution you'd like**
When hovering a code block, it should display a Copy button, and when clicking copy the code block's contents.

**Describe alternatives you've considered**

**Additional context**
The style of the copy button displayed [in this blog post](https://www.neoslash.net/blog/jekyllcopy) is interesting, although IDK if this is accessible. Found [this](https://fontawesome.com/icons/clipboard?s=light&f=classic) and [this](https://fontawesome.com/icons/clipboard-check?s=light&f=classic) icons that could be used for displaying. Also [this post](https://www.aleksandrhovhannisyan.com/blog/how-to-add-a-copy-to-clipboard-button-to-your-jekyll-blog/) has a really easy to implement solution, but the author did not made available the complete css it used.
Started to implement this using the code from this last post, but failed to position the button correctly (I struggled a lot with css customization), but the javascript works.

**Comment by tostenzel** [comment]
I would love that feature, too!

**Comment by alshedivat** [comment]
implemented in #1267
