### ISSUE TITLE
Mobile profile picture size

### ISSUE THREAD

**Issue by jdtorres96** [alshedivat/al-folio#127]
Hi, thank you for the awesome theme.

I am struggling with the profile picture in the mobile version of my website since it covers the whole screen and then shows the description. In contrast, the demo version seems to crop the profile picture to the right, side to side with the description.

**Comment by alshedivat** [comment]
Hi @jdtorres96, I'm not sure I understand the question/issue. Could you take a screenshot and explain the desired behavior vs what you get?

**Comment by jdtorres96** [comment]
Hi @alshedivat, thank you for replying.
Here are some links to screenshots of what I get in the mobile version of my website,

![IMG_1011](https://user-images.githubusercontent.com/44235561/95928889-2c9afc00-0d88-11eb-9495-85213f2cbe47.PNG)
![IMG_1010](https://user-images.githubusercontent.com/44235561/95928900-30c71980-0d88-11eb-84be-ad73b44ff4c3.PNG)

I guess I would like something like this, where the profile picture is small and placed next to the text.

![Captura de Pantalla 2020-10-13 a la(s) 7 13 49 p  m](https://user-images.githubusercontent.com/44235561/95928993-6f5cd400-0d88-11eb-8e7c-835f72f69dde.png)

**Comment by alshedivat** [comment]
The mock image you posted above (on an iPhone) displays a non-mobile version of the website, hence the difference. The mobile version has the profile picture in full width (this is the default behavior). You can change that by directly adjusting the CSS styles on your webpage: https://github.com/alshedivat/al-folio/blob/master/_sass/_base.scss#L43

**Comment by jdtorres96** [comment]
Thank you, worked fine!
