### ISSUE TITLE
Harmonize Dimensions and Altmetric Badges

### ISSUE THREAD

**Issue by razvanazamfirei** [alshedivat/al-folio#1281]
**Is your feature request related to a problem? Please describe.**

Dimensions and Altmetric badges do not align properly and are of visibly different style.

<img width="650" src="https://user-images.githubusercontent.com/7987698/226492817-0e3d93b9-6d2a-451d-852a-33554122ea4c.png">

**Describe the solution you'd like**

Use round Dimensions and Altmetric badges.  

<img width="650" src="https://user-images.githubusercontent.com/7987698/226493111-efe3f129-326f-4968-8310-38179e89b4d6.png">

**Describe alternatives you've considered**

This badge combination is the most consistent in its appearance. An alternative could be aligning the rectangle badges, but they color and resolution of the text remains different.

**Comment by george-gca** [comment]
I believe it would be better to add this as a param in `_config.yml`. Also, even though the rectangular badges do not align perfectly with the other buttons, it makes visually more sense to use them this way than the large icon.

Imagine this, a relatively big list of published papers, all with altmetric and dimensions badges. The large icons would be too much on this screen.
