### ISSUE TITLE
custom domain becomes blank after each deploy

### ISSUE THREAD

**Issue by eamanj** [alshedivat/al-folio#130]
I am using the theme to host my page on a custom domain. So the custom domain redirects to the github page. However, every time I deploy, my custom domain setting under github pages becomes empty and I have to reset it back to my domain (see image).

I thought I have to set some fields in the _config file, but nothing seemed to retain the custom domain name.
Thank you for the great work!

<img width="717" alt="Screen Shot 2020-10-12 at 12 51 52 PM" src="https://user-images.githubusercontent.com/7664300/95784042-0f3f3280-0ca1-11eb-8a27-d9fe200fa754.png">

**Comment by cdancette** [comment]
I had the same issue. You have to add the CNAME file to your master branch (check in your gh-pages branch to see its content).

By default when you add a custom domain, github adds the CNAME file to your gh-pages branch, which gets overwritten by the build from your master branch).

**Comment by kbrown** [comment]
e.g,. cat CNAME 
foo.com

**Comment by rsonger** [comment]
Hi, thanks for the awesome work.

I realize this is a closed issue, but I noticed that the deploy action located in `bin/deploy` appears to be actively deleting CNAME files after the Jekyll build. Could this be adversely effecting custom domain settings on GitHub.com?

I can confirm that committing a CNAME file to `master` on the remote repository will keep the custom domain, but I wonder if it's necessary for the deploy action to be actively deleting the CNAME files.

**Comment by rsonger** [comment]
Hi, thanks for the awesome work.

I realize this is a closed issue, but I noticed that the deploy action located in `bin/deploy` appears to be actively deleting CNAME files after the Jekyll build. Could this be adversely effecting custom domain settings on GitHub.com?

I can confirm that committing a CNAME file to `master` on the remote repository will keep the custom domain, but I wonder if it's necessary for the deploy action to be actively deleting the CNAME files.

**Comment by Fullchee** [comment]
@rsonger I'm getting the same thing

In my `ci.yml` I had `mkdocs gh-deploy --force` which removed the `CNAME` that GitHub added
