### ISSUE TITLE
Distill: support for details tag (collapsible boxes)

### ISSUE THREAD

**Issue by gaspardbb** [alshedivat/al-folio#1308]
# Details tag with Distill template 
I came upon [ejmastnak](https://www.ejmastnak.com/tutorials/vim-latex/intro/) blog and I really liked how the they use collapsible boxes to hide unnecessary details to the user. Basically, it consists of:
```html
<details> 
<summary> Title of the collapsible box </summary>
Some details
</details>
```
This is not supported in the theme's Distill template (no box, no dark theme, no markdown rendering). 

# Possible solution

What I did:

* **Formatting**: I edited `_sass/_distill.scss` to match roughly a code block in distill, which gives support for dark theme. 

* **Rendering markdown**: I used [this blog post](http://movb.de/jekyll-details-support.html) to create a plugin which makes Jekyll aware of `details` tag. 

## Example 

For instance, with the distill template this gives: 

```
## Example of detail box.

Some **markdown** content.

{% details Click here to know more %}
Additional details, correct math $$ 2x - 1 $$ and code `is rendered correctly`.
{% enddetails %}
```

this rendering 

![details-distill-example](https://user-images.githubusercontent.com/40466739/229139877-c5c79411-4aef-4621-b232-f0b22f1f61f7.gif)

## Limitations 

* Footnotes at the end of the details section are not rendered well (but I think that Distill's footnote would gain from being turned into Jekyll's plugins?)
* Would be nice to remove the details content from the "estimated reading time" of the blog's page 

I can submit a PR if you want with those modifications, with the caveat that I know next to nothing of CSS, ruby and Jekyll inner mechanics 🙂

**Comment by kjabon** [comment]
I am but a humble al-folio user, but I would find this incredibly useful, as I just searched for this exact functionality and came upon this issue. +1 to adding this! (And if it gets rejected, maybe share the code? :wink:)

**Comment by gaspardbb** [comment]
Sure! I opened a PR at #1321 . You can easily get the code from there for your own use in the meantime 🙂

**Comment by gaspardbb** [comment]
Thanks for accepting the PR! Glad it could be useful!
