### ISSUE TITLE
Metadata stays unchanged

### ISSUE THREAD

**Issue by zemanpeter** [alshedivat/al-folio#1317]
Hello,

I have an issue with changing meta-data. I changed the `description` in the `_config.yml` file to a different text. But when I copy the link to my website and paste it to some messenger, for example, I still get this original text that was there:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/1975496/230385569-943c1f6f-d61a-4ed8-a872-d1d23c376105.png">

Probably this has some easy solution, I am just no very well experienced with this framework.

Thank you.

**Comment by jmrplens** [comment]
You need to update the cache of the server where this preview has been generated. The description is updated correctly.

You can see it here: https://www.opengraph.xyz/url/https%3A%2F%2Fzemanpeter.github.io
