### ISSUE TITLE
Doesn't work. Cannot make website.

### ISSUE THREAD

**Issue by yajanbasel** [alshedivat/al-folio#1326]
Followed these Steps, Doesn't work:

For personal and organization webpages:

The name of your repository MUST BE <your-github-username>.github.io or <your-github-orgname>.github.io.
In _config.yml, set url to https://<your-github-username>.github.io and leave baseurl empty.
Set up automatic deployment of your webpage (see instructions below).
Make changes, commit, and push!
After deployment, the webpage will become available at <your-github-username>.github.io.

To enable automatic deployment:

Click on Actions tab and Enable GitHub Actions; do not worry about creating any workflows as everything has already been set for you.
Go to Settings -> Actions -> General -> Workflow permissions, and give Read and write permissions to GitHub Actions
Make any other changes to your webpage, commit, and push. This will automatically trigger the Deploy action.
Wait for a few minutes and let the action complete. You can see the progress in the Actions tab. If completed successfully, in addition to the master branch, your repository should now have a newly built gh-pages branch.
Finally, in the Settings of your repository, in the Pages section, set the branch to gh-pages (NOT to master). For more details, see [Configuring a publishing source for your GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source).

![image](https://user-images.githubusercontent.com/66814061/230862297-e59b40db-ac3e-43c7-bbb6-d5175523fc12.png)

**Comment by yajanbasel** [comment]
Now it worked. Changed branch to gh-pages. and now works.

**Comment by gubazoltan** [comment]
What do you mean by "changed branch to gh-pages. and works."? 
What did you change to gh-pages? The name of the branch?

**Comment by peter716** [comment]
I don't see a gh-pages after committing. Do I need to do anything?

**Comment by peter716** [comment]
I see it now, but one of my workflows fails.
