### ISSUE TITLE
Make Blog removable from navbar

### ISSUE THREAD

**Issue by danielmimimi** [alshedivat/al-folio#1328]
**Is your feature request related to a problem? Please describe.**

On all the other features like cv, projects, publications etc one can disable their nav visibility just like : 

```
layout: cv
permalink: /cv/
title: cv
nav: true #<--- that
nav_order: 0
cv_pdf: example_pdf.pdf
```

**Describe the solution you'd like**
I was wondering wheather this is possible for the blogs ? Or is there any other switch to disable its
presence in the navbar?

**Comment by chnsh** [comment]
If you change `_config.yaml` and edit it so that `blog_nav_title:` is an empty string, it is skipped from the navbar
