### ISSUE TITLE
Show "howpublished" or custom journal title for papers in subheading.

### ISSUE THREAD

**Issue by haukesand** [alshedivat/al-folio#1332]
I want to show that two short papers are published for a conference workshop. They are not in the proceedings, so i have to use misc or article. 

howpublished seems to be commonly used for this. But the title of the workshop will this way only show up in the bib entry but not on the page itself. See here: https://haukesand.github.io/.

**Comment by Gabrielcarvfer** [comment]
You can modify _layouts/bib.html
```
          {%- if entry.website %}
            <a href="{{ entry.website }}" class="btn btn-sm z-depth-0" role="button">Website</a>
          {%- endif %}
          +{%- if entry.howpublished %}
          +  <a href="{{ entry.howpublished }}" class="btn btn-sm z-depth-0" role="button">Link</a>
          +{%- endif %}
          {%- if entry.doi %}
            doi:<a href="http://dx.doi.org/{{entry.doi}}">{{entry.doi}}</a>
          {%- endif %}
```
