### ISSUE TITLE
How could I add a video button for my publication?

### ISSUE THREAD

**Issue by rolandying** [alshedivat/al-folio#1357]
Hi,

This is a really impressive work!
I'm starting to build my personal website based on this template. 
I meet trouble in adding a "TALK" button for my publication just as this [page](https://maruan.alshedivat.com/publications/). 
I understand I need to change the `bib.html` file, but since I got few knowledge on it, could anyone provide me a template code directly?
Lots of thanks!

**Comment by george-gca** [comment]
@alshedivat just realized that this is your site in the example. Do you think you could add this to the template? I also think it would be useful for more people.

Meanwhile @rolandying take a look at how it is done with the abstract part. More specifically, look at the [_layouts/bib.html](https://github.com/alshedivat/al-folio/blob/master/_layouts/bib.html) file, it is the one responsible for displaying the bibliography. Each `entry` comes straight from the [bib file](https://github.com/alshedivat/al-folio/blob/master/_bibliography/papers.bib).
