### ISSUE TITLE
Is it possible to add a team page?

### ISSUE THREAD

**Issue by alexkongy** [alshedivat/al-folio#1378]
**Is your feature request related to a problem? Please describe.**
Al-folio is excellent for personal website. It seems like a Team page is missing, or maybe just me don't know how to do it. I found a nice one from https://www.allanlab.org/team/, and I have been trying to integrate their team page to al-folio but no luck. Is it possible to add the team page to al-folio?

**Describe the solution you'd like**
Add team page from https://www.allanlab.org/team/ to al-folio.

**Describe alternatives you've considered**

**Additional context**
Thank you!

**Comment by george-gca** [comment]
Yes, it is possible and actually a lot of sites created from this template implemented their own solution. I'd recommend you check [their sites](https://github.com/alshedivat/al-folio#user-community) and repositories, since most (if not all) of them are open source.
