### ISSUE TITLE
adding date in a distill-style post

### ISSUE THREAD

**Issue by givasile** [alshedivat/al-folio#139]
Hello and congrats for the repo.

In the distill post, under "Published" it displays the value "undefined NaN, NaN", even though I have added a date. This also happens in the example you provide [here](https://alshedivat.github.io/al-folio/blog/2018/distill/). Is it a bug?

**Comment by alshedivat** [comment]
This might be a browser issue. Which browser are you using? Everything works fine in Chrome and Chromium.

**Comment by givasile** [comment]
> This might be a browser issue. Which browser are you using? Everything works fine in Chrome and Chromium.

It is indeed. In Chrome and Chromium it works well, but in Firefox (that I use) crashes. I think it is a browser's problem so we can close this bug.

**Comment by ryukzak** [comment]
Same problem with the last Safari.

**Comment by ryukzak** [comment]
In my case, it is a problem with the expected date format by distill and actual date format from the file.

distil expect (according to their examples): `published: Jan 10, 2017`

In file: `date:   2019-11-15 12:00:00 +0300`

So I a little bit patch `_layout/distil.html`:
```
diff --git a/_layouts/distill.html b/_layouts/distill.html
index 23995a0..683e9db 100644
--- a/_layouts/distill.html
+++ b/_layouts/distill.html
@@ -16,7 +16,7 @@
     <script async type="text/json">{
       "title": "{{ page.title }}",
       "description": "{{ page.description }}",
-      "published": "{{ page.date }}",
+      "published": "{{ page.date | date: "%b %d, %Y"}}",
       "authors": [
         {% for author in page.authors %}
         {
```

**Comment by alshedivat** [comment]
@ryukzak, thanks for pointing this out. It looks like #194 fixed the issue too (similar change to the one you proposed).
