### ISSUE TITLE
Don't hardcode years in publications page

### ISSUE THREAD

**Issue by pgunn** [alshedivat/al-folio#1390]
**Is your feature request related to a problem? Please describe.**
It's a maintenance burden to need to remember that we need to adjust the publications template every year. It'd be good to adjust that template so it first iterates over all the publications to build a list of years (and considers publications without a year as undated, which should still display at the bottom), and then generates the year-by-year sections automatically.

**Describe the solution you'd like**
A code adjustment to the publications template (and maybe the projects template, which would benefit from time-based ordering)

**Comment by CheariX** [comment]
Not yet tested, but you are basically looking for something like this?

```
---
layout: page
permalink: /publications/
title: publications
description: publications by categories in reversed chronological order. generated by jekyll-scholar.
starting_year: 2010
nav: true
nav_order: 1
---
<!-- _pages/publications.md -->
<div class="publications">

{%- assign current_year = site.time | date: "%Y" | plus: 0 -%}

{%- for y in (starting_year..current_year) %}
  {%- assign count = bibliography_count -f {{ site.scholar.bibliography }} -q @*[year={{y}}]* -%}
  {% if count > 0 %}
    <h2 class="year">{{y}}</h2>
    {% bibliography -f {{ site.scholar.bibliography }} -q @*[year={{y}}]* %}
  {% endif %}
{% endfor %}

</div>
```

I'm currently using something similar on my page.

**Comment by george-gca** [comment]
Just realized that jekyll scholar support this out-of-the-box. Implementing it right now.

**Comment by pgunn** [comment]
Thanks!
