### ISSUE TITLE
Sync workflow wants to override my commits

### ISSUE THREAD

**Issue by ma-sadeghi** [alshedivat/al-folio#1391]
I'm using `al-folio` as a "template" as described in the README page. I also added the sync workflow recommended in the README page. There's, however, one big problem: the pull request made by the sync workflow wants to override my commits (pretty much everything I customized, like publicatins, etc.), despite the fact that those files didn't change between the date I forked the template and the latest commit on al-folio.

To clarify what I mean, here's the PR made by the workflow: https://github.com/ma-sadeghi/ma-sadeghi.github.io/pull/2

PS. I think that had I just forked the repo - and not used it as a template - this would not have happened, since that way, I would have all the commit history of `al-folio` repo, hence no override when no conflict between my repo and the original (if this makes sense to you).

**Comment by george-gca** [comment]
What I did in my case was to use it as a template, then do all my changes in another branch. The `main` branch will always stay in sync with `al-folio`. After applying all the changes from al-folio to the main branch (by using the sync workflow), I simply merge my branch with the main branch to apply the updates. You can check [my repo](https://github.com/george-gca/george-gca.github.io), maybe it will be more clear.

**Comment by cynricfu** [comment]
> What I did in my case was to use it as a template, then do all my changes in another branch. The `main` branch will always stay in sync with `al-folio`. After applying all the changes from `al-folio` to the `main` branch (by using the sync workflow), I simply merge the `main` branch with my branch to apply the updates. You can check [my repo](https://github.com/george-gca/george-gca.github.io), maybe it will be more clear.

This workaround is just like the manual update approach, making the template sync almost meaningless. Perhaps a better solution is to make use of the `.templatesyncignore` file to minimize the effort of resolving conflicts. But it is still not elegant.

**Comment by george-gca** [comment]
One possibility would be to change the default behavior of sync workflow to something else, a rebase for example. For this you could use the `git_remote_pull_params` config param, as seen [here](https://github.com/AndreasAugustin/actions-template-sync#configuration-parameters).
