### ISSUE TITLE
Simplify Jupyter Notebook Blog Posts By Switching From Distill to Quarto

### ISSUE THREAD

**Issue by gil2rok** [alshedivat/al-folio#1405]
**Is your feature request related to a problem? Please describe.**
I love the Distill blog format. However, it is inconvenient to embed the output of Jupyter notebooks in my blogs: I need to run the Jupyter notebook to generate my output and then _manually copy it_ to my Distill blog post. 

**Describe the solution you'd like**
Instead of using Distill for blog posts, perhaps consider using [Quarto](https://quarto.org/), a versatile emerging standard on publishing scientific / LaTex / Jupyter Notebook documents. Quarto allows you to turn Jupyter notebooks _directly_ into blog posts in a format based on Distill blog posts! More details can be found [here](https://quarto.org/docs/tools/jupyter-lab.html).

The format is incredibly similar so is likely to be an easy transition for existing al-folio users. Please let me know what others think! Quarto even has documentation on how to set up a Quarto blog integrated into existing websites [here](https://quarto.org/docs/websites/website-blog.html).

**Describe alternatives you've considered**
I cold not find any other alternatives.

**Additional context**
The maintainers of RMarkdown have started Quarto as a more versatile project and they answer some relevant FAQs [here](https://quarto.org/docs/faq/rmarkdown.html#quarto-sounds-similar-to-r-markdown.-what-is-the-difference-and-why-create-a-new-project) that briefly talks about how Quarto can replace formats like Distill.

**Comment by george-gca** [comment]
@gil2rok idk if this is a good solution. It looks like Quarto is [distributed as a binary](https://quarto.org/docs/download/), which needs to be installed separately. Also, it is built on top of Pandoc, which is a Haskell library. This would add a lot more other tools to the build process.

**Comment by ez2rok** [comment]
I'd personally love to be able to use Quarto!

**Comment by george-gca** [comment]
There is [a tutorial](https://www.asterhu.com/post/2023-03-30-jekyll-migrating-to-quarto/) about how to migrate from Jekyll to Quarto. I believe if you want to use Quarto, it would be more useful to use it entirely instead of just using it to render jupyter notebooks. Like I said above, it would add a lot more other tools to the build process to do something that is already supported.
