### ISSUE TITLE
Unwanted blog feature

### ISSUE THREAD

**Issue by XuhuiZhou** [alshedivat/al-folio#141]
**Is your feature request related to a problem? Please describe.**
Might be a naive question here, but if I do not have any blogs to post right now and I want 'blog' to disappear in the navigation bar, how could I achieve that?

**Comment by alshedivat** [comment]
Simply remove or make empty the `blog_name` field in [_config.yml](https://github.com/alshedivat/al-folio/blob/master/_config.yml#L63). Let me know if that works.

**Comment by alshedivat** [comment]
I'm assuming the fix suggested above worked. Closing this issue.
