### ISSUE TITLE
profile image not displaying when deployed to website

### ISSUE THREAD

**Issue by doraldoa** [alshedivat/al-folio#1410]
Hi! Thanks for this amazing academic website.
I am having trouble displaying the profile image. 
The website can be built and deployed successfully, but the profile image of "about" just displays "named_by_me.jpg", not the context of the picture.
Meanwhile, there were no problems when compiling locally, the web looks perfectly normal.
I am not able to understand the error; could someone please help.

system: windows 11 with docker desktop.
Thanks

**Comment by doraldoa** [comment]
![1683768261417](https://github.com/alshedivat/al-folio/assets/64248259/d7b3d8bd-1790-4d64-98d4-42f791cb097c)
Going on like this.

**Comment by george-gca** [comment]
If it is working locally, maybe you forgot to add the image on the server?

**Comment by swaradgat19** [comment]
@george-gca I have pushed the changes to the forked repository. Am I missing some steps?

**Comment by KhalidAlnujaidi** [comment]
having same issue with project images

**Comment by KhalidAlnujaidi** [comment]
oka figured it out!

Do not put the relative path of the image. 

Only simply put the direct image name.

**Comment by KhalidAlnujaidi** [comment]
okay figured it out.

The solution was just to change format of images into .jpg

**Comment by george-gca** [comment]
@swaradgat19 is it working?

**Comment by swaradgat19** [comment]
@george-gca Yes it is working. My base URL was incorrect

**Comment by mbuenov** [comment]
what is the baseurl in the config yml

**Comment by eduardstan** [comment]
Hi, I have the same issue. First, I had to refresh the browser page to see the image, which was quite cumbersome. Moreover, from the mobile phone, I see this:

![Image](https://github.com/user-attachments/assets/b56a1760-366b-4769-9e1c-5fa9ebc0235e)

Please check it for yourself: https://eduardstan.github.io/

I'm looking forward to solving this issue. Thank you in advance!

**Comment by george-gca** [comment]
I believe your issue is the same as #3016.

**Comment by eduardstan** [comment]
Thank you! It works now!
