### ISSUE TITLE
"Map" type in CV cannot be seen/invisible text

### ISSUE THREAD

**Issue by jsigman** [alshedivat/al-folio#1421]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**

"Map" type in CV blocks has invisible text in dark mode. It can be toggled to light, then dark mode again to restore visibility.

**To Reproduce**
1. Compile and serve the master branch

**Expected behavior**

**Screenshots**

From [the public website](https://alshedivat.github.io/al-folio/cv/), you can see this issue

<img width="965" alt="Screenshot 2023-05-13 at 8 37 06 AM" src="https://github.com/alshedivat/al-folio/assets/2373529/02c1b22f-b6f1-4b2e-b2b1-0dfd4ad68633">

**Comment by george-gca** [comment]
I believe this is addressed in #1424. As soon as I confirm this, if fixed, I'll close this issue.

**Comment by jsigman** [comment]
Thanks! Confirm that I can see the text. However, it is delayed for about a second longer than the rest of the text on the page. Still, it works enough for now.

**Comment by george-gca** [comment]
Please @jsigman add this as an improvement, to keep this noted.
