### ISSUE TITLE
Error: Unknown tag 'toc'

### ISSUE THREAD

**Issue by DriesSmit** [alshedivat/al-folio#1438]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
I forked the repo as instructed. But the build then fails with the following message:

```
Warning:  github-pages can't satisfy your Gemfile's dependencies.
  Logging at level: debug
Configuration file: /github/workspace/./_config.yml
      GitHub Pages: github-pages v228
      GitHub Pages: jekyll v3.9.3
             Theme: jekyll-theme-primer
      Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0
         Requiring: jekyll-github-metadata
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
  Liquid Exception: Liquid syntax error (line 42): Unknown tag 'toc' in /_layouts/post.html
/usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:38:in `unknown_tag': Liquid syntax error (line 42): Unknown tag 'toc' (Liquid::SyntaxError)
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:38:in `unknown_tag'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:68:in `block in parse_body'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:32:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:58:in `parse_body'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:30:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tag.rb:10:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:34:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/document.rb:10:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/document.rb:5:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:130:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:[11](https://github.com/DriesSmit/DriesSmit.github.io/actions/runs/5031144714/jobs/9024025334#step:4:12)4:in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/liquid_renderer/file.rb:[12](https://github.com/DriesSmit/DriesSmit.github.io/actions/runs/5031144714/jobs/9024025334#step:4:13):in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:121:in `render_liquid'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:195:in `render_layout'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:88:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:479:in `render_regenerated'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:463:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:463:in `block in render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:462:in `each_value'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:462:in `render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:191:in `render'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:71:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
         Requiring: jekyll-seo-tag
         Requiring: jekyll-feed
         Requiring: jekyll-sitemap
         Requiring: jemoji
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
   GitHub Metadata: Initializing...
            Source: /github/workspace/.
       Destination: /github/workspace/./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       EntryFilter: excluded /bin
       EntryFilter: excluded /Gemfile
           Reading: _posts/2022-12-10-giscus-comments.md
           Reading: _posts/2023-04-24-videos.md
           Reading: _posts/2015-07-15-code.md
           Reading: _posts/2023-04-25-audios.md
           Reading: _posts/2015-03-15-formatting-and-links.md
           Reading: _posts/2021-07-04-diagrams.md
           Reading: _posts/2023-03-21-tables.md
           Reading: _posts/2020-09-28-twitter.md
           Reading: _posts/2015-05-15-images.md
           Reading: _posts/2022-02-01-redirect.md
           Reading: _posts/2018-12-22-distill.md
           Reading: _posts/2023-04-25-sidebar-table-of-contents.md
           Reading: _posts/2023-05-12-custom-blockquotes.md
           Reading: _posts/2015-10-20-disqus-comments.md
           Reading: _posts/2015-10-20-math.md
           Reading: _posts/2020-09-28-github-metadata.md
           Reading: _posts/2023-03-20-table-of-contents.md
           Reading: _news/announcement_1.md
           Reading: _news/announcement_3.md
           Reading: _news/announcement_2.md
           Reading: _projects/2_project.md
           Reading: _projects/4_project.md
           Reading: _projects/1_project.md
           Reading: _projects/3_project.md
           Reading: _projects/6_project.md
           Reading: _projects/5_project.md
        Generating: JekyllOptionalFrontMatter::Generator finished in 0.000254303 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 0.0014189[13](https://github.com/DriesSmit/DriesSmit.github.io/actions/runs/5031144714/jobs/9024025334#step:4:14) seconds.
       Jekyll Feed: Generating feed for posts
        Generating: JekyllFeed::Generator finished in 0.000706406 seconds.
        Generating: Jekyll::JekyllSitemap finished in 0.00101051 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 6.2e-06 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 0.000563406 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.000363103 seconds.
        Generating: JekyllTitlesFromHeadings::Generator finished in 2.3101e-05 seconds.
         Rendering: _posts/20[15](https://github.com/DriesSmit/DriesSmit.github.io/actions/runs/5031144714/jobs/9024025334#step:4:16)-03-15-formatting-and-links.md
  Pre-Render Hooks: _posts/[20](https://github.com/DriesSmit/DriesSmit.github.io/actions/runs/5031144714/jobs/9024025334#step:4:21)15-03-15-formatting-and-links.md
  Rendering Markup: _posts/2015-03-15-formatting-and-links.md
         Requiring: kramdown-parser-gfm
  Rendering Layout: _posts/2015-03-15-formatting-and-links.md
     Layout source: site
github-pages [22](https://github.com/DriesSmit/DriesSmit.github.io/actions/runs/5031144714/jobs/9024025334#step:4:23)8 | Error:  Liquid syntax error (line [42](https://github.com/DriesSmit/DriesSmit.github.io/actions/runs/5031144714/jobs/9024025334#step:4:43)): Unknown tag 'toc'
```
I tried the other solutions where I first set the branch in Pages to None. However it still fails to build. What is the recommended thnk to do here? Thank you for your time.

**To Reproduce**
I forked the repo and I am using an Ubuntu machine.

**Comment by kshiteesh** [comment]
I have the same issue

**Comment by george-gca** [comment]
Does it work when you try it locally?

**Comment by kshiteesh** [comment]
I solved it by moving to Docker. I set the branch from which the website is built to `gh-pages`. I make the changes, commit and push them and run `docker-compose up` on my machine. That's it! I highly recommend adopting this workflow to anyone encountering issues.

**Comment by dtrocellier** [comment]
I have also the same issue

**Comment by KhalidAlnujaidi** [comment]
Solution:

Setting of you the repository -> pages -> deploy from: select gh-pages branch , not the master brach.

This solution taken from someone from closed threads and it worked for me :)

**Comment by george-gca** [comment]
Actually, the `gh-pages` branch solution is documented [here](https://github.com/alshedivat/al-folio#deployment), under the `To enable automatic deployment` section.

**Comment by george-gca** [comment]
@DriesSmit is it working now?

**Comment by awsaf49** [comment]
I faced the same issue and resolved using `gh-pages`

**Comment by ClonedOne** [comment]
I am adding a comment here because, despite being linked in the README, this is not a complete solution. I am facing the same issue. The deploy process is failing during the build phase. the `gh-pages` branch is **not** generated. Therefore there is no way to select it as the branch from which to deploy.

**Comment by george-gca** [comment]
@ClonedOne trying to use as-is from the repo, changing only the name of the url in `_config.yml`, it doesn't work for you?

**Comment by Chiil** [comment]
I have the same problem. It fails in the build and hence does not create the `gh-pages`. Changing the url does not help.

**Comment by george-gca** [comment]
@Chiil have you tried a fresh start? Because if it fails from the very beginning it is an issue in the template itself, but if it was working before then it stopped, then the bug was introduced later, and it would be easier to debug. I always recommend from the beginning trying to deploy it as is, then adding some changes.

**Comment by Chiil** [comment]
Yes, I did, I forked the repository, pushed only one commit that changes the url and that is it. My repo is at https://github.com/Chiil/chiil.github.io

**Comment by george-gca** [comment]
Ok I just tried a fresh install with another user, and everything worked just fine. Here is the step-by-step I did (will update the README file soon):

1 - Start by clicking in
```
Use this template -> Create a new repository
```
Created a public repo with name `<your-github-username>.github.io`

2 - Go to
```
Settings -> Actions -> General -> Workflow permissions
```
and give `Read and write permissions` to GitHub Actions

3 - In `_config.yml`, set url to `https://<your-github-username>.github.io` and leave baseurl **empty**.

4 - Finally, go to
```
Settings -> Pages -> Build and deployment
```
make sure that `Source` is `Deploy from a branch` and set the branch to `gh-pages` (NOT to master)

5 - Wait until the GitHub actions finish, then simply navigate to `https://<your-github-username>.github.io` in your browser

**Comment by george-gca** [comment]
Just realized that your username has capital letters. I hope that I'm wrong in this, but maybe this might be affecting it.

**Comment by Chiil** [comment]
It works now! I have noticed that the essential difference is whether to do "Use this template" vs doing "Fork". What is different that if I fork, the Github Actions is already set (correctly though), whereas when I use  "Use this template" I can set it to read and write and things go OK. I am not sure whether I understand the difference.

**Comment by ClonedOne** [comment]
Sorry, have been out for a while and didn't check this. I ended up solving the issue by changing the "Build and deployment" setting to "Github Actions" and then accepting the default Jekyll configuration proposed by Github by clicking on the button below.

**Comment by MainulHossain-123** [comment]
Hello, I deployed the code with gh-pages but am facing the same issue still.

**Comment by MPenaR** [comment]
Fresh install and I face the same issue. 

Actually the error in build is thrown as soon as point 2. 

"In this new repository, go to Settings -> Actions -> General -> Workflow permissions and give Read and write permissions to GitHub Actions."

Failing in the initial commit.

**Comment by max870701** [comment]
> Ok I just tried a fresh install with another user, and everything worked just fine. Here is the step-by-step I did (will update the README file soon):
> 
> 1 - Start by clicking in
> 
> ```
> Use this template -> Create a new repository
> ```
> 
> Created a public repo with name `<your-github-username>.github.io`
> 
> 2 - Go to
> 
> ```
> Settings -> Actions -> General -> Workflow permissions
> ```
> 
> and give `Read and write permissions` to GitHub Actions
> 
> 3 - In `_config.yml`, set url to `https://<your-github-username>.github.io` and leave baseurl **empty**.
> 
> 4 - Finally, go to
> 
> ```
> Settings -> Pages -> Build and deployment
> ```
> 
> make sure that `Source` is `Deploy from a branch` and set the branch to `gh-pages` (NOT to master)
> 
> 5 - Wait until the GitHub actions finish, then simply navigate to `https://<your-github-username>.github.io` in your browser

Still NOT work.

**Comment by george-gca** [comment]
> Note:
> In step 1, select the option Include all branches.

This is not needed since it will copy a lot of branches that you'll probably never use, and only pollute your repository with unnecessary code.

**Comment by marsggbo** [comment]
Here is my solution:
1. **use this template** to create a new repo, instead of fork!!! instead of fork!!!
2. In this new repository, go to `Settings -> Actions -> General -> Workflow permissions` and give `Read and write permissions` to GitHub Actions.
3. Open file _config.yml, set url to https://<your-github-username>.github.io and leave baseurl empty (do NOT delete it).
4. You may probably find that **gh-pages** is not created. You can go to `Settings -> Pages -> Build and deployment`,  choose 'Github Action`
![image](https://github.com/alshedivat/al-folio/assets/13477956/bc87f234-896b-4986-935c-32c47e9dd62e)
5. Wait step 4 finishes, you will find `gh-pages` branch is created. Then, you website is deployed after the Action finishes.

**Comment by chiaradivece** [comment]
> @ClonedOne trying to use as-is from the repo, changing only the name of the url in `_config.yml`, it doesn't work for you?

Hello, I'm having the same issue. I've followed all the steps and as soon as I change the URL I get the error in Buid with Jekyll. 

`Warning: The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
  Liquid Exception: Liquid syntax error (line 64): Unknown tag 'toc' in /_layouts/post.liquid`
  
  I've tried all the suggested solutions but nothing seems to work. Any idea why? Thank you!

**Comment by lingium** [comment]
This works for me. Thanks @marsggbo

**Comment by wansiedler** [comment]
> Ok I just tried a fresh install with another user, and everything worked just fine. Here is the step-by-step I did (will update the README file soon):
> 
> 1 - Start by clicking in
> 
> ```
> Use this template -> Create a new repository
> ```
> 
> Created a public repo with name `<your-github-username>.github.io`
> 
> 2 - Go to
> 
> ```
> Settings -> Actions -> General -> Workflow permissions
> ```
> 
> and give `Read and write permissions` to GitHub Actions
> 
> 3 - In `_config.yml`, set url to `https://<your-github-username>.github.io` and leave baseurl **empty**.
> 
> 4 - Finally, go to
> 
> ```
> Settings -> Pages -> Build and deployment
> ```
> 
> make sure that `Source` is `Deploy from a branch` and set the branch to `gh-pages` (NOT to master)
> 
> 5 - Wait until the GitHub actions finish, then simply navigate to `https://<your-github-username>.github.io` in your browser

Worked, thank you!  [❤️](https://emojipedia.org/de/rotes-herz)
