### ISSUE TITLE
Disable teaching in navigation

### ISSUE THREAD

**Issue by moucheng2017** [alshedivat/al-folio#1465]
I am new to this, could you please kindly point me to where I can disable the teaching section and customize the navigation bar? Thanks!

**Comment by moucheng2017** [comment]
i found it

**Comment by nku-zhichengzhang** [comment]
> i found it

Could you kindly share the solution?

**Comment by moucheng2017** [comment]
> > i found it
> 
> Could you kindly share the solution?

It's in teaching.md in _pages folder. You can change nav: false in that teaching.md file, then it will turn off in the navigation bar. Same for other sections such as projects or repositories or anything. Hope it helps!

**Comment by nku-zhichengzhang** [comment]
> 

Thx! It works for teaching and for other sections. Nice solution.

**Comment by m3lixir** [comment]
Setting `nav: false` just removes the link from the navbar, how do I prevent the page being built?

**Comment by m3lixir** [comment]
Nevermind, I figured it out. Update `include` and `exclude` in `_config.yml`

**Comment by george-gca** [comment]
You can simply delete the page.
