### ISSUE TITLE
Docker manifest for Mac Silicon 

### ISSUE THREAD

**Issue by cranmer** [alshedivat/al-folio#1469]
**Is your feature request related to a problem? Please describe.**

On an apple silicon Mac I have installed docker-compose, but there is no docker manifest for this architecture. 

> $docker-compose up
> [+] Running 0/1
> ⠏ jekyll Pulling                                                                                                                                            0.9s 
> no matching manifest for linux/arm64/v8 in the manifest list entries

**Describe the solution you'd like**
A docker image that will work on apple silicon

**Describe alternatives you've considered**
I tried the standard install, but it is also having some issues related to mini-racer.

**Comment by cranmer** [comment]
Follow up. Building locally with `docker-compose -f docker-local.yml up` worked fine. I'm not sure if there is a way to contribute that image to docker hub so others can pull it.

**Comment by alshedivat** [comment]
thanks for reporting this. @pourmand1376, is there a way to push a new docker image built on apple silicon to the [dockerhub repository](https://hub.docker.com/r/amirpourmand/al-folio) that you are maintaining?

**Comment by pourmand1376** [comment]
Hi, 

I do not have an M1 MacBook. I will soon borrow one from my friends to see why it doesn't work. The whole purpose of docker was to make our website cross-platform. I can not understand why It shouldn't work. 

We may have to build a docker image per CPU configuration. (One for intel, One for AMD, and One for M1). I have to see if there is an automatic way of creating these images via Github Actions. 

Still, One can push docker images to Dockerhub manually. However, manually pushing docker images is tedious and not a stable solution.

**Comment by theophilegervet** [comment]
Hi @pourmand1376, I can't find the version compatible with `arm64/v8` at https://hub.docker.com/r/amirpourmand/al-folio. 
```
docker pull amirpourmand/al-folio
```
still gives
```
Using default tag: latest
latest: Pulling from amirpourmand/al-folio
no matching manifest for linux/arm64/v8 in the manifest list entries
```
Am I missing something?

**Comment by pvbaudin** [comment]
Same issue, honestly I would consider this fixed if the README were modified to specify that docker-local.yml should be used to build for Apple Silicon based systems

Right now the docker-local instructions are under a dropdown that says
> Note: this approach is only necessary if you would like to build an older or very custom version of al-folio.

M1 and M2 are now common enough platforms that an explicit instruction linked int he TOC would be a good idea

**Comment by pourmand1376** [comment]
Hi @theophilegervet 
You are right. I fixed the image. But the image is overwritten each time a commit is made to this repository. So, until my pull request is merged, you should use the image I've pushed to `mac` tag. 

So, It would be:

```
docker pull amirpourmand/al-folio:mac
```
or you could change `amirpourmand/al-folio` to `amirpourmand/al-folio:mac` in [docker-compose](https://github.com/alshedivat/al-folio/blob/master/docker-compose.yml) file.

@pvbaudin 
Just so you know, instructions specific to Mac are not needed. We just needed to build two images for each commit. One for standard CPUs and One for ARM (Mac) CPUs. Then, Docker itself would choose which image to download for each PC.

**Comment by pourmand1376** [comment]
Great news! The PR has been successfully merged, and you can now run the website by typing the following command into your terminal:
```
docker-compose up
```
If you encounter any issues while running the website, please let me know so that I can help you resolve them. Alternatively, if everything goes smoothly, please confirm that the issue can be closed.

**Comment by mhyatt000** [comment]
was going to open a new issue, but ill put here.
im on osx-arm64 m4

```sh
root@da0472423807:/srv/jekyll# ./bin/entry_point.sh
Entry point script running
Gemfile.lock is tracked by git, keeping it intact
Could not find nokogiri-1.18.9-aarch64-linux-gnu, rexml-3..2 in locally installed gems
Run `bundle install` to install missing gems.
```

and `bundle install` solves it like the README suggests.


> [@pvbaudin](https://github.com/pvbaudin) Just so you know, instructions specific to Mac are not needed. We just needed to build two images for each commit. One for standard CPUs and One for ARM (Mac) CPUs. Then, Docker itself would choose which image to download for each computer.

should I have used the mac docker image?
