### ISSUE TITLE
about and blog have hard-coded lower-case capitalization

### ISSUE THREAD

**Issue by AbeHandler** [alshedivat/al-folio#147]
Awesome theme! There seems to be an issue with hard-coded casing for the about and blog sections.

**Describe the bug**
I want to show my About and Blog pages with upper-case in the navbar. If I want to capitalize projects, I got to  `_pages/projects.md` and set `title: Projects` and the navbar shows this in uppercase. So I would think I could go to `_pages/about.md` and set `title: About`  to show About in upper case on the nav bar. But the casing is hard-coded in `_includes/header.html` so you cannot change the case, without changing `_includes/header.html`.

**To Reproduce**
1. go to `_pages/about.md` and set `title: About`

**Expected behavior**
The navbar should show the about section with the first letter capitalized (i.e. About)

**System (please complete the following information):**
 - OS: Max OS
 - Chrome 86.0.4240.198

**Additional context**
Here is where the names are hard-coded with lower case 
https://github.com/alshedivat/al-folio/blob/master/_includes/header.html#L28

https://github.com/alshedivat/al-folio/blob/master/_includes/header.html#L38

**Comment by monkeywithacupcake** [comment]
Do you think that this should be a preference in `config` or hardcode to have sentence case @alshedivat?

**Comment by josyulakrishna** [comment]
Is this issue resolved? I am seeing the same behavior for project titles on the projects page too I am not to be get capitalized letters 
To reproduce 
1. In `1_project.md` change the title to "Project Another Upper Case 1" 
Expected Behaviour:
The title has capitalized letters, however it doesn't appear to be capitalised. 

Also the same happens with navbar

**Comment by kahn-jms** [comment]
Hi, You can modify the following line in `_includes/projects.html`:
```
<h2 class="card-title text-lowercase">{{ project.title }}</h2>
```
to simply
```
<h2 class="card-title">{{ project.title }}</h2>
```
and it seems to fix this.
