### ISSUE TITLE
Related posts same for all blog pages

### ISSUE THREAD

**Issue by sjschmidt** [alshedivat/al-folio#1480]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
The auto-generated "related posts" list is the same for multiple different blog posts that have very different tags. 

**To Reproduce**
1. Have two different tags that do not overlap on any of the blog posts (on my blog, autism and career_change). Each tag has five or more total posts.
2. Enable related posts at the bottom (current default behavior).
3. The lists for one post tagged with autism and one post tagged with career_change are the same. 

**Expected behavior**
When clicking on a post with an autism tag, the related posts should all have the autism tag. When clicking a post with a career_change tag, the related posts should all have the career_change tag. 

**Screenshots**
It might be easier to look at the problem at https://sarahjaneschmidt.com/blog/, but I've attached screenshots. 

**System (please complete the following information):**
This problem happens both locally and on the deployed version, but I'll fill this in for completeness. 
 - OS: macOS big sur 11.7.7
 - Browser: chrome 14.0.5735.106 (Official Build) (x86_64)
 - Jekyll: 4.3.2
- Ruby: 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [x86_64-darwin20]

**Additional context**
I did notice that the related posts were the most recent, but that's not what "related" means. 

<img width="549" alt="Screenshot 2023-06-11 at 13 19 09" src="https://github.com/alshedivat/al-folio/assets/1139537/dd19a042-143c-4c3b-bc4c-e74808294469">
<img width="808" alt="Screenshot 2023-06-11 at 13 19 20" src="https://github.com/alshedivat/al-folio/assets/1139537/b5648187-2f0c-427b-a679-90200906eae5">
<img width="771" alt="Screenshot 2023-06-11 at 13 19 44" src="https://github.com/alshedivat/al-folio/assets/1139537/3b5e2166-a1e5-4119-a81a-ffcd3adebc53">
<img width="436" alt="Screenshot 2023-06-11 at 13 19 50" src="https://github.com/alshedivat/al-folio/assets/1139537/0a51ea55-1a17-43b6-b1cc-6a4f7844ce05">
<img width="658" alt="Screenshot 2023-06-11 at 13 20 08" src="https://github.com/alshedivat/al-folio/assets/1139537/5d0c8497-3e01-4f63-a804-a4ce6e72f790">
<img width="547" alt="Screenshot 2023-06-11 at 13 20 18" src="https://github.com/alshedivat/al-folio/assets/1139537/7b7c8589-13da-4044-9963-d49e398e6842">

**Comment by george-gca** [comment]
Actually the list of related posts is different for each post, as you can see in the screenshots. The current behavior is the expected behavior.

If you are using the default configuration from the repository, which is the one present in the official [Jekyll documentation](https://jekyllrb.com/docs/variables/#site-variables) (look for the `site.related_posts` variable), the related posts is not based on tags. It is instead calculated via [latent semantic indexing](https://en.wikipedia.org/wiki/Latent_semantic_analysis#Latent_semantic_indexing).

If you want a more customized solution for this, you will have to implement it. Feel free to submit a PR.

**Comment by george-gca** [comment]
This solution might be what you want @sjschmidt:
https://frankindev.com/2016/07/13/related-posts-in-jekyll/
