### ISSUE TITLE
Deployment (./bin/deploy) bug

### ISSUE THREAD

**Issue by HojeChun** [alshedivat/al-folio#1481]
**Acknowledge the following**
- [Y] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [Y] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [Y] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
I am trying to deploy (./bin/deploy) after some changes. It works fine locally, but the public url looks crashed (https://hojechun.github.io/). I have also tried auto deployment, pushing the changes to the master. 
I have followed the FAQ, checking the _config.yml. There seems few people had the same issue but I couldn't figure out solution for my case. 

The log seems to come our properly.

...
"""Switched to branch 'master'
Your branch is up to date with 'origin/master'.
Deployed successfully!"""

**Comment by george-gca** [comment]
Did it not work from the beginning?
I always recommend starting again from ground up, making sure the default repo works in your URL with the default configuration. Only then, do small incremental changes.
It is always hard to debug a fully customized site with new dependencies.

**Comment by HojeChun** [comment]
Thanks  for the reply, it did work from the beginning. I had been adding small incremental changes. I till try starting over again.

**Comment by george-gca** [comment]
Can you pinpoint which exactly change made it stop working?

**Comment by HojeChun** [comment]
Sorry for the late reply. `https://github.com/HojeChun/hojechun.github.io/` this is the current repo and it stopped working with this commit `db035660e5fa71acf9e129c94761360b2bebe9a7`.

**Comment by HuskyKingdom** [comment]
It is likely that you didnt allow github to read & write your file before deploy. Check the instruction.

**Comment by HojeChun** [comment]
Thanks all, 

I will try to change individually, and removing <scripts>. I wonder why I worked (and still working) locally tho.

I also did allow github to read & write according to the instruction, so guess this is not the case.

**Comment by george-gca** [comment]
If it is working locally but not in remote, maybe there is some files that you forgot to add to remote repo but are in local?

**Comment by HojeChun** [comment]
I have checked the files from local and remote repo. It did not work out. I started again with the new repo and it works again :) closing the issue.
