### ISSUE TITLE
Fresh Installation Error

### ISSUE THREAD

**Issue by majauhar** [alshedivat/al-folio#1491]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
I got the following error message when I tried `bundle exec jekyll serve --lsi` locally as well as on GitHub pages build
```
Incremental build: disabled. Enable with --incremental
      Generating...
"Fetching external posts from medium.com:"
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/usr/local/lib/ruby/gems/3.1.0/gems/feedjira-3.2.2/lib/feedjira.rb:63:in `parse': No valid parser for XML. (Feedjira::NoParserAvailable)
```
**System (please complete the following information):**
 - OS: [MacOS 12.3.1 (Intel)]
 - Jekyll version [4.3.2]
- Ruby version [3.1.2]

**Additional context**

**Comment by george-gca** [comment]
I might be wrong here, but maybe `feedjira` have a lib dependecy that is not currently satisfied in the system (maybe `libxml2` idk).

**Comment by majauhar** [comment]
I am trying to find what dependency might be unfulfilled. I have installed the dependencies listed in the `feedjira` website though. What's surprising for me is how it doesn't even run successfully inside GitHub since I would assume it should only throw errors, if any, when trying to run it locally.

**Comment by majauhar** [comment]
Update: I disabled `imagemagick` and now Pages deployment works fine. However, even on fresh installation, the issue persists on my local machine.

**Comment by majauhar** [comment]
That would be the obvious work around. However, since I did not modify the source code (except the repository name), it should have built without any issue. By the way, I am working via docker now and its working fine.

**Comment by george-gca** [comment]
@majauhar agreed. But without having the same system I can't help that much. Also, apparently this is not a common error, I couldn't find any recent issues on this matter.

**Comment by eguar11011** [comment]
I am on linux with manjaro and i have the same error

**Comment by pourmand1376** [comment]
Have you tested docker? You should be fine with all OSes with docker.

**Comment by eguar11011** [comment]
> Have you tested docker? You should be fine with all OSes with docker.

@pourmand1376 

If it works well with docker

**Comment by george-gca** [comment]
If it works? It means that it is not working? Or the `If` in your answer was a typo?

**Comment by eguar11011** [comment]
> If it works? It means that it is not working? Or the `If` in your answer was a typo?
@george-gca 

yes it works well  with Docker.

**Comment by pourmand1376** [comment]
Okay, good. If that resolves your problem, please close this issue.

**Comment by dongzhuoyao** [comment]
same issue here with Mac Sonoma
