### ISSUE TITLE
Fenced code blocks with unnecessary leading space

### ISSUE THREAD

**Issue by bykhov** [alshedivat/al-folio#1494]
**Acknowledge the following**
- [X] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [X] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
I have used fenced blocks in a bulleted list (followed [this](https://gist.github.com/clintel/1155906)), and the resulting code blocks in HTML have unnecessary leading space as presented in the picture (note the selection)
![image](https://github.com/alshedivat/al-folio/assets/4847480/2f6d32b3-216c-4a8b-90f0-05c2a069030f)

**To Reproduce and Expected behavior**
* The result may be verified by the following that is shown correctly on GitHub
	
    ```python
    import tensorrt
    print(tensorrt.__version__)
    ```

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 114

**Comment by george-gca** [comment]
Actually, according to [this answer on stackoverflow](https://stackoverflow.com/a/38090598) this is an internal thing of `kramdown`:

> The gist is that the indentation for the code block in lists is determined by the column number of the first non-space character after the list item marker.

Also

> 1.·some text    =>  use 3 spaces indentation e.g.

What this means is, for the code block to be displayed correctly, you should use 3 spaces indentation (awkward, I know)
```markdown
1. We can put fenced code blocks inside nested bullets, too.
   1. Like this:
      ```c
      printf("Hello, World!");
      ```

   2. The key is to indent your fenced block by **(4 * bullet_indent_level)** spaces.
```

And this will be displayed correctly

![image](https://github.com/alshedivat/al-folio/assets/31376482/c8d85353-fe35-47c7-b32e-042b0dd780aa)
