### ISSUE TITLE
Fix weird alignment between date and title in latest posts

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#1499]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Fix the weird alignment between date and post title in `latest posts` section in about page. It should have the same aligment as the `news` section.

**To Reproduce**
https://alshedivat.github.io/al-folio/

**Expected behavior**
Same alignment as the `news` section.

**Screenshots**
![image](https://github.com/alshedivat/al-folio/assets/31376482/6b9c3ed2-8d3a-43b8-800f-01c76904745d)

**Comment by VanniPrashar** [comment]
Can I fix this please
