### ISSUE TITLE
Blog post is not showing

### ISSUE THREAD

**Issue by underdogliu** [alshedivat/al-folio#150]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
I created a copy of the website and migrate everything from my old blog. I run `bundle exec Jekyll serve` and checked the local pages and it looks perfect. But when I put it onto the page, I found that everything works still great except the blog section where I cannot find my post. 

I checked my naming of file and it's in the right form I believe: `2020-08-23-summary.md`, where the date is same as what is included in the heading:
```
---
layout: post
title: xxx
date: 2020-08-23 11:12:00-0400
---
```
I also put one of the sample posts in the repository to `_posts` and run `bundle exec jekyll serve` before pushing it but same issue happened.

**System (please complete the following information):**
 - OS: Mac OS X 10.15
 - Browser (and its version): Chrome 87, Firefox, Safari
 - Jekyll version: 3.9.0
- Ruby version: 2.7.0

**Comment by SarthakV7** [comment]
I am facing the same problem, the site loads perfectly fine on my local machine but after hosting it on github pages, all the blogs from the blog page are gone.

**Comment by grantwilliamfisher** [comment]
Same here.  It works fine locally, but on GitHub pages the blog page loads while none of the posts do.

**Comment by underdogliu** [comment]
OK so I think I kinda figured out a way to solve this problem myself. But it's not a very nice-looking solution - In general, we need to form every section as `pages`, i.e. with `page` layout. For example, here is the header of my blog post:

`---
layout: page
permalink: /blog/20200823
title: xxx
description: yyy
nav: true
---`

and here is the `blog.md` in my `_pages` directory, which is the main page:

`---
layout: page
permalink: /blog/
title: xxx
description: I write here comfortably.
nav: true
---

### 2020
* [xxx](./20200823)
`

You can see there is an external link to the path of that blog. So that concludes my solution. I still do not know what's happened with the blog post specific option but this works for me.

**Comment by taxminion** [comment]
Still struggling with this. I think it _may_ be a case of the pagination breaking. When I tested disabling pagination locally in _config.yml none of the posts showed up just like they still don't on Github Pages. The posts are there when using a direct url, but when hosted by Github Pages the blog page just cannot retrieve them for some reason.
I seriously feel like I've tried everything. At least the things I've found on google.

**Comment by underdogliu** [comment]
> Still struggling with this. I think it _may_ be a case of the pagination breaking. When I tested disabling pagination locally in _config.yml none of the posts showed up just like they still don't on Github Pages. The posts are there when using a direct url, but when hosted by Github Pages the blog page just cannot retrieve them for some reason.
> I seriously feel like I've tried everything. At least the things I've found on google.

Yes that's what I found basically as well. I treated every page (blog, pubs, etc....) as `pages` as the solution then. It works for me though but if needing some other tweaks I don't know.

**Comment by alshedivat** [comment]
Thanks for raising this issue. This sounds odd. The [demo page](https://alshedivat.github.io/al-folio/blog/) does have a few sample blog posts and everything works fine. To locate the source of this issue, could you try the following:
1. Clone al-folio to a separate repo for testing.
2. Deploy it to github page following the README instructions.
3. Copy over your blog posts to the test repo without any other changes.
4. Deploy again, and check if the posts show up or not.
5. Post a link to the test repo here so I can take a look.

**Comment by taxminion** [comment]
When I created a new clone it didn't work until I had changed `baseurl` to the name of the GitHub repository. I also had to use `./bin/deploy` without the `--user` flag (I am on Windows). I had to redo my blog from scratch, but that didn't take long, and now everything is working perfectly. Hopefully that can fix everyone else's blogs.
Thank you alshedivat for your help!

**Comment by alshedivat** [comment]
@underdogliu, @smashmath, @SarthakV7, can you confirm that you were able to resolve this issue on your own or the solution outlined by @taxminion works for you. I'll close this issue in that case. Thanks.

**Comment by underdogliu** [comment]
@alshedivat allow me to try it later today.

**Comment by smashmath** [comment]
All is good here now.

**Comment by underdogliu** [comment]
@alshedivat Did not have time to try but since I already found a solution, if others find it working, we can close the issue.

**Comment by SarthakV7** [comment]
> When I created a new clone it didn't work until I had changed `baseurl` in `_config.yml` to the name of the GitHub repository. I also had to use `./bin/deploy` without the `--user` flag (I am on Windows) to deploy to github pages. I had to redo my blog from scratch, but that didn't take long, and now everything is working perfectly. Hopefully that can fix everyone else's blogs.
> Thank you alshedivat for your help!

Thanks for the workaround @taxminion your approach works. I forked the latest `al-folio` repo, renamed it, cloned it, migrated all the required content (`_pages`, `_posts`, `_projects`, `assets/img`) from the broken repo to the new clone repo folder, updated the `_config.yml` file (also changed the `baseurl` from "/al-folio" to the renamed repo name) and finally deployed it using `./bin/deploy` (without `-u|--user` flag).
All the pages are working now.

@alshedivat @underdogliu @taxminion Thanks for the input guys!

**Comment by underdogliu** [comment]
@SarthakV7 you are very welcome and thanks for the suggestions as well! I will close this issue.

**Comment by ricardogpinho** [comment]
I still can't figure out why it works on the local server and doesn't on the github server. For some reason `{% for post in paginator.posts %}` in blog/index.html doesn't iterate on anything.

**Comment by BijayKumarPun** [comment]
I came across the exact same issue today. An acceptable workaround was to use the `./bin/deploy` command to automatically generate static files and deploy from a branch.
Be aware that using this command means we will have to run this every time a change is made. Kinda tedious, but acceptable if changes aren't too frequent.

**Comment by konradpieczynski** [comment]
This solution worked for me:
![obraz](https://user-images.githubusercontent.com/121956436/211659144-0aee8e2a-d28a-41f9-a417-d4fcb6853a5f.png)

**Comment by tostenzel** [comment]
@konradpieczynski 's solution worked for me, too! Big thanks!

**Comment by YaolinGe** [comment]
The issue still exists and my repo is username.github.io. But disappears when the repo is username.github.io/Profile. 

Any clues on how to solve that. I want to use username.github.io as the repo name, so that I can link it to another customized domain name, I don't know how to link it when the repo is username.github.io/Profile?
