### ISSUE TITLE
Socials doesnt show up after deployment 

### ISSUE THREAD

**Issue by WalidGharianiEAGLE** [alshedivat/al-folio#1506]
socials icons and embeds does not show up after deployment. Any idea how fix this ?
https://walidgharianieagle.github.io/
https://github.com/WalidGharianiEAGLE/walidgharianieagle.github.io/blob/master/_config.yml#L72

*Locally*
![local](https://github.com/alshedivat/al-folio/assets/57763453/fdaed055-f5a1-4fd3-a8c5-0dea290136db)
*After deployment*
![deployed](https://github.com/alshedivat/al-folio/assets/57763453/513fb469-8531-4ad1-a8d3-cdd16f38fc7a)

**Comment by WalidGharianiEAGLE** [comment]
The issue I'm experiencing is that none of the Font Awesome icons are displaying correctly, including the social media icons, the dark/bright mode control icon, and the # and calendar icons. This problem specifically seems to occur when using Firefox as the browser. However, when I tested my site on Google, all the icons appeared correctly. Therefore, it must be a compatibility problem between Font Awesome and Firefox ?

**Firefox deployed**
![firefox_deployed](https://github.com/alshedivat/al-folio/assets/57763453/1a4d84cf-5879-4cb4-b692-b6add3c27d35)

**Google deployed**
![google_deployed](https://github.com/alshedivat/al-folio/assets/57763453/368b2680-f82d-4521-9a78-6a02bcfe6d46)

**Comment by george-gca** [comment]
Is the [demo from the repo](https://alshedivat.github.io/al-folio/) showing correctly in your firefox?

**Comment by WalidGharianiEAGLE** [comment]
@george-gca Yes it works. OK now it is fixed. Basically, I resolved it by removing my site from the search history "Forget About the site". This solved the issue and the icons shows up correctly on Firefox.
