### ISSUE TITLE
Json-Resume integration for the CV part

### ISSUE THREAD

**Issue by arunoruto** [alshedivat/al-folio#1513]
**Is your feature request related to a problem? Please describe.**
We can all agree that writing the same things at multiple places can be tedious. So we do it once and try to reuse it everywhere else. That is what [jsonresume](https://jsonresume.org/) aims for resumes. Write all information once in a json file, put it on github gist and use it everywhere else!

**Describe the solution you'd like**
Provide a jsonresume link in the config to be loaded and populate everything in the CV section according to the schema. For that, we can use the [jekyll-get-json](https://github.com/brockfanning/jekyll-get-json) plugin like:
```yaml
jekyll_get_json:
  - data: resume
    json: "https://gist.githubusercontent.com/<username>/<id>/raw"
```
And use the data with `{{ site.data.resume }}`.
To keep compatibility with previous setups, one can prioritize the jsonresume data. If not found, populate it using the yaml file.

**Describe alternatives you've considered**
The obvious alternative is to copy all the data into the yaml file <yikes>.

**Additional context**
I am currently trying out to port the styling for jsonresume. The file will be a lot longer/messier, but maybe someone has an idea how to make it more sleek.

**EDIT**
I tried to implement it on my own, and you can see the result [here](https://academic-5lq.pages.dev/cv). The relevant changes have been made in [include](https://github.com/arunoruto/academic/tree/master/_includes/resume) with a new folder resume (time table and map have been modified), and the [cv layout](https://github.com/arunoruto/academic/blob/master/_layouts/cv.html) has been split in two.

I know, it isn't beautiful, but it works for now. Maybe someone has a more beautiful way of how to manage it?

**Comment by george-gca** [comment]
Never heard of it, but it looks interesting. Definitely worth taking a look.

**Comment by arunoruto** [comment]
I sat down and made for each category its appropriate html file (for those I need and deemed necessary). You can find them in the [resume](https://github.com/arunoruto/academic/tree/master/_includes/resume) folder in my fork of al-folio. I also modified the [cv.html](https://github.com/arunoruto/academic/blob/master/_layouts/cv.html) layout to also take into consideration the jsonresume data and prioritize it. Some sections can be skipped, like the meta files and publications, since thats already available in a seperate bib file in al-folio. In my opinion it is a nicer solution, but maybe the bib file can be generated using data from jsonresume, but jsonresume lacks some informations in that regard for now...

I haven't done anything special regarding the html files, just modified them so it works with the data provided in the jsonresume file. I will try to make something up for the language, certificates, skills, interests, and reference sections. Maybe a list of what sections should be included (or skipped) can be made, so not all of the informations are generated on the page. The list could also define the order of the items, since currently they are defined by the order in the jsonresume file.

When I am done I could make a pull request. Would you be interested?

**Comment by george-gca** [comment]
Sure, also maybe it would be interesting to add more "theming" options as a layout. For example, [this one](https://github.com/alshedivat/al-folio/pull/1339).

**Comment by arunoruto** [comment]
I created a pull request to add this feature. I also incorporated the implementation in #1339 to the best of my abilities (maybe I missed something). So far it looks good on my implementation.
I will close the issue and further discussions can be moved to #1547.

**Comment by m3lixir** [comment]
It would be nice to see the `yml` version of CV conform to the RenderCV (https://github.com/sinaatalay/rendercv) schema, then we could actually generate a PDF from the given yml.

**Comment by george-gca** [comment]
I like the idea. Would you mind sending a PR for this?
