### ISSUE TITLE
[Help Wanted] How to Change the Font of the text, both overall and the distill style blog?

### ISSUE THREAD

**Issue by majauhar** [alshedivat/al-folio#1515]
I am trying to personalise the theme and have been stuck in my attempts to change the typeface of the website. Any input on this would really be helpful. Thank you 😃

**Comment by george-gca** [comment]
To change overall, you can simply add a `font-family` spec to your body css style. More specifically, adding something like this:

```css
body {
  font-family: 'Courier New', Courier, monospace;
}
```

to your [_base.scss](https://github.com/alshedivat/al-folio/blob/master/_sass/_base.scss) file. To find more specific rules as where you want to change the font, I'd recommend using the developer tools available in [Chrome](https://developer.chrome.com/docs/devtools/overview/) or [Firefox](https://firefox-source-docs.mozilla.org/devtools-user/).

**Comment by majauhar** [comment]
Great. That works. Thank you @george-gca 😃
