### ISSUE TITLE
mini_racer problem

### ISSUE THREAD

**Issue by Abhijrathod** [alshedivat/al-folio#1520]
Resolving dependencies...
Could not find compatible versions

Because mini_racer >= 0.8.0 depends on libv8-node ~> 18.16.0.0
  and Gemfile depends on mini_racer ~> 0.8.0,
  libv8-node ~> 18.16.0.0 is required.
So, because Gemfile depends on libv8-node ~> 20.2,
  version solving has failed.

bundle exec jekyll serve
Could not find gem 'mini_racer (~> 0.8.0)' in locally installed gems.
Run `bundle install` to install missing gems.

**Comment by george-gca** [comment]
Can you provide further info? What is your setup, system version, etc?

**Comment by Abhijrathod** [comment]
it is jekyll problem in installing bundle install problem ruby

**Comment by pourmand1376** [comment]
Have you tested the docker image? It is just `docker compose up`.

Installing these dependencies manually is really painful.
