### ISSUE TITLE
Using Slim to minify docker image

### ISSUE THREAD

**Issue by pourmand1376** [alshedivat/al-folio#1550]
[Slim](https://github.com/slimtoolkit/slim) says that it can minify docker images up to 30x. I should experiment to see if it works well on our docker images.

**Comment by george-gca** [comment]
Maybe we could also ditch docker hub and migrate to using [GitHub Container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) in the same step? I've seen some other people implementing this like [here](https://github.com/asreview/asreview/pull/1341).

**Comment by pourmand1376** [comment]
> Maybe we could also ditch docker hub and migrate to using [GitHub Container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) in the same step? I've seen some other people implementing this like [here](https://github.com/asreview/asreview/pull/1341).

Does the Github Container registry solve any problem? What does it offer compared to dockerhub?

**Comment by pourmand1376** [comment]
```
docker-slim build --compose-file docker-compose.yml --target-compose-svc jekyll
```
Docker-slim build command

**Comment by pourmand1376** [comment]
To Do: https://github.com/kitabisa/docker-slim-action

**Comment by george-gca** [comment]
Oh I didn't know about the compressing feature. I suggested simply because we use GitHub already, so for keeping it all up in one provider. Also Docker did a terrible job [communicating changes lately](https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/), although they reverted their decisions.

**Comment by pourmand1376** [comment]
The slim version is now available at this URL:
```
docker pull ghcr.io/pourmand1376/al-folio:slim
```
Test it if you can.

**Comment by pourmand1376** [comment]
You can also use a one-liner to use slim the image:
```
docker run --rm -v "$PWD:/srv/jekyll/" -p "8090:8080" ghcr.io/pourmand1376/al-folio:slim
```

**Comment by george-gca** [comment]
Currently throwing an error:
> Dependency Error: Yikes! It looks like you don't have jekyll-get-json or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll-get-json gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- jekyll-get-json' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

**Comment by pourmand1376** [comment]
Let's dig it. It is far more problematic than I thought. 

Just, let this be open for a month or two. Perhaps, someone expert on docker does something. Otherwise, 400MB is not that much and it is okay for now.

**Comment by george-gca** [comment]
Maybe the only thing missing here is an updated docker image. The `jekyll-get-json` dependency it is complaining about was recently introduced in #1547. Can you try to generate a newer version so I can check if it works? Or how can I try to create one myself? Is it just the steps you posted here?

> First you should use `docker compose up` to pull the image.
> 
> Then build an optimized version using:
> 
> ```
> docker-slim build --compose-file docker-compose.yml --target-compose-svc jekyll
> ```
> 
> Then, tag the image as slim:
> 
> ```
> docker image tag amirpourmand/al-folio.slim amirpourmand/al-folio:slim
> ```
> 
> Image size is reduced to 188 MBs.

**Comment by pourmand1376** [comment]
- https://github.com/kitabisa/docker-slim-action/issues/4

**Comment by george-gca** [comment]
Can we close this issue @pourmand1376?

**Comment by pourmand1376** [comment]
Yes. This is finished. 

One thing is still left to answer. When should we make this slim version the default version? As I see, It is basically the same but less in size. However, there may be some unpredicted issues.
