### ISSUE TITLE
Beautify Table of Contents in CV

### ISSUE THREAD

**Issue by awsaf49** [alshedivat/al-folio#1551]
**Is your feature request related to a problem? Please describe.**
For "Table of Contents" in recently merged CV #1339 , when there are many contents it leaves the right side empty which looks a bit odd.

<img src="https://github.com/alshedivat/al-folio/assets/36858976/586ad713-633c-4698-94db-9bb33425912e" width="600">

**Describe the solution you'd like**

1. Option for a horizontal table of contents would be nice.  Maybe something like this,
<img src="https://github.com/alshedivat/al-folio/assets/36858976/86eba756-114f-4c57-a50e-a4e358362d5f" width="600">

2. Table of contents on the sidebar like blog??
<img src="https://github.com/alshedivat/al-folio/assets/36858976/3cf998fa-dc07-4eaf-80d2-d3c9414ebc71" width="600">

cc: @george-gca @jmrplens

**Comment by george-gca** [comment]
Maybe it could look something like [this template](https://registry.jsonresume.org/thomasdavis?theme=timeline-fixed)?

**Comment by awsaf49** [comment]
Its table of contents looks very nice. But it doesn't have the nice floating "card" view that al-folio have. So may be table of contents from the template + al-folio theme???

**Comment by george-gca** [comment]
Exactly what I was thinking. Now let's see if anyone can tackle this issue.

**Comment by DavidKrassnig** [comment]
Would you be happy with the screenshots below? If yes, I can make a pull request. Or must there be dots on the sidebar as well? (which I would be unable to do at the moment)

![Screenshot_2023-07-18_09-47-49_alfoliotocsidebar_a](https://github.com/alshedivat/al-folio/assets/96623786/908702c0-5c32-4ec0-9aea-d40d49c209b2)
![Screenshot_2023-07-18_09-47-49_alfoliotocsidebar_b](https://github.com/alshedivat/al-folio/assets/96623786/3de754f7-6690-48f3-978e-fc7f79257f09)

**Comment by awsaf49** [comment]
I think it looks nice, @george-gca  what do you think???

**Comment by george-gca** [comment]
I believe it doesn't need to have the dots, but it would look nice. Maybe something as shown in [this template](https://registry.jsonresume.org/thomasdavis?theme=timeline-fixed). But create the PR, maybe we could help to create this layout.

**Comment by awsaf49** [comment]
@george-gca I agree the `dots` would make it even better
