### ISSUE TITLE
Increase "preview" image size in "Publication"

### ISSUE THREAD

**Issue by awsaf49** [alshedivat/al-folio#1552]
**Is your feature request related to a problem? Please describe.**
Preview image size in the publication seems okay for demo images but for most of the cases figures can't be understood due to its small size. Here's how it looks for a paper in [my site](https://awsaf49.github.io/publications/),

![image](https://github.com/alshedivat/al-folio/assets/36858976/54330792-44dd-4553-b52c-6e81da74c71a)

As we can see we can barely understand what is happening on the figure. For preview of paper I think it important that the figure could be understood easily.

**Describe the solution you'd like**
Here is demo from other websites which shows preview in more bigger size or they reduce the left-right margin which make the preview image comprehensive.

1. [Site1](https://shivamduggal4.github.io/) makes the preview image larger
![image](https://github.com/alshedivat/al-folio/assets/36858976/bf5eb78d-91f7-46b7-b346-f8dd95b78154)

2. [Site 2](https://shagunuppal.github.io/) reduces the margin for publication and also makes the preview image bigger.
![image](https://github.com/alshedivat/al-folio/assets/36858976/66cd641b-a3e0-4052-9af3-38f131540b00)

**Comment by awsaf49** [comment]
cc: @george-gca

**Comment by george-gca** [comment]
Don't you think a better solution would be to allow it to be zoomable, like in the [post about images](https://alshedivat.github.io/al-folio/blog/2015/images/)?

**Comment by awsaf49** [comment]
@george-gca, 

Thanks for introducing this feature. Here's my concise feedback:

1. The **zoom** feature might not be obvious for all users, especially those unaware of it. Also, users can view full images in a new tab, eliminating the need for zoom. I think the **preview** image should provide a quick insight, while zooming feels like an extra step.

2. The zoomable image on bib tends to block content and often gets cropped due to its size, making manual image resizing a necessity. I tried to resize it using `<img src=".." height="500">`  but doesn't seem to work.

<div align="center"><img src="https://github.com/alshedivat/al-folio/assets/36858976/8a16a705-8f29-47a7-92a7-7bee3cd93c68" width="500"></div>



Thus I think larger bib image would be a great addition. Also there seems to be unused space on the right side of the title of publication. Perhaps we could provide authors with an option to choose the preview image size?

**Comment by george-gca** [comment]
Actually I believe setting the size of the image is more of a per user setting, so this is something that should be applied to a site created from this template rather to be a setting in the template itself. But maybe we could add an option for setting this in the publications page front matter.

But increasing the size doesn't exactly solve the problem with the images. In your case, for example, the texts in the ArtiFact image would probably still be too small unless you increase the size too much. I believe this should be used more like a thumbnail than anything else.

Regarding the zoom, in a PC the mouse changes its cursor to a magnifier, so I believe it is pretty obvious. Also opening in a new tab would be an extra step. Regarding the size, I believe you can tweak it with some css settings.

**Comment by awsaf49** [comment]
@george-gca I saw your site and noticed you were able to reduce the margin (empty space on both sides) also you were able to increase the preview image size in "publication". This is exactly what I am looking for. Could you kindly mention which changes I need to make to do the same?? It will resolve my issue....

Here is a visual comparison,
![image](https://github.com/alshedivat/al-folio/assets/36858976/60f2f8d6-ef9d-4940-bdd8-3598112444aa)

**Comment by george-gca** [comment]
Sure. Actually I believe the only change I made was simply to increase the `max_width` setting in `_config.yml`. I set mine to 1000px. Since the image preview size is relative to the total width, it automatically increased.

If you look at [line 6 of _layouts/bib.html](https://github.com/alshedivat/al-folio/blob/42ad10a7719ccfa9537916608bd636e18dbdd3ec/_layouts/bib.html#L6C1-L6C1) you'll see that the preview is inside a `div` with class `col-sm-2`. You can increase the number in that class (e.g.: `col-sm-3`) and decrease a little the number for the next div.

**Comment by awsaf49** [comment]
Thanks. I've changed the `max_width` and it worked nicely

But for 2nd suggestion preview image doesn't get bigger and for paper w/o preview gets misaligned,

![image](https://github.com/alshedivat/al-folio/assets/36858976/67addd57-3c2c-4f91-b74a-c8ec69fd2b79)

You can check the  [commit](https://github.com/awsaf49/awsaf49.github.io/commit/effee852256e0d267dbbc6c6d0f5e564850c8759)

**Comment by george-gca** [comment]
Sorry, this is as far as my knowledge on web dev goes 😞. I tried here some solutions but couldn't fix this. Try opening it as a bug/question issue, see if somebody else has a solution. Nice publications btw.

**Comment by awsaf49** [comment]
@george-gca I'm glad you liked them. Thanks for all the help btw :D

**Comment by lcxrocks** [comment]
> Thanks. I've changed the `max_width` and it worked nicely
> 
> But for 2nd suggestion preview image doesn't get bigger and papers w/o preview gets misaligned,
> 
> ![image](https://private-user-images.githubusercontent.com/36858976/253366520-67addd57-3c2c-4f91-b74a-c8ec69fd2b79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDc2OTcsIm5iZiI6MTcxNjM0NzM5NywicGF0aCI6Ii8zNjg1ODk3Ni8yNTMzNjY1MjAtNjdhZGRkNTctM2MyYy00ZjkxLWI3NGEtYzhlYzY5ZmQyYjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAzMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZWUzMzdlZDc1ODYxZDBiNzEwMDAxMWVkNWRjZThjZTc2ZjIzMmRhYjQ0NjZiMDBjZDNkZTk3Y2FkMjliNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DcCirUF5DiU2HBjKT-ZrHFj3Qof56EFE1kYRYmJM2H4)
> 
> You can check the [commit](https://github.com/awsaf49/awsaf49.github.io/commit/effee852256e0d267dbbc6c6d0f5e564850c8759)

Sorry to bother, but may I ask how you managed to make your publication previews so large? They look clear and pretty on such a large scale! Perhaps increasing the `max_width` isn't the final solution?
