### ISSUE TITLE
Year in `news` is clickable but shows the `blog` rather than the news of that year

### ISSUE THREAD

**Issue by bykhov** [alshedivat/al-folio#1584]
**Acknowledge the following**
- [X] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [X] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Year in `news` is clickable but shows the `blog` rather than the news of that year.
![image](https://github.com/alshedivat/al-folio/assets/4847480/4257c077-f1f0-47d0-9044-77562ca5157e)

**To Reproduce**
1. Go to [news](https://alshedivat.github.io/al-folio/news/announcement_2/)
2. Click on 2015
3. See [blogs](https://alshedivat.github.io/al-folio/blog/2015/) and not news as expected.

**Additional context**
As a related feature, maybe tags and categories support in `news` can be added while fixing this issue.

**Comment by george-gca** [comment]
Since we use `jekyll-archives` plugin to handle this and it can only handle one collection, I would suggest removing the link to see all news by year from the page. What do you think?

**Comment by bykhov** [comment]
> Since we use `jekyll-archives` plugin to handle this and it can only handle one collection, I would suggest removing the link to see all news by year from the page. What do you think?

As far as tags and categories can be supported only for one collection  - it is probably the only solution.

**Comment by george-gca** [comment]
Just giving an update about this: I decided to create [jekyll-archives-v2](https://rubygems.org/gems/jekyll-archives-v2), which is basically `jekyll-archives` without the limitation of working only for posts. Haven't updated the docs yet, but you can see how to use it in #2866.
