### ISSUE TITLE
Inconsistent page width between different pages

### ISSUE THREAD

**Issue by ma-sadeghi** [alshedivat/al-folio#1591]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Page width is inconsistent between different tabs. For example, on my screen, the `body` element "about", "blog", "publications", "repositories", and "cv" is 1712px, whereas that in "projects" and "teaching" is 1727px. The width itself is not a problem, but it causes misalignment of the content when switching between different pages. 

**To Reproduce**
1. Go to [blog](https://al-folio.github.io/blog/)
2. Now switch to [projects](https://al-folio.github.io/blog/)
3. Notice that everything jumps to the right by about 15px (on my screen)
4. Now switch back to blog
5. Notice that everything jumps to the left by about 15px...

**Expected behavior**
That we don't see the jump and the content stays aligned between different pages.

**Screenshots**
![image](https://github.com/alshedivat/al-folio/assets/14086031/2136efd4-b1f7-421f-b1b8-5f9ab9b66fce)
![image](https://github.com/alshedivat/al-folio/assets/14086031/7cc246a6-b6ca-4042-8fb8-60c8bbb49e32)

**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser (and its version): Chrome 114.0.5735.198
 - Jekyll version: N/A (the bug can be reproduced using the official website)
 - Ruby version: N/A (the bug can be reproduced using the official website)

**Additional context**
N/A

**Comment by alshedivat** [comment]
I believe the difference you see is due to the scroll bar on the blog page. you can see the same effect on many other websites, like apple.com (eg, compare the the top menu bar on their home page vs account page).

**Comment by ma-sadeghi** [comment]
@alshedivat Thanks! You're right, forgive the OCD :smile:
