### ISSUE TITLE
Change Comments type to Announcements in repo

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#1608]
Don't really know if it would fix this, but anyway. There are a lot of comments that were created from derived sites, as can be seen [here](https://github.com/alshedivat/al-folio/discussions/categories/comments).

I was taking a look at the [giscus site](https://giscus.app/), and it has this line:

> Choose the discussion category where new discussions will be created. It is recommended to use a category with the Announcements type so that new discussions can only be created by maintainers and giscus.

I found out that the `Comments` category in al-folio is not of type `Announcements`, so maybe that's why there are so many comments created from derived sites. Maybe [changing its type](https://github.com/alshedivat/al-folio/discussions/categories/38542202/edit) would solve this?

PS: this can only be done by @alshedivat I believe.

**Comment by george-gca** [comment]
@alshedivat did you take a look at this? I believe this would prevent people that use this template from commenting in their site and the comments appearing in the discussions on this repo.

**Comment by alshedivat** [comment]
switched comments to announcements type. let's see if that works.
