### ISSUE TITLE
Mermaid Diagrams in Dark Mode

### ISSUE THREAD

**Issue by DavidKrassnig** [alshedivat/al-folio#1609]
I noticed that mermaid diagrams don't render correctly in dark mode (or, at least, not  really legibly). The dark colours should be switched to bright colours to contrast against the dark background..

**Current look:**
![mermaidiagram_dark_alfolio](https://github.com/alshedivat/al-folio/assets/96623786/f3831b34-8d4e-40b0-95cf-b0d028940e6c)

**Very same mermaid diagram rendered by, e.g., jekyll-theme-chirpy, for comparison:**
![mermaidiagram_dark_chirpy](https://github.com/alshedivat/al-folio/assets/96623786/3792b9a6-697d-4f9a-a8e1-1b9c4e8dc455)

I assume that the style sheets need to be modified accordingly. Unfortunately, not my field of expertise at all.

**Comment by george-gca** [comment]
Just verified and [mermaid support dark themes](https://mermaid.js.org/config/theming.html#available-themes). It is a question of changing this when changing to dark mode, probably the same way it is done with other elements in [assets/js/theme.js](https://github.com/alshedivat/al-folio/blob/master/assets/js/theme.js). If no one tackles this, maybe I can take a look, but not until next week.

**Comment by george-gca** [comment]
I might be wrong about this, but as I understood this can't be done so easily in our case.

We use [jekyll-diagrams](https://github.com/zhustec/jekyll-diagrams) plugin which takes care of rendering the diagram as a svg. It generates the svg "offline" and embed it directly into the html. As a result, it doesn't make any include to the `mermaid.js`.

If you check the template you sent, it does include `mermaid.min.js`, so it can dinamically render the svg and change its properties. So it is possible in that template to change mermaid theme and tell it to re-render the svg.

What you guys think @alshedivat @pourmand1376? The best solution I could think here would be to drop this plugin and use mermaid as an include so we could dinamically change this.

**Comment by pourmand1376** [comment]
I agree too. It is better to have an online version so that we can dynamically generate mermaid diagrams on-the-flow. 

How much is the size of this `mermaid.mis.js`?

Also, we should load it only if we have a mermaid diagram on that specific page. This could be tagged by some property like `has_mermaid` in page properties.

**Comment by george-gca** [comment]
Apparently [mermaid.min.js](https://cdn.jsdelivr.net/npm/mermaid@10.3.0/dist/mermaid.min.js) is 2.78 MB.

The [template](https://github.com/cotes2020/jekyll-theme-chirpy) @DavidKrassnig cited use mermaid this way, and it [has a solution](https://github.com/cotes2020/jekyll-theme-chirpy/blob/e8ef69ad1784661c5bb06dbcf530cfa37af63383/_includes/mermaid.html#L15) for theme changing.

**Comment by reinaldoacdc** [comment]
I'm not using jekyll-diagrams, I'm  using mermaid this way: 

First, In the page I want to load mermaid I declare on the top: 
`mermaid: true` 

So in the __includes/footer.html I import the mermaid script for this pages
```ruby
{% if page.mermaid %}
  {% include scripts/mermaid.html %}
{% endif %}
```

And finally in my scripts/mermaid.html I detect the theme and use just like this
```html
<script src="https://cdn.jsdelivr.net/npm/mermaid@10.3.0/dist/mermaid.min.js"></script>

<script>
  let giscusTheme = localStorage.getItem("theme")
  document.addEventListener('DOMContentLoaded', function () {
    mermaid.initialize({
      startOnLoad: true,
      theme: giscusTheme,
    })
    window.mermaid.init(undefined, document.querySelectorAll('.language-mermaid'))
  });

</script>
```

**Comment by reinaldoacdc** [comment]
Just a little update: 

Doing this way, it is also possible to use D3 to Zoom in and out, and move the svg with the mouse throught the canvas. 

Changing the code like this:
https://github.com/reinaldoacdc/reinaldoacdc.github.io/commit/1fd84b828d5e4568c146faf61ddc59d300700d0a

And the result is like this: 
https://reinaldoacdc.github.io/projects/1_project/
