### ISSUE TITLE
jekyll 3.9.0 | Error:  tried to create Proc object without a block

### ISSUE THREAD

**Issue by monkeywithacupcake** [alshedivat/al-folio#161]
**Acknowledge the following**
- [x ] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [ x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x ] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
cloned repo does not compile

**To Reproduce**
1. Git clone repo
2. cd al-folio
3. bundle install
4. bundle exec Jekyll serve
5. get error

**Expected behavior**
should serve the default site on localhost 

**Screenshots**

**System (please complete the following information):**
 - OS: Big Sur 11.0.1
 - Browser (and its version) [e.g. chrome, safari] NA Safari
 - Jekyll version [e.g. 3.8.7] 3.9.0
- Ruby version [e.g. 2.6.5] 3.0.0

**Additional context**
I can serve other Jekyll sites
Problem appears to be partially due to biblography.rb call to `&Proc.new` but I cannot confirm. Commenting out offending code just moved the problem somewhere else.

**Comment by monkeywithacupcake** [comment]
If I update the Gemfile to specify a Jekyll version, comment out the GitHub-pages, and add the webrick gem, I can get it to work. I don't really know why, though.

## Gemfile

```
source 'https://rubygems.org'
group :jekyll_plugins do
    #gem 'github-pages'
    gem "jekyll", "~> 4.2.0"
    gem 'jekyll-email-protect'
    gem 'jekyll-github-metadata'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
end
```

**Comment by alshedivat** [comment]
It looks like your ruby version 3.0.0 is too recent. I'm able to reproduce the error with ruby 3.0.0, but it works just fine with 2.6.5. I suggest installing a different version. You can manage multiple ruby environments using [rbenv](https://github.com/rbenv/rbenv).

**Comment by adib2149** [comment]
Just wanted to mention, I am also facing the same issue.

**Comment by alshedivat** [comment]
@adib2149, please use ruby version 2.x instead of 3 for now. Some of the gems do not support ruby 3 as it came out just recently. I'll look into supporting ruby 3 once things stabilize later this year.

**Comment by adib2149** [comment]
> @adib2149, please use ruby version 2.x instead of 3 for now. Some of the gems do not support ruby 3 as it came out just recently. I'll look into supporting ruby 3 once things stabilize later this year.

Sounds good.

**Comment by postylem** [comment]
I was getting the same issue.

For anyone getting here and realizing this means they finally need to look into what RVM is, this is what I ran to use the earlier ruby version, in case it's helpful.  First, install RVM: `\curl -sSL https://get.rvm.io | bash -s stable`, then use

```
rvm install 2.7.2 && rvm use 2.7.2
```

I also added a line in my Gemfile

```ruby
group :jekyll_plugins do
    # ....
    gem 'jekyll', '3.7.3'
    # ....
end
```

Then I re-ran
```
bundle install
```

With Ruby v2.7.2 and jekyll v3.7.3, I did not run into the issue anymore.

**Comment by monkeywithacupcake** [comment]
If you don't use RVM or you just want to use ruby3 for any other reason, my changes to the gemfile did make it work for me. It might work for you that way as well.

**Comment by alshedivat** [comment]
@monkeywithacupcake, good point, it looks like ruby3 could work if you remove `github-pages` (https://github.com/github/pages-gem/issues/752) and add `webrick` (as you did). Technically, `github-pages` is unnecessary for the current workflow.

**Comment by jrennstich** [comment]
Also facing issues here. Followed the above stated advice and ran into the following error now:
> bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/3.0.0/bin/jekyll)
/usr/local/lib/ruby/gems/3.0.0/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `require': cannot load such file -- rexml/parsers/baseparser (LoadError)

I did change the Gem file, downgraded to jekyll 3.7.2, ran bundle.

Any suggestions how to fix this?

**Comment by jrennstich** [comment]
I am still running into trouble (MacOS Big Sur v. 11.2.3 (20D91)). I followed the advice and downgraded ruby v. 2.7.2 and jekyll v. 3.7.3. Now I get the following error:
```
Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
jekyll 3.7.3 | Error:  jekyll-paginate
```
When I downgrade and change my Gem file to include `paginate` instead of `pgainate-v2` using
`    gem 'jekyll-paginate' `
I get the following error
```
  Dependency Error: Yikes! It looks like you don't have pygments or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- pygments' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
```
Any suggestions how to fix this? I am lost.

**Comment by AhmedSalih3d** [comment]
Hey guys, 2 years later this is still an issue. Was it ever fixed?

Using ruby 3.0, jekyll-scholar does not work.

Kind regards

**Comment by george-gca** [comment]
Or you could update your code to the latest version of the template. As you can see [here](https://github.com/alshedivat/al-folio/blob/b607e580adbf2b96194dce79146f8aa201016da3/.github/workflows/deploy.yml#L67) it builds the site using ruby 3.2.2.
