### ISSUE TITLE
cv.yml doesn't change the website

### ISSUE THREAD

**Issue by YuliaInn** [alshedivat/al-folio#1612]
I am trying to make changes in the CV section. In the file _pages/cv.md I was able to change the page description and the link to the pdf file of my cv. However, the next part that I thought was supposed to be changed in _data/cv.yml isn't displayed on the website after edits. 

this is the cv.md file:
![Screen Shot 2023-07-27 at 11 00 05 AM](https://github.com/alshedivat/al-folio/assets/54861076/4db69d99-3a06-4b23-b240-47aa5bf05159)

this is cv.yml:
![Screen Shot 2023-07-27 at 10 58 13 AM](https://github.com/alshedivat/al-folio/assets/54861076/09e76f71-d295-42dc-8910-3f87ca3500e4)

and this is what the website looks like:
![Screen Shot 2023-07-27 at 10 57 06 AM](https://github.com/alshedivat/al-folio/assets/54861076/00dac36e-9bb0-4f9c-a4f0-a3ba5a43ce1e)

how to change the part "table of content" and everything after that?

**Comment by george-gca** [comment]
Check #1611 for answers. But I will open a new feature request to make it clearer on the README.
