### ISSUE TITLE
Publications doesn't follow the max_width from config when not using preview

### ISSUE THREAD

**Issue by aakashba** [alshedivat/al-folio#1665]
I changed the max width of my site in the config file, which seems to work for all pages except the publication page. I'm not using the "preview" keyword in bibtex for my publications, it seems it leaves the preview space anyway making for an awkward page width like the difference between the width of the news and publications sections on my first page: 

https://aakashba.github.io

How do I get it to use full width when I don't plan on using the preview keyword?

Edit: Additionally, this empty space to the left of the publication entry is not on the mobile versions, only the desktop website.

**Comment by aakashba** [comment]
I solved it myself by manually commenting out the block that adds in preview in bib.html. But the default should probably be no margin if there is no preview.

**Comment by george-gca** [comment]
In your specific case you didn't use neither `preview` nor `abbr`. The template was thought with at least one of these 2 items in mind. This was made to keep the margins of the publications the same when you have publications with both (or only one) of these options, as can be seen in the demo:

![image](https://github.com/alshedivat/al-folio/assets/31376482/b8248eef-9be7-4f72-a834-d9b2ad324e00)

We could add some verification in the template for this, but then we would have to check if every bib entry doesn't have any of these entries, if not it would create a single entry with weird margin. In your specific case you could also do like this:

```html
      <div class="row">
        <!-- add this if surrounding this whole area -->
        {%- if entry.preview or entry.abbr -%}
          <div class="col-sm-2 {% if entry.preview %}preview{% else %}abbr{% endif %}">
          {%- if entry.preview -%}
            {% if entry.preview contains '://' -%}
            <img data-zoomable class="preview z-depth-1 rounded" src="{{ entry.preview }}">
            {%- else -%}
              {%- assign entry_path = entry.preview | prepend: '/assets/img/publication_preview/' -%}
              {% include figure.html
              path=entry_path
              class="preview z-depth-1 rounded"
              zoomable=true
              alt=entry.preview -%}
            {%- endif -%}
          {%- elsif entry.abbr -%}
            {%- if site.data.venues[entry.abbr] -%}
              {%- assign venue_style = nil -%}
              {%- if site.data.venues[entry.abbr].color != blank -%}
                {%- assign venue_style = site.data.venues[entry.abbr].color | prepend: 'style="background-color:' | append: '"' -%}
              {%- endif -%}
              <abbr class="badge" {% if venue_style %}{{venue_style}}{% endif %}><a href="{{site.data.venues[entry.abbr].url}}">{{entry.abbr}}</a></abbr>
            {%- else -%}
              <abbr class="badge">{{entry.abbr}}</abbr>
            {%- endif -%}
          {%- endif -%}
          </div>
        {%- endif -%}
```
