### ISSUE TITLE
Images not shown after deployment, working locally MacOS

### ISSUE THREAD

**Issue by saltoricristiano** [alshedivat/al-folio#1675]
Hello!

Thanks for the amazing job you are doing!
I'm trying to deploy my personal website, but images are not shown at all after deployment (using docker-compose up), see picture. Differently, if I run locally, everything works!
<img width="355" alt="Screenshot 2023-08-26 at 13 46 45" src="https://github.com/alshedivat/al-folio/assets/56728964/90d3fb84-3061-42af-92c5-73ee25356ffe">
I'm running on:
 - OS: MacOS Ventura 13.3.1
 - Browser (and its version): Safari and Opera

Thanks for the help in advance!
saltoricristiano

**Comment by ginlov** [comment]
Hey guy, how do you deal with this problem? I have the same one and it is even worst when the items in blogs also disappear (working when deploy locally).

**Comment by saltoricristiano** [comment]
Hi, I solved putting the correct URL in the config.yaml! It was the wrong one therefore everything was not loaded on my webpage. Not it works!
