### ISSUE TITLE
Error Running jekyll serve

### ISSUE THREAD

**Issue by JeelChatrola** [alshedivat/al-folio#1696]
bundle exec jekyll serve --lsi

shows error
'''
Configuration file: /home/jeelros/Github/JeelChatrola.github.io/_config.yml
bundler: failed to load command: jekyll (/home/jeelros/gems/bin/jekyll)
/home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/cache.rb:181:in `initialize': Permission denied @ rb_sysopen - /home/jeelros/Github/JeelChatrola.github.io/.jekyll-cache/Jekyll/Cache/Jekyll--Cache/b7/9606fb3afea5bd1609ed40b622142f1c98125abcfe89a76a661b0e8e343910 (Errno::EACCES)
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/cache.rb:181:in `open'
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/cache.rb:181:in `dump'
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/cache.rb:97:in `[]='
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/cache.rb:41:in `clear_if_config_changed'
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/site.rb:118:in `reset'
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/site.rb:35:in `initialize'
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:30:in `new'
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:30:in `process'
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/jeelros/gems/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /home/jeelros/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/jeelros/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/jeelros/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/jeelros/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/jeelros/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/jeelros/gems/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
	from /home/jeelros/gems/bin/jekyll:25:in `load'
	from /home/jeelros/gems/bin/jekyll:25:in `<top (required)>'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:58:in `load'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:23:in `run'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/cli.rb:492:in `exec'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/cli.rb:34:in `dispatch'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/cli.rb:28:in `start'
	from /home/jeelros/gems/gems/bundler-2.4.19/exe/bundle:37:in `block in <top (required)>'
	from /home/jeelros/gems/gems/bundler-2.4.19/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /home/jeelros/gems/gems/bundler-2.4.19/exe/bundle:29:in `<top (required)>'
	from /home/jeelros/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /home/jeelros/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'

'''

**Comment by pourmand1376** [comment]
Manual installation is not supported anymore. We have made it `legacy` installation because of problems like this. 

Please use docker installation if you wish to use it locally.

**Comment by JeelChatrola** [comment]
I tried from docker as per the readme file, but it still gives an error
![image](https://github.com/alshedivat/al-folio/assets/56308805/16e66a83-2644-4ad4-a4ff-29db88b277d8)

**Comment by JeelChatrola** [comment]
jeel@Legion-Y540:~/Github/jeelchatrola.github.io$ docker-compose -f docker-local.yml up
WARN[0000] Found orphan containers ([jeelchatrolagithubio-jekyll-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
[+] Running 1/1
 ✔ Container jeelchatrolagithubio-jekyll_custom-1  R...                                                  0.2s
Attaching to jeelchatrolagithubio-jekyll_custom-1
jeelchatrolagithubio-jekyll_custom-1  | Resolving dependencies...
jeelchatrolagithubio-jekyll_custom-1  |   Logging at level: debug
jeelchatrolagithubio-jekyll_custom-1  |     Jekyll Version: 4.3.2
jeelchatrolagithubio-jekyll_custom-1  | Configuration file: /srv/jekyll/_config.yml
jeelchatrolagithubio-jekyll_custom-1  |   Logging at level: debug
jeelchatrolagithubio-jekyll_custom-1  |     Jekyll Version: 4.3.2
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: /srv/jekyll/_plugins/cache-bust.rb
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: /srv/jekyll/_plugins/details.rb
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: /srv/jekyll/_plugins/external-posts.rb
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: /srv/jekyll/_plugins/file-exists.rb
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: /srv/jekyll/_plugins/hideCustomBibtex.rb
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-archives
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-diagrams
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-email-protect
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-feed
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-get-json
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-imagemagick
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-jupyter-notebook
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-link-attributes
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-minifier
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-paginate-v2
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll/scholar
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-sitemap
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-toc
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jekyll-twitter-plugin
jeelchatrolagithubio-jekyll_custom-1  |          Requiring: jemoji
jeelchatrolagithubio-jekyll_custom-1  |             Source: /srv/jekyll
jeelchatrolagithubio-jekyll_custom-1  |        Destination: /srv/jekyll/_site
jeelchatrolagithubio-jekyll_custom-1  |  Incremental build: disabled. Enable with --incremental
jeelchatrolagithubio-jekyll_custom-1  |       Generating...
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/about.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/archive-category.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/archive-tag.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/archive-year.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/bib.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/cv.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/default.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/distill.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/none.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/page.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: /_layouts/post.html
jeelchatrolagithubio-jekyll_custom-1  |        EntryFilter: excluded /Gemfile
jeelchatrolagithubio-jekyll_custom-1  |        EntryFilter: excluded /Gemfile.lock
jeelchatrolagithubio-jekyll_custom-1  |        EntryFilter: excluded /bin
jeelchatrolagithubio-jekyll_custom-1  |        EntryFilter: excluded /.jekyll-cache
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2015-03-15-formatting-and-links.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2015-05-15-images.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2015-07-15-code.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2015-10-20-disqus-comments.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2015-10-20-math.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2018-12-22-distill.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2020-09-28-github-metadata.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2020-09-28-twitter.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2021-07-04-diagrams.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2022-02-01-redirect.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2022-12-10-giscus-comments.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2023-03-20-table-of-contents.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2023-03-21-tables.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2023-04-24-videos.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2023-04-25-audios.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2023-04-25-sidebar-table-of-contents.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2023-05-12-custom-blockquotes.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2023-07-04-jupyter-notebook.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _posts/2023-07-12-post-bibliography.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _pages/repositories.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _pages/projects.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _pages/about.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _pages/dropdown.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _pages/publications.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _pages/cv.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _pages/teaching.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: blog/index.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: assets/css/main.scss
jeelchatrolagithubio-jekyll_custom-1  |            Reading: robots.txt
jeelchatrolagithubio-jekyll_custom-1  |            Reading: news.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: 404.html
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _news/announcement_1.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _news/announcement_2.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _news/announcement_3.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _projects/1_project.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _projects/2_project.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _projects/3_project.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _projects/4_project.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _projects/5_project.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _projects/6_project.md
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _data/coauthors.yml
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _data/cv.yml
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _data/repositories.yml
jeelchatrolagithubio-jekyll_custom-1  |            Reading: _data/venues.yml
jeelchatrolagithubio-jekyll_custom-1  |         Generating: JekyllGetJson::GetJsonGenerator finished in 0.0007562 seconds.
jeelchatrolagithubio-jekyll_custom-1  |         Generating: Jekyll::Scholar::DetailsGenerator finished in 5.34e-05 seconds.
jeelchatrolagithubio-jekyll_custom-1  | "Fetching external posts from :"
jeelchatrolagithubio-jekyll_custom-1  | /var/lib/gems/3.1.0/gems/httparty-0.21.0/lib/httparty/request.rb:87:in `path=': bad argument (expected URI object or URI string) (ArgumentError)
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/httparty-0.21.0/lib/httparty/request.rb:75:in `initialize'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/httparty-0.21.0/lib/httparty.rb:612:in `new'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/httparty-0.21.0/lib/httparty.rb:612:in `perform_request'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/httparty-0.21.0/lib/httparty.rb:526:in `get'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/httparty-0.21.0/lib/httparty.rb:645:in `get'
jeelchatrolagithubio-jekyll_custom-1  |         from /srv/jekyll/_plugins/external-posts.rb:14:in `block in generate'
jeelchatrolagithubio-jekyll_custom-1  |         from /srv/jekyll/_plugins/external-posts.rb:12:in `each'
jeelchatrolagithubio-jekyll_custom-1  |         from /srv/jekyll/_plugins/external-posts.rb:12:in `generate'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:193:in `block in generate'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:191:in `each'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:191:in `generate'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:79:in `process'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
jeelchatrolagithubio-jekyll_custom-1  |         from /usr/local/bin/jekyll:25:in `load'
jeelchatrolagithubio-jekyll_custom-1  |         from /usr/local/bin/jekyll:25:in `<main>'
jeelchatrolagithubio-jekyll_custom-1 exited with code 1

**Comment by pourmand1376** [comment]
What is you _config.yml?

**Comment by JeelChatrola** [comment]
# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Jeel
middle_name:
last_name: Chatrola
email: jeelchatrola046@gmail.com
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: Robotics, Computer Vision, Artificial Intelligence, Control  # add your own keywords or leave empty

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://jeelchatrola.github.io/ # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: false # set to true if you want to display last updated in the footer
impressum_path:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# code highlighter theme
highlight_theme_light: github   # https://github.com/jwarby/jekyll-pygments-themes
highlight_theme_dark: native    # https://github.com/jwarby/jekyll-pygments-themes

# repo color theme
repo_theme_light: default       # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark           # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat    # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed  # https://github.com/ryo-ma/github-profile-trophy

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true

# Dimensions
max_width: 800px

# TODO: add layout settings (single page vs. multi-page)

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
serve_schema_org: false # Include Schema.org in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: JeelChatrola# your GitHub user name
gitlab_username: # your GitLab user name
twitter_username: # your Twitter handle
mastodon_username: # your mastodon instance+username in the format instance.tld/@username
linkedin_username: jeelchatrola # your LinkedIn user name
telegram_username: # your Telegram user name
scholar_userid: Jeel Chatrola # your Google Scholar ID
semanticscholar_id: # your Semantic Scholar ID
whatsapp_number: # your WhatsApp number (full phone number in international format. Omit any zeroes, brackets, or dashes when adding the phone number in international format.)
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
lattes_id: # your ID on Lattes (Brazilian Lattes CV)
osf_id: # your OSF ID
research_gate_profile: # your profile on ResearchGate
scopus_id: # your profile on Scopus
blogger_url: # your blogger URL
work_url: # work page URL
keybase_username: # your keybase user name
wikidata_id: # your wikidata id
wikipedia_id: # your wikipedia id (Case sensitive)
dblp_url: # your DBLP profile url
stackoverflow_id: # your stackoverflow id
kaggle_id: # your kaggle id
lastfm_id: # your lastfm id
spotify_id: # your spotify id
pinterest_id: # your pinterest id
unsplash_id: # your unsplash id
instagram_id: # your instagram id
facebook_id: # your facebook id
youtube_id: # your youtube channel id (youtube.com/@<youtube_id>)
discord_id: # your discord id (18-digit unique numerical identifier)
zotero_username: # your zotero username

contact_note: >
  I am open to collaborations and internship oppurtunities, please feel free to email me

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics:  # your Google Analytics measurement ID (format: G-XXXXXXXXXX)
cronitor_analytics:  # cronitor RUM analytics site ID (format: XXXXXXXXX)

google_site_verification:  # your google-site-verification ID (Google Search Console)
bing_site_verification:  # out your bing-site-verification ID (Bing Webmaster)

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: jeelchatrola # blog_name will be displayed in your blog page
blog_nav_title: blog # your blog must have a title for it to be displayed in the nav bar
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/  

# Pagination
pagination:
  enabled: true

related_blog_posts:
  enabled: false
  max_related: 5

# Giscus comments (RECOMMENDED)
# Follow instructions on https://giscus.app/ to setup for your repo to fill out
# the information below.
giscus:
  repo: alshedivat/al-folio      # <your-github-user-name>/<your-github-repo-name>
  repo_id: MDEwOlJlcG9zaXRvcnk2MDAyNDM2NQ==
  category: Comments             # name of the category under which discussions will be created
  category_id: DIC_kwDOA5PmLc4CTBt6
  mapping: title                 # identify discussions by post title
  strict: 1                      # use strict identification mode
  reactions_enabled: 1           # enable (1) or disable (0) emoji reactions
  input_position: bottom         # whether to display input form below (bottom) or above (top) the comments
  theme: preferred_color_scheme  # name of the color scheme (preferred works well with al-folio light/dark mode)
  emit_metadata: 0
  lang: en

# Disqus comments (DEPRECATED)
disqus_shortname: al-folio # put your disqus shortname
# https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# External sources.
# If you have blog posts published on medium.com or other external sources,
# you can display them in your blog by adding a link to the RSS feed.
external_sources:
  - name: 
    rss_url:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

announcements:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 news items
  limit: 5 # leave blank to include all the news in the `_news` folder

latest_posts:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 new posts items
  limit: 3 # leave blank to include all the blog posts

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick  
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ['robots.txt']
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  enabled: [year, tags, categories] # enables year, tag and category archives (remove if you need to disable one of them).
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

display_tags: ['formatting', 'images', 'links', 'math', 'code'] # these tags will be displayed on the front page of your blog
display_categories: ['blockquotes'] # these categories will be displayed on the front page of your blog

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Chatrola]
  first_name: [Jeel]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

badges: # Display different badges for your publications
  altmetric_badge: true # Altmetric badge (https://www.altmetric.com/products/altmetric-badges/)
  dimensions_badge: true # Dimensions badge (https://badge.dimensions.ai/)

# Filter out certain bibtex entry keywords used internally from the bib output
filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website, preview, altmetric]

# Maximum number of authors to be shown for each publication (more authors are visible on click)
max_author_limit: 3  # leave blank to always show all authors
more_authors_animation_delay: 10  # more authors are revealed on click using animation; smaller delay means faster animation


# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

# These are the defaults
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:


# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: false # enables responsive images for your site (recommended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  output_formats:
    webp: "-resize 800x"

# -----------------------------------------------------------------------------
# Jekyll Diagrams
# -----------------------------------------------------------------------------

jekyll-diagrams:
    # configuration, see https://github.com/zhustec/jekyll-diagrams.
    # feel free to comment out this section if not using jekyll diagrams.

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    false  # enables google analytics
enable_cronitor_analytics: false  # enables cronitor RUM analytics
enable_google_verification: false  # enables google site verification
enable_bing_verification:   false  # enables bing site verification
enable_masonry:             true   # enables automatic project cards arrangement
enable_math:                true   # enables math typesetting (uses MathJax)
enable_tooltips:            false  # enables automatic tooltip links generated
                                   # for each section titles on pages and posts
enable_darkmode:            true   # enables switching between light/dark modes
enable_navbar_social:       false  # enables displaying social links in the
                                   # navbar on the about page
enable_project_categories:  true   # enables categorization of projects into
                                   # multiple categories
enable_medium_zoom:         true   # enables image zoom feature (as on medium.com)
enable_progressbar:         true   # enables a horizontal progress bar linked to the vertical scroll position

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
bootstrap:
  version: "4.6.1"
  integrity:
    css: "sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY="
    js: "sha256-fgLAgv7fyCGopR/gBNq2iW3ZKIdqIcyshnUULC4vex8="
bootstrap-table:
  version: "1.21.4"
fontawesome:
  version: "6.4.0"
  integrity: "sha256-HtsXJanqjKTc8vVQjO4YMhiqFoXkfBsjBWcX91T1jr8="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
mathjax:
  version: "3.2.0"
masonry:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
medium_zoom:
  version: "1.0.8"
  integrity: "sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8="

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json # it can also be an url
jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - certificates
  - skills
  - languages
  - interests
  - references

**Comment by george-gca** [comment]
Based on this part of the stacktrace:

```
jeelchatrolagithubio-jekyll_custom-1 | "Fetching external posts from :"
jeelchatrolagithubio-jekyll_custom-1 | /var/lib/gems/3.1.0/gems/httparty-0.21.0/lib/httparty/request.rb:87:in path=': bad argument (expected URI object or URI string) (ArgumentError) jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/httparty-0.21.0/lib/httparty/request.rb:75:in initialize'
jeelchatrolagithubio-jekyll_custom-1 | from /var/lib/gems/3.1.0/gems/httparty-0.21.0/lib/httparty.rb:612:in new' jeelchatrolagithubio-jekyll_custom-1  |         from /var/lib/gems/3.1.0/gems/httparty-0.21.0/lib/httparty.rb:612:in perform_request'
```

it seems problems with the external post. It is trying to get the url, which you left blank. Comment out these lines in your `_config.yml` instead of leaving it empty:

```yml
# External sources.
# If you have blog posts published on medium.com or other external sources,
# you can display them in your blog by adding a link to the RSS feed.
external_sources:
  - name: 
    rss_url:
```
