### ISSUE TITLE
_posts.scss ignored by jekyll serve

### ISSUE THREAD

**Issue by samfearn** [alshedivat/al-folio#17]
When I modify the `_sass/_posts.scss` file while jekyll serve is running, the auto-updater doesn't pick up on the change to the file, so I have to stop the serve and re-run it to see the changes. This is the only files I've noticed this happening with so far, though I haven't systematically checked all the files. Renaming it seems to fix the problem - obviously this requires changing the relevant import statement in `assests/css/main.scss`. Anyone have any idea what's going on here?

**Comment by alshedivat** [comment]
Interesting. Could you perhaps provide more info on the ruby and jekyll versions you used?

**Comment by samfearn** [comment]
Sure. Running `ruby -v` gives me

    ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

Running `bundle update jekyll` tells me I'm using jekyll 3.7.3

**Comment by alshedivat** [comment]
Not sure if this is still an issue (also, may be not relevant after the update to v0.3).
