### ISSUE TITLE
Select language

### ISSUE THREAD

**Issue by anarichter** [alshedivat/al-folio#1721]
With a view to communicate to a broader audience, I wanted to have my website in two languages: English (as it is) and Portuguese (of which I am a native speaker). 

For that, I gathered either one of these alternatives would do the job: 

1) having an option like the light/dark theme so the whole website would be displayed in the option selected (i.e. language);
2) specifically on the Blog page, allowing one to choose in which language the posts are to be shown.

Would any of this be feasible (or make sense)?

**Comment by george-gca** [comment]
Take a look at [multi-language-al-folio](https://github.com/george-gca/multi-language-al-folio). It is a fork of this repo I created specifically for this, and which I intend to keep as up-to-date as possible with this repo.

**Comment by anarichter** [comment]
Oh wow, this is exactly what I was looking for. Thanks a lot!
