### ISSUE TITLE
Menu button not visible in dark mode on mobile

### ISSUE THREAD

**Issue by junghans** [alshedivat/al-folio#173]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
In dark mode, the page menu button is not visible. 

**To Reproduce**
1. Go to http://alshedivat.github.io/al-folio/ on your phone
2. Click on 'Dark Mode'
3. Menu button not visible, but still here

**Expected behavior**
Menu button is visible.

**Screenshots**
Light theme:
![Screenshot_20210105-083224](https://user-images.githubusercontent.com/439483/103665614-d970b980-4f30-11eb-8e09-615e7e2ebaff.png)
Dark theme:
![Screenshot_20210105-083216](https://user-images.githubusercontent.com/439483/103665642-e2618b00-4f30-11eb-8145-51290f0d0c01.png)

**System (please complete the following information):**
 - OS: Android 10
 - Browser: Chrome

**Additional context**

**Comment by Jongwoo-Shim** [comment]
Bug fix : https://github.com/alshedivat/al-folio/pull/178
* Tested on mobile and web-dev mode.

**Comment by junghans** [comment]
Fixed by #178.
