### ISSUE TITLE
tables have really small padding

### ISSUE THREAD

**Issue by junghans** [alshedivat/al-folio#174]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
Make a table in markdown, result will have really small padding

**To Reproduce**
1. Edit `about.md`
2. Add something like
```
| Table1 | Table2 |
|-|-|
|word|word|
```
3. Deploy

**Expected behavior**
There would some padding

**Screenshots**

**System (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Jekyll version [e.g. 3.8.7]
- Ruby version [e.g. 2.6.5]

**Additional context**

Workaround, add:
```
th
        {
        padding         : .5em 0;
        }
td
        {
        padding         : .2em .5em;
        }
```
at the end of `assets/css/main.scss` helps.

**Comment by alshedivat** [comment]
Just double checking: this small padding is accidentally forced somewhere in al-folio styles or it is a default coming from bootstrap? If it's the latter, I would prefer to keep it (assuming bootstrap developers had a reason to use small padding).

**Comment by junghans** [comment]
Please reopen.

**Comment by hkof** [comment]
This is still an issue, can you reopen.

**Comment by george-gca** [comment]
Maybe #1283 fixes this.
