### ISSUE TITLE
Website not deploying

### ISSUE THREAD

**Issue by advaitmoharir** [alshedivat/al-folio#1766]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

** Bug Description**

I have followed the instructions in the YouTube video uploaded on the README. While I am able to customize and view the website on the local version using `bundle exec jekyll serve`,  I am unable to deploy the website. 

Please find my website repo [here](https://github.com/advaitmoharir/advaitmoharir.github.io). On my git bash, I run `bin/deploy --user`, and run into the following error (screenshot below)

![image](https://github.com/alshedivat/al-folio/assets/54736818/d37ac821-9456-4ce0-b2e3-b1bd270b7af7)
![image](https://github.com/alshedivat/al-folio/assets/54736818/b842cf03-5701-4564-9af5-19064dab66fe)

**System Info**

 - OS: Windows
 - Browser: Firefox
 - Jekyll version: 4.3.2
- Ruby version: 3.2.0

**Comment by sonukrbarnwal** [comment]
Hi @advaitmoharir,

I am also having an exact issue, can you please suggest to me how to resolve this issue?
