### ISSUE TITLE
Add image zoom feature

### ISSUE THREAD

**Issue by alshedivat** [alshedivat/al-folio#177]
Image zooming (https://github.com/kingdido999/zooming/) could be particularly useful for project pages and blog posts.

**Comment by Jongwoo-Shim** [comment]
I tried playing around with the zoom library that you provided, and I think that we'd be better off using a different one. When trying to integrate it with the existing dark-mode I encountered multiple bugs.

* Issues with opacity when trying to use css-variables.
* Not running until the mode toggle is first hit. This is despite the listener being initialized during the theming initialization.
* Say hello to stretchy al : 
![image](https://user-images.githubusercontent.com/20072820/104981209-0acf9780-59bd-11eb-93ef-c897aa089931.png)

I've been looking into [medium-zoom](https://github.com/francoischalifour/medium-zoom) instead. If this doesn't work either, then I think maybe just raw js might be the best option.
