### ISSUE TITLE
Weird behavior when clicking in bib information

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#1774]
**Acknowledge the following**
- [X] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [X] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
When clicking in `bib`, `abs`, or other button in the publications page, the button enlarges before returning back to previous size.

**To Reproduce**
1. Go to https://alshedivat.github.io/al-folio/publications/
2. Click on `ABS`, `BIB`, `HTML`, or `PDF` buttons

**Additional context**
Error introduced after #1562

**Comment by alshedivat** [comment]
@george-gca, this bug seems critical. if we can't figure out how to fix it today, please roll back #1562 until we figure it out (I can look into it this week).

note: if you click on the buttons multiple times, they grow uncontrollably lol

**Comment by george-gca** [comment]
I am looking at it now. Did a lot of tests, but forgot about this little thing.

After clicking in the buttons, it adds some new classes temporarily:

Before clicking:
![image](https://github.com/alshedivat/al-folio/assets/31376482/932b8ff2-5ade-493f-821f-865d32f0117a)

During weird behavior:
![image](https://github.com/alshedivat/al-folio/assets/31376482/d6a4d975-ba94-47e7-90f6-3d6b2bd9b922)
