### ISSUE TITLE
Add demo site to repo about

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#1775]
It would be easier to find the link to the demo if it was displayed in the repo about part, like this:

![image](https://github.com/alshedivat/al-folio/assets/31376482/5ad120a8-7428-437d-91fa-d0c26013760f)

@alshedivat you are the only one with permission for this.

**Comment by alshedivat** [comment]
done
![Screenshot 2023-09-28 at 2 47 02 PM](https://github.com/alshedivat/al-folio/assets/2126561/8ecc8831-dca4-4f1f-bc01-d931279bf64b)
