### ISSUE TITLE
By default `/cv/` seems to pull from missing `/_data/resume.yml` data?

### ISSUE THREAD

**Issue by ahubers** [alshedivat/al-folio#1779]
**Describe the bug**
The data that populates /cv/ (by default) is not the data in `_data/cv.yml`. In fact, none of that info appears to be used if `site.data.resume` is non-empty. See:

https://github.com/alshedivat/al-folio/blob/master/_layouts/cv.html#L5

But there is no `resume.yml` in `_data`. And it is not clear how this data is being initially populated with Einstein's info.

**To Reproduce**
1. Clone & build site via docker-compose.
2. Navigate to /cv/
3. Make (any) changes to `_data/cv.yml` and see that these changes are not reflected.

**Comment by george-gca** [comment]
Check #1611 for more information about this. I will create a new issue to remind us of updating this information in the README.
