### ISSUE TITLE
Issue in deploying website 

### ISSUE THREAD

**Issue by sonukrbarnwal** [alshedivat/al-folio#1787]
Hi All,

I am facing the exact same issue as the link (https://github.com/alshedivat/al-folio/issues/1766). Can someone please suggest how to resolve this issue?

_Originally posted by @sonukrbarnwal in https://github.com/alshedivat/al-folio/issues/1766#issuecomment-1742026010_
           

System Info

OS: Windows
Browser: Chrome
Jekyll version: 4.3.2
Ruby version: 3.2.2

**Comment by aaronguo1996** [comment]
[This solution](https://github.com/alshedivat/al-folio/discussions/290) works for me.

**Comment by alshedivat** [comment]
please carefully follow deployment instructions in the readme: https://github.com/alshedivat/al-folio#deployment. (deployment has been automated, you no longer need to manually run deployment scripts locally.)
