### ISSUE TITLE
Hide "blog" from the navigation bar and adjust navigation order

### ISSUE THREAD

**Issue by xiong-zx** [alshedivat/al-folio#1795]
I would like to hide "bolg" in the navigation bar. #1621 suggests setting
 
> blog_nav_title: blog

in `_config.yml`

However, if I want to keep the blog in the navigation bar yet adjust its order, how to do this?

Related issues:
#1559 #1189 #1196

**Comment by george-gca** [comment]
To adjust its order, currently you have to manually change it in the [_includes/header.html](https://github.com/alshedivat/al-folio/blob/a21bd492bc9950f86f160baea1a2e31d3cc6227d/_includes/header.html#L54). As you can see, I opened #1559 as a reminder to implement an easier way.
