### ISSUE TITLE
Dark mode not working for distill blog posts

### ISSUE THREAD

**Issue by huyen-nguyen** [alshedivat/al-folio#180]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
Regarding: Dark mode for distill blog posts. The dark mode works ok for most cases, except for distill blog posts:
- Text color does not change to white on a dark background, the font color keeps being dark.
- When the post is being viewed, the dark/light button is unclickable.

**To Reproduce**
1. Turn on dark mode by setting `enable_darkmode: true` in `_config.yml` file
2. Run the site `bundle exec jekyll serve`
3. Click on the dark/light switch button on the top right corner to turn on dark mode
4. Click on menu **blog**
5. Click on a distill post

**Expected behavior**
1. Text color changes to white to be displayed on a dark background, to ensure contrast for legibility.
2. Dark/light switch button is clickable when a distill post is being viewed

**Screenshots**

![image](https://user-images.githubusercontent.com/22818938/104108316-2d471e00-52f6-11eb-868d-35fb8f51aea3.png)

**System (please complete the following information):**
 - OS: macOS Catalina
 - Browser (and its version): Chrome 88.0. 4324.79
 - Jekyll version: 3.9.0
 - Ruby version: 2.6.0

**Comment by Jongwoo-Shim** [comment]
I took a quick look and it seems that the issue is that the dark_mode.js file is not being loaded in for the distill pages. I'll try and work on it and get a fix for it by the end of the week.

**Comment by Jongwoo-Shim** [comment]
Here's the bugfix : https://github.com/alshedivat/al-folio/pull/182

**Comment by huyen-nguyen** [comment]
Thank you @Jongwoo-Shim. Looking good 👍
