### ISSUE TITLE
Hide some publications that I don't engage

### ISSUE THREAD

**Issue by lyhsieh** [alshedivat/al-folio#1807]
**Is your feature request related to a problem? Please describe.**
I cite some papers from others in project page using `related_publications` tag, but I don't want these publications shown in my own publication page. How can I do?

**Describe the solution you'd like**
I want to hide some papers that are not written by me in my publication page.

**Additional context**
For example, I want the paper we read for the project, <b>Intrusion Detection Using Mouse Dynamics</b>, shown in https://lyhsieh.github.io/projects/meichu/ , but I don't want it shown in https://lyhsieh.github.io/publications/ . How can I do?

**Comment by george-gca** [comment]
I believe this is currently not supported. Maybe this could be achieved by using the [hideCustomBibtex](https://github.com/search?q=repo%3Aalshedivat%2Fal-folio%20HideCustomBibtex&type=code) plugin?

**Comment by lyhsieh** [comment]
Thanks to @bwbwchen.
I fixed it by adding an additional flag `my` in `papers.bib`, 
```
@article{antal2018intrusion,
  author      = {Antal, Margit and Egyed‐Zsigmond, Elöd},
  year        = {2019},
  title       = {Intrusion Detection Using Mouse Dynamics},
  journal     = {IET Biometrics},
  doi         = {10.1049/iet-bmt.2018.5126},
  preview     = {antal2018intrusion.jpg},
  bibtex_show = {true},
  my          = {false}
}
```
and also added a query in `publications.md` to only list the publications with `my = true`.
```
{% bibliography -f {{ site.scholar.bibliography }} -q @[my=true] %}
```

**Comment by george-gca** [comment]
I am thinking if is there a better solution, maybe if it is possible to create 2 bib files, one with your publications and another with publications for references like you said.

**Comment by stevedanomodolor** [comment]
> Thanks to @BWbwchen. I fixed it by adding an additional flag `my` in `papers.bib`,
> 
> ```
> @article{antal2018intrusion,
>   author      = {Antal, Margit and Egyed‐Zsigmond, Elöd},
>   year        = {2019},
>   title       = {Intrusion Detection Using Mouse Dynamics},
>   journal     = {IET Biometrics},
>   doi         = {10.1049/iet-bmt.2018.5126},
>   preview     = {antal2018intrusion.jpg},
>   bibtex_show = {true},
>   my          = {false}
> }
> ```
> 
> and also added a query in `publications.md` to only list the publications with `my = true`.
> 
> ```
> {% bibliography -f {{ site.scholar.bibliography }} -q @[my=true] %}
> ```

this does not work for me, has this feature been included?

**Comment by george-gca** [comment]
Did you also add the change to the query?

**Comment by stevedanomodolor** [comment]
I noticed that when I use -q it does not work but with --query it does.
