### ISSUE TITLE
Support for Google Scholar badge

### ISSUE THREAD

**Issue by rm-asif-amin** [alshedivat/al-folio#1809]
**Is your feature request related to a problem? Please describe.**
Dimensions doesn't seem to pick up on all citations. There are 2 versions for one of my articles(one for conference proceedings, one for a journal  it was later included in). Google scholar citation count is slightly higher, would appreciate the option to include that.

**Describe the solution you'd like**
Support for a button like Altmetrics and Dimensions for Google Scholar.

**Describe alternatives you've considered**
Tried to add my custom button, but didn't succeed yet. This is my first ruby/jekyll project. Also have minimal exposure to web dev.

**Additional context**

Dimensions button visible here.
<img width="467" alt="image" src="https://github.com/alshedivat/al-folio/assets/50940878/59736948-cd0a-4fb6-bc08-7f4f0244ad4b">

I tried to add a custom ruby script for fetching citation count for each article by modifying this script that fetches summary for author-
https://jonathanchang.org/blog/easily-showcase-your-google-scholar-metrics-in-jekyll/

Here's my modified script-

```ruby

require 'open-uri'
require 'nokogiri'

# Replace with an array of your article IDs
ARTICLE_IDS = ['Article ID 1', 'Article Id 2', 'Article Id 3'].freeze # change to real value
SCHOLAR_ID = 'Scholar ID'.freeze # change to real value

def fetch_citation_counts(article_ids)
  article_citations = {}

  # Iterate through each article ID
  article_ids.each do |article_id|
    article_url = "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=#{SCHOLAR_ID}&citation_for_view=#{SCHOLAR_ID}:#{article_id}"

    begin
      doc = Nokogiri::HTML(URI.parse(article_url).open)

      # Attempt to extract the "Cited by n" string from the meta tags
      citation_count = 0

      # Look for meta tags with "name" attribute set to "description"
      description_meta = doc.css('meta[name="description"]')
      og_description_meta = doc.css('meta[property="og:description"]')

      if !description_meta.empty?
        cited_by_text = description_meta[0]['content']
        matches = cited_by_text.match(/Cited by (\d+)/)

        if matches
          citation_count = matches[1].to_i
        end
      elsif !og_description_meta.empty?
        cited_by_text = og_description_meta[0]['content']
        matches = cited_by_text.match(/Cited by (\d+)/)

        if matches
          citation_count = matches[1].to_i
        end
      end

      # Store the article ID and citation count in the hash
      article_citations[article_id] = citation_count

      # Print the citation count for testing
      puts "Citation count for #{article_id}: #{citation_count}"
    rescue Exception => e
      # Handle any errors that may occur during fetching
      article_citations[article_id] = 0

      # Print the error message including the exception class and message
      puts "Error fetching citation count for #{article_id}: #{e.class} - #{e.message}"
    end
  end

  # Return the article citations hash
  article_citations
end

# Call the function with the array of article IDs
article_citations = fetch_citation_counts(ARTICLE_IDS)

# Optionally, you can print the entire article_citations hash for testing
puts "Article Citations:"
puts article_citations
```
This script successfully prints citation count for each article id. But Not sure how to integrate these counts into the final form.

I think the modification is needed in these 4 locations-
1. badges.html:
```html
{%- if site.badges.gscholar_badge %}
<span class="google-scholar-citations-count">{{ page.citation_count }}</span>
{%- endif %}
```
2. bib.html:

```html
{%- if site.badges.google_scholar_citations_badge %}
            <span class="__google_scholar_badge_embed__"
            {% if entry.doi %}
              data-doi="{{ entry.doi }}"
            {% else if entry.pmid %}
              data-pmid="{{ entry.pmid }}"
            {% else %}
              data-id="{{ entry.gscholar }}"
            {% endif %}
            data-hide-zero-citations="true" data-style="small_rectangle" data-legend="hover-right" style="margin-bottom: 3px;"></span>
          {%- endif %}
```

3. Global binary flag in config.yml:
```yaml

badges: # Display different badges for your publications
  altmetric_badge: true # Altmetric badge (https://www.altmetric.com/products/altmetric-badges/)
  dimensions_badge: true # Dimensions badge (https://badge.dimensions.ai/)
  gscholar_badge: true # Google Scholar Citations Badge )
```
4. The bibtex key value pairs:
```
  altmetric={true},
  dimensions={true},
  gscholar={true},
```

The HTML parts are just random shots from my side. How to proceed to string these pieces together?

**Comment by george-gca** [comment]
You are in the right path there. You will need to create a plugin for this. Take a look at how [hideCustomBibtex](https://github.com/search?q=repo%3Aalshedivat%2Fal-folio%20HideCustomBibtex&type=code) is created and used. I believe you could do it the same way.

As for styling, maybe you could achieve that by using [Shields](https://shields.io/).

**Comment by rm-asif-amin** [comment]
Thanks, I'll send a PR if I manage to solve this.

**Comment by george-gca** [comment]
Also, since this relies on a local service, it would not automatically update the papers citations unless you build your site again. But currently this would be the best solution to integrate Google Scholar citations afaik.

**Comment by Fratorhe** [comment]
Is there any update on this? it would be awesome to have!

**Comment by rm-asif-amin** [comment]
Hello,
I didn't pursue it further yet.

**Comment by george-gca** [comment]
Based on @rm-asif-amin code I was able to create a plugin for this, but there are caveats:
1 - it only works at build time, which means it won't update the numbers unless you build your site again
2 - Google might block the request if it receives lots of it, failing the whole process.

I will submit a PR with this.
