### ISSUE TITLE
Recommendation isn't showing up

### ISSUE THREAD

**Issue by pablodiegoo** [alshedivat/al-folio#1819]
**Acknowledge the following**
- [X] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [X] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
I filled the "Recommendation" section on CV and still don't showing up, probably because of the Layout missing the following code on "__layout/cv.html" on the line 86:

`{% when "references" %}
include resume/references.html %}`

I made a pull request about it.

**Comment by george-gca** [comment]
Fixed in #1820
