### ISSUE TITLE
Readability during dark-mode

### ISSUE THREAD

**Issue by Jongwoo-Shim** [alshedivat/al-folio#183]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
Several areas are difficult to read during dark mode. 
I found that the main offenders are the following : 
* Distill page.
* Project page.
* Code

**To Reproduce**
1. Turn on dark mode by setting enable_darkmode: true in _config.yml file
2. Run the site bundle exec jekyll serve
3. Click on the dark/light switch button on the top right corner to turn on dark mode

**Screenshots**
![image](https://user-images.githubusercontent.com/20072820/104274723-5b437400-5456-11eb-8fc9-a20ffc9b653f.png)
![image](https://user-images.githubusercontent.com/20072820/104274754-6c8c8080-5456-11eb-85be-c35c002a7904.png)
![image](https://user-images.githubusercontent.com/20072820/104274839-934ab700-5456-11eb-862c-a9d408730c4b.png)
![image](https://user-images.githubusercontent.com/20072820/104274855-9c3b8880-5456-11eb-8e38-0c8c8e833203.png)

**System (please complete the following information):**
 - Windows 10
 - Firefox 84.0
 - Jekyll version: 3.9.0
 - Ruby version: 2.6.0

**Comment by Jongwoo-Shim** [comment]
I've been playing around with the css and have resolved most of the major offenders; however I want input on fixing the code blocks.

There are a few possible fixes for the legibility of code.
1. Modify the css to have a background for code snippets during dark-mode : 
![image](https://user-images.githubusercontent.com/20072820/104275161-2b48a080-5457-11eb-9489-2e97df47cc55.png)
2. Change the default to another syntax highlighter theme. Personally I think that Monokai or Native would work best for this.
3. Find a way to toggle between highlighter themes <- This one would be the most difficult to write in I think.

**Comment by Jongwoo-Shim** [comment]
@alshedivat Should we continue the discussion about the distill css here?

**Comment by huyen-nguyen** [comment]
Hi! Thank you for all your work on this topic. I'm just wondering is there a way to set the light theme as the default one when we first open the site? Currently, the default is set to the dark theme.

**Comment by Jongwoo-Shim** [comment]
@huyen-nguyen I believe that it was written to be based off your computer settings. Check the theme.js file for the logic.
ie. If you've set your computer to dark-mode, it'll default to dark-mode for the website.

This is for the first time you jump on the website, and then it stores said preference in local memory. If you're having issues where it's consistently loading up in dark-mode : 
* Check your computer settings.
* Clear your local storage.

**Comment by Jongwoo-Shim** [comment]
@huyen-nguyen Additionally you can rewrite the logic on lines 4-7 of theme.js if you need it to start in light theme.

**Comment by huyen-nguyen** [comment]
> @huyen-nguyen I believe that it was written to be based off your computer settings. Check the theme.js file for the logic.
> ie. If you've set your computer to dark-mode, it'll default to dark-mode for the website.
> 
> This is for the first time you jump on the website, and then it stores said preference in local memory. If you're having issues where it's consistently loading up in dark-mode :
> 
> * Check your computer settings.
> * Clear your local storage.

That makes sense. Got it. Thanks! By *local storage* do you mean cache?

**Comment by Jongwoo-Shim** [comment]
Yup. Just clear that stuff and you should be good to go.

**Comment by alshedivat** [comment]
@Jongwoo-Shim, thanks for opening this issue. Just got a chance to take a look.

- If you already have fixes to some/most of the issues, it'd be great if you could create a PR.
- Re: code blocks -- I think a combination of 1+2 (i.e., adjusting background color + switching to a different highlighter theme). I think toggling the highlight theme may not be possible.
- I remember you mentioned issues with distillpub (#182). Did you manage to find an elegant way to override distillpub styles?

**Comment by Jongwoo-Shim** [comment]
@alshedivat 
* Sure thing, however I wasn't able to really resolve the issue with distillpub.
* Should the distill fixes be included?
* Should I make a separate issue for the code block?

**Comment by alshedivat** [comment]
@Jongwoo-Shim, let's keep a single issue for readability. Feel free to create a separate PR that resolves non-distill issues.

For the distill stuff, I think the best way to go about it is to update styles in [my mirror of `distillpub/template`](https://github.com/alshedivat/distillpub-template/tree/al-folio). For example, to fix the color of the author links in the byline, we can change [this line](https://github.com/alshedivat/distillpub-template/blob/al-folio/src/styles/d-byline.css#L65):
```css
color: rgba(0, 0, 0, 0.8);
```
to (I think it's better to create separate variables for distill, for example `--global-distill-author-color`):
```css
color: var(--global-text-color);
```
After such changes are made, I'll need to re-generate `template.v2.js`. In this case, we won't need to hack the auto-generated `template.v2.js` directly, so it's a cleaner solution.

**Comment by alshedivat** [comment]
Adding to the collection of readability issues footnotes and citations:
<img width="780" alt="Screen Shot 2021-01-24 at 9 20 55 PM" src="https://user-images.githubusercontent.com/2126561/105653550-17a32e00-5e8a-11eb-95b2-e52eecf14a4f.png">
<img width="780" alt="Screen Shot 2021-01-24 at 9 20 44 PM" src="https://user-images.githubusercontent.com/2126561/105653555-18d45b00-5e8a-11eb-91c0-95cc0e24efc5.png">
