### ISSUE TITLE
a post with redirect: link broken?

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#1831]
### Discussed in https://github.com/alshedivat/al-folio/discussions/1818

<div type='discussions-op-text'>

<sup>Originally posted by **ckassung** October 12, 2023</sup>
Dear @,
 
if I access the blog entry "a post with redirect" not directly from the blog section via
https://alshedivat.github.io/al-folio/assets/pdf/example_pdf.pdf
but from a tag (2022) the link is
https://alshedivat.github.io/al-folio/blog/2022/redirect/
and does not show the pdf. Would be great if anybody could fix it.

Best, Chris</div>

**Comment by alshedivat** [comment]
thanks for reporting, looks like this is a bug.
