### ISSUE TITLE
Can you give some open code,please?

### ISSUE THREAD

**Issue by 181210231** [alshedivat/al-folio#1868]
I read your paper 'GAT-GAN : A Graph-Attention-based Time-Series Generative Adversarial Network',this is very  novel. I want reproduce your experiment，but your code address is not found 404 (https://github.com/srikrish010697/GAT-GAN.). If it's convenient for you, please send me a code. Thank you very much.

**Comment by alshedivat** [comment]
this is irrelevant to al-folio
