### ISSUE TITLE
Request a HTML version

### ISSUE THREAD

**Issue by jingxixu** [alshedivat/al-folio#187]
Hi,

I really like the design and look of this theme. However, I am more used to writing HTML directly but now if I take the generated `_site` on its own, the website won't look the same as using jekyll. I am wondering if a version of pure html + css can be provided? Many thanks!

**Comment by alshedivat** [comment]
@jingxixu, thanks for bringing this up. Could you explain what exactly you mean by `the website won't look the same as using jekyll`? Jekyll essentially displays the static website generated in the `_site` folder.
