### ISSUE TITLE
Dates in CSV too near and too low with respect to left text

### ISSUE THREAD

**Issue by raffaem** [alshedivat/al-folio#1882]
The dates in the CV are too near the text on the left (i.e., the margin is too low), and moreover they are too low with respect to the text on the left:

![image](https://github.com/alshedivat/al-folio/assets/54762742/b080d5ff-9fcb-42aa-861f-541a1fa1db63)

**Comment by vedanthanekar45** [comment]
How can I work on it?

**Comment by george-gca** [comment]
You will basically need to play with the css of the page.

**Comment by vedanthanekar45** [comment]
Oh, okay. This is actually my first time doing open source, so... Thank you
