### ISSUE TITLE
Need to add demo website

### ISSUE THREAD

**Issue by sreekaransrinath** [alshedivat/al-folio#189]
A demo website is something that is necessary for people to take a look and decide whether they want to use this or not

A github-pages hosted demo will do, but a demo site is required.

**Comment by alshedivat** [comment]
The demo is here: https://alshedivat.github.io/al-folio/. It is linked in the README (see the [![demo](https://img.shields.io/badge/theme-demo-brightgreen.svg)](https://alshedivat.github.io/al-folio/) badge).

**Comment by sreekaransrinath** [comment]
That's one tiny badge that's almost impossible to notice at a glance. Maybe add it to the About section or have it at the beginning of the readme? I could make a PR if you'd like.

**Comment by alshedivat** [comment]
Thanks for your suggestion. I think it's fine as is now. Apart from the tiny badge, people can also click on the huge preview image in the README (the one with a desktop, laptop, tablet, and phone), which would also take you to the demo page.

**Comment by sreekaransrinath** [comment]
As a new visitor looking through, that's not obvious to me. Didn't mean to sound rude, was just a suggestion :)

**Comment by sreekaransrinath** [comment]
Btw, your research is really interesting!
