### ISSUE TITLE
toc disappeared

### ISSUE THREAD

**Issue by shaoleiren** [alshedivat/al-folio#1972]

**Comment by adamnicholasprice** [comment]
Same issue!

**Comment by george-gca** [comment]
Can you provide any information about this?

**Comment by awsaf49** [comment]
toc also suddenly disappeared from the site as well
![image](https://github.com/alshedivat/al-folio/assets/36858976/1bb7dde1-cca8-4d92-a45b-614310586d9c)

But noticed in https://alshedivat.github.io/al-folio/cv/ the toc is working.

**Comment by awsaf49** [comment]
@george-gca even yesterday it was working but the it disappeared!

**Comment by sara-suzuki** [comment]
I believe I am experiencing an issue related to the toc. I cannot publish my website and the error message says Unknown tag 'toc'.

Specifically, the error message is:

Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v228 GitHub Pages: jekyll v3.9.3 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-feed Requiring: jekyll-sitemap Requiring: jemoji Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /bin EntryFilter: excluded /Gemfile Reading: _posts/2023-04-25-sidebar-table-of-contents.md Reading: _posts/2015-10-20-disqus-comments.md Reading: _posts/2015-05-15-images.md Reading: _posts/2015-03-15-formatting-and-links.md Reading: _posts/2023-03-21-tables.md Reading: _posts/2023-05-12-custom-blockquotes.md Reading: _posts/2023-03-20-table-of-contents.md Reading: _posts/2022-12-10-giscus-comments.md Reading: _posts/2023-04-24-videos.md Reading: _posts/2020-09-28-github-metadata.md Reading: _posts/2023-07-12-post-bibliography.md Reading: _posts/2020-09-28-twitter.md Reading: _posts/2023-07-04-jupyter-notebook.md Reading: _posts/2018-12-22-distill.md Reading: _posts/2015-07-15-code.md Reading: _posts/2015-10-20-math.md Reading: _posts/2022-02-01-redirect.md Reading: _posts/2021-07-04-diagrams.md Reading: _posts/2023-04-25-audios.md Reading: _news/announcement_1.md Reading: _news/announcement_3.md Reading: _news/announcement_2.md Reading: _projects/3_project.md Reading: _projects/5_project.md Reading: _projects/6_project.md Reading: _projects/4_project.md Reading: _projects/1_project.md Reading: _projects/2_project.md Generating: JekyllOptionalFrontMatter::Generator finished in 0.000272151 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.001164288 seconds. Jekyll Feed: Generating feed for posts Generating: JekyllFeed::Generator finished in 0.000707089 seconds. Generating: Jekyll::JekyllSitemap finished in 0.001041377 seconds. Generating: Jekyll::Paginate::Pagination finished in 2.995e-06 seconds. Generating: JekyllRelativeLinks::Generator finished in 0.000679357 seconds. Generating: JekyllDefaultLayout::Generator finished in 0.000794783 seconds. Generating: JekyllTitlesFromHeadings::Generator finished in 9.2103e-05 seconds. Rendering: _posts/2015-03-15-formatting-and-links.md Pre-Render Hooks: _posts/2015-03-15-formatting-and-links.md Rendering Markup: _posts/2015-03-15-formatting-and-links.md Requiring: kramdown-parser-gfm Rendering Layout: _posts/2015-03-15-formatting-and-links.md Layout source: site github-pages 228 \| Error: Liquid syntax error (line 55): Unknown tag 'toc'

**Comment by microbiology-marcus** [comment]
When trying to duplicate the template into a new repository, the build job fails.

`Error:  Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v228 GitHub Pages: jekyll v3.9.3 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-feed Requiring: jekyll-sitemap Requiring: jemoji Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /bin EntryFilter: excluded /Gemfile Reading: _posts/2023-12-12-tikzjax.md Reading: _posts/2020-09-28-twitter.md Reading: _posts/2020-09-28-github-metadata.md Reading: _posts/2023-04-25-sidebar-table-of-contents.md Reading: _posts/2021-07-04-diagrams.md Reading: _posts/2022-02-01-redirect.md Reading: _posts/2023-05-12-custom-blockquotes.md Reading: _posts/2015-10-20-math.md Reading: _posts/2015-03-15-formatting-and-links.md Reading: _posts/2015-07-15-code.md Reading: _posts/2023-04-24-videos.md Reading: _posts/2023-07-04-jupyter-notebook.md Reading: _posts/2015-05-15-images.md Reading: _posts/2023-07-12-post-bibliography.md Reading: _posts/2023-03-21-tables.md Reading: _posts/2022-12-10-giscus-comments.md Reading: _posts/2023-04-25-audios.md Reading: _posts/2015-10-20-disqus-comments.md Reading: _posts/2018-12-22-distill.md Reading: _posts/2023-03-20-table-of-contents.md Reading: _news/announcement_3.md Reading: _news/announcement_2.md Reading: _news/announcement_1.md Reading: _projects/6_project.md Reading: _projects/3_project.md Reading: _projects/5_project.md Reading: _projects/1_project.md Reading: _projects/4_project.md Reading: _projects/2_project.md Generating: JekyllOptionalFrontMatter::Generator finished in 0.00027778 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.001215214 seconds. Jekyll Feed: Generating feed for posts Generating: JekyllFeed::Generator finished in 0.000682477 seconds. Generating: Jekyll::JekyllSitemap finished in 0.001072186 seconds. Generating: Jekyll::Paginate::Pagination finished in 2.876e-06 seconds. Generating: JekyllRelativeLinks::Generator finished in 0.000709457 seconds. Generating: JekyllDefaultLayout::Generator finished in 0.000916255 seconds. Generating: JekyllTitlesFromHeadings::Generator finished in 8.539e-05 seconds. Rendering: _posts/2015-03-15-formatting-and-links.md Pre-Render Hooks: _posts/2015-03-15-formatting-and-links.md Rendering Markup: _posts/2015-03-15-formatting-and-links.md Requiring: kramdown-parser-gfm Rendering Layout: _posts/2015-03-15-formatting-and-links.md Layout source: site github-pages 228 | Error: Liquid syntax error (line 55): Unknown tag 'toc' `

**Comment by george-gca** [comment]
A few minutes ago I just created a new site for another user, and everything worked smoothly. Please, try to follow these steps:

1 - Start by clicking in
```
Use this template -> Create a new repository
```
Created a public repo with name `<your-github-username>.github.io`

2 - Go to
```
Settings -> Actions -> General -> Workflow permissions
```
and give `Read and write permissions` to GitHub Actions

3 - In `_config.yml`, set url to `https://<your-github-username>.github.io` and leave baseurl **empty**.

4 - Finally, go to
```
Settings -> Pages -> Build and deployment
```
make sure that `Source` is `Deploy from a branch` and set the branch to `gh-pages` (NOT to master)

5 - Wait until the GitHub actions finish, then simply navigate to `https://<your-github-username>.github.io` in your browser

**Comment by george-gca** [comment]
@awsaf49 you are trying to use the toc sidebar in the main projects page, and it was thought to be used in blog posts and inside projects pages. The way the toc works is by automatically getting the headers from the page and then creating the toc. By this I mean:
```markdown
# header 1
## subheader 1
### subsubheader 1
```

will become

```
header 1
| subheader 1
| | subsubheader 1
```

so the toc is not really fit for this page.

**Comment by awsaf49** [comment]
> and it was thought to be used in blog posts and inside projects pages

for me `toc` disappeared from all pages. For example, it disappeared from the experience page.
![image](https://github.com/alshedivat/al-folio/assets/36858976/f7324685-5de3-40b1-869d-9a636a45f484)

**Comment by awsaf49** [comment]
The weird part is before that day, everything was okay. Dunno what happened that day. I checked the commits of this repo and mine. Nothing significant changed.

**Comment by george-gca** [comment]
Maybe it is something related to the latest changes introduced with this matter? We introduced cache busting in #1557 and support for PurgeCSS in #1562. Since then, we load some of the libraries from local dir, and not CDN.

Also, if you check the console when loading in your site, it displays some errors. Maybe this will help you debug the problem.
