### ISSUE TITLE
How to add video to the project

### ISSUE THREAD

**Issue by ZongyuanShen** [alshedivat/al-folio#1983]
I am trying to insert a video in the project using the command below. However, it does not work.
![snapshot](https://github.com/alshedivat/al-folio/assets/136994172/6be53cfb-3799-4b56-ac69-18bfde8d670b)

**Comment by jwdinius** [comment]
Have you tried converting your video to a gif?  I was able to include the gif using the usual markdown syntax for including images in this [post](https://raw.githubusercontent.com/jwdinius/jwdinius.github.io/master/_posts/2023-10-14-sim-observer.md).

You could also redirect to YouTube which is what I did in this [project writeup](https://raw.githubusercontent.com/jwdinius/jwdinius.github.io/master/_projects/vehicle_detections.md)

**Comment by ZongyuanShen** [comment]
Thanks for the reply. Yes, I replaced the video by gif.

**Comment by george-gca** [comment]
What exactly is happening? What is the console in the browser displaying as error? Maybe what is missing is you setting the number of columns the video will occupy.

**Comment by ZongyuanShen** [comment]
> What exactly is happening? What is the console in the browser displaying as error? Maybe what is missing is you setting the number of columns the video will occupy.

Hi, there is no compling error. The website just render half of a picture instead of the video. But its ok, i use gif pictures now and it works well.

**Comment by thkelper** [comment]
> > What exactly is happening? What is the console in the browser displaying as error? Maybe what is missing is you setting the number of columns the video will occupy.
> 
> Hi, there is no compling error. The website just render half of a picture instead of the video. But its ok, i use gif pictures now and it works well.

How to insert a git?

**Comment by jwdinius** [comment]
> > > What exactly is happening? What is the console in the browser displaying as error? Maybe what is missing is you setting the number of columns the video will occupy.
> > 
> > 
> > Hi, there is no compling error. The website just render half of a picture instead of the video. But its ok, i use gif pictures now and it works well.
> 
> How to insert a git?

I posted two links in [this comment](https://github.com/alshedivat/al-folio/issues/1983#issuecomment-1848999060).  The first link will show you how to insert a gif.  You will first need to convert your video to a gif using [Cloud Convert](https://cloudconvert.com/gif-converter) or a comparable service.
