### ISSUE TITLE
Fresh template does not work on git, only docker

### ISSUE THREAD

**Issue by tpresser570** [alshedivat/al-folio#2009]
When I open the fresh template after configuring my git URL the website fails to load properly. However, if I load the website using docker, then everything appears fine. 

1. Create a new website using the template
2. Visit the git URL: https://tpresser570.github.io/tpresser570/
3. run the docker commands on the same repository

I have attached the screenshots of both instances below. You can see the docker image with the localhost URL and the regular one with my git URL. 

System
- Mac OS
- Chrome

<img width="1133" alt="Screenshot 2023-12-21 at 2 38 48 PM" src="https://github.com/alshedivat/al-folio/assets/69375669/10d1ea97-e95d-4f0d-bac6-168d85b6fe2e">

<img width="1095" alt="Screenshot 2023-12-21 at 2 33 22 PM" src="https://github.com/alshedivat/al-folio/assets/69375669/44c5184b-5af6-49dd-9d9a-130331df61fc">

**Comment by tpresser570** [comment]
Closing issue, fixed.

**Comment by adib2149** [comment]
@tpresser570 how did you fix the issue? I am having similar problems.

**Comment by george-gca** [comment]
Did you make it work without modifications at first?

**Comment by adib2149** [comment]
I had an old version running my website before, i wanted to try an updated repo with docker and automatic pages deployment. 

The current fresh template runs locally perfectly, but on github pages automated deployment, it shows same error as shown in this issue. 

Upon checking, i found, it is adding ‘al-folio’ to all my urls, creating issue of not finding static files and this looking broken. 

It is not happening in local docker though.

**Comment by adib2149** [comment]
No worries, I resolved it finally. Turns out, my GitHub pages option "Build and deployment" was set to "Github Actions (beta)" and NOT "deploy from a branch". I changed it to "Deploy from a branch", and it fixed itself.
