### ISSUE TITLE
No valid parser for XML when pushing on GitHub with external source for posts. (Feedjira::NoParserAvailable)

### ISSUE THREAD

**Issue by theosaulus** [alshedivat/al-folio#2027]
**Acknowledge the following**
- [X] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [X] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Locally, my website runs smoothly, with external source for blog posts (from Medium). When pushing the master branch of my website, I get the following error: No valid parser for XML. (Feedjira::NoParserAvailable), and the deployment step fails.

**System (please complete the following information):**
 - OS: Windows, but I guess here the problem is on GitHub's side
 - Jekyll version : locally, 4.3.1, on Github 4.3.3
 - Ruby version : locally 3.1.1, on GitHub 3.0.2

**Comment by george-gca** [comment]
Is it possible that a dependency is missing in the docker image @pourmand1376?

**Comment by george-gca** [comment]
Do you run it locally using docker?

**Comment by theosaulus** [comment]
Yes, I'm on Windows, I use Docker.

**Comment by pourmand1376** [comment]
I don't think this is related to the docker image as he says it happens only when pushing to github (not local).

**Comment by Andy-zd** [comment]
For me, I add  ```bundle add webrick``` before ```bundle exec jekyll build``` and specify Jekyll to a specific version in Gemfile(for me I use  gem 'jekyll', '4.3.2'). This solved my problem.

**Comment by theosaulus** [comment]
Thanks a lot! I believe it's not only linked to the two things you mentioned, I also had to use gem 'mini_racer','~>0.6.2' in Gemfile. Now it works
