### ISSUE TITLE
Docker amirpourmand/al-folio build 0.11.0 or latest tag, missing jekyll-diagrams

### ISSUE THREAD

**Issue by MarkMorow** [alshedivat/al-folio#2051]
**Acknowledge the following**
- [ x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x ] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x ] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
When pulling the latest docker image the site will not run locally as an error about a missing gem causes it to exit. 

**To Reproduce**
1. docker compose pull
2. docker compose up
3. Container will be created

Attaching to al-folio-website
al-folio-website  | bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
al-folio-website  | /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/resolver.rb:332:in `raise_not_found!': Could not find gem 'jekyll-diagrams' in locally installed gems. (Bundler::GemNotFound)
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/resolver.rb:392:in `block in prepare_dependencies'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/resolver.rb:377:in `each'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/resolver.rb:377:in `map'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/resolver.rb:377:in `prepare_dependencies'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/resolver.rb:61:in `setup_solver'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/resolver.rb:28:in `start'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/definition.rb:600:in `start_resolution'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/definition.rb:311:in `resolve'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/definition.rb:553:in `materialize'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/definition.rb:203:in `specs'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/definition.rb:270:in `specs_for'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/runtime.rb:18:in `setup'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler.rb:162:in `setup'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/setup.rb:26:in `block in <top (required)>'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/ui/shell.rb:159:in `with_level'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/ui/shell.rb:111:in `silence'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/setup.rb:26:in `<top (required)>'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:56:in `require_relative'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:56:in `kernel_load'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/cli/exec.rb:23:in `run'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/cli.rb:451:in `exec'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/cli.rb:34:in `dispatch'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/cli.rb:28:in `start'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/exe/bundler:4:in `load'
al-folio-website  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.3/exe/bundler:4:in `<top (required)>'
al-folio-website  | 	from /usr/local/bin/bundler:25:in `load'
al-folio-website  | 	from /usr/local/bin/bundler:25:in `<main>'
al-folio-website exited with code 1

**Expected behavior**
The site is expected to run locally as in previous version. 

**Screenshots**
![CleanShot 2024-01-07 at 15 42 21@2x](https://github.com/alshedivat/al-folio/assets/16296440/6bddfd26-6c5a-4ab8-969e-9337d778cfcd)

**System (please complete the following information):**
 - OS: [macOS 14.2.1]
 - Docker [4.26.1]
 - Jekyll version [4.3.3]

**Additional context**
When specifying an older version of the container (https://hub.docker.com/r/amirpourmand/al-folio/tags) such as v0.10.1 via 'docker run -p 8080:8080 --name jekyll -v $(pwd):/srv/jekyll amirpourmand/al-folio:v0.10.1' the local instance works as expected. 

I also experience the same missing jekyll-diagrams error when using 'docker run -p 8080:8080 --name jekyll -v $(pwd):/srv/jekyll amirpourmand/al-folio:v0.11.0'.

**Comment by george-gca** [comment]
`jekyll-diagrams` support was dropped in #1992 in favor of using mermaid.js directly. Simply update your code to get the latest changes.
