### ISSUE TITLE
[GitHub Pages] bundler: failed to load command: jekyll

### ISSUE THREAD

**Issue by cozheyuanzhangde** [alshedivat/al-folio#2058]
**Describe the bug**
bundler: failed to load command: jekyll (/home/runner/work/cozheyuanzhangde.github.io/cozheyuanzhangde.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll)

**To Reproduce**:
It worked all fine until today after I changed a PDF file in assets which shouldn't affect any other of the source code being compiled. Therefore I don't know what might cause this bug happens.

![image](https://github.com/alshedivat/al-folio/assets/54963496/673cabd4-6618-4646-9477-c049fd5612ea)

You can see that I only updated cv.pdf, and suddenly it cannot be auto deployed.

**Versions:**
 - Jekyll version: 4.3.3
- Ruby version: 3.0.2

**Additional context**
The error starts after executing "+ bundle exec jekyll build":
+ bundle exec jekyll build
bundler: failed to load command: jekyll (/home/runner/work/cozheyuanzhangde.github.io/cozheyuanzhangde.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll)
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated uri 0.10.1, but your Gemfile requires uri 0.13.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:25:in `block in setup'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/spec_set.rb:191:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/spec_set.rb:191:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:24:in `map'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:24:in `setup'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler.rb:162:in `setup'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/setup.rb:26:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/ui/shell.rb:159:in `with_level'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/ui/shell.rb:111:in `silence'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/setup.rb:26:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:56:in `require_relative'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:56:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:[45](https://github.com/cozheyuanzhangde/cozheyuanzhangde.github.io/actions/runs/7465784899/job/20315711593#step:7:46)1:in `exec'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor.rb:[52](https://github.com/cozheyuanzhangde/cozheyuanzhangde.github.io/actions/runs/7465784899/job/20315711593#step:7:53)7:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:34:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/base.rb:[58](https://github.com/cozheyuanzhangde/cozheyuanzhangde.github.io/actions/runs/7465784899/job/20315711593#step:7:59)4:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x[64](https://github.com/cozheyuanzhangde/cozheyuanzhangde.github.io/actions/runs/7465784899/job/20315711593#step:7:65)/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:28:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:28:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:20:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `<main>'
yes: standard output: Broken pipe
Error: Process completed with exit code 1.

**Comment by brendanjmeade** [comment]
I'm seeing this too as of today.  Guidance welcome!

<img width="344" alt="Screenshot 2024-01-09 at 5 49 39 PM" src="https://github.com/alshedivat/al-folio/assets/4225359/a591b027-8d08-4852-8558-dbf07ff10d4b">

**Comment by alshedivat** [comment]
interesting. the ruby version that you have seems outdated. the one we currently have set in the deploy github actoin is `3.2.2`: https://github.com/alshedivat/al-folio/blob/master/.github/workflows/deploy.yml#L27. if you are using an oder version of the deploy action, please consider upgrading (just copy-paste `.github/workflows/deploy.yml` from al-folio master branch to your repo).

**Comment by cozheyuanzhangde** [comment]
> > interesting. the ruby version that you have seems outdated. the one we currently have set in the deploy github actoin is `3.2.2`: https://github.com/alshedivat/al-folio/blob/master/.github/workflows/deploy.yml#L27. if you are using an oder version of the deploy action, please consider upgrading (just copy-paste `.github/workflows/deploy.yml` from al-folio master branch to your repo).
> 
> Hey there! I was having the same issue. I tried updating the deploy action as you mentioned, but it didn't work out at first. However, I managed to fix the issue by simply editing the Ruby version in my deploy.yml file. Changing it from 3.0.2 to 3.2.2 under the "with" section did the trick, and everything's running smoothly now.
> 
> ```
> with:
>   ruby-version: '3.2.2'
> ```
> 
> Appreciate your help!

Thanks a lot! Simply changing the ruby-version fixed the problem!
