### ISSUE TITLE
error not working

### ISSUE THREAD

**Issue by khanhjt** [alshedivat/al-folio#2065]
when i fork to my repo, i want it become new page, but in Action have error:

Annotations
1 error and 1 warning
[build](https://github.com/khanhjt/khanhjt.github.io/actions/runs/7496888765/job/20409646347#step:4:56)
 Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v228 GitHub Pages: jekyll v3.9.3 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-feed Requiring: jekyll-sitemap Requiring: jemoji Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /bin EntryFilter: excluded /Gemfile Reading: _posts/2023-12-12-tikzjax.md Reading: _posts/2020-09-28-twitter.md Reading: _posts/2020-09-28-github-metadata.md Reading: _posts/2023-04-25-sidebar-table-of-contents.md Reading: _posts/2021-07-04-diagrams.md Reading: _posts/2022-02-01-redirect.md Reading: _posts/2023-05-12-custom-blockquotes.md Reading: _posts/2015-10-20-math.md Reading: _posts/2015-03-15-formatting-and-links.md Reading: _posts/2015-07-15-code.md Reading: _posts/2023-04-24-videos.md Reading: _posts/2023-07-04-jupyter-notebook.md Reading: _posts/2015-05-15-images.md Reading: _posts/2023-07-12-post-bibliography.md Reading: _posts/2023-03-21-tables.md Reading: _posts/2022-12-10-giscus-comments.md Reading: _posts/2023-04-25-audios.md Reading: _posts/2015-10-20-disqus-comments.md Reading: _posts/2018-12-22-distill.md Reading: _posts/2023-03-20-table-of-contents.md Reading: _news/announcement_3.md Reading: _news/announcement_2.md Reading: _news/announcement_1.md Reading: _projects/6_project.md Reading: _projects/3_project.md Reading: _projects/5_project.md Reading: _projects/1_project.md Reading: _projects/4_project.md Reading: _projects/2_project.md Generating: JekyllOptionalFrontMatter::Generator finished in 0.000453675 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.001173456 seconds. Jekyll Feed: Generating feed for posts Generating: JekyllFeed::Generator finished in 0.000694804 seconds. Generating: Jekyll::JekyllSitemap finished in 0.001291505 seconds. Generating: Jekyll::Paginate::Pagination finished in 3.115e-06 seconds. Generating: JekyllRelativeLinks::Generator finished in 0.021792102 seconds. Generating: JekyllDefaultLayout::Generator finished in 0.002320852 seconds. Requiring: kramdown-parser-gfm Generating: JekyllTitlesFromHeadings::Generator finished in 0.013239215 seconds. Rendering: _posts/2015-03-15-formatting-and-links.md Pre-Render Hooks: _posts/2015-03-15-formatting-and-links.md Rendering Markup: _posts/2015-03-15-formatting-and-links.md Rendering Layout: _posts/2015-03-15-formatting-and-links.md Layout source: site github-pages 228 | Error: Liquid syntax error (line 60): Unknown tag 'toc'
please help me

**Comment by george-gca** [comment]
The bug report template is there for a reason. With this little unformatted information there is not much we can do to help.

**Comment by george-gca** [comment]
What changes have you made? Does it work locally?

**Comment by CharlieJCJ** [comment]
Facing same issue.

**Comment by CharlieJCJ** [comment]
[Related FAQ post](https://github.com/alshedivat/al-folio/blob/master/FAQ.md#my-webpage-works-locally-but-after-deploying-it-fails-to-build-and-throws-unknown-tag-toc-how-do-i-fix-that)
[Related Issue](https://github.com/alshedivat/al-folio/issues/1438)

My problem is fixed.

**Comment by alroborol** [comment]
Hi @khanhjt , I met the same problem and no previous solution worked.
I solved it by copying .github folder into my repo and replace the `npm install -g xxx` with `npm install --no-fund -g xxx`.
Maybe you also need to commit Gemfile too.

The basic concept is:
- Workflow in .github creates contents on gh_pages branch
- Default github workflow publish gh_pages branch
