### ISSUE TITLE
Out-of-date package

### ISSUE THREAD

**Issue by boyuan-zhang** [alshedivat/al-folio#2073]
When I update my photo or something using GithubDesktop, it fails to deploy because of the following error:

bundler: failed to load command: jekyll (/home/runner/work/boyuan-zhang.github.io/boyuan-zhang.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll)
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated uri 0.10.1, but your Gemfile requires uri 0.13.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:25:in `block in setup'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/spec_set.rb:191:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/spec_set.rb:191:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:24:in `map'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:24:in `setup'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler.rb:162:in `setup'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/setup.rb:26:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/ui/shell.rb:159:in `with_level'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/ui/shell.rb:111:in `silence'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/setup.rb:26:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:56:in `require_relative'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:56:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:[45](https://github.com/boyuan-zhang/boyuan-zhang.github.io/actions/runs/7514773297/job/20458015131#step:7:46)1:in `exec'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor.rb:[52](https://github.com/boyuan-zhang/boyuan-zhang.github.io/actions/runs/7514773297/job/20458015131#step:7:53)7:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:34:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/base.rb:[58](https://github.com/boyuan-zhang/boyuan-zhang.github.io/actions/runs/7514773297/job/20458015131#step:7:59)4:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x[64](https://github.com/boyuan-zhang/boyuan-zhang.github.io/actions/runs/7514773297/job/20458015131#step:7:65)/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:28:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:28:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:20:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `<main>'
yes: standard output: Broken pipe
Error: Process completed with exit code 1.

- OS: MacOS
- Browser: chrome

**Comment by danbischof** [comment]
I encounter the exact same issue. I have tried going back to older versions of my page but that doesn't help here.

**Comment by george-gca** [comment]
The only thing you changed was the profile picture? Was this done on a modified repo or on a fresh install?

**Comment by danbischof** [comment]
In my case: I only changed text on bio and landing pages today. Last changes I did two weeks ago didn’t create this error. 

Webpage is template build: www.danbischof.com

**Comment by boyuan-zhang** [comment]
In my case, I changed one pdf file under asset fold. I was able to change the profile picture 5-6 days ago.

**Comment by george-gca** [comment]
If you check your actions' runs, both of you are using deprecated libraries/commands. Apparently this happens because you are using a very old version of al-folio. I suggest [upgrading your code](https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#upgrading-from-a-previous-version) to the latest version. More specifically:

Assuming the current directory is `your-repo-name`

```bash
git remote add upstream https://github.com/alshedivat/al-folio.git
git fetch upstream
git rebase v0.11.0
```

Note that probably you will need to do a lot of manual merging. If you find it easier, you could create a copy of your repository, do a fresh install from the template and reapply all your changes. For this I would recommend a tool like [meld](https://meldmerge.org/) or [winmerge](https://winmerge.org/) to check the differences between directories/files.

**Comment by danbischof** [comment]
Thanks a lot, that’s what I feared :( I think I’ll go with your second suggestion.

**Comment by anupamsobti** [comment]
I can attest that the second option would be better. Although it's unfortunate that this suddenly broke since it's a live website and the fix isn't straightforward either.

Anything we could do to make sure this backward compatibility is maintained for future enhancements?

**Comment by george-gca** [comment]
I believe the best way to ensure this is trying to keep your site as up-to-date as possible with the template repo. Libraries tend to be deprecated and support for them dropped as they are no longer maintained, and keep using them involves security breaches. Also some of these deprecations are enforced, for example, by GitHub itself, so there's so much we can do.

Also we have been adding tons of new functionalities as well as tyding things up and improving overall speed and structure. I believe after the last changes get introduced there won't be much code changes like the ones before, so keeping your sites up-to-date with the template will be easier. For instance, #2048 introduced code formatting to our repo, which led to changes in basically all of our files, while #2034 changed the structure of the entire README file.

**Comment by anupamsobti** [comment]
Thank you. That makes sense.
