### ISSUE TITLE
Trying to deploy but failed.

### ISSUE THREAD

**Issue by hantsy** [alshedivat/al-folio#208]
I was trying to deploy this  source into my personal home page, https://hantsy.github.io, but failed in the Github actions.

```bash
Run yes | bin/deploy --verbose  --src source --deploy master
+ shift
+ [[ 4 > 0 ]]
+ key=--src
+ case $key in
+ SRC_BRANCH=source
+ shift
+ shift
+ [[ 2 > 0 ]]
+ key=--deploy
+ case $key in
+ DEPLOY_BRANCH=master
+ shift
+ shift
+ [[ 0 > 0 ]]
+ set -e
+ echo Deploying...
Deploying...
+ echo 'Source branch: source'
Source branch: source
+ echo 'Deploy branch: master'
Deploy branch: master
+ read -r -p 'Do you want to proceed? [y/N] ' response
+ [[ ! y =~ ^([yY][eE][sS]|[yY])+$ ]]
+ git diff-index --quiet HEAD --
+ echo 'Changes to the following files are uncommitted:'
Changes to the following files are uncommitted:
+ git diff-index --name-only HEAD --
bin/cibuild
bin/deploy
+ echo 'Please commit the changes before proceeding.'
+ echo Aborting.
+ [[ bin/deploy = \b\i\n\/\d\e\p\l\o\y ]]
+ exit 1
yes: standard output: Broken pipe
Please commit the changes before proceeding.
Aborting.
Error: Process completed with exit code 1.
````

**Comment by hantsy** [comment]
My source is hosted on: https://github.com/hantsy/hantsy.github.io

**Comment by hantsy** [comment]
The reason is  the *execute* permission  of *bin/deploy*  will be lostunder Windows when I cloned it in my disk. 

I  added a step in the *deploy.yml* Github action to fix permission issue.

see: https://github.com/hantsy/hantsy.github.io/blob/source/.github/workflows/deploy.yml#L51-L55

**Comment by hantsy** [comment]
@alshedivat Do you think this is an issue? I can send a PR for this, or you have better solution for this.

**Comment by alshedivat** [comment]
@hantsy, thanks for reporting this.

It looks like the deploy script fails b/c of the uncommitted changes to the `bin/*` files. Does this happen during the github action running or when you are deploying manually? I'm not sure how Windows is related to github actions b/c they are executed on the latest Ubuntu (see [this line](https://github.com/alshedivat/al-folio/blob/master/.github/workflows/deploy.yml#L15) in `.github/workflows/deploy.yml`). I'm confused.

**Comment by hantsy** [comment]
>It looks like the deploy script fails b/c of the uncommitted changes to the bin/* files. 

This happens when I added the execute permission to `bin/deploy`.

If I did not add this  https://github.com/hantsy/hantsy.github.io/blob/source/.github/workflows/deploy.yml#L51-L55

The `bin/deploy` in Github actions workflow will fail because of lack of *executes* permissions.

**Comment by alshedivat** [comment]
> The `bin/deploy` in Github actions workflow will fail because of lack of executes permissions.

This is very strange, I haven't seen anyone report this before. Also, looks like your repository is not a fork of `al-folio`. I'm guessing, you probably downloaded al-folio code, created a new repo yourself, and pushed the code, right?. That might be the source of the issue. Please try creating a fork instead to avoid problems with the execution permissions.

**Comment by hantsy** [comment]
Yes, I clone it in my local disk firstly and then push it to my repos. This maybe is the source of the problem. Thanks.

**Comment by adib2149** [comment]
Hi @hantsy , curious to know how you resolved this issue. I am facing the same issue, getting the same error as "Changes to the following files are uncommitted:" and the master branch is not being built. 

I also did not fork the repo, rather cloned, edited, and uploaded it to my own repo. Is there any solution where we don't fork the original repo?

**Comment by adib2149** [comment]
> Hi @hantsy , curious to know how you resolved this issue. I am facing the same issue, getting the same error as "Changes to the following files are uncommitted:" and the master branch is not being built.
> 
> I also did not fork the repo, rather cloned, edited, and uploaded it to my own repo. Is there any solution where we don't fork the original repo?

My error log, in case that helps:

```
0s
Run yes | bin/deploy --verbose  --src source --deploy master
  yes | bin/deploy --verbose  --src source --deploy master
  shell: /usr/bin/bash -e {0}
+ shift
+ [[ 4 > 0 ]]
+ key=--src
+ case $key in
+ SRC_BRANCH=source
+ shift
+ shift
+ [[ 2 > 0 ]]
+ key=--deploy
+ case $key in
+ DEPLOY_BRANCH=master
+ shift
+ shift
+ [[ 0 > 0 ]]
+ set -e
+ echo Deploying...
+ echo 'Source branch: source'
Deploying...
+ echo 'Deploy branch: master'
Source branch: source
+ read -r -p 'Do you want to proceed? [y/N] ' response
Deploy branch: master
+ [[ ! y =~ ^([yY][eE][sS]|[yY])+$ ]]
+ git diff-index --quiet HEAD --
+ echo 'Changes to the following files are uncommitted:'
Changes to the following files are uncommitted:
+ git diff-index --name-only HEAD --
.bundle/config
+ echo 'Please commit the changes before proceeding.'
Please commit the changes before proceeding.
Aborting.
+ echo Aborting.
+ [[ bin/deploy = \b\i\n\/\d\e\p\l\o\y ]]
+ exit 1
yes: standard output: Broken pipe
Error: Process completed with exit code 1.
```

**Comment by josyulakrishna** [comment]
> Hi @hantsy , curious to know how you resolved this issue. I am facing the same issue, getting the same error as "Changes to the following files are uncommitted:" and the master branch is not being built.
> 
> I also did not fork the repo, rather cloned, edited, and uploaded it to my own repo. Is there any solution where we don't fork the original repo?

Hi @adib2149  did you somehow manage to resolve this issue? please let me know. thank you.

**Comment by adib2149** [comment]
> > Hi @hantsy , curious to know how you resolved this issue. I am facing the same issue, getting the same error as "Changes to the following files are uncommitted:" and the master branch is not being built.
> > I also did not fork the repo, rather cloned, edited, and uploaded it to my own repo. Is there any solution where we don't fork the original repo?
> 
> Hi @adib2149 did you somehow manage to resolve this issue? please let me know. thank you.

Yeah i gave up on this issue. I tried many things, but nothing worked. Now I have two branches, one for the main code and one for github pages, with locally built version. You can check it in my repos.

**Comment by josyulakrishna** [comment]
> > > Hi @hantsy , curious to know how you resolved this issue. I am facing the same issue, getting the same error as "Changes to the following files are uncommitted:" and the master branch is not being built.
> > > I also did not fork the repo, rather cloned, edited, and uploaded it to my own repo. Is there any solution where we don't fork the original repo?
> > 
> > 
> > Hi @adib2149 did you somehow manage to resolve this issue? please let me know. thank you.
> 
> Yeah i gave up on this issue. I tried many things, but nothing worked. Now I have two branches, one for the main code and one for github pages, with locally built version. You can check it in my repos.

Thank you for the response, I gave up on this too, things only seem to work when I fork the repo and host it.

**Comment by hantsy** [comment]
@adib2149 @josyulakrishna It is working in my fork, [hantsy.github.io](https://github.com/hantsy/hantsy.github.io), I added this https://github.com/hantsy/hantsy.github.io/blob/source/.github/workflows/deploy.yml#L51-L54.

**Comment by hantsy** [comment]
There is a blog described my experience of building my homepage, https://hantsy.github.io/blog/2021/jekyll/

**Comment by Mustapha-AJEGHRIR** [comment]
For this problem, just try to add `bash` before the command, see the link 
https://github.com/Mustapha-AJEGHRIR/Mustapha-AJEGHRIR.github.io/blob/12a45515d2ac8538e6b3d87b52518e7deeb4b234/.github/workflows/deploy.yml#L49
