### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#2086]
Many communities, both on [GitHub](https://github.com/github/renaming) and in the [wider Git community](https://sfconservancy.org/news/2020/jun/23/gitbranchname/), have renamed the default branch name of their repository from master to main. I believe it would be nice if [we did the same](https://github.com/github/renaming?tab=readme-ov-file#renaming-existing-branches).

**Comment by JoaoDiogoDuarte** [comment]
Just want to express my support for this.

**Comment by scottleechua** [comment]
+1 here too. Does this create any big blockers to development?

**Comment by george-gca** [comment]
I believe not. The [main changes](https://github.com/github/renaming?tab=readme-ov-file#rename-existing) that will happen for other users are:
- Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
- Show a notice to contributors who `git push` to the old branch

**Comment by scottleechua** [comment]
Sounds about right! Perhaps this change can be scheduled to happen along with the 2024 Q4 release?

**Comment by alshedivat** [comment]
added `main` branch and made it default. I kept `master` for posterity / to avoid disruption.

**Comment by george-gca** [comment]
Before closing this issue I think we should update our documentation pointing to `main` whenever it was `master`. I can do that.
