### ISSUE TITLE
Build errors during deployment to GitHub Pages

### ISSUE THREAD

**Issue by eftekhar-hossain** [alshedivat/al-folio#209]
**I am failed to deploy the ai-folio theme in my personal repository. Even I don't find any fruitful reason why it is happening. 

Need Help**

![Capture](https://user-images.githubusercontent.com/69648363/109480870-45d9e600-7aa6-11eb-90b1-b7396e6fb367.PNG)

**Comment by brucewlee** [comment]
same here

**Comment by alshedivat** [comment]
The website will not be correctly deployed until you make some changes, commit, and push. Please make sure to follow the deployment instructions provided in the README.

**Comment by syncdoth** [comment]
Same here. What I did was:

1. fork the repo
2. rename the repo to `<my user name>.github.io`
3. change the name of the branch `master` to `source`
4. enable github actions
5. clone the repo to local
6. make some changes & push to `source` branch

Then, I get the same error as @eftekhar-hossain: 

```
GitHub Pages failed to build your site.

The tag twitter on line 7 in _posts/2020-09-28-twitter.md is not a recognized Liquid tag.
```

Any ideas?

**Comment by raghavmittal101** [comment]
Got rid of this error by deleting the post mentioned in the error message. It's probably because of some mistyping.

**Comment by FloorVerhoeven** [comment]
Same here as @syncdoth

**Comment by alshedivat** [comment]
Looks like github made some updates recently, so there are a couple more steps you need to follow to setup a personal page:

1) As usual, fork the repository.

2) Click on Actions and enable Github Actions:
<img width="536" alt="Screen Shot 2021-03-14 at 1 52 49 AM" src="https://user-images.githubusercontent.com/2126561/111060172-f06be480-8468-11eb-9e42-55f7d45629e0.png">

3) Go to Settings and rename your fork to `<your-username>.github.io`.

4) In the settings, select Branches and rename the `master` branch to `source`:
<img width="870" alt="Screen Shot 2021-03-14 at 1 55 18 AM" src="https://user-images.githubusercontent.com/2126561/111060131-b7cc0b00-8468-11eb-876c-a1cd251012bf.png">

5) Finally, again in the settings, in the Github Pages section, set the source branch to `master` (NOT to `source`).

6) Make any changes to your webpage (in the `source` branch), commit, and push.

Point 5 is important and is the source of error. If GitHub Pages Source is set to `source` branch, it will attempt to automatically build and deploy your webpage. This results in the error because GitHub Pages does not support some of the jekyll plugins (bibliography, twitter, etc.). Instead, we use a custom github action for deploying the website (that's why you have to enable github actions on your fork in point 2), which correctly builds the website and pushes the built version to `master`. GitHub Pages simply picks up the built version of the website from the `master` branch.

**Comment by AndrewWilliams3142** [comment]
@alshedivat thanks for this! Perhaps I'm being silly, but if we're renamed the `master` branch to `source`, I don't think we can then set the source branch to `master` in the Github Pages settings?

**Comment by lzfelix** [comment]
Is it okay if I make a PR moving these changes to the README.md?

**Comment by alshedivat** [comment]
@lzfelix, I wasn't sure how to update README without over-cluttering it. It'd be great if you could find a nice way!

**Comment by yangzhaogit** [comment]
@alshedivat I did the exact steps as your instructions. But the website is not working properly. Some plugins are not working I think. 
![123](https://user-images.githubusercontent.com/66415631/114697850-fa775080-9d50-11eb-9bee-5417f8c879de.PNG)

**Comment by RajGhugare19** [comment]
@AndrewWilliams3142  How long does that take?

**Comment by alshedivat** [comment]
#261 adds the latest instructions to README. Closing this issue.

**Comment by npitsillos** [comment]
Hello, I have had some problems recently where the changes pushed to source were not reflected on the deployed website and decided to start over.  I came across the following question.  Since we are changing master to source (naming) then the github workflow should also be changed from master to source as well?

**Comment by danbischof** [comment]
This solution does not work for me. Followed all steps but cannot do 5. "Master" never appears here -- also not after waiting. 

Thus, I still receive this error: 

The page build failed for the `source` branch with the following error:

The tag `twitter` on line 5 in `_posts/2020-09-28-twitter.md` is not a recognized Liquid tag. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.

For information on troubleshooting Jekyll see:

**Comment by arielsho** [comment]
Sorry, the updated instruction doesn't work for me. The "master" branch didn't show up automatically. Could you please help? Thanks! @alshedivat 

> Looks like github made some updates recently, so there are a couple more steps you need to follow to setup a personal page:
> 
> 1. As usual, fork the repository.
> 2. Click on Actions and enable Github Actions:
> 
> <img alt="Screen Shot 2021-03-14 at 1 52 49 AM" width="536" src="https://user-images.githubusercontent.com/2126561/111060172-f06be480-8468-11eb-9e42-55f7d45629e0.png">
> 
> 1. Go to Settings and rename your fork to `<your-username>.github.io`.
> 2. In the settings, select Branches and rename the `master` branch to `source`:
> 
> <img alt="Screen Shot 2021-03-14 at 1 55 18 AM" width="870" src="https://user-images.githubusercontent.com/2126561/111060131-b7cc0b00-8468-11eb-876c-a1cd251012bf.png">
> 
> 1. Finally, again in the settings, in the Github Pages section, set the source branch to `master` (NOT to `source`).
> 2. Make any changes to your webpage (in the `source` branch), commit, and push.
> 
> Point 5 is important and is the source of error. If GitHub Pages Source is set to `source` branch, it will attempt to automatically build and deploy your webpage. This results in the error because GitHub Pages does not support some of the jekyll plugins (bibliography, twitter, etc.). Instead, we use a custom github action for deploying the website (that's why you have to enable github actions on your fork in point 2), which correctly builds the website and pushes the built version to `master`. GitHub Pages simply picks up the built version of the website from the `master` branch.

**Comment by vss245** [comment]
hey @arielsho, I had the same issue and I edited the 'deploy' file to say 'main' instead of 'master' because my first branch in the repo was named main (without renaming any other branches etc) - it seems to work so far. 

> Sorry, the updated instruction doesn't work for me. The "master" branch didn't show up automatically. Could you please help? Thanks! @alshedivat

**Comment by charleslipku** [comment]
> @alshedivat thanks for this! Perhaps I'm being silly, but if we're renamed the `master` branch to `source`, I don't think we can then set the source branch to `master` in the Github Pages settings?
> 
> ![image](https://user-images.githubusercontent.com/56925856/111087797-79435880-851b-11eb-8a69-e21d9656837c.png)
> 
> **EDIT:** Ignore this! You have to wait until Github Actions has run and generated a new `master` branch..



> @alshedivat thanks for this! Perhaps I'm being silly, but if we're renamed the `master` branch to `source`, I don't think we can then set the source branch to `master` in the Github Pages settings?
> 
> ![image](https://user-images.githubusercontent.com/56925856/111087797-79435880-851b-11eb-8a69-e21d9656837c.png)
> 
> **EDIT:** Ignore this! You have to wait until Github Actions has run and generated a new `master` branch..

I cannot see the new 'master' branch, do you know what is the reason?

**Comment by superfreeze** [comment]
@alshedivat yeah I dont have a new master branch

**Comment by LiquidAmmonia** [comment]
Until now, the bug still remains...

**Comment by chwag** [comment]
> Until now, the bug still remains...

Had the same problem, and found issue #342, where it was proposed to set the default branch back to master (delete any other master branch you may have created in between) and set gh-pages as source branch for Pages. Worked for me! :)

**Comment by bicmfcs** [comment]
I keep getting build and deployment error while trying to publish my gh pages, it workes locally, does anyone could help me ?
[Repository](https://github.com/bicmfcs/bicmfcs.github.io) that I'm using.
I'm using jekyll al-folio for my webpage. 
let me know if you need any more information.

**Comment by fastzhong** [comment]
Such bad UX on Github, forget about the Github pages/actions/workflows, use Netlify or Vercel.

**Comment by haiyun-he** [comment]
> > Until now, the bug still remains...
> 
> Had the same problem, and found issue #342, where it was proposed to set the default branch back to master (delete any other master branch you may have created in between) and set gh-pages as source branch for Pages. Worked for me! :)

work for me too!

**Comment by nasirlukman** [comment]
Does anyone still have the same issue? I already followed the steps in the docs to set gh-pages as my source branch but it still fails to deploy

**Comment by DiegoIBH** [comment]
> I keep getting build and deployment error while trying to publish my gh pages, it workes locally, does anyone could help me ? [Repository](https://github.com/bicmfcs/bicmfcs.github.io) that I'm using. I'm using jekyll al-folio for my webpage. let me know if you need any more information.

I just re-run all jobs on the actions window and it worked. 
![Captura](https://github.com/alshedivat/al-folio/assets/80715295/dc90e4be-25c3-4ced-bdb7-368f80361f6b)

**Comment by kun126** [comment]
Hi I just followed all the steps to initialise the webpage. The pages build and deployment works, while I keep getting an error from the `Lighthouse Badger` step in GitHub Actions:

> [lighthouse-badger-easy](https://github.com/kun126/kun126.github.io/actions/runs/11755918113/job/32751498748#step:3:24)
> Input required and not supplied: token

It seems to have no influence on the webpage itself. Would you suggest to ignore it or do something? Thanks

**Comment by gael-vanderlee** [comment]
> Hi I just followed all the steps to initialise the webpage. The pages build and deployment works, while I keep getting an error from the `Lighthouse Badger` step in GitHub Actions:
> 
> > [lighthouse-badger-easy](https://github.com/kun126/kun126.github.io/actions/runs/11755918113/job/32751498748#step:3:24)
> > Input required and not supplied: token
> 
> It seems to have no influence on the webpage itself. Would you suggest to ignore it or do something? Thanks

Same here

**Comment by george-gca** [comment]
This issue was closed years ago and is related to another error, so this should be treated in another issue.

About our workflows, check our [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md#what-do-all-these-github-actionsworkflows-mean).
