### ISSUE TITLE
INSTALL.md Local setup using Docker instruction not clear

### ISSUE THREAD

**Issue by TanYuanXiangElroy** [alshedivat/al-folio#2090]
When in the install page at section on

# Local setup using Docker (Recommended)

First, install [docker](https://docs.docker.com/get-docker/) and [docker-compose](https://docs.docker.com/compose/install/).

it is outdated as the [docker link](https://docs.docker.com/get-docker/) gets u to download `docker desktop` that already have `docker compose in docker desktop` .

Then u need to clone your repository to the local machine. (not mention)
Go to where the file is stored in command prompt (not mention)
 
Then type in the 2 commands
```bash
$ docker compose pull
$ docker compose up
```
And wait for abit untill it says server running and that local host port number/address will change.

For me my server address was  `http://0.0.0.0:8080` not `8888`  I didn't edit the `docker-compose.yml` file yet

Also when I edited the template after I save the changes in VS code it render the new version after a  few min I didn't need to do ( `docker compose up `) to render the webpage with all you changes like recomended

----
Thanks for looking through my message.

And I hope to get feedback it has been a while since I touch coding at all after almost a year break so it took me a while to understand that section and  and get it to work 
 
It is also the first time I did a issue so I hope for feedback on what I could improve on my language thanks

**Comment by pourmand1376** [comment]
You're right. Maybe we should completely rewrite that section. 

Maybe adding a `tldr` would also help.

**Comment by george-gca** [comment]
Do you think a TOC would be useful?

**Comment by TanYuanXiangElroy** [comment]
> Maybe we should completely rewrite that section. Maybe adding a `tldr` would also help

yes I believe so as I feel
`Installing and Deploying` and `Local setup using Docker (Recommended)`

is the only thing u need when installing the latest version of the template I believe.

and since it is recommended it should be above `Local setup on Windows`

>Do you think a `TOC` would be useful?

I feel the content is so small that i could read all pretty quick. I feel a `tldr` on what chapter I need to read to get thing up and running should be all I need

e. g

start up blog on latest version on GitHub pages `follow Installing and Deploying, Local setup using Docker (Recommended)`

start up blog locally on GitHub page not recommended `follow Installing and Deploying, Local Setup (Legacy)` if u are using window follow `Local setup on Windows` instead of `Local Setup (Legacy)`

`deployment` chapter over laps with `Installing and Deploying`.

`Installing and Deploying` cover the first half of `deployment` and only chapter  `Manual deployment to GitHub Pages` and bellow seems different

**Comment by george-gca** [comment]
> yes I believe so as I feel `Installing and Deploying` and `Local setup using Docker (Recommended)` is the only thing u need when installing the latest version of the template I believe. And since it is recommended it should be above `Local setup on Windows`

We put this section `Local setup on Windows` above everything because even with Docker people using Windows (which maybe is most of our users) are having problems, and we still don't know how to solve it. But if you install WSL and Docker inside, everything runs smoothly, so the idea is to install WSL first, then docker inside it.

> I feel the content is so small that i could read all pretty quick. I feel a `tldr` on what chapter I need to read to get thing up and running should be all I need

I believe the titles of the sections pretty much sum them up, don't they? Like you said, it is a small read, don't know if a TLDR for it will make much of a difference. That's why I suggested a TOC, so you look at the title of the section and jump straight to it.

**Comment by TanYuanXiangElroy** [comment]
>But if you install WSL and Docker inside, everything runs smoothly, so the idea is to install WSL first, then docker inside it.

I understand it makes sense now. I just skipped to docker as I didn't want to install WSL

>TOC, so you look at the title of the section and jump straight to it.

if it includes the sub chapter like
* deployment
   * For personal and organization webpages
   * For project pages

then it is very helpful I brain dead and though `TOC` will only include the main chapters which will be not very helpful

**Comment by george-gca** [comment]
No, it would include all subsections. Did everything worked with docker on windows for you?

**Comment by TanYuanXiangElroy** [comment]
> No, it would include all subsections. Did everything worked with docker on windows for you?

I downloaded the docker desktop for windows and jsut opened it so I think docker worked for me. 

but I dont think I sould be used as a use case now that I think of it. As my laptop is full of downloaded stuff which I forgot I even downloaded

**Comment by george-gca** [comment]
No, all of this is being implemented, since the improvements are needed. After we merge it in master we close this.
