### ISSUE TITLE
Google monetization ads.txt not working

### ISSUE THREAD

**Issue by QuwsarOhi** [alshedivat/al-folio#2092]
Added ads.txt in the root directory of github.io page. On al-folio 0.3.5 ads.txt was recognized by google ads. But with same settings al-folio 0.11 fails to be accepted by google ads. Google ads says "ads.txt was not found".

Has anyone tried adding ads.txt and did it work?

**Comment by george-gca** [comment]
Maybe something is preventing it to be copied to `_site/`. Try building your site locally with `bundle exec jekyll build --lsi` then check the generated `_site/` directory. If it is not being copied to `_site/`, try adding it to [keep_files](https://jekyllrb.com/docs/configuration/options/) in [_config.yml](https://github.com/alshedivat/al-folio/blob/master/_config.yml).

**Comment by QuwsarOhi** [comment]
ads.txt exists without adding it in keep_files. Also, I tried adding it in keep_files but it did not work. After some days adsense claims the ads.txt does not exist.

**Comment by george-gca** [comment]
The build process before uploading the site to GitHub pages is done in [.github/workflows/deploy.yml](https://github.com/alshedivat/al-folio/blob/1d84621f220e157d0701d5cbd69f334cb6730a4c/.github/workflows/deploy.yml#L33). Try to replicate these steps locally and see if the `ads.txt` file is copied to the `_site/` directory that is generated after the build. If it is, then something outside our template is blocking you. Maybe check `JamesIves/github-pages-deploy-action` action documentation to see if this action doesn't handle it.
