### ISSUE TITLE
Delete unused branches

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#2099]
Just realized that our repo have [a lot of different branches](https://github.com/alshedivat/al-folio/branches/all), and probably almost all of them were created to introduce some change. I believe most of them can be safely deleted, but idk since I haven't created any of them. I normally create a branch in my fork of the repo, submit a PR, then delete the branch from my repo after it is merged. Can you guys take a look at it @alshedivat @pourmand1376 @rohandebsarkar?

This is of course low priority, but just adding it here so we don't forget about it.

Also I would like to acknowledge all the effort that was put to create and maintain this repo.

**Comment by pourmand1376** [comment]
Hi. I removed my branches. 5 of them were mine and they were merged into source code previously. So, they were no longer needed. 

Thanks for your attention!

**Comment by guscastilloa** [comment]
Hi! Do you know why there is a `gh-pages` branch? I nuked my personal website after deleting the branch and now trying to learn how al-folio and jekyll+GitHub pages work is a titanic task for me. Appreaciate your help!

**Comment by george-gca** [comment]
Please ask this question in the Q&A section so other users can benefit from the answer.
