### ISSUE TITLE
ABS badge not working 

### ISSUE THREAD

**Issue by bischofMuenster** [alshedivat/al-folio#2100]
**Acknowledge the following**

- [x] I carefully read and followed the [Getting Started](../../README.md#getting-started) guide.
- [x] I read through [FAQ](../../FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Going on your test website: [https://alshedivat.github.io/al-folio/publications/](url) and clicking on the ABS, BIB badges on the publications sites doesn't do anything. In older versions the Abstract popped open. I tried this on three different browsers to be sure.

I'm asking this as I use a quite old version of your theme that now stopped working and I tried updating but realized these issues. 

**To Reproduce**
Steps to reproduce the behavior: Go to  [https://alshedivat.github.io/al-folio/publications/](url), click on publications, click on ABS or BIB. Nothing happens. 

**Expected behavior**
A clear and concise description of what you expected to happen. I expect the badges to open and show me the Abstract of the publications.

**Screenshots**

**System (please complete the following information):**

- OS: [e.g. iOS] iOS 
- Browser (and its version) [e.g. chrome, safari] chrome, safari, arc 
- Jekyll version [e.g. 3.8.7]
- Ruby version [e.g. 2.6.5]

**Additional context**

**Comment by bischofMuenster** [comment]
PS: Same applies to the "darkmode", "submenus" buttons. They do not work on your test webpage and also not on mine.

**Comment by george-gca** [comment]
Fixed both of them later on yesterday. Update your code and check it again. I inadvertently changed the code of purgecss.

**Comment by bischofMuenster** [comment]
Great, thanks a lot!
