### ISSUE TITLE
lighthouse-badger-easy Input required and not supplied: token

### ISSUE THREAD

**Issue by charleslipku** [alshedivat/al-folio#2122]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

lighthouse-badger-easy Input required and not supplied: token

### How to reproduce the bug

[lighthouse-badger-easy](https://github.com/charleslipku/caselab/actions/runs/7648371246/job/20841035499#step:3:24)
Input required and not supplied: token

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

**Comment by george-gca** [comment]
Thanks for pointing this out. This is something I must add to the documentation.

For this action to work you must create in your repository a new encrypted repository secret named `LIGHTHOUSE_BADGER_TOKEN` with this information. Check [lighthouse-badger](https://github.com/MyActionWay/lighthouse-badger-workflows#lighthouse-badger-easyyml) documentation on how to do this. More specifically check the `create a new encrypted repository secret` section inside the `Set it up (click to toggle)` part of `lighthouse-badger-easy.yml`
