### ISSUE TITLE
prettier code formatter workflow run failed for master branch

### ISSUE THREAD

**Issue by sdiomedi** [alshedivat/al-folio#2140]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description
Every time i try to modifie some file in github.io al folio theme, I obtain these error.
prettier code formatter workflow run failed for master branch

### How to reproduce the bug

just do some modificatoin on some file and commit, I always obtain: prettier code formatter workflow run failed for master branch

### Error messages and logs

```
prettier code formatter workflow run failed for master branch

Run npx prettier . --check
Checking formatting...
[warn] _config.yml
[warn] _pages/about_einstein.md
[warn] _pages/about.md
[warn] Code style issues found in 3 files. Run Prettier to fix.
Error: Process completed with exit code 1.

```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Deployed site

**Comment by george-gca** [comment]
This is not an issue. We implemented support for [Prettier](https://prettier.io/) code formatting a while ago. It basically ensures that your code is well formated. If you want to disable it for your repo just delete the file [.github/workflows/prettier.yml](https://github.com/alshedivat/al-folio/blob/master/.github/workflows/prettier.yml).

**Comment by george-gca** [comment]
Just added information about Prettier to [FAQ.md](https://github.com/alshedivat/al-folio/blob/master/FAQ.md).

**Comment by sdiomedi** [comment]
> This is not an issue. We implemented support for [Prettier](https://prettier.io/) code formatting a while ago. It basically ensures that your code is well formated. If you want to disable it for your repo just delete the file [.github/workflows/prettier.yml](https://github.com/alshedivat/al-folio/blob/master/.github/workflows/prettier.yml).
> 
> But I agree that we should add this information on the FAQ.

ok but why faild every time?
![Screenshot 2024-01-30 112235](https://github.com/alshedivat/al-folio/assets/132673084/11510b6e-82e6-44a1-9460-da3f671e33b6)

**Comment by george-gca** [comment]
Because your code is not formatted in the way prettier is expecting.

The easiest way for you to check what the problems are is to check the artifact that is created by the failed run. I made it so when the prettier check fails it generates an artifact to be downloaded, and that artifact is an html file containing the changes you should made to make it pass the test.

**Comment by george-gca** [comment]
You can see it in the failed action in your repo, below `Annotations`.

**Comment by minzhezhu** [comment]
> You can see it in the failed action in your repo, below `Annotations`.

Oh, I find it! Thanks a lot!
