### ISSUE TITLE
Guidance on filenames for blog posts

### ISSUE THREAD

**Issue by sebastianrowan** [alshedivat/al-folio#2142]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

The documentation and FAQs do not inform the user that filenames for blog posts must adhere to a specific format as far as I have seen. I discovered this problem after spending hours trying to debug my site, only to realize the issue was the file name. I did find one post in the Q&A on this topic, but I feel it would be nice to have info on this in the README or FAQ page.

### Pitch

Simply add a new FAQ to the document describing the proper format for blog posts.

Q: When I add a new file to the /_posts directory, the post does not appear on my blog.

A: Here are common reasons why a post may not be showing up on your blog:

- **Describe proper filename convention here.**
- If there are other common issues, also include them in the answer.

### Alternatives

An alternative would be to change whatever code is forcing this naming convention. That may be the "best" approach, but also I assume more complicated.

**Comment by george-gca** [comment]
What do you mean exactly? What was the name that you gave that was an issue?

**Comment by sebastianrowan** [comment]
I added a new file to _posts named `testimony.md` which was not showing up on my site. I checked the yaml header and related setting in `_config.yml`, and I couldn't find anything that could explain why the post wasn't showing up. I eventually renamed the file `2024-01-25-testimony.md` and once I did that the post appeared on my site. 

So it seems to me that for a blog post to be properly parsed and rendered onto the site the file name must be formatted as `yyyy-mm-dd-filename-text.md`.

**Comment by george-gca** [comment]
Yes it has, it is stated in the [jekyll documentation](https://jekyllrb.com/docs/posts/#creating-posts). But this information is actually in our documentation already. See the [Creating new blog posts](https://github.com/alshedivat/al-folio/blob/master/CUSTOMIZE.md#creating-new-blog-posts) section on `CUSTOMIZE.md`.

**Comment by sebastianrowan** [comment]
Thanks! I assumed there was a good chance that once I posted this, someone would quickly point out the obvious answer I didn't see. Not really sure how I missed that, tbh.
