### ISSUE TITLE
[Feature Request] Add tags to the publications and filter them by tags

### ISSUE THREAD

**Issue by mingwei-liu** [alshedivat/al-folio#2174]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

Can I add some tags to the publications like blogs? Further, can I filter the publications by its tags? Is it possible to implement such functionality? Thanks.

**Comment by george-gca** [comment]
This functionality is already supported by [jekyll-scholar](https://github.com/inukshuk/jekyll-scholar?tab=readme-ov-file#bibliographies) plugin, and it is currently used to filter selected papers to display at the about page. Just check the [bib file](https://github.com/alshedivat/al-folio/blob/master/_bibliography/papers.bib) and how it is filtered out in [_includes/selected_papers.liquid](https://github.com/alshedivat/al-folio/blob/master/_includes/selected_papers.liquid). You just have to create your own fields and use it that way.
