### ISSUE TITLE
problem with the link of my site

### ISSUE THREAD

**Issue by vasilisfloudas** [alshedivat/al-folio#2181]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

can't create the link to the site, however everything seems to work fine

### How to reproduce the bug

trying to create my personal site i overcame the problems i saw from other users like the gem mini race or the problem with the diagram or the problem with imagemagick, my site locally works perfectly, but after i do the procedure to push it to my github it doesn't give me a link to the site (i waited long enough and it doesn't give a link, i also followed the instructions). Does anyone have any suggestions? 

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Running locally without Docker

**Comment by george-gca** [comment]
You didn't post the `Error messages and logs` part. Check your GitHub actions' logs to see what the problem was while deploying, and try to fix those issues. If there is any issue that is not yet covered by our [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) or previos issues, please post the log here.

**Comment by vasilisfloudas** [comment]
thanks for the quick reply and sorry if it sounds stupid, but where can i find actions' logs? Do u mean the actions' logs on the process or on my repository?

**Comment by george-gca** [comment]
On your repository. You can check the [actions tab in your repository](https://github.com/vasilisfloudas/vasilisfloudas.github.io/actions) for more information about the failed workflows. For example, in the [last one](https://github.com/vasilisfloudas/vasilisfloudas.github.io/actions/runs/7849083318/job/21421669039) it says `Error: Liquid syntax error (line 59): Unknown tag 'toc'`. You can check more information about this error on our FAQ.

**Comment by george-gca** [comment]
My recommendation is, follow the instructions in [installing and deploy](https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#installing-and-deploying) strictly. First make it work with as few changes as possible. Only them made the changes you want.

**Comment by vasilisfloudas** [comment]
- i did what you say, i follow the instructions stricly, my site was up until i clone the repo to make some little changes

### more specifically 

- change name and turn off some cv/people/ teaching/publication
- change  gem mini racer to →  gem execjs
- add gem gem 'wdm', '>= 0.1.0'
- change .ipynb to .IPYNB and works
- turn magickimage enable to false
- all these one because the commands οf jekyll for hosting topically did not work.  
- all fine with the site hosting topic → 
![image](https://github.com/alshedivat/al-folio/assets/92634747/f69834e1-2b22-4b40-9616-f9452a0e8ce5)

  with ctrl+click showing my edited site

- **HOWEVER**, after run these commands (

> git init
> git checkout -b gh-pages
> git status 
> git add .
> git commit -m “initial commit”
> git remote add origin  https://github.com/myusername.io.git
> git branch gh-pages
> git push origin gh-pages

) 


 the problem that has arisen (and is probably off-topic) is this -> 
![image](https://github.com/alshedivat/al-folio/assets/92634747/92869ec4-35d8-4b04-8445-22d0729078b1)


 **Any suggestions?** 

**thank you very much for your time. I appreciate it**

**Comment by george-gca** [comment]
You should not mess with `gh-pages` branch. Only GitHub actions should use it. All your modifications should be at the main branch only.

Also, did you make all these changes in a single commit? If yes, you are kind of missing the point of git. You should keep your commits as minimal as possible, so it is not only easier to find which modification caused the issue, but also it is easier to revert the changes.

**Comment by vasilisfloudas** [comment]
the commands (include for gh-pages) its from this tutorial: [Jekyll Tutorial](https://www.taniarascia.com/make-a-static-website-with-jekyll/) . 

What process do u suggest (with commands include) to push my site? 

> Also, did you make all these changes in a single commit?
-  changes yes, commands no. I will do it again with one-to-one process. Thank you!

**Comment by george-gca** [comment]
Forget the tutorial, this template have everything you need to set it up as easy as possible. Since you said your site worked on the beginning, then obviously another change you introduced breaked the code.

The workflow is simple:
- Make it work for the first time, changing the minimum
- It is working, now do changes as small as possible, always testing them both locally and when you push your code to your repo
 
The repository is set so every commit you do in the main branch of your repo builds the site and automatically deploy it to your page. If the build fails, then something is wrong. Doing small changes at a time makes it easier to pinpoint the exact change that messed up.

You can check the results of the build and deploy in the actions part of your repository. All workflows defined in the `.github/workflows/` directory will appear in this part and their execution can be checked there.

**Comment by vasilisfloudas** [comment]
if local works perfectly i proceed with: modify a mini change-> push -> check if the change works on the site and again and again the same procedure for each change. No problem if it works. fingers crossed

**Comment by vasilisfloudas** [comment]
Does it HAVE to work local? is it necessary? or do we just push and let it not work with the command bundle exec jekyll server

PS: the instructions for beginners  are completely problematic and do not help, on the contrary they are more confusing

**Comment by vasilisfloudas** [comment]
george thank you very much for your help, the site is up and running

**Comment by george-gca** [comment]
If you think this is still confusing, create a PR with the changes you think are necessary, so we can further discuss this. Closing this issue.
