### ISSUE TITLE
Line break before comma in author list.

### ISSUE THREAD

**Issue by goldblum** [alshedivat/al-folio#2185]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

In author lists, the lines often break right before a comma so the next line starts with a comma.

### How to reproduce the bug

This issue happens when you leave max_author_limit blank in _config.yml. See https://goldblum.github.io/publications/.  I attached a screenshot.
<img width="991" alt="Screenshot 2024-02-11 at 09 53 38" src="https://github.com/alshedivat/al-folio/assets/442416/e2453d4d-20b0-4e20-8397-f401175d20be">

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

**Comment by george-gca** [comment]
Related discussion #2153.

**Comment by goldblum** [comment]
> Related discussion #2153.

Is the solution to the line breaks to remove the space before the commas?

**Comment by george-gca** [comment]
Probably yes, but it is kind of tricky to find the right places to remove the spaces. If you manage to do so, please submit a PR.

**Comment by goldblum** [comment]
Should it be on line 104 of bib.liquie:
`            {% assign more_authors_show = more_authors_show | append: ', ' %}
`
to
            {%- assign more_authors_show = more_authors_show | append: ', ' %}

**Comment by goldblum** [comment]
That didn't work

**Comment by george-gca** [comment]
Like I said, it is kinda tricky. Probably needs the `-` in a few more places.
