### ISSUE TITLE
Sidebar Table of Content Lists Bibliography and Years on an Equal Level

### ISSUE THREAD

**Issue by DavidKrassnig** [alshedivat/al-folio#2192]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

When you use the Sidebar-ToC feature, it lists references and then all years that contain a bibliographical entry on the same level

### How to reproduce the bug

1. Add this to the preamble of a post:
```
toc:
  sidebar: left
related_publications: true
```
2. Add some citations to the post
3. Check resulting table of content in the sidebar

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Linux, Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Running locally without Docker

### More info

Screenshot:
<img src="https://github.com/alshedivat/al-folio/assets/96623786/3eb13786-1589-4ff6-87c1-e0249e527429" width="350" height="350">

**Comment by george-gca** [comment]
The problem seems to be that `jekyll-scholar` when creating the grouped version of papers add `h2` to the group title. See here:

![image](https://github.com/alshedivat/al-folio/assets/31376482/773e23e8-6256-407e-847f-8367c95cc3ff)

Not sure yet how to fix this.
