### ISSUE TITLE
main content shadowed by the footer 

### ISSUE THREAD

**Issue by Xivid** [alshedivat/al-folio#22]
I know this is a feature, but I am wondering how I can keep the footer at the page bottom while not letting it shadow the main content. I don't want the footer bar to disturb the reader when the actual page bottom has not been reached.

Any suggestions/pointers would be welcome.

**Comment by alshedivat** [comment]
If you want the header/footer to not move while scrolling the page, you will need to change the styles of the corresponding blocks by removing `position: fixed;`. For the header, it is defined in [_header.scss](https://github.com/alshedivat/al-folio/blob/master/_sass/_header.scss#L5) and for the footer in [_footer.scss](https://github.com/alshedivat/al-folio/blob/master/_sass/_footer.scss#L28). Simply removing these styles may add some unnecessary padding before/after the corresponding blocks.

It would be wonderful if you could add a couple of options in `_config.yml` that control this behavior of the header and footer (and correctly handle the padding) and send a pull request.
