### ISSUE TITLE
"Liquid Exception: Liquid syntax error" during creating Blog from Jupyter notebook

### ISSUE THREAD

**Issue by awsaf49** [alshedivat/al-folio#2208]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

While creating a blog form jupyter notebook, I'm getting this error "Liquid Exception: Liquid syntax error". However, this is for a specific notebook not for all the notebooks as I've already created few blogs with jupyter notebook. So, seems this problem is occuring for specific for this notebook

### How to reproduce the bug

Step1: Create a `.md` file in `/_data/_posts/data-name.md` and use following code

```markdown
---
layout: post
title: Token Classification aka Named Entity Recognition (NER) from Scratch
date: 2024-02-16 08:57:00-0400
description: Detect and remove personally identifiable information (PII) from student writing.
categories: kaggle notebook transformer nlp
giscus_comments: true
related_posts: false
featured: true
---
It may take a few moments for the Jupyter notebook to load. Thank you for your patience =)

{::nomarkdown}
{% assign jupyter_path = "assets/notebook/pii-data-detection.ipynb" | relative_url %}
{% capture notebook_exists %}{% file_exists assets/notebook/pii-data-detection.ipynb %}{% endcapture %}
{% if notebook_exists == "true" %}
    {% jupyter_notebook jupyter_path %}
{% else %}
    <p>Sorry, the notebook you are looking for does not exist.</p>
{% endif %}
{:/nomarkdown}
```

Step2: Download the `.ipynb` notebook from [kaggle](https://www.kaggle.com/code/awsaf49/pii-data-detection-kerasnlp-starter-notebook/notebook) and add it in `assets/notebook/` as `pii-data-detection.ipynb`

### Error messages and logs

```
   Liquid Exception: Liquid syntax error (line 655): Variable '{{\n", " x.observe(notebookContainer, {childList: true}' was not properly terminated with regexp: /\}\}/ in assets/notebook/pii-data-detection.ipynb
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

**Comment by george-gca** [comment]
Internally jekyll-jupyter-notebook calls like this the converting command. Test converting the notebook isolated. If something goes wrong, then it is a bug with the nbconvert tool.

**Comment by awsaf49** [comment]
Thanks @george-gca for the suggestion, I will try it out and let you know.
