### ISSUE TITLE
Link contains "#"

### ISSUE THREAD

**Issue by uverma** [alshedivat/al-folio#221]
I am able to generate the static website locally without any error. But the link for publication (top right-hand corner) points to "<username>.github.io/#publications". 

I am not sure why this "#" is included in the link. 

PS; I have verified that the publications page is generated correctly by manually entering "<username>.github.io/publications". and it works fine

**Comment by alshedivat** [comment]
@uverma, thanks for reporting this. How do the `url` and `baseurl` fields in your `_config.yml` look like? It seems like "#" might be appended for some reason to the relative urls that jekyll generates.

**Comment by uverma** [comment]
@alshedivat Thanks for the follow-up. I also thought that I have appended "#" by mistake. 

The url and baseurl fields in config.yml are blank. I have three hyperlinks generated, one is the link to the homepage, other is a link to the publications and project page. Surprisingly, the link to the project page is <username>.github.io/projects (without any "#")

**Comment by alshedivat** [comment]
@uverma, this is odd. Could you please deploy your webpage to github and share a link so I can look into what's happening?

**Comment by uverma** [comment]
@alshedivat While deploying to GitHub, I noticed that the links point to <localhost:4000>/projects, or <localhost:4000>/#publication. Is there something I am missing here? 

I have uploaded the source code and the generated file at https://github.com/vermauj/vermauj.github.io

**Comment by alshedivat** [comment]
@uverma, the repository you linked looks very outdated. Could you please upgrade to the latest version of al-folio and see if the issue persists? Thanks.

**Comment by uverma** [comment]
Thanks. I updated the version. And it is working fine. Thanks again for your help
