### ISSUE TITLE
Add hyperlink in publications for items with a url

### ISSUE THREAD

**Issue by smith478** [alshedivat/al-folio#2222]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

It would be nice if items in the [bibliography](https://github.com/alshedivat/al-folio/blob/master/_bibliography/papers.bib) (`_bibliography/papers.bib`) with a `url` value (e.g. [here](https://github.com/alshedivat/al-folio/blob/master/_bibliography/papers.bib#L42)) included a hyperlink on the `publications` page.

I found one somewhat related (resolved) issue [here](https://github.com/alshedivat/al-folio/issues/29), however that one is for links to pdfs stored within the project. What I'm suggesting is for a link to the publication url.

**Comment by smith478** [comment]
If this is a feature that seems worth adding I created a PR [here](https://github.com/alshedivat/al-folio/pull/2223).

**Comment by george-gca** [comment]
Isn't this kind of the point of the `html` part of the entry? Also aesthetically speaking imagine the case where some publications have a url and some do not, so some titles would be looking different than the others. In this case don't you think the `html` button is a better solution?

**Comment by smith478** [comment]
Ah I missed that. Yeah I agree that using the `html` button is better! Thanks @george-gca !
