### ISSUE TITLE
Harmonizing width and height of cards in /projects/

### ISSUE THREAD

**Issue by clairedavid** [alshedivat/al-folio#2246]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

Have an option to set the cards in /projects/ to be the same height in a given row and their width so that they nicely fill the entire text width.

### Pitch

The /projects/ layout has cards of fixed width of 250px and variable height depending on the content. It would render better if the cards are of same height (the one of the longest element grid-item in the row).
Additionally, the cards are left-ragged. Aesthetically, it would render better if their width and padding are such that the cards fill the entire text width.
Would that be possible? Thanks!

**Comment by mcopik** [comment]
This would be a great enhancement. Right now, the projects card can look a bit chaotic when there are many projects with a varying description length.
