### ISSUE TITLE
Option to follow system theme for dark-mode

### ISSUE THREAD

**Issue by SamAdamDay** [alshedivat/al-folio#2256]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

It would be great to have a third option for the dark mode toggle which follows the system theme (`prefers-color-scheme: dark`). Currently as soon as the user either sets the page theme to dark mode or sets their system to dark mode, this setting is remembered so the theme has to be manually changed if the user later uses a light system theme.

This is a little annoying for me since I change my system theme frequently (dark mode during the night, light mode during the day). In my experience most websites with a dark theme allow following the system theme.

### Pitch

A third option for the theme toggle which follows the system theme.

### Alternatives

Manually changing theme every time I visit the page.

### Additional context

The Numpy docs gives an example of what I'm suggesting: https://numpy.org/doc/1.26/

I'm happy to contribute to a PR for this.

**Comment by george-gca** [comment]
I thought about the same solution of numpy site (having a 3rd option there with half icon), but if possible using half sun, half moon icon. Do you know if this is feasible with the free version of font awesome? Also a PR is always welcome.

**Comment by SamAdamDay** [comment]
It looks like there are [some good symbols in Font Awesome](https://fontawesome.com/search?q=sun%20moon&o=r
), but they all require the pro version (e.g. 'moon-over-sun'). 

![image](https://github.com/alshedivat/al-folio/assets/1466743/494097ef-2bd8-4a6e-b69e-7f28d250ce1a)

The [half circle symbol](https://fontawesome.com/icons/circle-half-stroke?f=classic&s=solid) is available for free though.

![image](https://github.com/alshedivat/al-folio/assets/1466743/d867ea36-7dbe-46b0-987b-decf644e92bc)

I'll try to make a PR in the next few days

**Comment by SamAdamDay** [comment]
I've made a PR for this:  #2261

Currently it uses the half-circle symbol, but that can be changed
