### ISSUE TITLE
Distill l-gutter not working

### ISSUE THREAD

**Issue by vmasrani** [alshedivat/al-folio#227]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
Longer text within the l-gutter div causes weird spacing as seen in the screenshot below: 

<img width="1081" alt="Screen Shot 2021-03-27 at 10 31 40 PM" src="https://user-images.githubusercontent.com/3288149/112743520-e825a600-8f4c-11eb-8522-4888b22eddf0.png">

**To Reproduce**
I modified the text at the bottom of `2018-12-22-distill.md`  to:
 
```

The final layout is for marginalia, asides, and footnotes.
It does not interrupt the normal flow of `.l-body` sized text except on mobile screen sizes.

<div class="fake-img l-gutter">
  <p>.l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter .l-gutter </p>
</div>

The final layout is for marginalia, asides, and footnotes.
It does not interrupt the normal flow of `.l-body` sized text except on mobile screen sizes.

The final layout is for marginalia, asides, and footnotes.
It does not interrupt the normal flow of `.l-body` sized text except on mobile screen sizes.
```
and this produced the screenshot above

**Expected behavior**
The gutter text doesn't add whitespace to the body

**System (please complete the following information):**
 - OS: macOS Catalina
 - Browser (and its version) Edge:  89.0.774.63
 - Jekyll version: 3.9.0
- Ruby version: 2.6.5

**Comment by alshedivat** [comment]
This issue is coming from distill.pub's `template.v2.js`. I can reproduce the behavior by directly editing the styles of [one of their articles](https://distill.pub/2019/computing-receptive-fields/) that uses v2 template (see the screenshot below). I recommend raising this issue directly in [distilpub/template](https://github.com/distillpub/template).

<img width="1200" alt="Screen Shot 2021-03-29 at 12 59 56 PM" src="https://user-images.githubusercontent.com/2126561/112872933-f5e34480-908e-11eb-949e-5cd8dd1ad65a.png">

**Comment by vmasrani** [comment]
Great will do - thanks!
