### ISSUE TITLE
Extra whitespace on mobile

### ISSUE THREAD

**Issue by aidanconnoroneill** [alshedivat/al-folio#2288]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

When I open the hamburger menu on mobile, scroll down and scroll up, extra white space is added to my projects page

### How to reproduce the bug

1.  Go to 'aidanconnoroneill.github.io' on mobile.  
2. Visit the teaching tab
3. Open the hamburger menu
4. Scroll down and scroll up, and lots of whitespace appears at the top of the page

### Error messages and logs

N/A -- just unexpected whitespace

### What operating system are you using?

Windows, Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Running locally with Docker, Deployed site

### More info

I've verified this happens on someone else's website that also uses al-folio, only on their projects page.  When I inspect on a local build using dev-tools, I notice that padding-top becomes a huge number, but the navbar seems to be hiding fine.  I'm curious what is causing the fixed-top-nav to have such a large whitespace creep only on the projects page (which my teaching page is modeled on) - this doesn't seem to happen on any of the others.  
Thanks for looking into!

**Comment by abhilesh** [comment]
I tested out your website and am unable to reproduce the issue - 
![ScreenRecording2024-08-12at10 35 35-ezgif com-optimize](https://github.com/user-attachments/assets/8d603945-4cf4-435f-a487-10d4c1ba05f8)
