### ISSUE TITLE
jekyll scholar undefined method 'numeric'

### ISSUE THREAD

**Issue by atwu** [alshedivat/al-folio#2323]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Everytime I try to deploy, I get a bug saying "Liquid Exception: undefined method 'numeric?' for nil:NilClass in _pages/publications.md"

### How to reproduce the bug

I never used the method numeric though, so I'm assuming it's a backend thing. You can see the full error description in the following: 
[https://github.com/atwu/atwu.github.io/actions/runs/8585646428/job/23527263410](url)

### Error messages and logs

```
  Populating LSI... 
Rebuilding index... 
                    
  Liquid Exception: undefined method `numeric?' for nil:NilClass in _pages/publications.md
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/runner/work/atwu.github.io/atwu.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-scholar-7.1.3/lib/jekyll/scholar/utilities.rb:343:in `group_value': undefined method `numeric?' for nil:NilClass (NoMethodError)

          if value.numeric?```


### What operating system are you using?

Windows, Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Running locally without Docker

### More info

In addition, gh-pages isn't updating after I commit. I'm not sure if it's related to master not being deployed correctly. Thanks!

**Comment by george-gca** [comment]
Looking at the error again, it states:

```
/home/runner/work/atwu.github.io/atwu.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-scholar-7.1.3/lib/jekyll/scholar/utilities.rb:343:in `group_value': undefined method `numeric?' for nil:NilClass (NoMethodError)
```

The error happens inside `group_value` function in `jekyll-scholar`. We set `jekyll-scholar` to group papers by year by default. Just checked and not all your papers have associated years, so probably that's why this happens.

**Comment by atwu** [comment]
Dear George,

Yep that fixed the problem. Thanks! Also, is there a way for me to look into the jekyll code/the tracebacks? I don't want to keep bothering you every time I see something :)

**Comment by george-gca** [comment]
I just looked at the output of the failed build action. From there you can get at least a place to start. Also always search for the error message or part of it in this repository. Lots of problems have been reported already and solutions provided. If they are frequent enough we add them to the FAQ.
