### ISSUE TITLE
How to add multiple tags to a post so that one can retrieve posts by tags?

### ISSUE THREAD

**Issue by poodarchu** [alshedivat/al-folio#237]

**Comment by alshedivat** [comment]
Jekyll supports tagging by default. However, the theme does not support tags currently. To enable tagging, you need to add `tags: [<list of your tags>]` to the header of your posts and [create a tag page](https://www.untangled.dev/2020/06/02/tag-management-jekyll/) for listing posts of the selected tag.

I don't have the capacity/time to add this feature myself, but PRs are very welcome!

**Comment by alshedivat** [comment]
Support for tags was added in #346.
