### ISSUE TITLE
Is there a way to get bibtex generated for each of my posts that people can use to cite me?

### ISSUE THREAD

**Issue by chnsh** [alshedivat/al-folio#2374]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

I have a minor request, I would love to get automated bibtex generated for my blog posts that someone can use to cite me.

An example is the following image obtained from https://eugeneyan.com/writing/evals/
<img width="748" alt="image" src="https://github.com/alshedivat/al-folio/assets/7926657/067b7563-3a6b-42a9-b2ac-7148e920b3f9">

**Comment by george-gca** [comment]
I think this is a good idea, and in fact it can be easily implemented.

**Comment by chnsh** [comment]
Wow you are quick! Thank you so much!
