### ISSUE TITLE
Continuously report error message right after creating the repo from the template and changing the url and baseurl.

### ISSUE THREAD

**Issue by Hanning-Liu** [alshedivat/al-folio#2382]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Continously report error message right after creating the repo from the template and changing the url and baseurl.

### How to reproduce the bug

1. Create the repo from the template
2. change the url and baseurl in the _config.yml file

### Error messages and logs

![image](https://github.com/alshedivat/al-folio/assets/42676581/f00018fc-3a1b-48d3-b833-422d6c33e69a)

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Deployed site

**Comment by Hanning-Liu** [comment]
https://hanning-liu.github.io/Hanning-Liu/
The format of the website isn't correct either:
![image](https://github.com/alshedivat/al-folio/assets/42676581/41c0763c-a85a-4b00-aedf-b5fbe7279b75)

**Comment by Hanning-Liu** [comment]
Also report error after I fork this repo to local and use “open folder in a dev container” command in VSCode

**Comment by ethan-wu366** [comment]
Also seeing the same error on https://ethan-wu366.github.io/al-folio/

**Comment by ethan-wu366** [comment]
Looks to be missing data-theme and data-theme-setting in html
Ex of normal site:
<img width="573" alt="Screenshot 2024-05-01 at 11 39 41 PM" src="https://github.com/alshedivat/al-folio/assets/58535115/61da19c9-38b1-4a9e-a24b-d5e78a5abbe7">
Ex of my site: 
<img width="573" alt="Screenshot 2024-05-01 at 11 39 47 PM" src="https://github.com/alshedivat/al-folio/assets/58535115/09376c13-81dc-40db-b218-5feefa58ae05">

**Comment by ethan-wu366** [comment]
Didn't make any changes, but it looks correct on my site now..

**Comment by george-gca** [comment]
You should follow every single detail of [INSTALL.md](https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#recommended-approach) instructions. You missed this:

> If you plan to upload your site to `<your-github-username>.github.io`, note that the name of your repository ⚠️ MUST BE ⚠️ `<your-github-username>.github.io` or `<your-github-orgname>.github.io`, as stated in the [GitHub pages docs](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites).
