### ISSUE TITLE
Workflow for adding posts

### ISSUE THREAD

**Issue by chaitanyamalaviya** [alshedivat/al-folio#24]
Hi,

Thanks for the great looking theme! I am finding it difficult to add posts to the blog page and was wondering if you could describe the workflow for the same. Is it as simple as adding another markdown page under the `_posts/` directory. If yes, that does not seem to be working for me.

Thanks!

**Comment by samfearn** [comment]
Hi,

To add a new post, you need to create a new file in the `_posts` directory, with a name of the form `YYYY-MM-DD-name.md`. It’s important that the date is included in the file name as above, and that your post starts with a YAML header with the title, date, description and layout as in the example posts.

**Comment by samfearn** [comment]
I should add, once you’ve created the new post as described, you need to run `bundle exec jekyll serve` to build the site and be able to preview it.

**Comment by chaitanyamalaviya** [comment]
Thanks for the reply! In fact, I had been doing exactly what you described. 
The reason why the page was not getting regenerated was somehow because of the `--incremental` flag. Not providing it and rerunning `bundle exec jekyll serve` worked for me.

**Comment by fackelm2** [comment]
In my case the new post was not shown because of the "date: YYY-MM-DD-name" entry! You can see this in your log when  starting "docker-compose up" for example ..

```
sudo docker-compose up
...
jekyll_1  |            Reading: _posts/backup/2020-01-01-videos.md
jekyll_1  |           Skipping: _posts/2024-07-19-pythonvenv.md has a future date
...
```
