### ISSUE TITLE
scholar.google.com no longer updates new publications from my homepage

### ISSUE THREAD

**Issue by DoHaiSon** [alshedivat/al-folio#2406]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

After a few months ago, I updated my homepage to al-folio v0.10.1. From this time, my googlescholar profile no longer updates any new papers or information from my Homepage. 

When I used v0.9.0, everything worked fine.  Scholar auto updates publications and embedded .pdf file from the github page. For example: https://scholar.google.com/scholar?oi=bibs&hl=vi&cluster=2857353449177665639. You can realize that the .pdf from github page was recorded a year ago, but It did not update the new .pdf file at this moment.

### What operating system are you using?

WSL

### Where are you seeing the problem on?

Deployed site

**Comment by george-gca** [comment]
I don't think I understand. I didn't even know that Google Scholar tracked files from the site, and I am not sure that the reason it is not tracking anymore is in our side. How did it even worked before? I mean, how Google Scholar finds the pdf files and relates them to publications?

**Comment by DoHaiSon** [comment]
> I don't think I understand. I didn't even know that Google Scholar tracked files from the site, and I am not sure that the reason it is not tracking anymore is in our side. How did it even worked before? I mean, how Google Scholar finds the pdf files and relates them to publications?

I didn't know how it work as well, anything is automatic :v. But somehow, it's worked at v0.9.0 and sooner. There are some tracked file on my scholar.
 
![image](https://github.com/alshedivat/al-folio/assets/50046954/a4e5e255-f56a-4db8-9df1-27a62cc0a8a8)
![image](https://github.com/alshedivat/al-folio/assets/50046954/1a0f560e-7565-4965-974b-654ff74e8519)

**Comment by george-gca** [comment]
Anyone have any idea about this @alshedivat @pourmand1376?

**Comment by DoHaiSon** [comment]
Oh, after a period of time, somehow, the scholar continues update my publications from the github page. So, I'll close this issue. Thx.
