### ISSUE TITLE
Installataion breaks. After changing _config.ym, action gives error!

### ISSUE THREAD

**Issue by rvraghvender** [alshedivat/al-folio#2407]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Lighthouse badger error

### How to reproduce the bug

As per the installation steps:
1. Use this template and create the directory as <github.username>.github.io.
2.  Give Read and Write workflow permission.
3. Change the URL in _config.yml.

Now after this step, there is error in completion in actions (specifically Lighthouse bager error).

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

**Comment by george-gca** [comment]
The only actions needed for your site to work are Build and Deploy. All the rest are actions that help keep your code/site organized and working as expected, or do some testing on it, which is the case of the Lighthouse action. Check information about it on our [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md#what-do-all-these-github-actionsworkflows-mean).
