### ISSUE TITLE
Removing accents from coauthor names causes issues

### ISSUE THREAD

**Issue by kaanaksit** [alshedivat/al-folio#2409]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Coauthor names are not highlighted when they have accents in their names

### How to reproduce the bug

https://github.com/alshedivat/al-folio/blob/36bc24f7e4f8525ce6f00ccb234073771c898430/_layouts/bib.liquid#L69

The line above has `remove_accents`, and this causes issues if the surnames have accents or special characters from other languages.

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Linux

### Where are you seeing the problem on?

Running locally without Docker

**Comment by george-gca** [comment]
If you look at the line just below:

https://github.com/alshedivat/al-folio/blob/36bc24f7e4f8525ce6f00ccb234073771c898430/_layouts/bib.liquid#L70

This line means that we look for this clean name in the [list of coauthors](https://github.com/alshedivat/al-folio/blob/master/_data/coauthors.yml), which in this case are the keys: `"adams", "podolsky", "rosen", "bach", "przibram", "schrodinger", "lorentz", "planck"`. Note that these are just keys to search for these coauthors. When writing their names in the publications we use the names provided in the bib entry, not this key.
