### ISSUE TITLE
Inint failed problem

### ISSUE THREAD

**Issue by sundongwei** [alshedivat/al-folio#2410]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

i have folk this template, follow the install.md, but always failed.

### How to reproduce the bug

<img width="1378" alt="Screenshot 2024-05-12 at 19 14 38" src="https://github.com/alshedivat/al-folio/assets/30918654/c5eb7e99-5d0a-4419-b537-2050444672c2">

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Deployed site

**Comment by george-gca** [comment]
I can't open your image here, and since you didn't add your logged error in the specified `Error messages and logs` field neither you posted a link to your repo so we could check the error there, there's not much we can do.

**Comment by sundongwei** [comment]
https://github.com/sundongwei/sundongwei.github.io/actions/runs/9056155873/job/24878286772
this is my workflow,you can check the error

**Comment by sundongwei** [comment]
> I can't open your image here, and since you didn't add your logged error in the specified `Error messages and logs` field neither you posted a link to your repo so we could check the error there, there's not much we can do.

**Comment by sundongwei** [comment]
> I can't open your image here, and since you didn't add your logged error in the specified `Error messages and logs` field neither you posted a link to your repo so we could check the error there, there's not much we can do.

https://github.com/sundongwei/sundongwei.github.io/actions/runs/9056155873/job/24878286772
this is my workflow,you can check the error

**Comment by george-gca** [comment]
If you check your error message (in red) it is actually: `Liquid Exception: Liquid syntax error (line 60): Unknown tag 'toc' in /_layouts/post.liquid`. We have an answer for this in our [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md#my-webpage-works-locally-but-after-deploying-it-fails-to-build-and-throws-unknown-tag-toc-how-do-i-fix-that).
