### ISSUE TITLE
Add Back To Top button

### ISSUE THREAD

**Issue by simonwei97** [alshedivat/al-folio#2425]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

Add back to top button for post.

Some example:
- https://jeffreytse.github.io/jekyll-theme-yat/

![image](https://github.com/alshedivat/al-folio/assets/119845914/69883a5d-995e-4564-89a8-b55ac623f376)

### Pitch

when user browse the post content to any position except the top of the article, `back_to_top` button will appear in the lower left corner of the screen. If user touch the button, it will go back to the top of article.

### Additional context

I will contribute for this feature as possible as I can.

**Comment by simonwei97** [comment]
@george-gca Thanks for your time to review my commit code. 

My PR has been merge into master #2427. I will close this issue.

**Comment by george-gca** [comment]
@simonwei97 thanks for your contribution. Would you mind taking a look at the mobile version? The button is too close to the footer.

**Comment by simonwei97** [comment]
> @simonwei97 thanks for your contribution. Would you mind taking a look at the mobile version? The button is too close to the footer.

OK. I will work on it. I was not considering to much for mobile device before.

- [ ] mobile version optimization for `back-to-top` feature

**Comment by simonwei97** [comment]
> > @simonwei97 thanks for your contribution. Would you mind taking a look at the mobile version? The button is too close to the footer.
> 
> OK. I will work on it. I was not considering to much for mobile device before.
> 
> * [x]  mobile version optimization for `back-to-top` feature

@george-gca hi, #2433 have some optimzation, will you review @abhilesh codes? Thanks.
