### ISSUE TITLE
Checking the formatting _config.yml will report an error!

### ISSUE THREAD

**Issue by chenjunyan1** [alshedivat/al-folio#2426]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

First of all, I set [baseurl :] in _config.yml to empty, and deployed without error, but when I clicked on the name in the web page, it navigated to an error page, so I changed it to [baseurl :/], but in actions it would report an error.  Prettier Check 🔎 Run npx prettier . --check   npx prettier . --check   shell: /usr/bin/bash -e {0} Checking formatting... [warn] _config.yml [warn] Code style issues found in the above file. Run Prettier to fix. Error: Process completed with exit code 1. But the page opens without any problem, I want to know why? I want the page to open in actions without reporting errors.

### How to reproduce the bug

<img width="695" alt="截屏2024-05-17 18 14 48" src="https://github.com/alshedivat/al-folio/assets/61654255/6fac6b17-b576-46d8-aed1-116e467e0d9a">

### Error messages and logs

# Actions
```
Prettier Check 🔎
Run npx prettier . --check
  npx prettier . --check
  shell: /usr/bin/bash -e {0}
Checking formatting...
[warn] _config.yml
[warn] Code style issues found in the above file. Run Prettier to fix.
Error: Process completed with exit code 1.
```

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Running locally without Docker

**Comment by chenjunyan1** [comment]
This is my github page : https://chenjunyan1.github.io/

**Comment by george-gca** [comment]
`baseurl` should be set to empty, which looks like this:

```yml
baseurl:
```

You can check that by looking at the code of some of the sites generated from this template that have open source code.

**Comment by george-gca** [comment]
About prettier errors, check our [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md#my-code-runs-fine-locally-but-when-i-create-a-commit-and-submit-it-it-fails-with-prettier-code-formatter-workflow-run-failed-for-master-branch-how-do-i-fix-that).
