### ISSUE TITLE
Add support for deploys based on PRs to make it easier to test them

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#2432]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

To have a deployed version of the site ready to be tested based on a PR would make it much simpler for us (maintainers) to validate them.

### Alternatives

I was able to make it work for Netlify only.

### Additional context

Suggested in #1981, made it work for a forked repo and shown in [#2415](https://github.com/alshedivat/al-folio/pull/2415#issuecomment-2118105841).

Steps needed:
1. Create an account in [Netlify](https://www.netlify.com/)
2. Add a [Deploy with Git](https://docs.netlify.com/site-deploys/create-deploys/#deploy-with-git) from this template (note: you should give access to Netlify to your repositories, but this can be limited by repo)
3. In the new deployed site, go to `Site configuration` -> `Build & deploy` -> `Continuous deployment` -> `Build settings`. Set the `Build command` as `sed -i "s/^\(baseurl: \).*$/baseurl:/" _config.yml && bundle exec jekyll build` and the `Publish directory` as `_site`. This can be seen in the screenshot below:
  
  ![image](https://github.com/alshedivat/al-folio/assets/31376482/29ea713c-d2e9-4a87-b666-e5f842e86670)
  
4. Enable [Deploy Previews](https://docs.netlify.com/site-deploys/deploy-previews/)

**Comment by alshedivat** [comment]
@george-gca, that sounds like a great idea. let me set this up. also, appreciate all the features you've been shipping! 🚀

**Comment by george-gca** [comment]
The best way to test this is to create a PR with a really obvious change and see if after a while the Netlify bot adds the link to the built page in the PR.

**Comment by george-gca** [comment]
How is it going? Need any help?

**Comment by george-gca** [comment]
Any updates on this @alshedivat?

**Comment by CheariX** [comment]
Is there anything we can do to help with this?
Or is this something that only @alshedivat can do?

This feature would help so much with PRs!

**Comment by george-gca** [comment]
There are changes that only the owner of the repo can do such as this one and #2086.

**Comment by george-gca** [comment]
Can you take a look at this @alshedivat?

**Comment by alshedivat** [comment]
@george-gca, I setup netlify, but deploys are failing with the following error:
```
10:59:20 PM: Attempting Ruby version 2.7.2, read from environment
10:59:21 PM: Using Ruby version 2.7.2
10:59:22 PM: Using Bundler version 2.5.7 from Gemfile.lock
10:59:48 PM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit code: 1
10:59:48 PM: ERROR:  Error installing bundler:
10:59:48 PM: 	There are no versions of bundler (= 2.5.7) compatible with your Ruby & RubyGems
10:59:48 PM: 	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.2.137.
10:59:48 PM: Error installing Bundler
10:59:48 PM: Failing build: Failed to install dependencies
```
looks like it uses an old ruby version. I haven't used netlify before, how do I make it use ruby 3.x?

**Comment by george-gca** [comment]
You have to set a [RUBY_VERSION](https://docs.netlify.com/configure-builds/manage-dependencies/#ruby) environment variable.

![image](https://github.com/user-attachments/assets/365ef6ea-67b5-4671-8bfa-0219f308307e)

**Comment by alshedivat** [comment]
ok, setting env variable made initialization stage pass, but the build is still failing:
```
11:05:27 PM: Netlify Build                                                 
11:05:27 PM: ────────────────────────────────────────────────────────────────
11:05:27 PM: ​
11:05:27 PM: ❯ Version
11:05:27 PM:   @netlify/build 29.55.2
11:05:27 PM: ​
11:05:27 PM: ❯ Flags
11:05:27 PM:   accountId: 671470a055c5556c0527b6ce
11:05:27 PM:   baseRelDir: true
11:05:27 PM:   buildId: 67147313840ac76aefa76866
11:05:27 PM:   deployId: 67147313840ac76aefa76868
11:05:28 PM: ​
11:05:28 PM: ❯ Current directory
11:05:28 PM:   /opt/build/repo
11:05:28 PM: ​
11:05:28 PM: ❯ Config file
11:05:28 PM:   No config file was defined: using default values.
11:05:28 PM: ​
11:05:28 PM: ❯ Context
11:05:28 PM:   production
11:05:28 PM: ​
11:05:28 PM: Build command from Netlify app                                
11:05:28 PM: ────────────────────────────────────────────────────────────────
11:05:28 PM: ​
11:05:28 PM: $ sed -i "s/^\(baseurl: \).*$/baseurl:/" _config.yml && bundle exec jekyll build
11:05:29 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
11:05:29 PM: /opt/build/cache/bundle/ruby/3.2.0/gems/mini_racer-0.15.0/lib/mini_racer.rb:22:in `load': /opt/build/cache/bundle/ruby/3.2.0/extensions/x86_64-linux/3.2.0/mini_racer-0.15.0/mini_racer_extension.so: undefined symbol: __libc_single_threaded (LoadError)
	from /opt/build/cache/bundle/ruby/3.2.0/gems/mini_racer-0.15.0/lib/mini_racer.rb:22:in `<top (required)>'
	from /opt/buildhome/.rvm/gems/ruby-3.2.2/gems/bundler-2.5.7/lib/bundler/runtime.rb:60:in `require'
	from /opt/buildhome/.rvm/gems/ruby-3.2.2/gems/bundler-2.5.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /opt/buildhome/.rvm/gems/ruby-3.2.2/gems/bundler-2.5.7/lib/bundler/runtime.rb:55:in `each'
	from /opt/buildhome/.rvm/gems/ruby-3.2.2/gems/bundler-2.5.7/lib/bundler/runtime.rb:55:in `block in require'
	from /opt/buildhome/.rvm/gems/ruby-3.2.2/gems/bundler-2.5.7/lib/bundler/runtime.rb:44:in `each'
	from /opt/buildhome/.rvm/gems/ruby-3.2.2/gems/bundler-2.5.7/lib/bundler/runtime.rb:44:in `require'
	from /opt/buildhome/.rvm/gems/ruby-3.2.2/gems/bundler-2.5.7/lib/bundler.rb:187:in `require'
	from /opt/build/cache/bundle/ruby/3.2.0/gems/jekyll-4.3.4/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	from /opt/build/cache/bundle/ruby/3.2.0/gems/jekyll-4.3.4/exe/jekyll:11:in `<top (required)>'
	from /opt/build/cache/bundle/ruby/3.2.0/bin/jekyll:25:in `load'
	from /opt/build/cache/bundle/ruby/3.2.0/bin/jekyll:25:in `<main>'
	from /opt/buildhome/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `eval'
	from /opt/buildhome/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `<main>'
​
11:05:29 PM: "build.command" failed                                        
11:05:29 PM: ────────────────────────────────────────────────────────────────
11:05:29 PM: ​
11:05:29 PM:   Error message
11:05:29 PM:   Command failed with exit code 1: sed -i "s/^\(baseurl: \).*$/baseurl:/" _config.yml && bundle exec jekyll build (https://ntl.fyi/exit-code-1)
11:05:29 PM: ​
11:05:29 PM:   Error location
11:05:29 PM:   In Build command from Netlify app:
11:05:29 PM:   sed -i "s/^\(baseurl: \).*$/baseurl:/" _config.yml && bundle exec jekyll build
11:05:29 PM: ​
11:05:29 PM:   Resolved config
11:05:29 PM:   build:
11:05:29 PM:     command: 'sed -i "s/^\(baseurl: \).*$/baseurl:/" _config.yml && bundle exec jekyll build'
11:05:29 PM:     commandOrigin: ui
11:05:29 PM:     environment:
11:05:29 PM:       - RUBY_VERSION
11:05:29 PM:     publish: /opt/build/repo/_site
11:05:29 PM:     publishOrigin: ui
11:05:29 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:05:29 PM: Failing build: Failed to build site
11:05:30 PM: Finished processing build request in 1m20.696s
```

**Comment by alshedivat** [comment]
looks like there's a problem with mini-racer lib

**Comment by CheariX** [comment]
To me, it looks like the `sed` causes the issue. Maybe the brackets?

Question: what are the advantages of using netlify over standard GitHub features?
I just stumbled on this action:
https://github.com/rossjrw/pr-preview-action

**Comment by george-gca** [comment]
Actually the sed command just removes the `baseurl` value, so the built site has the correct urls.

The error is here:
```
mini_racer-0.15.0/mini_racer_extension.so: undefined symbol: __libc_single_threaded (LoadError)
```

**Comment by george-gca** [comment]
I believe this is working now. Closing the issue.
