### ISSUE TITLE
Display your own blog posts from other sources (like medium.com) on the blog page

### ISSUE THREAD

**Issue by poodarchu** [alshedivat/al-folio#246]
**Describe the demand you'd like**
For example, if I want to show some blogs from my medium.com / other websites directly in a post, how can I modify the page layout?

**Comment by jasongfleischer** [comment]
I use iframe html tag within the markdown of a page and it works fine (at least for the google docs viewer, 90% of the time, and a refresh always takes care of any problems)

See my CV page https://github.com/jasongfleischer/jasongfleischer.github.io/blob/master/_pages/publications.md

**Comment by alshedivat** [comment]
For medium posts specifically, there's apparently a plugin: https://github.com/jameshamann/jekyll-display-medium-posts.

I'll have to test a few things first, but I generally like the idea of displaying blog posts from multiple sources (medium, maybe a university blog, etc.) on the blog page. Keeping this issue to track progress in this direction.
