### ISSUE TITLE
Math in Jupyter Notebook Doesn't Render

### ISSUE THREAD

**Issue by GeorgeRPu** [alshedivat/al-folio#2468]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

When embedding a Jupyter notebook into a post, any math expressions between dollar signs isn't converted to math symbols but stays as plain text.

### How to reproduce the bug

1. Create Jupyter notebook with $f(x) = a^x$ in a markdown cell.
2. Create a post with 

```
{::nomarkdown}
{% assign jupyter_path = '<path_to_juypter_notebook>' | relative_url %}
{% capture notebook_exists %}{% file_exists assets/jupyter/2024-01-06-exp-inflection-point.ipynb %}{% endcapture %}
{% if notebook_exists == 'true' %}
  {% jupyter_notebook jupyter_path %}
{% else %}
  <p>Sorry, the notebook you are looking for does not exist.</p>
{% endif %}
{:/nomarkdown}
```

3. Run 

```
docker compose pull
docker compose up
```

Expected:
<img width="1415" alt="Screenshot 2024-05-31 at 9 46 14 AM" src="https://github.com/alshedivat/al-folio/assets/32757596/a97c59b9-7993-4b0e-a666-bd185ef4f18b">

Actual:
<img width="576" alt="Screenshot 2024-05-31 at 9 44 39 AM" src="https://github.com/alshedivat/al-folio/assets/32757596/80b69fc2-3437-4ce3-ae2e-321213389d7d">

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Running locally with Docker

**Comment by george-gca** [comment]
We use [jekyll-jupyter-notebook](https://github.com/red-data-tools/jekyll-jupyter-notebook) plugin to convert jupyter notebooks to html, which in turn relies on `jupyter nbconvert`, as can be seen [here](https://github.com/red-data-tools/jekyll-jupyter-notebook/blob/4f890d1324890a4d124ec35d1a2907a81a75c984/lib/jekyll-jupyter-notebook/converter.rb#L52). Check if the converted notebook displays correctly the equation first in the html. If it doesn't, then you should open a bug in [jupyter nbconvert](https://github.com/jupyter/nbconvert). If it does, then you should open a bug in [jekyll-jupyter-notebook](https://github.com/red-data-tools/jekyll-jupyter-notebook).
