### ISSUE TITLE
Add external blog post icon indicator in search

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#2471]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

I already added a `TODO` in our code in the correct place with the svg icon in it. I am just having a hard time positioning it correctly on the line with the title.

https://github.com/alshedivat/al-folio/blob/b4f90ff416b5961136cb9ed59e4edbcdf02109c1/_includes/scripts/search.liquid#L83

### Pitch

Inform when the link takes to an external blog post.

**Comment by ajyey** [comment]
Whats the goal here? To have the eternal icon be more vertically aligned with the title?

**Comment by george-gca** [comment]
Exactly. When I used the code that is commented there the icon is weirdly placed inside the line, making its height bigger than the other lines in search.
