### ISSUE TITLE
Cannot run out-of-the-box locally on Windows 10 using the VS Code extensions

### ISSUE THREAD

**Issue by Fontanapink** [alshedivat/al-folio#2486]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Tried to follow the steps in the instructions, but failed to opened it in VS Code and run it locally

### How to reproduce the bug

I've been following the steps in https://github.com/alshedivat/al-folio/blob/master/INSTALL.md to try and develop the website locally using VS Code on my Windows computer. So I've:

1. Had the repository copied to my GitHub repository and changed all the settings/names as in the instructions
2. Installed WSL in PowerShell following https://learn.microsoft.com/en-us/windows/wsl/install
3. Downloaded the repository locally
4. Opened the repository using VS Code
5. Tried opening it using dev container
6. Getting the following error:

```
[34563 ms] Start: Run in container: /bin/sh -c ./bin/entry_point.sh
/bin/sh: 1: ./bin/entry_point.sh: not found
[34647 ms] postAttachCommand failed with exit code 127. Skipping any further user-provided commands.
Done. Press any key to close the terminal.
```

And some pop-up windows saying "Ruby LSP" failed, and "Ruby LSP client: couldn't create connection to server".

If I close and re-open VS Code, I get a pop-up windows saying: "Reopen using Dev Container". If I click on that then I get the following error:

```
[14449 ms] Command failed: ls -a c:/Users/User/Documents/GitHub/TIG/data-centric-biodesign-tig.github.io
[14449 ms] ls: cannot access 'c:/Users/User/Documents/GitHub/TIG/data-centric-biodesign-tig.github.io': No such file or directory
[14449 ms] Exit code 2
```

Which I am guessing is a permission problem??

Anyway, I've been trying to solve this by: 
Downloading docker desktop
Downloading ubuntu from the Microsoft store
Setting up docker desktop to use WSL 2 and Ubuntu

I don't know how to solve this. Please help!

### Error messages and logs

```
[34563 ms] Start: Run in container: /bin/sh -c ./bin/entry_point.sh
/bin/sh: 1: ./bin/entry_point.sh: not found
[34647 ms] postAttachCommand failed with exit code 127. Skipping any further user-provided commands.
Done. Press any key to close the terminal.
```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Running locally with Docker

### More info

![image](https://github.com/alshedivat/al-folio/assets/12236668/70859966-b86c-435b-8c00-bd943b73e945)

**Comment by george-gca** [comment]
The solution I would recommend is to install Ubuntu on Windows (via WSL2) then clone the repo on it and [access the directory through VSCode](https://code.visualstudio.com/docs/remote/wsl).

**Comment by Fontanapink** [comment]
Ok I've been trying to do this. Copied the repository to the ubuntu system, opened a VS Code with wsl navigated there, then tried to re-open with the dev-container and it failed again. Is there anything that I might be doing wrong?

**Comment by george-gca** [comment]
Instead of copying the repo to the ubuntu system, download it inside the ubuntu system. If this is really a permission problem, the best solution is to do everything locally in the ubuntu system. Do you have any other suggestion @CheariX?

**Comment by Fontanapink** [comment]
Oh wow that actually worked! Steps:
1) Deleted all the local repo's
2) Open a bash terminal (fro the ubuntu app in Windows)
3) Git clone the repo to the ubuntu file system
4) Open VS code, change to WSL
5) Open repo local folder
6) Let the dev-container extension do the rest

THANK YOU!
