### ISSUE TITLE
double curly bracket in markdown breaks Jeklly build in github.io deployment

### ISSUE THREAD

**Issue by kevinli-webbertech** [alshedivat/al-folio#2504]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

double curly bracket in markdown breaks Jeklly build in github.io deployment

### How to reproduce the bug

Make a .md file, and the .md file contains shell expression,

```
{{1..3},{7..9}} is an example of shell feature
```

### Error messages and logs

```
To use retry middleware with Faraday v2.0+, install faraday-retry gem
Liquid Exception: Liquid syntax error (line 74): Variable '{{1..3}' was not properly terminated with regexp: /}}/ in blog/md/ref/linux/linux_shell.md
/usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:[13](https://github.com/kevinli-webbertech/kevinli-webbertech.github.io/actions/runs/9493104568/job/26161311609#step:4:14)6:in `raise_missing_variable_terminator': Liquid syntax error (line 74): Variable '{{1..3}' was not properly terminated with regexp: /\}\}/ (Liquid::SyntaxError)
```

### What operating system are you using?

Linux

### Where are you seeing the problem on?

Deployed site

### More info

![image](https://github.com/alshedivat/al-folio/assets/1467278/7d6a7ed6-db58-4004-b805-0a651ae7932a)

Not entirely sure if this report finds its proper place.

Thanks!

**Comment by george-gca** [comment]
When using double curly code (`{{ ... }}`) on a markdown file that is not a Jekyll expression, you should surround it with `{% raw %}` and `{% endraw %}` tags. Take a look at [Jekyll documentation](https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting). We do it quite a while in our code to post the example code that will generate the desired output in blog posts, like in the [jupyter one](https://github.com/alshedivat/al-folio/blob/1a7fddecf85e03ee6a2663d655cc0f6ccfb5bd34/_posts/2023-07-04-jupyter-notebook.md?plain=1#L14).
