### ISSUE TITLE
Add Docker-Compose Watch

### ISSUE THREAD

**Issue by pourmand1376** [alshedivat/al-folio#2530]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

Today I've understood about this feature `Docker compose Watch` which does exactly what I've manually done in the project. It watches for changes and updates the website accordingly. 

I should implement this in our system and remove my old code. 

https://youtu.be/zfNqp85g5JM?t=347

**Comment by CheariX** [comment]
Wow. That is pretty cool. I did not know about this. A real gamer changer!

If you talk about your “old” code, do you mean the `_config.yml` watcher in `entrypoint.sh`?
In this case, keep in mind that the Development Container is currently benefiting from this reload, too.

**Comment by pourmand1376** [comment]
I didn't know about that. So, I suppose we shouldn't implement it and Let it be as is. 

Plus, it doesn't generate any value this way. It would only generate "value" if it would remove some code from our side.
