### ISSUE TITLE
Already deployed site does not update

### ISSUE THREAD

**Issue by cloybar** [alshedivat/al-folio#2539]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

The already deployed site, does not update after modifications. I can locally modify it and see the site locally working, but afther the push to git, the deploy run fails.

### How to reproduce the bug

1. Start with the code of the deployed site
2. Modify it locally. In particular, I updated it with a publication and the link to the PDF, which I just added to the folder /assets/pdf in this step. (When visualizing the site locally, it looks fine)
3. Push
4. Error: the deploy fails and the site does not update

### Error messages and logs

If I try to run the site locally, I receive the following message:
```
Configuration file: C:/Users/crist/Documents/git/cloybar.github.io/_config.yml
            Source: C:/Users/crist/Documents/git/cloybar.github.io
       Destination: C:/Users/crist/Documents/git/cloybar.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
       Imagemagick: Disabled in site.config
       Jekyll Feed: Generating feed for posts
   Jekyll Diagrams: Command Not Found: mmdc
                    ------------------------------------------------
      Jekyll 4.3.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:1395:in `initialize': Permission denied @ rb_sysopen - C:/Users/crist/Documents/git/cloybar.github.io/_site/assets/pdf/LL24_NLW_UC_FT.pdf (Errno::EACCES)
        from C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:1395:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:1395:in `block in copy_file'
        from C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:1394:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:1394:in `copy_file'
        from C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:504:in `copy_file'
        from C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:423:in `block in cp'
        from C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:1577:in `block in fu_each_src_dest'
        from C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:1593:in `fu_each_src_dest0'
        from C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:1575:in `fu_each_src_dest'
        from C:/Ruby31-x64/lib/ruby/3.1.0/fileutils.rb:422:in `cp'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:193:in `copy_file'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:223:in `write'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:231:in `block in write'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:368:in `block (2 levels) in each_site_file'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:365:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:365:in `block in each_site_file'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:364:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:364:in `each_site_file'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:230:in `write'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:82:in `process'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby31-x64/bin/jekyll:32:in `load'
        from C:/Ruby31-x64/bin/jekyll:32:in `<main>'
```
When I look at what happened in Actions, it shows the following:
```
Annotations
1 error 
Invalid workflow file: .github/workflows/deploy.yml#L40 
You have an error in your yaml syntax on line 40
```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Deployed site

### More info

If I only modify some text on the site, I am able to still visualize the site well locally, but after the push, the same error appears.

**Comment by george-gca** [comment]
Why do you have [this](https://github.com/cloybar/cloybar.github.io/blob/043e4ad9ac918cc4297508517f975981c93ffb58/.github/workflows/deploy.yml#L39) in your deploy action?

**Comment by cloybar** [comment]
> Why do you have [this](https://github.com/cloybar/cloybar.github.io/blob/043e4ad9ac918cc4297508517f975981c93ffb58/.github/workflows/deploy.yml#L39) in your deploy action?

I have no idea. I checked an earlier version of the repo and it has been always there since I forked the proyect. Sadly, I am not skilled in these matters to provide an actual answer.

**Comment by george-gca** [comment]
I have no idea why this was there, your repo version seems to be older than from when I started contributing. But validating your yml file [here](https://yamlchecker.com/), it states that your indentation is incorrect (the run line inside [Fix permission](https://github.com/cloybar/cloybar.github.io/blob/043e4ad9ac918cc4297508517f975981c93ffb58/.github/workflows/deploy.yml#L40)). Try to fix that and see if it works.

If not, I would suggest you update your repository to the latest version. It would not only be easier to help, you would also benefit from the latest features and code organization. In this matter it would probably be easier to re-install the new version of the theme from scratch and port over your content and changes from the previous version manually. You can use tools like [meld](https://meldmerge.org/) or [winmerge](https://winmerge.org/) to help in this process.

**Comment by cloybar** [comment]
> I have no idea why this was there, your repo version seems to be older than from when I started contributing. But validating your yml file [here](https://yamlchecker.com/), it states that your indentation is incorrect (the run line inside [Fix permission](https://github.com/cloybar/cloybar.github.io/blob/043e4ad9ac918cc4297508517f975981c93ffb58/.github/workflows/deploy.yml#L40)). Try to fix that and see if it works.
> 
> If not, I would suggest you update your repository to the latest version. It would not only be easier to help, you would also benefit from the latest features and code organization. In this matter it would probably be easier to re-install the new version of the theme from scratch and port over your content and changes from the previous version manually. You can use tools like [meld](https://meldmerge.org/) or [winmerge](https://winmerge.org/) to help in this process.

Well, I messed up and there is no website anymore. I am starting from 0 again and still have issues with the deployment. Gonna call the issue closed and open a new one with the new problems.

Thank you very much for your help!
