### ISSUE TITLE
Deployment failed with Gemfile.lock (created by local setup)

### ISSUE THREAD

**Issue by justinhou95** [alshedivat/al-folio#2544]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Deployment failed with Gemfile.lock

### How to reproduce the bug

1. Local setup using Docker creates Gemfile.lock
2. Uploading Gemfile.lock causes error in deployment action

### How to solve it
4. Solved by adding Gemfile.lock into .gitignore

### Error messages and logs

```
bundle install
/opt/hostedtoolcache/Ruby/3.2.2/x64/bin/bundle config --local path /home/runner/work/justinhou95.github.io/justinhou95.github.io/vendor/bundle
/opt/hostedtoolcache/Ruby/3.2.2/x64/bin/bundle config --local deployment true
Cache key: setup-ruby-bundler-cache-v6-ubuntu-22.04-x64-ruby-3.2.2-wd-/home/runner/work/justinhou95.github.io/justinhou95.github.io-with--without--only--Gemfile.lock-03358d48efe98caee97dcb4e12a28f649[26](https://github.com/justinhou95/justinhou95.github.io/actions/runs/9794626471/job/27045011792#step:3:32)5ecc3d62e7fddd6bef7fe0b35c8ce
Cache Size: ~155 MB (162713749 B)
/usr/bin/tar -xf /home/runner/work/_temp/cd43a20f-23d2-49fb-ba6d-763e124ad1f6/cache.tzst -P -C /home/runner/work/justinhou95.github.io/justinhou95.github.io --use-compress-program unzstd
Received 16[27](https://github.com/justinhou95/justinhou95.github.io/actions/runs/9794626471/job/27045011792#step:3:33)13749 of 162713749 (100.0%), 155.0 MBs/sec
Cache restored successfully
Found cache for key: setup-ruby-bundler-cache-v6-ubuntu-22.04-x64-ruby-3.2.2-wd-/home/runner/work/justinhou95.github.io/justinhou95.github.io-with--without--only--Gemfile.lock-02f2f3fb583f91aee8d3bdf99af70[28](https://github.com/justinhou95/justinhou95.github.io/actions/runs/9794626471/job/27045011792#step:3:34)535c7e6e8cbcbd49011b5b1d319db5486
/opt/hostedtoolcache/Ruby/3.2.2/x64/bin/bundle install --jobs 4
Your bundle only supports platforms ["aarch64-linux-gnu"] but your local
platform is x86_64-linux. Add the current platform to the lockfile with
`bundle lock --add-platform x86_64-linux` and try again.
Error: The process '/opt/hostedtoolcache/Ruby/3.2.2/x64/bin/bundle' failed with exit code 16
```

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

**Comment by pourmand1376** [comment]
Hi. @justinhou95 

I see your problem. Also, I see [here](https://github.com/justinhou95/justinhou95.github.io/commit/e29019361f3dca103f229850088e0119556f42ce) that `Gemfile.lock` is updated. Is it done automatically? 

What is your linux distribution? I see that it is not categorized as linux but linux-gnu.

**Comment by pourmand1376** [comment]
It seems that we should add `x86_64-linux` to existing platforms on `Gemfile.lock`.

**Comment by george-gca** [comment]
If this fixes the problem we could add it to our repo. @justinhou95 any feedback?

**Comment by CheariX** [comment]
I have the same problem when running locally on an ARM based macbook. The updated `Gemfile.lock`does not have `x86_64-linux`, which leads to a failure when deploying on github.

My current solution is to _not_ commit `Gemfile.lock`, which is suboptimal.

**Comment by george-gca** [comment]
I believe the discussion was in #2384.

> I think it is very uncommon to have `Gemfile.lock` managed in git, is it?

Not really. It is even recommended in the [bundler docs](https://bundler.io/guides/faq.html#:~:text=A%3A%20Yes%2C%20you%20should%20commit,towards%20new%20and%20existing%20contributors) and [rails](https://github.com/rails/rails), for example, include it in their repo. Also I agree with [this guy](https://github.com/heartcombo/devise/pull/3147#issuecomment-52193788):

> The Gemfile.lock should stay in the repository because contributors and developers should be able to fork the project and run it using versions that are guaranteed to work.

**Comment by tim-puhlfuerss** [comment]
Hi folks,
I ran into the same problem on my MacBook with the M2 chip. The command mentioned by @pourmand1376 solved it.
I found the solution on [StackOverflow](https://stackoverflow.com/questions/76756736/error-the-process-opt-hostedtoolcache-ruby-3-1-4-x64-bin-bundle-failed-with).
