### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by eborbath** [alshedivat/al-folio#258]
Thanks for the beautiful theme!

I am wondering, is there a way to incorporate multi-language support in a future iteration? It would be great if the user could pick between two or three languages and the website would switch to url/en/page for english or url/de/page for german etc.

**Comment by alshedivat** [comment]
Thank you for the suggestion! Yes, I believe Jekyll supports internationalization (i18n) through plugins (e.g., see [this one](https://github.com/kurtsson/jekyll-multiple-languages-plugin) and [a blog post](https://github.com/kurtsson/jekyll-multiple-languages-plugin) on how to set it up). The translation is not automatic though, i.e., you would have to add multiple versions of each page/post in each language you would like to have it; the plugin takes care of correctly switching between the translations.

**Comment by curtiscali** [comment]
@george-gca Thanks for the hard work man! Been looking to add Chinese support to my site and after fumbling with plugins, decided to see if anyone else did something similar. Your post is helpful thank you so much

**Comment by george-gca** [comment]
Since I know this is of interest to a lot of people (me included), I decided to create a [multilingual version of al-folio](https://github.com/george-gca/multi-language-al-folio). Maybe in the future this could be merged into the main repo?

**Comment by george-gca** [comment]
What do you think @alshedivat? Maybe we can incorporate the changes I made [in this repo](https://github.com/george-gca/multi-language-al-folio) here, but currently I think it is better to keep it as a different repo, since it might not be of everyone's interest.
