### ISSUE TITLE
Docker startup freezing at 'convert' command

### ISSUE THREAD

**Issue by mkenworthy** [alshedivat/al-folio#2587]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

running docker-compose up freezes at ImageMagick convert

### How to reproduce the bug

I pull my al-folio from github, start up Docker desktop, then cd into the repo and run:

`docker-compose up`

and it builds the site, but then freezes when it tries to run the convert command. ImageMagick is already installed and working on my machine.

### Error messages and logs

```
jekyll_1  |         Generating: JekyllJupyterNotebook::Generator finished in 0.028812606 seconds.
jekyll_1  |        Jekyll Feed: Generating feed for posts
jekyll_1  |         Generating: JekyllFeed::Generator finished in 0.001988283 seconds.
jekyll_1  |        Imagemagick: Searching files in /srv/jekyll/assets/img/
jekyll_1  |        Imagemagick: Generating image "/srv/jekyll/_site/assets/img/10-480.webp"
jekyll_1  |        Imagemagick: Running command "convert "/srv/jekyll/assets/img/10.jpg" -quality 85 -resize "480>" "/srv/jekyll/_site/assets/img/10-480.webp""
```

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Running locally with Docker

**Comment by pourmand1376** [comment]
Hi, @mkenworthy 

I can't replicate this issue. Is there anyway in which I can replicate this issue?

**Comment by mkenworthy** [comment]
O am sorry, it was my fault. I upgraded Docker and it started working. Thank you! Sent from my iPhoneOn 28 Jul 2024, at 11:34, Amir Pourmand ***@***.***> wrote:﻿
Hi, @mkenworthy
I can't replicate this issue. Is there anyway in which I can replicate this issue?
