### ISSUE TITLE
Unable to fetch stylesheet on initial deploy

### ISSUE THREAD

**Issue by Manav1712** [alshedivat/al-folio#2588]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Not able to fetch stylesheet

### How to reproduce the bug

I followed all setup steps, fixed the lighthouse badger by adding the secret and made the deployment off of gh-pages. However, my site is unable to fetch the stylesheet. 

### Error messages and logs

None

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Deployed site

**Comment by Manav1712** [comment]
<img width="1440" alt="Screenshot 2024-07-21 at 2 45 01 PM" src="https://github.com/user-attachments/assets/d0b3b09a-59ef-42c2-bb41-c4aeb588562b">

**Comment by george-gca** [comment]
Check our [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md#my-webpage-works-locally-but-after-deploying-it-is-not-displayed-correctly-css-and-js-are-not-loaded-properly-how-do-i-fix-that).

**Comment by Manav1712** [comment]
I'm sorry you thought that. However, I actually have gone through the entire FAQ. I have followed everything you posted as well. Another user @Sustainability4  posted the same issue as well. I followed all the steps of your recommended approach, I tried loading it after cleaning my history or on incognito, updated all URLS and checked the entire error thread https://github.com/alshedivat/al-folio/issues/1398#issuecomment-1609518404 . I just asked a simple question, I don't see the reason for being impolite.

**Comment by stsfaroz** [comment]
@george-gca same situation here , i added the secrets in lighthouse badger , still same problem

Error: Input required and not supplied: token

**Comment by george-gca** [comment]
I will copy/paste the contents of the [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md#my-webpage-works-locally-but-after-deploying-it-is-not-displayed-correctly-css-and-js-are-not-loaded-properly-how-do-i-fix-that) entry here, expliciting the answer:

---

#### Question

My webpage works locally. But after deploying, it is not displayed correctly (CSS and JS are not loaded properly). How do I fix that?

#### Answer (part that you missed)

If you are deploying a personal or organization website, leave baseurl blank.

What this means is: change this line:

```yml
baseurl: /al-folio
```

to this:

```yml
baseurl:
```

**Comment by vitorpmh** [comment]
Thanks! The thing here for me was that yml's shows a red squigly line on vscode if you leave it blank like this.
