### ISSUE TITLE
Content jumps horizontally whenever browser adds a scrollbar

### ISSUE THREAD

**Issue by ayuroman** [alshedivat/al-folio#26]
Page content  'jumps' a little on Safari/Chrome/IE when navigating between short and long pages:
https://alshedivat.github.io/al-folio/blog/ vs https://alshedivat.github.io/al-folio/projects/

**Comment by alshedivat** [comment]
What do you mean by "jumps when navigating?" When I switch between the two pages (in Chrome), the behavior seems normal, nothing jumps anywhere.

**Comment by ayuroman** [comment]
![jump](https://user-images.githubusercontent.com/42931270/46260307-15a84a80-c4dc-11e8-8878-6373a9902fe4.jpg)

**Comment by alshedivat** [comment]
No idea how to fix this.

**Comment by samfearn** [comment]
Pull request #48 created to resolve this.
