### ISSUE TITLE
Inline mathjax in image caption renders as display

### ISSUE THREAD

**Issue by TomClabault** [alshedivat/al-folio#2601]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Inline mathjax in image caption renders as display

### How to reproduce the bug

```
<div class="caption">
    Inline $$Mathjax$$ isn't inline.
</div>
```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Running locally with Docker

### More info

**Expected result:**
Should render all 4 words on the same line

**Result observed:**
![image](https://github.com/user-attachments/assets/11b718d7-808a-43b2-892d-d7e9517a2470)

Note that this isn't really only related to image captions. Having the Mathjax code in a simple `<div>` with no class renders the same (although not centered within the page).

**Comment by m-julian** [comment]
@TomClabault From the [mathjax documentation](https://docs.mathjax.org/en/latest/basic/mathematics.html) : 

```
The default math delimiters are $$...$$ and \[...\] for displayed mathematics, and \(...\) for in-line mathematics. Note in particular that the $...$ in-line delimiters are not used by default. That is because dollar signs appear too often in non-mathematical settings, which could cause some text to be treated as mathematics unexpectedly.
```

The `$$...$$` should be used for displayed mathematics, which are on separate lines. You should be able to use `$...$` or `\(...\)` for the in-line mathematics. Can you try these instead?

**Comment by CodeLikeAGirl29** [comment]
The issue you're encountering happens because ``$$`` in MathJax is used for display math, not inline math. To render inline math in MathJax, you should use single dollar signs ``$...$`` instead of double dollar signs ``$$...$$``.

Here’s how to fix it:

```html
<div class="caption">
    Inline $Mathjax$ isn't inline.
</div>
```

If you want to configure MathJax to recognize $$ for inline math as well, you'll need to adjust the MathJax configuration. Add the following configuration in your MathJax setup:

```js
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']],
    displayMath: [['$$', '$$'], ['\\[', '\\]']]
  }
};
```
This config ensures that ``$...$`` is used for inline math and ``$$...$$`` for display math.

#hacktoberfest

**Comment by TomClabault** [comment]
> MathJax, you should use single dollar signs $...$ instead of double dollar signs $$...$$.

That did the trick, thanks!
