### ISSUE TITLE
Vector images not generating webp files

### ISSUE THREAD

**Issue by KingHowler** [alshedivat/al-folio#2660]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

al-folio doesn't convert ".svg" files to ".webp" files. ".svg" files are small and their quality isn't lost when being displayed so not converting it is the best option. I should also mention that the images are displayed on the website without any faults. The issue which I want to bring forth is the error logs. The workflow "Check for broken links on site" produces an error log which should not be generated.

### How to reproduce the bug

- Add a ```.svg``` file in ```assets/img/```
- Include this image in a post
- Push changes and check the ```Check for broken links on site```

### Error messages and logs

```
✗ [ERR] file:///home/runner/work/kinghowler.github.io/kinghowler.github.io/_site/assets/img/dec/logic-gates/NOR.svg-800.webp | Failed: Cannot find file
```

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

### More info

I suggest to create an exception case to not search for converted .svg files

**Comment by george-gca** [comment]
If it looks for converted svg files it means that the `jekyll-imagemagick` plugin is "converting" svg files. By converting I mean it is at least creating the tags with the `.webp` extension, since the `Check for broken links on site` workflow gets the links straight from the built site.

How are you adding the svg image to the post? Using `figure.liquid`?

**Comment by KingHowler** [comment]
Yes I am using ```figure.liquid```

In the ```deploy``` workflow's log, there is a section which tells each image converted.

I have multiple images and Imagegick is converting all of them, but there is no log for any of my svg files which leads me to believe they are ignored when generating images.

**Comment by george-gca** [comment]
If you check

https://github.com/alshedivat/al-folio/blob/de4e89d11b44ca2b1660aeeafde5e88b6415542f/_includes/figure.liquid#L17 

it creates a `source` to a `.webp` image even though none was generated. I believe we should add a check if the extension is not one of the ones in

https://github.com/alshedivat/al-folio/blob/de4e89d11b44ca2b1660aeeafde5e88b6415542f/_includes/figure.liquid#L1

and if it is not, don't add `.webp` source. If you manage to fix this, can you send a PR?

**Comment by KingHowler** [comment]
> If you check
> 
> https://github.com/alshedivat/al-folio/blob/de4e89d11b44ca2b1660aeeafde5e88b6415542f/_includes/figure.liquid#L17 
> 
> it creates a `source` to a `.webp` image even though none was generated. I believe we should add a check if the extension is not one of the ones in
> 
> https://github.com/alshedivat/al-folio/blob/de4e89d11b44ca2b1660aeeafde5e88b6415542f/_includes/figure.liquid#L1
> 
> and if it is not, don't add `.webp` source. If you manage to fix this, can you send a PR?

Ok will look into it

**Comment by KingHowler** [comment]
> > If you check
> > 
> > https://github.com/alshedivat/al-folio/blob/de4e89d11b44ca2b1660aeeafde5e88b6415542f/_includes/figure.liquid#L17 
> > 
> > it creates a `source` to a `.webp` image even though none was generated. I believe we should add a check if the extension is not one of the ones in
> > 
> > https://github.com/alshedivat/al-folio/blob/de4e89d11b44ca2b1660aeeafde5e88b6415542f/_includes/figure.liquid#L1
> > 
> > and if it is not, don't add `.webp` source. If you manage to fix this, can you send a PR?
> 
> Ok will look into it

The faulty ```</source>``` tags might also be originating from here

**Comment by KingHowler** [comment]
I just took a look, the </source> is not a fault in the code.
How do you process the .liquid files?

**Comment by george-gca** [comment]
What do you mean? Liquid files are processed during jekyll build.

**Comment by KingHowler** [comment]
Basically what I mean is that liquid has a feature where it automatically adds closing tags which it thinks are missing. The creators of Liquid must have accidentally set ```<source>``` to have a separate closing tag. In order to fix it we'll have to contact the ones maintaining Liquid.

**Comment by KingHowler** [comment]
> Every file that starts with a [frontmatter](https://jekyllrb.com/docs/front-matter/)
> 
> ```
> ---
> 
> ---
> ```
> 
> is processed by jekyll during build.

@george-gca, that's exactly what I meant. Jekyll processes liquid files right?
You haven't done anything to modify how the processing takes place. This means that the error is in liquid itself.

**Comment by KingHowler** [comment]
Right now I am working on adding repos to projects. When I am done I will fix the issue with vector images and then send a pull request.

**Comment by george-gca** [comment]
> You haven't done anything to modify how the processing takes place

No, I haven't.

Actually [liquid](https://jekyllrb.com/docs/liquid/) is a template language that jekyll uses. `.liquid` files only have this extension for better usage by code editors and prettier. But every file that starts with the front matter is processed by jekyll, no matter what the contents are. I've seem even some templates add the front matter to a javascript file to further change its contents.

**Comment by KingHowler** [comment]
> > You haven't done anything to modify how the processing takes place
> 
> No, I haven't.
> 
> Actually [liquid](https://jekyllrb.com/docs/liquid/) is a template language that jekyll uses. `.liquid` files only have this extension for better usage by code editors and prettier. But every file that starts with the front matter is processed by jekyll, no matter what the contents are. I've seem even some templates add the front matter to a javascript file to further change its contents.

Yeah I read about all that. I also found at that liquid has this neat feature where it auto-closes missing tags.
That's where the issue of the non-existent ```</source>``` tag occurs. Liquid must think that ```<source>``` has a closing tag even though it doesn't. That's why even if you didn't write ```</source>``` you can still find it in the HTML files produced.
