### ISSUE TITLE
Prettier bug in config.yml

### ISSUE THREAD

**Issue by avarndell** [alshedivat/al-folio#2673]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Pettier issues in config.yml

### How to reproduce the bug

change baseurl: to blank

### Error messages and logs

```
baseurl: to blank gives incorrect type. Expected "string".
line 194 gives error that property Defaults are not allowed.
```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Running locally without Docker, Deployed site

**Comment by george-gca** [comment]
If you are starting fresh, check our [video tutorial](https://github.com/alshedivat/al-folio/blob/master/assets/video/tutorial_al_folio.mp4)

**Comment by KingHowler** [comment]
![image](https://github.com/user-attachments/assets/62a8e1b9-d7f3-4ac0-9631-0d1ff744775a)

Works fine for me, but I am not using it locally
