### ISSUE TITLE
Video tutorial deployment failed

### ISSUE THREAD

**Issue by jacky-mo-1111** [alshedivat/al-folio#2690]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

I followed the tutorial video to deploy the website. And I have two bugs. 1. the deployed site url: instead of seeing https://<your-github-username>.github.io, it shows https://<your-github-username>.github.io/<your-github-username>.github.io. 2. css and js can't load no matter I switch browser or use incognito window

### How to reproduce the bug

Just follow video tutorial

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Deployed site

**Comment by AzharSindhi** [comment]
I had issues with following the provided video tutorial, this issue worked for me: https://github.com/alshedivat/al-folio/issues/1398
