### ISSUE TITLE
Failed to deploy when new commits are pushed

### ISSUE THREAD

**Issue by QinengWang-Aiden** [alshedivat/al-folio#2723]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Initially, my website was successfully deployed three months ago. However, when I tried to update my personal website today, the deployment fails at 'install and build' part.

### How to reproduce the bug

1. commit new changes and push it to repo
2. wait for deployment

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```
For the job 'deploy', it fails at `Install and Build` stage. Below is complete error message:

```
Run pip3 install --upgrade jupyter
  pip3 install --upgrade jupyter
  export JEKYLL_ENV=production
  bundle exec jekyll build
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 68 for the detailed specification.
Error: Process completed with exit code 1.
```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Deployed site

### More info

This error never appeared before, so I am very confused. Any assistance would be highly appreciated!

Thanks!

**Comment by george-gca** [comment]
Can you post your [deploy](https://github.com/alshedivat/al-folio/blob/master/.github/workflows/deploy.yml) workflow file? Maybe there is something missing.

**Comment by QinengWang-Aiden** [comment]
Thank you such much for your reply! I just adopted the latest al-folio template, and modified `Install and Build 🔧` part in `deploy.yml` file into following
```yml
- name: Install and Build 🔧
  run: |
    sudo apt-get update
    sudo apt-get install -y imagemagick
    pip3 install --upgrade jupyter --break-system-packages
    export JEKYLL_ENV=production
    bundle exec jekyll build
``` 

Then everything was okay. Though I had no clue why running environment seemed different, adding commands `sudo apt-get update` and `sudo apt-get install -y imagemagick` and param `--break-system-packages` did work.

**Comment by QinengWang-Aiden** [comment]
I think I can close the issue for now.

Thanks for your reply once again!
