### ISSUE TITLE
Version Issue from Docker Compose

### ISSUE THREAD

**Issue by jagar2** [alshedivat/al-folio#2733]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Main Branch Does not build

### How to reproduce the bug

When I git clone the repo on a clean branch and run docker compose up the website does not build

### Error messages and logs

```
jekyll-1  | Gemfile.lock is tracked by git, keeping it intact
jekyll-1  | /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/definition.rb:596:in `materialize': Could not find sass-embedded-1.79.3-x86_64-linux-gnu in locally installed gems (Bundler::GemNotFound)
jekyll-1  |     from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/definition.rb:203:in `specs'
jekyll-1  |     from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/definition.rb:270:in `specs_for'
jekyll-1  |     from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/runtime.rb:18:in `setup'
jekyll-1  |     from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler.rb:162:in `setup'
jekyll-1  |     from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
jekyll-1  |     from /usr/local/bundle/gems/jekyll-4.3.4/exe/jekyll:11:in `<top (required)>'
jekyll-1  |     from /usr/local/bundle/bin/jekyll:25:in `load'
jekyll-1  |     from /usr/local/bundle/bin/jekyll:25:in `<main>'
```

### What operating system are you using?

Linux

### Where are you seeing the problem on?

Running locally with Docker

**Comment by dylanhogan** [comment]
I'm getting a similar error, also running locally with Docker on Linux:

```
jekyll-1  | Gemfile.lock is tracked by git, keeping it intact
jekyll-1  | /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated sass-embedded 1.79.4, but your Gemfile requires sass-embedded 1.79.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/runtime.rb:25:in `block in setup'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/spec_set.rb:191:in `each'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/spec_set.rb:191:in `each'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/runtime.rb:24:in `map'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler/runtime.rb:24:in `setup'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.7/lib/bundler.rb:162:in `setup'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.3.4/exe/jekyll:11:in `<top (required)>'
jekyll-1  | 	from /usr/local/bundle/bin/jekyll:25:in `load'
jekyll-1  | 	from /usr/local/bundle/bin/jekyll:25:in `<main>'
```

Appreciate any help.

**Comment by george-gca** [comment]
Did you make any modifications to your `Gemfile.lock`?

**Comment by jagar2** [comment]
> Did you make any modifications to your `Gemfile.lock`?

No I did not. Fresh pull.

**Comment by Laura05010** [comment]
I'm having the same issue :/ 
Not sure how to fix it

**Comment by Nemo0312** [comment]
having similar issue, however, interesting find docker will actually compile and server the page if you delete gemfile.lock and let docker recreate it. But it will give the same error if you make a change and re-serve the page or if you redeploy docker.

**Comment by nuria95** [comment]
Having same issue as @dylanhogan in macOS.

**Comment by tomas-hansen** [comment]
Same problem here, using windows with wsl

**Comment by george-gca** [comment]
Maybe this has something to do with this @pourmand1376?

https://github.com/alshedivat/al-folio/blob/c20074c8cab8df2050350e2367482fdd5328a08e/.devcontainer/devcontainer.json#L16

**Comment by Nemo0312** [comment]
> Maybe this has something to do with this @pourmand1376?
> 
> https://github.com/alshedivat/al-folio/blob/c20074c8cab8df2050350e2367482fdd5328a08e/.devcontainer/devcontainer.json#L16

I tried reverting the "entry_point.sh" to the 0.11.0 version. still same error

**Comment by anvuongb** [comment]
I have the same issue, fresh pull from master, Ubuntu 22.04, Docker version 27.3.1-build ce12230.

**Comment by cmanage1** [comment]
Seeing a similar issue on WSL2, Ubuntu 22.04.4 LTS, Docker version 27.3.1, build ce12230.

```
al-folio-website  | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
al-folio-website  | /usr/local/bundle/gems/bundler-2.5.20/lib/bundler/resolver.rb:354:in `raise_not_found!': Could not find gem 'jekyll-diagrams' in locally installed gems. (Bundler::GemNotFound)
al-folio-website  |     from /usr/local/bundle/gems/bundler-2.5.20/lib/bundler/resolver.rb:445:in `block in prepare_dependencies'
al-folio-website  |     from /usr/local/bundle/gems/bundler-2.5.20/lib/bundler/resolver.rb:420:in `each'
al-folio-website  |     from /usr/local/bundle/gems/bundler-2.5.20/lib/bundler/resolver.rb:420:in `map'
al-folio-website  |     from /usr/local/bundle/gems/bundler-2.5.20/lib/bundler/resolver.rb:420:in `prepare_dependencie
```

**Comment by Laura05010** [comment]
I just downloaded the latest version on MacOS. Still getting the same issue. 
Only thing that seems to be working so far is to _delete the Gemfile.lock_ , make updates and then run _docker compose up_ to test the site

**Comment by pourmand1376** [comment]
Hey Guys. 

Thanks for bringing up this issue. 

The problem is that your docker image is not matching the latest docker image that we have:

```
docker compose pull
docker compose up -d
```

This should solve the problem completely.

**Comment by george-gca** [comment]
Question for everyone running into this issue. How exactly have you been running with docker? Using [docker compose](https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#local-setup-using-docker-recommended) manually, or using [dev container](https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#local-setup-with-development-containers)?

**Comment by pourmand1376** [comment]
So, only using 
```
Docker compose pull
Docker compose up
```

Didn't work? If that's the case, what is the error?

**Comment by nuria95** [comment]
The problem seems to be finally solved for me now.
Retried:
docker compose pull
docker compose up
and works!
Thanks for fixing it (at least for me) :)
