### ISSUE TITLE
Cannot link co-author with non-ASCII character in surname

### ISSUE THREAD

**Issue by raffaem** [alshedivat/al-folio#2745]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

If the co-author contains a non-ASCII character in his surname, it is not linked from _data/coauthors.yml

### How to reproduce the bug

1. In `_bibliography/papers.bib`, add a paper with a co-author who has a non-ASCII character in his name, for example [here](https://github.com/raffaem/raffaem.github.io/blob/27a35c1c9748a6d00f030de3594e1b3101c2f022/_bibliography/papers.bib#L31)
2. Add the corresponding entry in `_data/coauthors.yml`, for example [here](https://github.com/raffaem/raffaem.github.io/blob/27a35c1c9748a6d00f030de3594e1b3101c2f022/_data/coauthors.yml#L21)
3. The co-author website is not linked in the publications page, for example [here](https://raffaem.github.io/publications/)

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

**Comment by george-gca** [comment]
This is needed so we can actually find the coauthor information. If you look closer at the algorithm, you'll see that we use the `clean_last_name` only to find the coauthor by key in the data, for example

https://github.com/alshedivat/al-folio/blob/b74b292cac3ced3f3df51f164719970df8edffc7/_data/coauthors.yml#L5

So as long as you create a key for your coauthor without special characters it will work fine. We don't use the clean version to display its name.

**Comment by raffaem** [comment]
1. Looks like "Podolsky" doesn't contain accents?
![image](https://github.com/user-attachments/assets/89ca4d09-2585-4033-b03e-090800d46e49)

2. I don't understand why we are doing that ... what's wrong with
```
"schrödinger":
  - firstname: ["Erwin"]
    url: https://en.wikipedia.org/wiki/Erwin_Schr%C3%B6dinger
```
?

3. Can we at least document this in the FAQ? It is not obvious that it would look for surnames after lowering and removing accents

**Comment by george-gca** [comment]
Change `schrödinger` for `schrodinger`. It will work.

I agree, we need to add this to our `CUSTOMIZE.md`.

**Comment by raffaem** [comment]
> Change `schrödinger` for `schrodinger`. It will work.
> 
> I agree, we need to add this to our `CUSTOMIZE.md`.

My question is, if we do remove `remove_accents` from the pipeline, and in `coauthors.yml` we use:

```
"schrödinger":
  - firstname: ["Erwin"]
    url: https://en.wikipedia.org/wiki/Erwin_Schr%C3%B6dinger
```

What is the problem with that?

**Comment by george-gca** [comment]
The problem is that not all publications write your name correctly, and this can make it hard to find the specified coauthor. If we standardize the name before searching for it, it is easier to make sure we find the correct person.

For instance, [I had this problem](https://george-gca.github.io/publications/) with one of my coauthors. In one publication they wrote his name `Artur Jordao` without the accent, while in the other they put it with the accent `Artur Jordão`.

**Comment by raffaem** [comment]
Can't you just repeat it?

```
"Jordao":
  - firstname: ["Artur"]
    url: my-coauthor-arthur.com
"Jordão":
  - firstname: ["Artur"]
    url: my-coauthor-arthur.com
```

The possibile way it could end up mispelled are many

**Comment by george-gca** [comment]
If it works best for you repeating it, you can. I prefer to avoid having repeated entries in my bib file, and since most of the misspelling are regarding missing accents (not letters) it is easier to just strip the accents and change to lower case to compare.
