### ISSUE TITLE
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll) for local docker deployment. Works only with old docker image tag

### ISSUE THREAD

**Issue by shashikantilager** [alshedivat/al-folio#2747]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Throws blunder: failed to load command:jekyll error 

### How to reproduce the bug

Hello,

I always deployed locally with docker and enabled GitHub action for automatic deployment. However, recently, when I do the  "docker compose pull" and "docker compose up", I get the deployment error.

Local deployment works only if I mention docker image tag "v0.10.1", however, the GitHub action fails to deploy with this version. Using any other version or "latest" tag throws the error for local deployment. Can you please help me to solve this?

Thanks

### Error messages and logs

```
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
 | /usr/local/bundle/gems/bundler-2.5.20/lib/bundler/resolver.rb:354:in `raise_not_found!': Could not find gem 'jekyll-diagrams' in locally installed gems. (Bundler::GemNotFound)
```

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Running locally with Docker (docker compose)

**Comment by george-gca** [comment]
Duplicate of #2042.

**Comment by shashikantilager** [comment]
> Duplicate of #2042.

Hi, thanks. The post says that it was solved with a permission issue with bundle install. Can you please let me know how to resolve this permission issue?
Thanks

**Comment by shashikantilager** [comment]
Hi, I updated to recent version of code (v0.12.0), and the above issue got solved. However, I got github action workflow issue. I opened new issue for it. Thanks for the help, I am closing this issue.

**Comment by ChristopherSiems** [comment]
> Hi, I updated to recent version of code (v0.12.0), and the above issue got solved. However, I got github action workflow issue. I opened new issue for it. Thanks for the help, I am closing this issue.

Did you only change the version? I tried setting my version to v0.12.0 and I am getting the same issue as before. I get the issue on both latest and v0.12.0.

Thanks in advance!
