### ISSUE TITLE
Cannot load from scholar

### ISSUE THREAD

**Issue by DoHaiSon** [alshedivat/al-folio#2748]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

I moved to the latest version of al-folio. Yesterday, everything was oke. But today, the numbers of schoolar citations for all my .bib are N/A.

### How to reproduce the bug

1. `bundle exec jekyll serve`
2. Look at my website: [https://dohaison.github.io/publications/](https://dohaison.github.io/publications)

### Error messages and logs

```
Error fetching citation count for ufrVoPGSRksC: OpenURI::HTTPError - 429 Too Many Requests
Error fetching citation count for 9yKSN-GCB0IC: OpenURI::HTTPError - 429 Too Many Requests
Error fetching citation count for qjMakFHDy7sC: OpenURI::HTTPError - 429 Too Many Requests
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
Error fetching citation count for u-x6o8ySG0sC: OpenURI::HTTPError - 429 Too Many Requests
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
Error fetching citation count for : OpenURI::HTTPError - 429 Too Many Requests
Error fetching citation count for Tyk-4Ss8FVUC: OpenURI::HTTPError - 429 Too Many Requests
Error fetching citation count for WF5omc3nYNoC: OpenURI::HTTPError - 429 Too Many Requests
Error fetching citation count for YsMSGLbcyi4C: OpenURI::HTTPError - 429 Too Many Requests
Error fetching citation count for W7OEmFMy1HYC: OpenURI::HTTPError - 429 Too Many Requests
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
Error fetching citation count for UeHWp8X0CEIC: OpenURI::HTTPError - 429 Too Many Requests
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
Error fetching citation count for 2osOgNQ5qMEC: OpenURI::HTTPError - 429 Too Many Requests
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
Error fetching citation count for IjCSPb-OGe4C: OpenURI::HTTPError - 429 Too Many Requests
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
Error fetching citation count for d1gkVwhDpl0C: OpenURI::HTTPError - 429 Too Many Requests
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
Error fetching citation count for u5HHmVD_uO8C: OpenURI::HTTPError - 429 Too Many Requests
[NbConvertApp] Converting notebook /tmp/jekyll-jupyter-notebook20241005-1679-idtfgf.ipynb to html
/home/haison98/.local/lib/python3.10/site-packages/nbconvert/filters/highlight.py:71: UserWarning: IPython3 lexer unavailable, falling back on Python 3
  return _pygments_highlight(
                    done in 57.976 seconds.
 Auto-regeneration: enabled for '/mnt/c/Users/SON/Desktop/al-folio'
LiveReload address: http://127.0.0.1:35729
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
        LiveReload: Browser connected
```

### What operating system are you using?

Linux

### Where are you seeing the problem on?

Running locally without Docker, Deployed site

**Comment by DoHaiSon** [comment]
And I wonder that those numbers of scholar citation is live update like almetrics website or static generated when I deploying?

**Comment by george-gca** [comment]
For Google Scholar and INSPIRE they are statically generated during build.

The problem in your case is that every time you build your site it scraps the information from Google Scholar for every paper you added this information. Since you added for a lot of them, it tried to fetch this for all of them, but Google found weird a lot of connection requests from the same IP and blocked it for some time.

One thing that might work is to increase the delay between requests, so it doesn't do a lot of requests in a small time frame and avoid being blocked by Google. Increase it here:

https://github.com/alshedivat/al-folio/blob/421bdf860bb24a052480b99109384361ea7dc73b/_plugins/google-scholar-citations.rb#L32

**Comment by DoHaiSon** [comment]
> For Google Scholar and INSPIRE they are statically generated during build.
> 
> The problem in your case is that every time you build your site it scraps the information from Google Scholar for every paper you added this information. Since you added for a lot of them, it tried to fetch this for all of them, but Google found weird a lot of connection requests from the same IP and blocked it for some time.
> 
> One thing that might work is to increase the delay between requests, so it doesn't do a lot of requests in a small time frame and avoid being blocked by Google. Increase it here:
> 
> https://github.com/alshedivat/al-folio/blob/421bdf860bb24a052480b99109384361ea7dc73b/_plugins/google-scholar-citations.rb#L32

Thx for your reply,
I increased the delay from 1.5->3s to 3->5s. However, sometime, the request still be blocked and the same error.
Moreover, more than 3s to fetch a request is too slow. Especially in case, I have a lot of publications in the future (it's more than 10, rn).

**Comment by george-gca** [comment]
One solution that could work them would be to store the results from these fetches and simply reuse them, but them the citation count wouldn't be updated.

Since afaik there's no official Google product to provide these citations count, and we can't simply fetch this information from [your profile](https://scholar.google.com/citations?user=qc6CJjYAAAAJ&hl=en) because they might not all be loaded, there's not much we can do. 

Maybe the best solution for you would be to enable this only for some papers, or disabling it entirely.

**Comment by DoHaiSon** [comment]
> One solution that could work them would be to store the results from these fetches and simply reuse them, but them the citation count wouldn't be updated.
> 
> Since afaik there's no official Google product to provide these citations count, and we can't simply fetch this information from [your profile](https://scholar.google.com/citations?user=qc6CJjYAAAAJ&hl=en) because they might not all be loaded, there's not much we can do.
> 
> Maybe the best solution for you would be to enable this only for some papers, or disabling it entirely.

I see. I think right now it's still oke for me, waiting a little bit until fetch all of citation numbers is worthy. Hopefully in the future, we will have official method to get the citation number from scholar.

Thx for all, I'll close this issue.
