### ISSUE TITLE
Blockquote Appears to Be Broken

### ISSUE THREAD

**Issue by alexandermichels** [alshedivat/al-folio#280]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
It appears that blockquotes are indistinguishable from normal text. You can see it on this blog post on the demo site (the second-to-last paragraph is a blockquote): https://alshedivat.github.io/al-folio/blog/2015/formatting-and-links/ and the problem exists on [my site](https://alexandermichels.github.io/blog/2015/formatting-and-links/) as well. The problem seems to exist for both light and dark modes and when using the markdown `>` syntax and html blockquote tag. Using inspect confirms that it is a blockquote, just doesn't appear different at all.

**To Reproduce**
See the demo site: https://alshedivat.github.io/al-folio/blog/2015/formatting-and-links/ or you can test it locally by using the `>` markdown syntax such as:

```
> this is a blockquote test
```
> this is a blockquote test

**Expected behavior**
I would expect (and believe the old behavior was) that the text looks different from regular text. I believe it used to be indented with a line to the left of the text.

**System (please complete the following information):**
Obviously this only relevant to my site, not sure what the demo site is using:
 - OS: Linux Mint
 - Browser (and its version): checked on Chrome (Version 90.0.4430.212 (Official Build) (64-bit)) and Firefox 88.0.1
- Jekyll version [e.g. 3.8.7]: 4.2.0
- Ruby version [e.g. 2.6.5]: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu

**Comment by dag7dev** [comment]
I can confirm this, I solved this by manually styling a div but I can confirm this issue.

**Comment by ivanpuhachov** [comment]
Confirming this. As a temporary fix I added this to `_base.scss`:

```
blockquote {
  background: #f9f9f9;
  border-left: 2px solid #000;
  margin: 1.5em 10px;
  padding: 0.5em 10px;
  font-size: 1.2rem;
}

```

**Comment by alshedivat** [comment]
I believe #299 fixed this. Please re-open if this is not the case.
