### ISSUE TITLE
Improve Project page UX by Adding a return to projects button.

### ISSUE THREAD

**Issue by kartikey2001** [alshedivat/al-folio#2805]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

I would like to suggest an improvement to the Project page to enhance the user experience. Currently, the page lacks a `return button` which will bring the user back to the project section page, and I believe adding the following changes will significantly improve usability.

<b>Current Behavior:</b>
If we currently open a project card there is no way to return back to the project page.

### Pitch

[Change 1]: I would like to add a button which will take us back to the project page.

<b>Why this is needed:</b> It will make the page more efficient.

<b>How it helps:</b>  It will make it easier for the users to toggle between the different pages.

##

![image](https://github.com/user-attachments/assets/4762c911-f4cb-414e-b9ca-15e888914c36)

```
This is a sample of the return button .
```
After the proposed changes are made:
Users will be able to easily able to toggle between different projects.
The overall user experience will be improved by this one button.

### Additional context

If you have any specific design or suggestions for this feature, I would appreciate your feedback.

I am eager to contribute to improving the user experience by working on this feature. May I proceed with the development and submit a pull request for your review?

**Comment by george-gca** [comment]
I am not convinced. You can either click on the projects tab on the header and it will take you there, or click the back button of your browser. Why would we need another button for this?

**Comment by kartikey2001** [comment]
While navigating the site, I noticed a usability challenge when moving from the project card section back to the main project page. It felt unintuitive, as most users today prefer simpler navigation without relying on the browser's back button, which can disrupt focus. Repeatedly using the main navigation bar to return feels inconvenient and affects the flow of the experience. Adding a dedicated "Back" button or link would enhance the UI, keeping users’ attention on the content and making navigation more seamless.

If you’d like, you could gather feedback from users or team members with a poll to see if this navigation feature would be beneficial for them in future updates.
