### ISSUE TITLE
SCSS Compilation Error: Undefined function in _themes.scss

### ISSUE THREAD

**Issue by allitnils** [alshedivat/al-folio#2820]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

I tried to build this template, however, the SCSS compilation fails due to an undefined function in _themes.scss. The error message specifically highlights an issue with the color.channel() function or similar color-related functions. This error prevents the successful generation of the site.

### How to reproduce the bug

Run bundle exec jekyll build on the project.

### Error messages and logs

```
Error: Undefined function.
   ╷
23 │     #{color.channel($black-color, "red", $space: rgb)},
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  _themes.scss 23:7                                        @import
  /home/username/project/assets/css/main.scss 8:3          root stylesheet
```

### What operating system are you using?

Linux

### Where are you seeing the problem on?

Deployed site

### More info

Jekyll version: 4.3.4
Sass embedded version: 1.69.5
Ruby version: 3.0.0
System: Ubuntu

According to GPT:

Solution 1: Update the SCSS Function Usage
If you don’t need this function and can substitute it with simpler code, consider hardcoding or adjusting the color channels without color.channel. For instance, instead of:
`#{color.channel($black-color, "red", $space: rgb)},`
You could directly specify the desired color values if known.

Solution 2: Install Dart Sass
Since color.channel() is only available in Dart Sass, you can try switching to it instead of the default Ruby Sass (deprecated in Jekyll). 
To use Dart Sass in Jekyll, follow these steps:

Add sass-embedded to your Gemfile:

```
gem 'sassc-rails'
gem 'jekyll-sass-converter', '~> 3.0', '>= 3.0.0'
Run bundle install to update your project.
Solution 3: Use sass:math.div() or Rewrite Color Logic
```
If color.channel cannot be easily replaced and updating the Sass compiler is not feasible, you can rewrite the SCSS to avoid color.channel or refactor color manipulation to manual RGB adjustments.

Solution 4: Use Node-Sass as a Build Step
If these options aren’t feasible, you could run SCSS preprocessing with a build tool like Gulp or Webpack using Node-Sass or Dart Sass to handle modern SCSS features, then include the resulting CSS in Jekyll

**Comment by riccardoinghilleri** [comment]
It's just a Ruby version problem. Use version 3.1.0 or higher.

**Comment by george-gca** [comment]
Since it is a Ruby version issue, I'll close this issue. But maybe we need a `.ruby-version` file inside the root directory.
