### ISSUE TITLE
Inline $$|$$ cut text unexpectedly

### ISSUE THREAD

**Issue by Sr-11** [alshedivat/al-folio#2838]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

In posts, symbol | creates columns but does not display symbol |.

### How to reproduce the bug

1. Create a new post with the content:
```
---
layout: post
title: test
date: 2024-01-01 23:58
description:
tags: 
categories: 
tabs: 
published: true

---
The vibrant community of al-folio users is growing! Academics around the world use this theme for their homepages, blogs, lab pages, as well as webpages for courses, workshops, conferences, meetups, and more. Test $$\psi\rangle$$ and $$|\psi\rangle$$. Check out the community webpages below. Feel free to add your own page(s) by sending a PR.
```
2. Run "docker compose up" to deploy the webpage. 

### Error messages and logs

See the screenshot below. The symbol | unexpectedly cut the text into two columns rather than displaying $$|\psi\rangle$$. 
<img width="992" alt="image" src="https://github.com/user-attachments/assets/ca81a116-baaf-4718-9ee3-2de8620ee112">

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Running locally with Docker (docker compose)

**Comment by ShuhongDai** [comment]
Some personal experience for your reference: When working with quantum operators, I use `\vert` to represent the `|` symbol, which avoids any issues.
