### ISSUE TITLE
Blog Page Navigation Breaks Widens Mobile Layout

### ISSUE THREAD

**Issue by imsi32** [alshedivat/al-folio#2841]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Blog page navigation breaks widens mobile layout as it does not fit in.

### How to reproduce the bug

1. Go to [https://alshedivat.github.io/al-folio/blog/](https://alshedivat.github.io/al-folio/blog/) in small screen.
2. You will be able to slide to right.

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

### More info

https://github.com/user-attachments/assets/0fa7098e-6410-4138-ae74-e7a86ba406e9

**Comment by imsi32** [comment]
I am neither front-end developer nor designer but I find following adjustments which fixes the until 320px width without breaking main logic.

- Changing "Newer" and "Older" to arrows "<" and ">" in `_includes/pagination.liquid`.
- I couldn't find where it takes from but changing `padding: .75rem 1.15rem` in `bootsrap.min.css` in
``` css
.pagination-lg .page-link {
  padding: .75rem 1.5rem;
  font-size: 1.25rem;
  line-height: 1.5;
}
```



Images:
![desktop](https://github.com/user-attachments/assets/83a7ada6-8085-499a-b3ad-4aa6642147bf)
![width320](https://github.com/user-attachments/assets/6fd443ac-7a9a-495c-b6a7-927637d56e58)

**Comment by george-gca** [comment]
You can add these css properties in [_sass/_base.scss](https://github.com/alshedivat/al-folio/blob/main/_sass/_base.scss), since it is loaded after mdb and bootstrap here

https://github.com/alshedivat/al-folio/blob/b7ee266824c6cfa53cd63d876ab1fe4ce9ddd9a9/_includes/head.liquid#L68

it will override these values. If this works fine, can you send a PR for this?
