### ISSUE TITLE
Deploy fails due to Jekyll Scholar bug

### ISSUE THREAD

**Issue by coopersigrist** [alshedivat/al-folio#2849]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

The deployment is failing due to the 'numeric?' function being used in Jeyll-scholar 

### How to reproduce the bug

Default settings, installation and deployment instructions followed (only changes made), Auto Github Page Deploy and local docker fail for the same reason

### Error messages and logs

```
/home/runner/work/coopersigrist.github.io/coopersigrist.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-scholar-7.1.3/lib/jekyll/scholar/utilities.rb:343:in `group_value': undefined method `numeric?' for nil (NoMethodError)

          if value.numeric?
```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Running locally with Docker (docker compose), Deployed site

### More info

This is line 343 here: https://github.com/inukshuk/jekyll-scholar/blob/main/lib/jekyll/scholar/utilities.rb

From what I can tell this is using the Object#numeric? defined in finishing_moves here: https://github.com/BattleBrisket/finishing_moves/wiki/Object#objectnumeric

Truthfully, I am unfamiliar with Ruby / Bundle, so apologies if this is just user error

**Comment by george-gca** [comment]
Looking at the error, your group by is probably returning some `nil` value, that is why it is failing. This is probably due to some error in your bib entries.

**Comment by coopersigrist** [comment]
wow I'm dumb. 

thanks a ton, resolved
