### ISSUE TITLE
Add to menu item a redirect to external website

### ISSUE THREAD

**Issue by saguileran** [alshedivat/al-folio#2858]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

I want to create a menu item that redirects to the github repository. I am trying to change the permalink parameter to the url but it is not working, it is giving me something like: `user_name.github.io/https://etc...`
Is it possible to do it?

**Comment by saguileran** [comment]
Solved it!

Just remove the permalink and add `redirect: url`. This will redirect the user to the url after a few seconds.

**Comment by george-gca** [comment]
But this adds a delay, and it is not the best solution. Adding this change now.
