### ISSUE TITLE
`convert` Command Not Found on Ubuntu 24.04

### ISSUE THREAD

**Issue by dfuchss** [alshedivat/al-folio#2902]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

The convert command from ImageMagick fails to run in workflows using the latest ubuntu-latest tag in GitHub Actions. I guess this issue occurs because ubuntu:latest now uses Ubuntu 24.04 instead of 22.04.

### How to reproduce the bug

Just build a website with images and look into the logs.

### Error messages and logs

```
Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
       Imagemagick: Searching files in /home/runner/work/ardoco.github.io/ardoco.github.io/assets/img/
       Imagemagick: Generating image "/home/runner/work/ardoco.github.io/ardoco.github.io/_site/assets/img/icsa2019_poster-480.webp"
       Imagemagick: Command returned pid 1991 exit 127 with error sh: 1: convert: not found 
       Imagemagick: Generating image "/home/runner/work/ardoco.github.io/ardoco.github.io/_site/assets/img/icsa2019_poster-800.webp"
```

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

### More info

The page still reders, but the webp files are not generated anymore

**Comment by george-gca** [comment]
Can you give a link to your repository? I manually run the [deploy action](https://github.com/alshedivat/al-folio/actions/runs/12395800034) yesterday on this repo and everything run smoothly.

**Comment by dfuchss** [comment]
-> https://github.com/ArDoCo/ardoco.github.io/actions/runs/12394598016/job/34598413409

**Comment by dfuchss** [comment]
This commit is the interesting one: https://github.com/ArDoCo/ardoco.github.io/commit/c33c080a9898369f53fcf3ae6426486bef96c44d

And as far as I can see the runner of the build before was 22.04 and for this commit it was 24.04.

**Comment by dfuchss** [comment]
> Can you give a link to your repository? I manually run the [deploy action](https://github.com/alshedivat/al-folio/actions/runs/12395800034) yesterday on this repo and everything run smoothly.

Yes, this action still uses "22.04.5" .. tbh I don't know how github decides whether to use 24.04 or 22.04 :D

**Comment by george-gca** [comment]
Your [deploy action](https://github.com/ArDoCo/ardoco.github.io/actions/workflows/deploy.yml) is working just fine, and I can see that it is using the `latest` ubuntu tag. What is the problem?

**Comment by ananthu-aniraj** [comment]
Hi @dfuchss, I had the same issue. A temporary work-around is to replace the "ubuntu-latest" in the github workflow files with "ubuntu-22.04" (https://github.com/actions/runner-images?tab=readme-ov-file#available-images)

The corresponding files can be seen here: https://github.com/search?q=repo%3Aalshedivat%2Fal-folio%20ubuntu-latest&type=code

**Comment by dfuchss** [comment]
> Your [deploy action](https://github.com/ArDoCo/ardoco.github.io/actions/workflows/deploy.yml) is working just fine, every run of deploy, and I can see that it is using the `latest` ubuntu tag. What is the problem?

In the logs you can see that the creation of webp files fail silently :) so the srcSet of the images are empty .

**Comment by dfuchss** [comment]
> Now I understand. The action that failed is actually not using ubuntu 24.04 as can be seen in the [warning](https://github.com/ArDoCo/ardoco.github.io/actions/runs/12394598016). I don't think this is actually the problem.
> 
> 
> 
> > Hi @dfuchss, I had the same issue. A temporary work-around is to replace the "ubuntu-latest" in the github workflow files with "ubuntu-22.04" (https://github.com/actions/runner-images?tab=readme-ov-file#available-images)
> 
> 
> 
> Did this work for you? If it didn't, we can be sure it is not a problem of ubuntu version.

Yes that works. After downgrading the version, the webp files are generated again.

**Comment by lijiaqi** [comment]
@dfuchss @george-gca 
I solved this issue by manually adding an extra step to explicitly run `sudo apt-get install -y imagemagick` in the workflow file. This step should be put before ` - name: Install and Build 🔧`.

```
...
      - name: Update _config.yml ⚙️
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          propertyPath: "giscus.repo"
          value: ${{ github.repository }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
      - name: Install and Build 🔧
        run: |
          pip3 install --upgrade nbconvert
          export JEKYLL_ENV=production
          bundle exec jekyll build
...
```

**Comment by george-gca** [comment]
Can you send a PR for this? Only 1 suggestion, move all install code inside the `Install and Build` step, like this:

```yml
      - name: Install and Build 🔧
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          pip3 install --upgrade nbconvert
          export JEKYLL_ENV=production
          bundle exec jekyll build
```

and also do that for the `axe` and `broken-links-site` actions?

**Comment by lijiaqi** [comment]
@george-gca 
Sure. Made it at https://github.com/alshedivat/al-folio/pull/2906
