### ISSUE TITLE
Navbar not collapsing in mobile

### ISSUE THREAD

**Issue by csianglim** [alshedivat/al-folio#3]
![image](https://user-images.githubusercontent.com/7519832/27098648-333c3e46-502d-11e7-84a3-35a72d4d479a.png)

**Comment by alshedivat** [comment]
Good point. The styles do not currently support nav bar collapse for mobile. Most probably will be added in the next update (or feel free to open a pull request that adds this feature!).

**Comment by monkeywithacupcake** [comment]
I just added PR #10  that should close this - works for me.
