### ISSUE TITLE
Rebase error

### ISSUE THREAD

**Issue by XuhuiZhou** [alshedivat/al-folio#311]
Following the README:

```
$ git remote add upstream https://github.com/alshedivat/al-folio.git
$ git fetch upstream
$ git rebase upstream/v0.3.5
```
However, no matter

`git rebase upstream/v0.3.6`
or
`git rebase upstream/v0.3.5`

produce error: 
`fatal: Needed a single revision
invalid upstream 'upstream/upstream/v0.3.5'`

**Additional context**
I also tried to `rebase` in both `source` and `master` branch, but they do not work.

**Comment by johannagunawan** [comment]
Having the same error; what was the solution?

**Comment by XuhuiZhou** [comment]
I just re-installed things.
