### ISSUE TITLE
Site description variable in config.yaml is ignored when generating site

### ISSUE THREAD

**Issue by RahulRajkumar** [alshedivat/al-folio#318]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
Changing description in config.yaml does not change the description meta tag generated by Jekyll. Pasting the link into eg discord or inspecting page source gives the following description regardless of changes to config.yaml: "A beautiful, simple, clean, and responsive Jekyll theme for academics"

**To Reproduce**
1. Build site
2. inspect page source
3. <meta name="description" content="A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.

**Expected behavior**
The content generated by {{site.description}} in the head.html file ought to mirror variable in config.yaml

**Screenshots**

**System (please complete the following information):**
 - OS: Pop!_OS 20.10 (Ubuntu Groovy-derivative)
 - Browser (and its version) Mozilla Firefox for ubuntu 88.0.1 (64-bit)
 - Jekyll version 4.2.0
- Ruby version ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]

**Comment by alshedivat** [comment]
Thanks for reporting this. Everything works as expected on my end -- if I change the description in `_config.yml`, it changes on webpage. A couple of things to note:
- If you change anything in `_config.yml`, you have to rebuild the website again after that (e.g., if you are running `bundle exec jekyll serve`, you have to kill it and re-run again).
- Do you happen to have `.jekyll-cache` folder in your repo's root directory? It might be caching some old stuff, so you may need to remove it and re-build the website again.

Please lmk if you are still running into this issue.
