### ISSUE TITLE
The page build failed for the `source` branch with the following error:

### ISSUE THREAD

**Issue by rokas-bendikas** [alshedivat/al-folio#320]
**Describe the bug**

I followed all the instructions and can deploy the website locally. However, the it fails to build on GitHub. The error I get:

The page build failed for the `source` branch with the following error:

The tag `bibliography` on line 3 in `_includes/selected_papers.html` is not a recognized Liquid tag.

**System (please complete the following information):**
 - OS: iOS 11.4
 - Browser (and its version) Safari 14.1.1
 - Jekyll version [e.g. 3.8.7] 4.2.0
- Ruby version [e.g. 2.6.5] 3.0.1

**Comment by BenXu86** [comment]
Hi, could you please tell me how you fix this bug? I find that github doesn't support Jekylly-scholar.

**Comment by rokas-bendikas** [comment]
Hey, check out https://github.com/alshedivat/al-folio/issues/209

I didn't switch my main branch to master.
