### ISSUE TITLE
Error deploying the website (GitHub action)

### ISSUE THREAD

**Issue by nadgowdas** [alshedivat/al-folio#321]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
I am getting following error in the GitHub action:
```
Please commit those files or stash them before proceeding.
29212
Aborting.
29213
Error: Process completed with exit code 1.
```

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="832" alt="Screen Shot 2021-06-21 at 3 42 40 PM" src="https://user-images.githubusercontent.com/8685412/122818585-63c29500-d2a7-11eb-804d-1e5de7d91e35.png">

**System (please complete the following information):**
 - Browser (and its version) [e.g. chrome, safari]
 - Jekyll version [e.g. 3.8.7]
- Ruby version [e.g. 2.6.5]

**Additional context**

**Comment by alshedivat** [comment]
@nadgowdas, I'm not able to reproduce the issue. Could you confirm that you followed the [installation instructions](https://github.com/alshedivat/al-folio#installation)?

**Comment by nadgowdas** [comment]
@alshedivat i tried debugging it and realized it was because github has started naming default branch as `main` instead of `master`. I changed bin/deploy and I was able to host my pages.

I really like your theme, thanks for putting it up.
