### ISSUE TITLE
PlantUML and mermaid UML support

### ISSUE THREAD

**Issue by ihexon** [alshedivat/al-folio#322]
Using code chunks  to generate UML diagram:
        
        ```mermaid
         ```

         ```plantuml
         ```
It is a very useful feature if can support in al-folio .

**Comment by alshedivat** [comment]
@ihexon, thanks for the suggestion! Would you mind providing more details/examples of how `mermaid` and `plantuml` rendering would work? Are there any JS libraries that provide support? Thanks.

**Comment by ihexon** [comment]
[mermaid](https://github.com/mermaid-js/mermaid)
 [plantuml](https://github.com/plantuml/plantuml)

Project using mermaid and plantuml:
- [codime](https://github.com/hackmdio/codimd)
- [jekyll-TeXt-theme](https://github.com/kitian616/jekyll-TeXt-theme/commit/3f115f9d680b24a605e50bd4fdf0e65a0464b6d9)
   - [relate commit](https://github.com/kitian616/jekyll-TeXt-theme/commit/3f115f9d680b24a605e50bd4fdf0e65a0464b6d9)

**Comment by alshedivat** [comment]
it looks like [jekyll-diagrams](https://github.com/zhustec/jekyll-diagrams) provides support for mermaid, platuml, vega-lite, etc. definitely worth integrating into al-folio.
