### ISSUE TITLE
Display First Names First

### ISSUE THREAD

**Issue by goldblum** [alshedivat/al-folio#329]
I have been trying to figure out how to display paper authors first name first instead of "lastname, firstname", but I am unable to do this.  It would be great if there were a simple way to do this.

**Comment by alshedivat** [comment]
Thanks for the suggestion. Currently, the logic of how publications are displayed is specified in [`_layouts/bib.html`](https://github.com/alshedivat/al-folio/blob/master/_layouts/bib.html#L38-L67). Should be possible to switch from "last, first" to "first last" either by editing `_layouts/bib.html` or adding a flag to `_config.yml` and some additional if-then-else logic. If you end up doing the latter, would be great if you could send a PR with the change!

**Comment by goldblum** [comment]
Thanks for your help.  I changed mine the hacky way, since it's easy enough.
