### ISSUE TITLE
blog posts not loading + "about" page issue

### ISSUE THREAD

**Issue by CPRyan** [alshedivat/al-folio#33]
First, thank you for a wonderful template. 

1. I am having issues with blog posts appearing. At first, I thought I had deleted or changed something after I started customizing, but to test out the cause I forked, cloned, and started everything from scratch. The "blog" page still doesn't work. see: https://cpryan.github.io/blog/ and the image below:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/17647405/49559886-f8299f80-f8d5-11e8-8e2a-4b0fde2b9398.png">

I saw somebody having an issue with 'workflow' and blog posts, and tried both with and without --incremental with the jekyll bundle, but no change. 

2. When I navigate to the "about" page from the (broken) blog page, there is 404 error. No idea why this is. Any thoughts? 

Here is the repo:
https://github.com/CPRyan/CPRyan.github.io

If anybody has any suggestions, I would be much obliged. I am pretty new to jekyll and even git so please bear with me.

**Comment by monkeywithacupcake** [comment]
I went to your page today @CPRyan, and it appears to be working. Can you advise if this issue should be closed? Also, what changed?

**Comment by CPRyan** [comment]
I just figured out last week that it was a problem on my end. 

I had a separate github blog that was interfering with this one uploading correctly. 

Thanks again for your help and a great package.
