### ISSUE TITLE
how to include publication into about page

### ISSUE THREAD

**Issue by Andrewtor** [alshedivat/al-folio#34]
Can we include publication page as one part into about page, like the news part or social part?
It is unclear how to do this with automatic generation of publication page.

**Comment by monkeywithacupcake** [comment]
Yes. You can do this. The jekyll-scholar gem does not care which page you put your pubs in. 

In your About page, add years to your YAML, like so:

```---
layout: about
permalink: /
title: <strong>Albert</strong> Einstein
description: Something about relativity
profile:
  align: right
  image: faces/img.png
  address: >
    <p>whatever</p>

news: true
social: true
nav: true
years: [2014, 2012, 2011, 2010, 2009, 2007]
---```

Then, add the Publications code wherever you want it on the page:

```{% for y in page.years %}
  <h3 class="year">{{y}}</h3>
  {% bibliography -f papers -q @*[year={{y}}]* %}
{% endfor %}```

**Comment by Andrewtor** [comment]
Thanks! @monkeywithacupcake , very helpful! It is possible to make publication in the menu link to this publication in about page instead of a new page of publication?

**Comment by Andrewtor** [comment]
Ok, I figured it out, using tag name works for me. However, with @monkeywithacupcake suggestions, the publication section in about page doesn't have a good space between itself and other section.

**Comment by monkeywithacupcake** [comment]
You can change the spacing with css or just add in <br/> if you want to manually break. 

I think the best approach would be to put your publications section in a div.
```
<div class="XXXX">
{% for y in page.years %}
  <h3 class="year">{{y}}</h3>
  {% bibliography -f papers -q @*[year={{y}}]* %}
{% endfor %}
</div>
```
You can either create a css style that you want or find a styling that you like the spacing of and apply it to the div, where it says `class = "XXXX"`.

**Comment by Andrewtor** [comment]
Thank you very much! @monkeywithacupcake
