### ISSUE TITLE
Add last blog posts to the about page

### ISSUE THREAD

**Issue by sdaza** [alshedivat/al-folio#340]

**Comment by alshedivat** [comment]
Thanks for the suggestion. al-folio is intentionally designed to separate the about page from the blog content, unlike most other Jekyll themes that make the blog a central part. Having said that, let's keep this issue open to see how much interest there is in supporting this feature (people can vote with 👍 if they'd like to have this supported).

**Comment by pourmand1376** [comment]
It is been a year since this issue was created. This one is favorable to some people (including me). Perhaps, we can add this feature but only make it optional.
