### ISSUE TITLE
Deployment workflow enhancement

### ISSUE THREAD

**Issue by neerajgangwar** [alshedivat/al-folio#342]
The deployment workflow currently uses two sets of branches:

1. For the project pages: `master` branch for the source code and `gh-pages` branch for the generated website.
2. For personal or organization webpages: `source` branch for the source code and `gh-pages` branch for the generated website.

**Describe the solution you'd like**
The above-mentioned behavior can be unified. For both use cases, `master` can be used for the source code and `gh-pages` can be used for deployment.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by neerajgangwar** [comment]
I have raised a PR for this - https://github.com/alshedivat/al-folio/pull/343. I am still unsure about the manual deployments. Happy to hear suggestions.

**Comment by neerajgangwar** [comment]
I have raised a PR for this - https://github.com/alshedivat/al-folio/pull/344.

**Comment by ivanpuhachov** [comment]
Hi! I was following the previous instruction and `source` branch, and after sync with upstream, github actions are no longer triggered. What should I do to fix it?

**Comment by neerajgangwar** [comment]
@ivanpuhachov Can you share your repo link?

**Comment by ivanpuhachov** [comment]
Fixed it.

1. `.github/workflows/deploy` add `source` to the branches:
```
on:
  push:
    branches:
      - master
      - source
```
2. On Github - repo - Settings - Pages select `gh-pages` as a source branch – as it is written in current readme file. In old instructions it was `master`

**Comment by neerajgangwar** [comment]
Yes, this is one way. But the idea was to have source code in the `master` branch. So you could also do the following:

1. Delete the `master` branch.
2. Rename `source` to `master`.
3. Push all the future changes to `master`. The generated site will be pushed to `gh-pages` which should be selected as the source branch in the publishing source.

**Comment by ivanpuhachov** [comment]
Got it, thank you!
