### ISSUE TITLE
Issue with LaTeX math mode from bibliography

### ISSUE THREAD

**Issue by mbarbetti** [alshedivat/al-folio#357]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
MathJax _partially_ fails in rendering LaTeX math mode of abstracts content in [`papers.bib`](https://github.com/alshedivat/al-folio/blob/master/_bibliography/papers.bib). Issues identified:
- The mathematical expressions remove the whitespace that follows
- The `~` symbol is ignored
- The `\mbox{...}` function is unrecognized
- Longer superscripting fails

**To Reproduce**
1. Go to `_bibliography/papers.bib`
2. Add a new article like what follows
```LaTeX
@article{Aaij:2021lxk,
  abbr={arXiv},
  title={Angular analysis of the rare decay \(B_s^0 \to \phi \mu^+ \mu^-\)},
  collaboration={LHCb Collaboration},
  author={Aaij, R. and others},
  abstract={An angular analysis of the rare decay \(B_s^0 \to \phi \mu^+ \mu^-\) is presented,
            using proton-proton collision data collected by the LHCb experiment at centre-of-mass 
            energies of \(7\), \(8\) and \(13~\mbox{TeV}\), corresponding to an integrated luminosity 
            of \(8.4~\mbox{fb}^{−1}\). The observables describing the angular distributions of the 
            decay \(B_s^0 \to \phi \mu^+ \mu^-\) are determined in regions of \(q^2\), the square of 
            the dimuon invariant mass. The results are consistent with Standard Model predictions.},
  journal={arXiv preprint},
  year={2021},
  month={July},
  arxiv={2107.13428},
  selected={true}
}
```
3. Open the corresponding abstract on the publications page

**Expected behavior**
Adding the abstract text directly within the [`bib.html`](https://github.com/alshedivat/al-folio/blob/master/_layouts/bib.html) file, MathJax is able to render correctly the LaTeX content desidered. How can I obtain the same result from `papers.bib`?

**Screenshots**
![issue_pic](https://user-images.githubusercontent.com/55536905/127557620-664f41f8-cadc-409a-8040-770bc6e05d94.png)

**System:**
- OS: Windows 10 Home (v21H1)
- Browser: Microsoft Edge (v91.0.864.67)
- Jekyll version: 4.2.0
- Ruby version: 2.7.0p0

**Comment by alshedivat** [comment]
@mbarbetti, thanks for the detailed bug report. Could you double check that the math you are trying to render works when used outside of bibliography? E.g., does the same math render correctly when you use in a post (like [this one](https://alshedivat.github.io/al-folio/blog/2015/math/))?

**Comment by mbarbetti** [comment]
@alshedivat, I have checked that before opening this issue, and I can confirm that the LaTeX content attached is correctly rendered within MD and HTML files. I fear that is an issue related to the conversion from BibTeX, it is possible?
