### ISSUE TITLE
Website extremely slow to load

### ISSUE THREAD

**Issue by yang-song** [alshedivat/al-folio#367]
Some personal websites using `al-folio` theme are now extremely slow to load. I started to observe this issue around 1 week ago.

Examples:
https://www.compphys.de/
https://dineshnatesan.com/

**Comment by yang-song** [comment]
I think the issue comes from this line: 

https://github.com/alshedivat/al-folio/blob/5a655959189e13a49f3ad7e2f7af28002cbc44ca/_includes/head.html#L37

The link to pygments theme no longer works.

**Comment by alshedivat** [comment]
Thanks for reporting this! I thought #364 solved the issue, but you are saying that it still persists?

The style sheet seems to load correctly on [the demo page](https://alshedivat.github.io/al-folio/) and if you try to go to https://gitcdn.link/repo/jwarby/jekyll-pygments-themes/master/github.css directly, it seems to work as well.

**Comment by yang-song** [comment]
Now both https://gitcdn.link/repo/jwarby/jekyll-pygments-themes/master/github.css and https://gitcdn.link/repo/jwarby/jekyll-pygments-themes/master/github.css work. When I tried visiting the second link yesterday, it gave something like "this link is blacklisted..." I am afraid that these links may not be very stable.

**Comment by alackles** [comment]
I'm encountering the same issue; these links do not appear stable. .link works well now, but .xyz hangs.

**Comment by ivanpuhachov** [comment]
Same with me, `.xyz` hangs

**Comment by lsterzinger** [comment]
#364 Fixed the issue for me, I was hanging on https://gitcdn.xyz but https://gitcdn.link resolves instantly

**Comment by s-adithya** [comment]
The issue still persists with me. Changing `.xyz` to `.link` doesn't change the time at which my site loads.
[My website](https://s-adithya.github.io/)

**Comment by arafathm** [comment]
I had the same problem. Changing https://gitcdn.xyz with https://gitcdn.link solved the problem.

**Comment by tillgrallert** [comment]
Same problem here with <https://gitcdn.xyz>. As such links are prone to fail (see the demise of rawgit), wouldn't it make sense to include the targetted CSS in al-folio's code base?

**Comment by syncdoth** [comment]
both the https://gitcdn.xyz and https://gitcdn.link are down (https://github.com/schme16/gitcdn.xyz/issues/94), and although it wouldn't take long to load, the code syntax highlighting will not work. 

I'm using https://combinatronics.io instead as a workaround.

**Comment by ningding97** [comment]
> Now both https://gitcdn.xyz/repo/jwarby/jekyll-pygments-themes/master/github.css and https://gitcdn.link/repo/jwarby/jekyll-pygments-themes/master/github.css work. When I tried visiting the second link yesterday, it gave something like "this link is blacklisted..." I am afraid that these links may not be very stable.

Yes, the gitcdn.link is unstable for me (China), have you found any solutions?

**Comment by alshedivat** [comment]
@ningding97, could you please try switching to raw.githubusercontent.com or jsdelivr.com as an alternative to gitcdn.link and let us know here if it is more stable in China?

**Comment by ningding97** [comment]
> @ningding97, could you please try switching to raw.githubusercontent.com or jsdelivr.com as an alternative to gitcdn.link and let us know here if it is more stable in China?

Hi, I've tried raw.githubusercontent.com and it is significantly more stable so far, thanks!

**Comment by NeoNeuron** [comment]
Hi, it seems that cdn.jsdelivr.net is not accessible in China (if without VPN) now. I fix this issue by replacing links to [cdnjs.cloudflare.com](https://cdnjs.com), which was used before #521. And also for code syntax highlighting, raw.githubusercontent.com is not working in my cases. Thus, I adapted the advice from @syncdoth using https://combinatronics.io to generate links to corresponding links. For me, https://combinatronics.io/jwarby/pygments-css/master/github.css is working.

Here is my fixation on our own lab-webpage, for the ease of reference. https://github.com/LCNS-SJTU/lcns-sjtu.github.io/commit/2732d883e3959a1f21fc13b2adfb301ff7be7c44
