### ISSUE TITLE
Tags for projects

### ISSUE THREAD

**Issue by siantonelli** [alshedivat/al-folio#391]
Is there a way to list the projects having a specific tag, as `Jekyll-tagging` does with posts' tags?

**Comment by rohandebsarkar** [comment]
#346

**Comment by alshedivat** [comment]
@rohandebsarkar, I believe #346 adds support for archive pages for post tags, not for project tags. I believe that tagging projects should be possible (from Jekyll's perspective, projects are just another collection of objects, similar to posts).

**Comment by george-gca** [comment]
I just don't know exactly how visually this could be done. Currently there is no tag information on the projects page, and I am not sure it should. Maybe the tags should be shown only inside a projects page, and from there be possible to navigate through other projects with that tag?
