### ISSUE TITLE
Distill posts does not obey site wide max_width

### ISSUE THREAD

**Issue by rohandebsarkar** [alshedivat/al-folio#394]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Distill blog posts do not obey the `max_width` in the `_config.yml` file.

**Screenshots**
![Screenshot 2021-09-18 at 23-27-11 You R Name](https://user-images.githubusercontent.com/50144004/133898078-c7e8416b-daa8-4a59-ab38-0ecbd454a7ec.png)
![Screenshot 2021-09-18 at 23-27-23 You R Name a distill-style blog post](https://user-images.githubusercontent.com/50144004/133898080-ee6f951e-2ad9-4b68-ad5d-ab91ae8853a8.png)

**Comment by alshedivat** [comment]
good observation. however, I don't think this is fixable without having to re-write and/or deeply integrate distill.pub styles into al-folio. currently, distill-style posts directly use native distill.pub styles (+ night mode overrides in [`_sass/_distill.scss`](https://github.com/alshedivat/al-folio/blob/master/_sass/_distill.scss)), which are not controlled by `_config.yml` variables.

if you are using distill-style posts now, the easiest workaround is to make `max_width` match the max width of distill posts. not sure how many folks are actively using distill-style posts, but if there's a lot of interest, would be awesome to start looking into tighter integration! :)

**Comment by teng-gao** [comment]
Yes, this feature would be great ..
