### ISSUE TITLE
No Gemfile in repo; internet guide doesn't work

### ISSUE THREAD

**Issue by Corneliuscob** [alshedivat/al-folio#4]
Hi, 

It was challenging getting jekyll to run with al-folio.  I followed the first link when searching ' Gemfile for  Jekyll'. Running 

`source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins `

returns an error with bibliography when launching the jekyll server

`source 'https://rubygems.org'`
`group :jekyll_plugins do `
 ` gem 'github-pages'`
`  gem 'jekyll-paginate'`
 ` gem 'jekyll-scholar'`
`  gem 'jemoji'`
`end`

made it work

**Comment by alshedivat** [comment]
Thanks for pointing out. Gemfile added.
