### ISSUE TITLE
Strip Bibtex key-values before printing

### ISSUE THREAD

**Issue by bonassifabio** [alshedivat/al-folio#401]
**Is your feature request related to a problem? Please describe.**
The publications page makes use of some key-values, such as `pdf`, `bibtex_show`,  `abbr`, and even `abstract`. 
However, if one sets `bibtex_show = {true}`, all these auxiliary key-values are exported as well in the bibtex citation code.
If one copies such citation code in his/her paper, undesired text may appear.

**Describe the solution you'd like**
The auxiliary key-values should be removed before printing {entry.bibtex}. This could be done stripping the keys that are contained in a list of known auxiliary key-values.

**Comment by th2l** [comment]
One temporary solution you can try:
1. Add _gem 'jekyll-regex-replace'_ in Gemfile
2. Run `bundle install`
3. Modify __layouts/bib.html_ line 144
`{% assign bibtext_str = entry.bibtex | regex_replace: "( )*((html)|(code)|(selected)|(bibtex_show)|(abbr)|(pdf)|(abstract)|(blog)|(poster)|(slides)|(website)|(supp)|(arxiv))+(.)*(\n)*(\r)*", "" %}`
`      {% highlight bibtex %}{{ bibtext_str }}{% endhighlight %}`

**Comment by bonassifabio** [comment]
I can confirm that the solution works! Thank yo so much @th2l

**Comment by p-costa** [comment]
It would be nice to have https://github.com/alshedivat/al-folio/issues/401#issuecomment-927849008 or any alternative solution featured on the repo (cc @alshedivat).
