### ISSUE TITLE
add jekyll target blank plugin

### ISSUE THREAD

**Issue by pourmand1376** [alshedivat/al-folio#408]
Hi,

I think it would be awesome if I don't have to include `target="_blank"` for every external site I am going to refer to, especially in the blog posts. So I did some research and I found [this](https://github.com/keithmifsud/jekyll-target-blank) plugin. I also made a pull request. #404

Thank you for your attention.

**Comment by alshedivat** [comment]
sweet! this plugin is a nice find. thanks for sending a PR!
