### ISSUE TITLE
Blog post comments

### ISSUE THREAD

**Issue by ricvolpe** [alshedivat/al-folio#43]
Dears,

Great theme: I just love it! A quick question for a feature that would make real difference for me. How complex do you think is to add commenting abilities to the blog posts? Any indications on how would I add that (happy to make a pull request about if I find specific guidance!)

**Comment by samfearn** [comment]
Hey,

It’s easy using Disqus. Support is built into the theme. You need to create a Disqus account and put your account details into the relevant part of the _config file. Then for any page/post where you want comments, you just have to turn an option on for the page/post — I can’t remember what the name of the option is, I can look later or you can look at my fork for some examples if the main branch doesn’t have any.

**Comment by alshedivat** [comment]
The theme demo has a post with comments: https://alshedivat.github.io/al-folio/blog/2015/comments/

**Comment by ricvolpe** [comment]
Thanks for guidance! I think end I choose to go for **Talkyard** because of the better privacy settings (it is very easy to install: https://jekyll-demo.talkyard.io/2018/01/09/installation-instructions.html)
