### ISSUE TITLE
How to deploy to github

### ISSUE THREAD

**Issue by ngcthuong** [alshedivat/al-folio#44]
Hello, 

Thank you for sharing a super great repo. 
I am pretty new here, and not sure how to run the deploy on Window. 
I always get '.' is not recognized as the internal or external command by using CMD for `$ ./bin/deploy [--user]`

Thank you

**Comment by ngcthuong** [comment]
I found the solution for the window os. 
change `deploy ` to `deploy.sh` and use
>  bin\deploy.sh --user

**Comment by yatingilhotra** [comment]
Hi,

I have the same issue, and I am not able to solve the issue using the resolution that you mentioned above. Could you please help by providing more details?  Are we required to setup somethings in the windows cmd before we can use this deploy script? Are we required to setup ruby and bundler?

Any help would be highly appreciated.

Thanks!
