### ISSUE TITLE
It looks like that Jeklly only supports lower case tags or categories.

### ISSUE THREAD

**Issue by yuanjames** [alshedivat/al-folio#453]
It looks like that Jeklly only supports lower case tags or categories. Otherwise, it always display errors.

**Comment by alshedivat** [comment]
interesting, thanks for pointing this out. could you provide more info so that this behavior can be reproduced and fixed?

**Comment by yuanjames** [comment]
When xxx.md files in post file have the head in which the keyword categories give the word with the capitalisation, then the archive function will crash.

for example,
---
layout: post
comments: false
title : xxxx
description: xxx
categories: Abc
date: 2021-11-21 12:00:00
---

Even you can ope this page, but when you click the Abc button, it will give you a not found mistake

**Comment by cnut1648** [comment]
Yeah I can confirm that in the latest version this problem still exists

**Comment by alshedivat** [comment]
not able to reproduce this error. created `_posts/2022-03-01-test.md` with the following content:
```
---
layout: post
comments: false
title: test
date: 2022-03-01 00:00:00
description: test
categories: Abc
tags: Xyz
---

test
```
this correctly creates the test blog post page, the page for category `Abc`, and the tag page for tag `Xyz`.
