### ISSUE TITLE
Preview images for publications

### ISSUE THREAD

**Issue by udion** [alshedivat/al-folio#475]
Just like we have images for projects, it will be nice to have images for publications. 

I got it to work can have a look here: https://udion.github.io/ but it does not look good on mobile screen, the images blow out of proportion. Perhaps I did something wrong, it will be nice to have it officially implemented.

**Comment by Emadmasroor** [comment]
@udion Can you please explain how you got this to work? What code did you modify in your fork?

**Comment by bchao1** [comment]
@Emadmasroor go to `_layouts/bib.html` and modify the bibliography layout. For me, I added something like:

```
<div class="col-sm-3">
        {%- if entry.teaser -%}
          {% if entry.teaser contains '://' -%}
          <img class="teaser" src="{{ entry.teaser }}">
          {%- else -%}
          <img class="teaser" src="{{ entry.teaser | prepend: '/assets/img/paper_teasers/' | relative_url }}">
          {%- endif -%}
        {%- endif -%}
 </div>
```

as the children of the root div. The `col-sm-3` class specifies the width of the left-most div (which, in this case, is the div where the image resides). You can change the number `3` to whatever number you want to adjust the size of the div.

`entry.teaser` is a new key I defined in each bibliography entry, which you can add in `_bibliography/papers.bib`.

**Comment by rohandebsarkar** [comment]
PR #730.

**Comment by zhufyaxel** [comment]
This could be solved by editing the _base.scss with .preview feature. Set the max-width under ti works, as the image below shows
<img width="901" alt="image" src="https://github.com/alshedivat/al-folio/assets/13378632/0a07dab8-7d04-4286-bd2d-8a2afd5e13ca">
The results will look good as expected. Hope it will help people in future.
