### ISSUE TITLE
Ordering tabs - missing label after upgrading to 0.3.5

### ISSUE THREAD

**Issue by RafalKucharskiPK** [alshedivat/al-folio#483]
I lately upgraded to al-folio 0.3.5 (for automatic deployment - which is great). 
However I am confused with some features.
For instance I do not know how to order tabs. Before, each page in the table at the top had the label `order` - now it is only `nav = true` - **so how do I set order of my tabs at the top of the main page?**

Thanks

**Comment by RafalKucharskiPK** [comment]
PS. I tried to name the files `"1_*.md" , "2_*.md"` etc but it did not work. Pages seem to sorted alphabetically by their names, not the file names.

**Comment by alshedivat** [comment]
thanks for raising this issue! in the latest version, the template sorts links in the nav bar alphabetically by default. it's not the first time people are asking for more control over how the links are ordered (or capitalized #147). will add this feature in the upcoming version.
