### ISSUE TITLE
Deployment error when forking

### ISSUE THREAD

**Issue by itaigat** [alshedivat/al-folio#484]
Hey, 

I forked this rep, followed the instructions, the deployment works perfectly, and immediately after I got the following error in Github page build:

![image](https://user-images.githubusercontent.com/11094765/144464044-e229cca0-becc-4c02-b35d-d2363a998f89.png)

Deployment:

![image](https://user-images.githubusercontent.com/11094765/144464312-dd10b49c-e733-415b-b397-bc68440e124d.png)

I also followed Issue #209 but it didn't help. What can I do with it?

Thanks!

**Comment by itaigat** [comment]
Misplaced backslash

**Comment by smashmath** [comment]
> Misplaced backslash

@itaigat Can you specify where the misplace backslash is?

**Comment by bradyhunt** [comment]
@itaigat I am also getting this error.  Can you share what you did to resolve it?
