### ISSUE TITLE
Distill TOC not working with special characters (e.g. ', ?)

### ISSUE THREAD

**Issue by LoryPack** [alshedivat/al-folio#489]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
I have added the TOC to my distill blog posts, following #470. That works fine. However, if the section or subsection contain special characters (as for instance apostrophe ' or question mark ?), the links in the table of contents do not work. 

**To Reproduce**
Simply create a distill blog post, add a section with a question mark and add it to the TOC. 

An example is present in my blog post [here](http://www.lorenzopacchiardi.me/blog/2021/generalizedBayes/#so-what-is-wrong?). See also the source code on Github [here](https://github.com/LoryPack/lorypack.github.io/blob/bbc1667949a8516f43d1199dd2f9dfa8f34ff25f/_posts/2021-08-05-generalizedBayes.md).

**Expected behavior**
TOC link should work.

**System (please complete the following information):**
 - OS: Linux, Ubuntu 20.04
 - Browser (and its version) Firefox 94.0
 - Jekyll version: 3.9.0
- Ruby version: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**Comment by alshedivat** [comment]
@LoryPack, thanks for raising this issue.

do you mind testing something quick for me in your blog? if you edit `_layouts/distill.html` and change `#{{ section.name | downcase | replace: ' ','-' }}` to `#{{ section.name | handleize }}` on lines 75 and 79, does that help? thanks.

**Comment by LoryPack** [comment]
Hello, thanks for that. I have tried what you suggest, but if you do that no link in TOC works!

I realized the issue in the first place is not due to the links in TOC. In fact, if I remove the TOC from the blog post, still the links with # go to the right section, except for the ones in which a "?" or " ' " appear. For instance, in my example, going to 
http://www.lorenzopacchiardi.me/blog/2021/generalizedBayes/#power-likelihood 

goes to the right section, while 

http://www.lorenzopacchiardi.me/blog/2021/generalizedBayes/#so-what-is-wrong?

does not, even if no TOC is present.

**Comment by alshedivat** [comment]
@LoryPack, makes sense. looks like `handleize` is not a valid jekyll filter; the correct one is `slugify`. #519 should fix the issue (see code changes [here](https://github.com/alshedivat/al-folio/pull/519/files#diff-dd8ca147cf4c0469aa879c10a03b9c9e1183486699aadcb0d14f52f8ac398cc4)). please check and let me know if it works on your end. thanks!

**Comment by LoryPack** [comment]
Seems to be working now, thanks a lot!
