### ISSUE TITLE
Deployment error: does the workflow need an update? 

### ISSUE THREAD

**Issue by danbischof** [alshedivat/al-folio#494]
Today, I tried pushing a new file to my webpage to be then confronted with a deployment error: 

https://github.com/danbischof/danbischof.github.io/actions/workflows/deploy.yml
``0s 1``
``Run actions/setup-ruby@v1 4``
``------------------------ 5``
``NOTE: This action is deprecated and is no longer maintained. 6``
``Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained. 7``
``------------------------ 8``
``Error: Version 3.0.2 not found``

I first figured the error is my machine, but it appears that it might be an issue in the workflow routine. As I don't know anything about workflows: How can I re-solve this? Anyone else struggling with this error? 

Thanks so much in advance! 

**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Deployment returns the error "Error: Version 3.0.2 not found" not found from github workflow. 

**To Reproduce**
Go to: https://github.com/danbischof/danbischof.github.io/actions/runs/1550335930

**Expected behavior**
It is expected that the deployment workflow does not return any errors and deploys changes to the webpage without returning jekyll errors. 

**Screenshots**
Link above fully reports error 

**System (please complete the following information):**
 - OS: Monterey
 - Browser (and its version) safari
 - Jekyll version 4.2.1
- Ruby version 3.0.2

**Additional context**
Error in wokflow

**Comment by danbischof** [comment]
Solved by updating the workflow. My bad!

**Comment by juanfung** [comment]
@danbischof just ran into this issue. Sorry to be dense but how do you update the workflow?

**Comment by alldbi** [comment]
@juanfung I replaced the file .github/workflows/deploy.yml with the newest version in the repository and the issue is resolved.
