### ISSUE TITLE
Github Action Failure: github-pages 222 | Error:  Liquid syntax error (line 5): Unknown tag 'bibliography'

### ISSUE THREAD

**Issue by ganler** [alshedivat/al-folio#513]
![image](https://user-images.githubusercontent.com/38074777/147158034-bc914575-3843-4763-8eb9-a7905f0e52f7.png)

Here is the content from `publications.md`:

```markdown
---
layout: page
permalink: /publications/
title: Publications
description: 
years: [2021,2022]
nav: true
---

<div class="publications">

{% for y in page.years %}
  <h2 class="year">{{y}}</h2>
  {% bibliography -f papers -q @*[year={{y}}]* %}
{% endfor %}

</div>
```

Can succeed in local environment but failed in github actions.

**Comment by ganler** [comment]
The CI can be found here: https://github.com/jiawei-site/jiawei-site.github.io/runs/4611859544?check_suite_focus=true

**Comment by ganler** [comment]
So strange... It suddenly works again... I guess this is a github issue...

**Comment by XinhuiLi** [comment]
Hi I have the same issue and I haven't figured out how to solve it. Any suggestions?
