### ISSUE TITLE
Custom Page Order in NavBar

### ISSUE THREAD

**Issue by emalgorithm** [alshedivat/al-folio#526]
In the navigation bar, the order of the pages is defined by sorting alphabetically: `{%- assign sorted_pages = site.pages -%}.` 
Is there an easy way to specify a different order?

**Comment by babaknasr** [comment]
checkout my workaround in following commit:
https://github.com/babaknasr/babaknasr.github.io/commit/d900a98c3861fe6819932e2213405d98b8213a09

I added a new tag "sort_menu" for each page using numbers and then sorted based on "sort_menu":
{% assign sorted_pages = site.pages | sort: "sort_menu" %}
by changing the value of the tag, manually you can manipulate the order of menu items.

**Comment by bchao1** [comment]
Isn't there an `importance` tag for each page already?

**Comment by emalgorithm** [comment]
@bchao1 Do you have an example for that?

**Comment by bchao1** [comment]
Not sure which version you're using, In my case, line 39 in `_includes/header.html` specifies that the tabs in the navbar is sorted using the `order` attribute:
```
{%- assign sorted_pages = site.pages | sort: "order" -%}
```

So, you can simply add the `order` attribute in each markdown file in `_pages` to change the ordering. Example:
```
---
layout: page
permalink: /publications/
title: publications
order: 2
description: Brian Chao's publications.
years: [2022, 2021, 2020]
nav: true
---
```
