### ISSUE TITLE
Change Bibliography Style

### ISSUE THREAD

**Issue by emalgorithm** [alshedivat/al-folio#527]
The default style has the format: Author1_Surname, Author1_Name, Author2_Surname, Author2_Name
Where can we change it to be: Author1_Name Author1_Surname, Author2_Name Author2_Surname?

Thanks

**Comment by bchao1** [comment]
@emalgorithm you change it in `_layouts/bib.html`. The template specifies that the author surname comes first:

```
{{author.last}}, {{author.first}}
```

Simply swap the ordering.
