### ISSUE TITLE
pages build and deployment failed: "Liquid syntax error (line 5): Unknown tag 'bibliography'"

### ISSUE THREAD

**Issue by XinhuiLi** [alshedivat/al-folio#529]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Same as #513, I keep getting this error in GitHub Actions pages build and deployment, though it works locally: https://github.com/XinhuiLi/xinhuili.github.io/runs/4829656563?check_suite_focus=true

```
Liquid Exception: Liquid syntax error (line 5): Unknown tag 'bibliography' in _pages/publications.md
/usr/local/bundle/gems/liquid-4.0.3/lib/liquid/block.rb:38:in `unknown_tag': Liquid syntax error (line 5): Unknown tag 'bibliography' (Liquid::SyntaxError)

github-pages 223 | Error:  Liquid syntax error (line 5): Unknown tag 'bibliography'
```

The error doesn't go away when I re-run the workflow.

`_pages/publications.md` is shown as below:
```
---
layout: page
permalink: /publications/
title: publications
description: 
years: [2021, 2020, 2019]
nav: true
---

<div class="publications">

{% for y in page.years %}
  <h2 class="year">{{y}}</h2>
  {% bibliography -f papers -q @*[year={{y}}]* %}
{% endfor %}

</div>
```

**Expected behavior**
The page can be built without errors.

**System (please complete the following information):**
 - OS: iOS
 - Browser (and its version): chrome

**Comment by sarsid** [comment]
> Finally, in the Settings of your repository, in the Pages section, set the branch to gh-pages (NOT to master). For more details, see Configuring a publishing source for your GitHub Pages site.

This step (from automatic deployment instructions) fixed this exact error for me.

**Comment by XinhuiLi** [comment]
That did the trick!! Thank you so much @sarsid

**Comment by vanshaj18** [comment]
setting source to gh-pages also does the trick for the build error **"Liquid Exception: Liquid syntax error (line 5): Unknown tag 'twitter' in /github/workspace/_posts/2020-09-28-twitter.md"**

OS-ubuntu 20.04
browser- brave

**Comment by ewingard** [comment]
Hi, I'm also having this error now but I have my source set to deploy in github-pages?

**Comment by AzharSindhi** [comment]
this worked for me: https://github.com/alshedivat/al-folio/issues/1398
