### ISSUE TITLE
pdf not loading

### ISSUE THREAD

**Issue by cnut1648** [alshedivat/al-folio#534]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**

Hi, I have a page in the `_posts` that looks like this
```
---
layout: page
title: "A Title"
categories:
 - cat1
 - cat2
nav: true
permalink: /files/1.pdf
---
```
and I have put a `1.pdf` in the `files` folder. However when I open that post, although the link indeed is redirected to the `xxx/files/1.pdf`, I receive the error 
```
Failed to load PDF document.
```

![image](https://user-images.githubusercontent.com/37067883/150265625-6a41eb37-9a88-4bcb-b290-295e58801f91.png)

I'm wondering what might cause such issue. I double checked that I can open the pdf just fine using local machine; and I also think my syntax is correct: I tried to do something similar for the CV and it was fine; and I checked that the permission is `777` (not sure if this is important).
Thanks!!!

**System (please complete the following information):**
 - OS: manjaro
 - Browser (and its version) Chromium 96.0.4664.110 Arch Linux
 - Jekyll version 4.2.1
- Ruby version ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]

**Comment by alshedivat** [comment]
I'm not sure if the way you are trying to link a PDF is standard for Jekyll. I'm getting the same error and the following message in the console during the local build:
```
Conflict: The following destination is shared by multiple files.
The written file may end up with unexpected contents.
/Users/maruan/Documents/dev/al-folio/master/_site/assets/pdf/example_pdf.pdf
 - /Users/maruan/Documents/dev/al-folio/master/assets/pdf/example_pdf.pdf
 - /Users/maruan/Documents/dev/al-folio/master/_posts/2022-01-15-pdf.md
```
what happens is that Jekyll generates HTML blog page that overrides your original PDF. all the generated files are located under `_site/` folder. you can check this by looking at `_site/files/1.pdf` in your case. I don't think you can redirect a blog post page to a PDF file via `permalink`. one way to go about this is add `redirect` field to the blog post header and add some custom logic to [`blog/index.html`](https://github.com/alshedivat/al-folio/blob/master/blog/index.html) that handles it.

supporting blog posts that redirect users to arbitrary pages (including PDFs) would be a nice feature. it would be awesome if you could send a PR!

**Comment by cnut1648** [comment]
Thanks!! I created a PR #550 for this!!
