### ISSUE TITLE
Project page on mobile devices 

### ISSUE THREAD

**Issue by mpmdean** [alshedivat/al-folio#55]
The Project page does not display very well on mobile devices.

Can the images be made to shrink uniformly?
![079C7DCD-F6CF-4EF5-B3F0-B1234F6096C2](https://user-images.githubusercontent.com/699991/64107690-62934180-cd7b-11e9-8503-9f96ff3ba752.png)

**Comment by mpmdean** [comment]
Just bouncing this issue back

**Comment by alshedivat** [comment]
Good point. I plan to upgrade the theme styles and move away from custom CSS to Bootstrap, which would be mobile-friendly (here's [an example](http://platanios.org/projects/), where al-folio styles were converted into Material Bootstrap).

This may not happen until the end of this year though. (I could definitely use some help here, so contributions are very welcome.)

**Comment by mpmdean** [comment]
Thanks. That solution would be great.  I’m a bit out of my depth to change it myself.

**Comment by mpmdean** [comment]
Happy New Year @alshedivat !

I'm hoping that you might be able to devote some time to upgrade the CSS to Bootstrap? I checked the reference site that you cited which indeed looks good. I'm not in a good position to help myself here as I'm not familiar with either system.

**Comment by mpmdean** [comment]
Hi @alshedivat I'm just bouncing this back in the hope (maybe not expectation :)) that you're less busy.

**Comment by alshedivat** [comment]
@mpmdean, it's on my todo list... I wish I had more time! Definitely plan to move to Bootstrap sometime this year (likely in the 2nd half). If the repo hits 1k+ stars sooner, it'd make me more motivated :)

**Comment by mpmdean** [comment]
Sounds good!

**Comment by alshedivat** [comment]
A preview of al-folio with responsive styles is available in the `dev` branch now and will be available in master starting al-folio v0.3. Closing this issue.

**Comment by mpmdean** [comment]
Thanks @alshedivat ! This is very much appreciated. The dev site builds and looks great.
