### ISSUE TITLE
"No news so far" message not showing up when news directory is empty

### ISSUE THREAD

**Issue by benjaminh** [alshedivat/al-folio#556]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
The news section within about page should display `No news so far…` if there are no news to show up (according to `_includes/news.html` file). Yet, if the `_news` directory is empty or has been removed, the message is not showing up.

I fixed the issue by replacing the condition `{% if site.news %}` by `{% if site.news != blank %}` and I was wondering if this is a real bug or maybe due to the Jekyll/Ruby version ?

**To Reproduce**
1. Remove the content in `_news` directory
2. Go to the `about` page
3. Scroll down to the news section

**Expected behavior**
The message `No news so far…` should be displayed as stated in `_includes/news.html` (line 23).

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser (and its version): Firefox 96.0
 - Jekyll version: 4.2.1
- Ruby version: 3.1.0

**Comment by alshedivat** [comment]
thanks for reporting this. looks like it's a bug.
