### ISSUE TITLE
Some problems with #386

### ISSUE THREAD

**Issue by rohandebsarkar** [alshedivat/al-folio#565]
1. Some Unicode characters are more than one character, for example: ⚛️. So the `site.icon.size == 1` does not work for those icons.
https://github.com/alshedivat/al-folio/blob/07a2e0577e406cd880c3d2a7a61f1f0ef7b6577f/_includes/head.html#L17-L19
2. There is a typo: it should be `prepend` instead of `prepent`.
https://github.com/alshedivat/al-folio/blob/07a2e0577e406cd880c3d2a7a61f1f0ef7b6577f/_includes/head.html#L20

**Comment by alshedivat** [comment]
thanks for raising the issue! should be fixed now in 53eef90be219b7f24cf0bd3c28913371aab89c40.
