### ISSUE TITLE
Deploy to username.github.io

### ISSUE THREAD

**Issue by d-alex-hughes** [alshedivat/al-folio#6]
As you've built this currently, the `./bin/deploy` deploys to a `gh-page` branch on a user's project repo. But, since the (really handsome!) theme you've built is directed toward academic users, I'm not sure this is really meeting the use case -- single users can only host on their `master` branch, per the [documentation](https://help.github.com/articles/user-organization-and-project-pages/). 

I had thought about switching default branches? Perhaps making a `source` branch the default that includes all the `_site` and `_pages` and `_config.yml` etc. content and a `master` branch that includes only the resulting files and structure within `_site`? But then, I couldn't get it deploying. 

So, the issue, probably labeled an enhancement, is - 

* **Can a secondary deploy script be written that builds and deploys toward a user who has to host at a `username.github.io` site?**

**Comment by alshedivat** [comment]
Good point. I personally don't use GitHub pages to host my own homepage, so never thought about that (also it makes more sense for me to keep the `al-folio` demo page as a project). I will fix this in the next update (or feel free to open a PR that improves the `deploy` script and I will be happy to merge it).

**Comment by andreasvlachos** [comment]
Thanks for the good work in this, great template! Just to say that it would great to have the option to have it deployed on username.github.io. I got it working without the deploy script, but this meant loosing the capability of jekyll-scholar. Thanks again!

**Comment by d-alex-hughes** [comment]
I wound up writing a little patch for my specific issue. In essence, I cloned the repo, and then built a parallel repo that was for serving the website on a username.github.io site. After building the jekyll site, inside the base repo, I copy over to the serving repo, and push. 

So, the tree is something like: 
```
   | - username.github.io
    |- assets
    |- bin
    |- blog
   | - al-folio
    |- _bibliography
    |- _bin
    |- ... 
```

And the serve shell script is: 

```
#!/usr/bin/env sh

echo "starting to build site" 

# build site files in website 
bundle exec jekyll build
git add -A
git commit -m 'updating site'
git push origin master

# copy files into serving site folder
cp -r _site/* ../username.github.io

# move to serving folder 
cd ../username.github.io
git add -A
git commit -m 'updating site'
git push origin master

echo "finished building site" 
```

I didn't want to issue a pull request for this, because it is _kind_ of far outside the use case that you've built toward.

**Comment by andreasvlachos** [comment]
Hi D. Alex,

Thanks for sharing! I will give it a go next time I update my website!

Cheers,
Andreas

**Comment by nadnaps** [comment]
Hi everyone, 

I have an additional issue along the same lines. When i run the server locally, everything seems fine as you can see in the screenshot below.
<img width="1238" alt="local" src="https://user-images.githubusercontent.com/5851367/30103602-6d2409c8-92f3-11e7-9d09-07ffc3e01ff1.png">


However, when i host it onto github, the layout changes (see screenshot below) . I am guessing its something very trivial which i am unable to figure out. Any help here ?
<img width="1233" alt="github" src="https://user-images.githubusercontent.com/5851367/30103618-77ba2b88-92f3-11e7-9820-76132da6e79b.png">

**Comment by alshedivat** [comment]
The deploy script now has `--user` flag that makes it deploy to `master` and keep the source code in `source`. Alternatively, you can specify explicitly source and deploy branches using `--source` and `--deploy` flags.

@nadnaps make sure `url` and `baseurl` field in `_config.yml` are correctly specified; `url` should point to `<your-username>.github.io` and `baseurl` should typically be empty.

**Comment by timothyhibbard** [comment]
Hi. I updatedthe _config.yml with my url and left the baseurl empty as directed. and the about page runs beautifully, but the other pages, "publications" "projects" and "teaching" are only showing html, just like the about page did before I made the baseurl empty. Possible solution?

Thanks! I'm sure it's something simple.
<img width="1013" alt="projects" src="https://user-images.githubusercontent.com/32397200/31057491-b737c8de-a6b1-11e7-94b4-ef67408e338c.png">

**Comment by alshedivat** [comment]
@timothyhibbard Interesting, haven't seen this bug before. What happens if you leave `url` blank?

Basically, the paths of CSS and JS resources get messed up. In your case, it looks like the url gets duplicated for some mysterious reason (i.e., the path your page tries to access CSS and JS has the following form: `http://<url>/<url>/<path-to-the-resource>`). This might be due to using a custom domain with GitHub pages (never tried that myself). For you reference, the line that generates the loading path for `main.css` is [here](https://github.com/alshedivat/al-folio/blob/master/_includes/head.html#L11) (for other resources, check out `_includes/head.html` and `_includes/hemline.html`).

If you figure out what causes the problem, please do let me know, and I'll update the README.

**Comment by timothyhibbard** [comment]
That worked! I just went back into the _config.yml file and made the url to blank as well, and that cleared it all up! Thank you so much!

**Comment by shivampotdar** [comment]
Hey! I certainly feel @d-alex-hughes script is very useful, it does work very easily even for custom domain, given that you have CNAME in the username.github.io repo. Also please note that in this case, both url and base_url in_config.yml should be empty to render the themes correctly even if you have custom domain.
Thanks Alex :)
