### ISSUE TITLE
Github action cannot build because "Unknown tag 'bibliography'"

### ISSUE THREAD

**Issue by hminle** [alshedivat/al-folio#602]
Hi team,

**Describe the bug**
When I run the repo locally, it is fine. But when I create my own repo and push the code. The Github action cannot build the code.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/16201681/158301420-aeef4a3a-4636-4e04-8819-9e0b5002c36f.png">

Do you guys have any idea?

Thanks

**Comment by fedebotu** [comment]
I managed to get it working from this answer https://github.com/alshedivat/al-folio/issues/529

(I get another issue if I want to modify the page after the first deployment, but this time it seems to be a Github problem)

**Comment by hminle** [comment]
oh thank, I got it
