### ISSUE TITLE
Cannot (re)Deploy Page: request failed with status code 400

### ISSUE THREAD

**Issue by fedebotu** [alshedivat/al-folio#606]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
After the first successful commit and deployment, I would like to modify the website. However, on the newer deployments this happens:

> {"message":"Deployment request failed for fdfafa4756e1fda18fb8c6dc80218065fc91b490 due to in progress deployment. Please cancel 33f692b0aac0e6da4aa66120ad5e61be425dd958 first or wait for it to complete.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}
> Error: Error: Request failed with status code 400

33f692b0aac0e6da4aa66120ad5e61be425dd958 refers to the previous run. 
You may find more details on the run [here](https://github.com/fedebotu/fedebotu.github.io/runs/5584967078?check_suite_focus=true). However, the previous run(s) have been completed already. Even deleting them does not change the issue: it looks like Github considers that run still running.

**To Reproduce**
1. Deploy the page the first time
2. Edit your page and push modifications (note: I am manually re-deploying the website with `$ ./bin/deploy`
3. The error should appear 

**Additional context**
This problem may be related to Github itself as [this very recent Stackoverflow post suggests](https://stackoverflow.com/questions/71508559/400error-for-github-page-during-deployment) 

Thanks in advance for your help 😄

**Comment by alshedivat** [comment]
thanks for reporting this! looks like a github actions issue. glad you were able to resolve it. closing the issue.
