### ISSUE TITLE
Adding GA4-Google Analytics to the site

### ISSUE THREAD

**Issue by tirtharajdash** [alshedivat/al-folio#613]
Google recently launched [GA4 analytics](https://support.google.com/analytics/answer/9304153?hl=en). While the present **al-folio** version supports Google analytics, a simple change in analytics.html activates GA4 analytics too.

In the **_config.yml** file, add the following line at a convenient place:

`ga4_analytics: G-XXXXXXXXXX    #This is your GA4 measurement ID
`

Now, go to **_includes/scripts/analytics.html** and add the following (maybe just below the current gtag.js:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ site.ga4_analytics }}"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '{{ site.ga4_analytics }}');
  </script>
```

Then, commit and push. Done.

**Comment by rohandebsarkar** [comment]
Seems like GA4 analytics use the same scripts as previous Google Analytics. In that case, I don't think we need to make any more changes. Just adding a note in the `_config.yml` and probably changing the ID to `G-XXXXXXXXXX` will make thing clear.

Please reach out if I am missing anything.

**Comment by rohandebsarkar** [comment]
Created PR #727.

It would be helpful if you or someone else could verify, this is working or not. And probably give any suggestions if needed.
