### ISSUE TITLE
Fail to deploy automatically

### ISSUE THREAD

**Issue by JeffreyYH** [alshedivat/al-folio#630]
Hi when I commit some changed to the master branch. It fails to deploy automatically. I think I followed the procedures in _To enable automatic deployment_ instructions. But each time I push, it will emails me `Run failed at startup: Deploy - master `. So I have to deploy manually but the `./bin/deploy ` script seems to be deleting some files.

Thank you!

**Comment by alshedivat** [comment]
> I think I followed the procedures <...>

looking at your repo, doesn't look like you followed all the steps exactly. it's impossible to diagnose the issue from the provided brief description, so I'm closing it.

I recommend trying to follow all the steps provided in the readme as is before applying customizations. if still no luck, feel free to open a new issue, but please make sure to provide enough detail and use the bug report template. thanks.
