### ISSUE TITLE
the "gh-pages" brach cannot be automatically synced

### ISSUE THREAD

**Issue by charleslipku** [alshedivat/al-folio#654]
I follow the new instructions to change the "master" to "source", and I push all the changes to the "source" branch, but the "gh-pages" brach cannot be automatically synced. @alshedivat

**Comment by focus85** [comment]
same here worked fine first time around with manual deploy ( ./bin/deploy --user) and after that its not working

**Comment by rohandebsarkar** [comment]
I don't think the `master` branch needs to be renamed to `source` anymore.

**Comment by rohandebsarkar** [comment]
> I don't think the `master` branch needs to be renamed to `source` anymore.

Though, I don't think that should cause any problem. Can you post the complete log?

**Comment by rohandebsarkar** [comment]
@RochanaChaturvedi, can you post the logs?

I don't think the automatic deploy scripts support `source` branch. The branch must be named either `main` or `master`. If everything is right, GitHub Pages will generate the site and deploy it to `gh-pages` branch.

**Comment by RochanaChaturvedi** [comment]
This issue doesn't appear the first time I deploy. Thereafter, the deploy script deletes the current master branch and pushes source to master (see logs below). Any recent changes committed to master would therefore be lost when we run the script.
$bin/deploy --user
Deploying...
Source branch: source
Deploy branch: master
Do you want to proceed? [y/N] y
Deleted branch master (was aec08bf).
Switched to a new branch 'master'

Therefore, checking out the source branch and committing changes to source fixed this issue for me.
