### ISSUE TITLE
Cannot install on Mac Catalina (10.15.2)

### ISSUE THREAD

**Issue by jermp** [alshedivat/al-folio#698]
Hi,
I tried the latest release (42abefc3f1f1aa52204facecb97b661d9f05f943)
and I can run `bundle install` correctly.
But then jekyll won't serve. See below.

Any hints on this? Thank you!

    ➜  al-folio git:(42abefc) bundle exec jekyll serve                             
    To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
    bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
    Traceback (most recent call last):
	    31: from /usr/bin/bundle:23:in `<main>'
	    30: from /usr/bin/bundle:23:in `load'
	    29: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/exe/bundle:36:in `<top (required)>'
	    28: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	    27: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/exe/bundle:48:in `block in <top (required)>'
	    26: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:25:in `start'
	    25: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	    24: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:31:in `dispatch'
	    23: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	    22: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	    21: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	    20: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:483:in `exec'
	    19: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:23:in `run'
	    18: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
	    17: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `load'
	    16: from /usr/local/bin/jekyll:23:in `<top (required)>'
	    15: from /usr/local/bin/jekyll:23:in `load'
	    14: from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.2.2/exe/jekyll:11:in `<top (required)>'
	    13: from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	    12: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler.rb:187:in `require'
	    11: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:44:in `require'
	    10: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:44:in `each'
	     9: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:55:in `block in require'
	     8: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:55:in `each'
	     7: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	     6: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:60:in `require'
	     5: from /Library/Ruby/Gems/2.6.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:4:in `<top (required)>'
	     4: from /Library/Ruby/Gems/2.6.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:4:in `require'
	     3: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	     2: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	     1: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/extension.rb:7:in `<top (required)>'
    /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/extension.rb:7:in `require_relative': dlopen(/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle, 0x0009): could not use '/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle' because it is not a compatible arch - /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle (LoadError)
	    32: from /usr/bin/bundle:23:in `<main>'
	    31: from /usr/bin/bundle:23:in `load'
	    30: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/exe/bundle:36:in `<top (required)>'
	    29: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	    28: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/exe/bundle:48:in `block in <top (required)>'
	    27: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:25:in `start'
	    26: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	    25: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:31:in `dispatch'
	    24: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	    23: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	    22: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	    21: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli.rb:483:in `exec'
	    20: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:23:in `run'
	    19: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
	    18: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `load'
	    17: from /usr/local/bin/jekyll:23:in `<top (required)>'
	    16: from /usr/local/bin/jekyll:23:in `load'
	    15: from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.2.2/exe/jekyll:11:in `<top (required)>'
	    14: from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	    13: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler.rb:187:in `require'
	    12: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:44:in `require'
	    11: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:44:in `each'
	    10: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:55:in `block in require'
	     9: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:55:in `each'
	     8: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	     7: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.15/lib/bundler/runtime.rb:60:in `require'
	     6: from /Library/Ruby/Gems/2.6.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:4:in `<top (required)>'
	     5: from /Library/Ruby/Gems/2.6.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:4:in `require'
	     4: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	     3: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	     2: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	     1: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
    /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.6-arm64-darwin/lib/nokogiri/extension.rb:30:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)

**Comment by rohandebsarkar** [comment]
See #338.

**Comment by jermp** [comment]
Thank you,
I can confirm that with commit on Mac OS Catalina (10.15.2)
`bundle install` works just fine but before running `bundle exec jekyll serve`, the following two lines should be removed from the file
`Gemfile.lock`:

      nokogiri (1.13.6-arm64-darwin)
        racc (~> 1.4)
