### ISSUE TITLE
Project Images

### ISSUE THREAD

**Issue by timothyhibbard** [alshedivat/al-folio#7]
Hi,

Thanks for the great help on my last issue!

I notice that this issue is going on in the demo as well, so it's not just me. The problem is that the images used on the projects page only show the top left of the images rather than the entire image. For example, the images in the screen shot should be a gavel on the left, and the Facebook logo on the right, but the left image is getting cut off, and the Facebook logo isn't even visible.
<img width="730" alt="ss" src="https://user-images.githubusercontent.com/32397200/31798547-5466faa4-b502-11e7-838b-a7fa2c5be11a.png">

And in the demo below, image 12, the image shown in the on the top row, left column, should have a cup in the image.
<img width="738" alt="ss2" src="https://user-images.githubusercontent.com/32397200/31798618-b62872ea-b502-11e7-9e06-8507f4107b80.png">

How do I fix this so that the entire image is displayed?

Thank you so much in advance!

Best,
Tim

**Comment by mayank26saxena** [comment]
Facing the same issue.

**Comment by alvaropp** [comment]
You can change the thumbnail behaviour inside `/_sass/_projects.scss`, inside the `img` section.

By default, it crops a section of the image, but you can change this to show the full image, scale it to any size, or basically do anything you want!
