### ISSUE TITLE
Blog archive / category tag list

### ISSUE THREAD

**Issue by smashmath** [alshedivat/al-folio#707]
**Is your feature request related to a problem? Please describe.**
With so many blog posts (currently 8 pages with 5 per page), it's become very difficult for casual readers to sort through and find posts which would be relevant to them. The newer tags/categories feature helps this a bit, but it's not so helpful if the latest post in a category is 4 pages in.
To fix this, initially, I converted all of my posts to projects. That way, every post on my blog is easily accessible, and readers can browse through all the different categories. The problem with that is that it's nigh impossible to tell when a new post is added, since the projects are sorted by importance, not date. So to fix that, I copied all the projects to blog posts as well (changing every file name and header...). Allowing users to see the newest posts on the blog, and all the posts in projects. Basically letting the projects page function as a blog archive. However, this means I need two copies of my posts with slightly different headers. Meaning, to make a new post I need to make two files, and if I want to change any of them, I have to change both files, which is inconvenient.

**Describe the solution you'd like**
The simplest/most manageable solution I can think of might be to add a list of categories/tags which is always visible somewhere on the blog page so that users can click on a category even if the latest post for it was a while ago. 

**Describe alternatives you've considered**
Having a blog archive which lists every blog post on one page (sorted by categories rather than date) would be a more straightforward and helpful (but harder to implement) solution. But, since the projects page can already do this pretty well, just a copy of the projects page which is slightly modified to read from _posts rather than projects might not be too much more difficult?

Alternatively, an option to automatically put blog posts to projects (or vice versa) would be nice.  Or any changes to make blog posts/projects more compatible/interchangeable would go a long way. Such as removing dates from the url when they're in the file name, having category/categories function more identically, etc.

Also, a search bar and last page option (such as 1 2 3 4 ... 8) for example, would be helpful too (but now I'm just putting a wishlist of features...)

Thank you!

**Comment by rohandebsarkar** [comment]
PR #734.
