### ISSUE TITLE
Circular/Elliptical profile picture

### ISSUE THREAD

**Issue by vatsal-kr** [alshedivat/al-folio#721]
Is there any way to change the shape of the profile picture displayed? I would like it to be a circle/ellipse.

**Comment by rohandebsarkar** [comment]
#728 solved this.

Pull the latest commit. Update the `image_circular` variable in `_pages/about.md` to `true`.

https://github.com/alshedivat/al-folio/blob/bcd43a18fe67da84193fb6df21b0f27f993fe5f8/_pages/about.md?plain=1#L10

**Comment by alpsencer** [comment]
> #728 solved this.
> 
> Pull the latest commit. Update the `image_circular` variable in `_pages/about.md` to `true`.
> 
> https://github.com/alshedivat/al-folio/blob/bcd43a18fe67da84193fb6df21b0f27f993fe5f8/_pages/about.md?plain=1#L10

Why did you used the word "cicular "in the code instead of "circular"? Is this a typo? @rohandebsarkar

**Comment by rohandebsarkar** [comment]
@alpsencer It's a typo. Will fix it in a future PR.

**Comment by alpsencer** [comment]
> @alpsencer It's a typo. Will fix it in a future PR.

I have already created a pull request.

**Comment by rohandebsarkar** [comment]
@alpsencer, I did not notice your PR, if you can reopen it, I will merge.

**Comment by alpsencer** [comment]
> @alpsencer, I did not notice your PR, if you can reopen it, I will merge.

Ok. I reopened. https://github.com/alshedivat/al-folio/pull/822

**Comment by alpsencer** [comment]
> @alpsencer, I did not notice your PR, if you can reopen it, I will merge.

I put parenthesis on the previous PR's name, then I think it crashed the deployment. I fixed the name. I did not know that.
