### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by petrasvestartas** [alshedivat/al-folio#737]
**Describe the bug**
Deployment is correct but the page is completely different from what I see locally.

**To Reproduce**
I forked the currecnt github project in a private github repository and changed the`  url: https://petrasvestartas.github.io`
Gh pages seems to have a correct link to gh-pages branch.

**Expected behavior**

**System (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Jekyll version Latest
- Ruby version  Latest

![image](https://user-images.githubusercontent.com/18013985/176745864-b6a10a82-bb75-4f7a-a911-7d4a82cf9d99.png)
![image](https://user-images.githubusercontent.com/18013985/176747385-882edb4d-a893-44f0-83fd-4be7fa29c903.png)
![image](https://user-images.githubusercontent.com/18013985/176743776-7e25552b-3271-46bf-9f6d-98180f167781.png)

# I changed the master to gh-pages and I get this preview:

![image](https://user-images.githubusercontent.com/18013985/176744934-f3197535-a5b4-45b5-8411-57050ab66dcf.png)

# While locally:
![image](https://user-images.githubusercontent.com/18013985/176745012-e986f621-c71e-4b8f-9601-b6409b76a02b.png)

# I push changes to source branch:
![image](https://user-images.githubusercontent.com/18013985/176745244-d7d8df84-9b75-413d-82e1-9c3596514f6c.png)

**Comment by pourmand1376** [comment]
As far as I know, you shouldn't push your changes to the `source` branch. You should do them on `master` branch.

**Comment by petrasvestartas** [comment]
@pourmand1376 

If I push to master, I get this error in Actions:
![image](https://user-images.githubusercontent.com/18013985/176748731-11981d98-60fd-41c2-8f58-558ab0b40fcd.png)

**Comment by petrasvestartas** [comment]
I give up.

**Comment by rohandebsarkar** [comment]
I couldn't find your `master` branch.

Follow the steps in README. Do not rename `master` branch, enable github actions. Push changes to master branch. You should be good to go.

**Comment by rohandebsarkar** [comment]
It seems the problem is because you renamed `master` branch to `source`.

From your [logs](https://github.com/petrasvestartas/petrasvestartas.github.io/runs/7146383974?check_suite_focus=true#step%3A7%3A1=): ` yes | bash bin/deploy --verbose  --src master --deploy gh-pages`

It will take the Jekyll code from `master` branch, compile it and finally push it to `gh-pages` branch.
