### ISSUE TITLE
Can you enable tracking IP address of visitors

### ISSUE THREAD

**Issue by bhatiasiddharth** [alshedivat/al-folio#74]
Is there a way to easily integrate ip address of visitors with the code? Using mixpanel or something?
Thanks!

**Comment by alshedivat** [comment]
Currently, the theme supports google analytics (see [`_config.yml`](https://github.com/alshedivat/al-folio/blob/master/_config.yml#L42)). I'm not sure if that allows tracking that you are looking for.
