### ISSUE TITLE
Support equally contributed sign ^* on publications. 

### ISSUE THREAD

**Issue by Zhendong-Wang** [alshedivat/al-folio#749]
Hi, 

Thanks for providing this awesome persnal page template. I am wondering whether it is possble to add equally contributed sign ^* on publications, when it is needed to be shown on the list of authors. For example, Name1$^{\*}$, Name2$^{\*},$ .... 

Thanks!

**Comment by gzwongkk** [comment]
The asterisks should be added to the corresponding papers' author list. For example, in papers.bib,
`author={Einstein, A. and Podolsky, B. and Rosen, N.}` => `author={Einstein*, A. and Podolsky*, B. and Rosen, N.}`

For the rest regarding the identification of authors' last names, I have put it in #770 for your reference.

**Comment by CryoSky** [comment]
There is another question: I have a paper that I was one of the co-first authors. If I add a star sign on the paper.bib, then the underscore line cannot recognize my name because in the _config.yml I didn't put a star sign behind my last name. How to solve this problem then?
