### ISSUE TITLE
how to run deploy in windows os?

### ISSUE THREAD

**Issue by lwozny** [alshedivat/al-folio#75]
Hi. Thanks for this great theme! It works perfectly on my localhost. I just dont know how to run your deploy script on windows os . Tried deploy.sh but it didnt work. Sorry, I am completly new to github and ruby. Can you please help with that?

**Comment by mpmdean** [comment]
I would suggest trying using gitbash
https://codebase.custservhq.com/articles/getting-started/git-on-windows
But I'm not a windows users so I cannot promise this will work

**Comment by alshedivat** [comment]
I'm not a Windows user either, but as long as you can [install Linux Bash on Windows](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/), you should be able to run `deploy.sh`.
