### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by bttgcm** [alshedivat/al-folio#768]
Dear everyone,

I have forked the site and went through the configuration as explained in the " Deployment For project pages".
I have set the Actions as "Allow all actions and reusable workflows".
but
I have noticed some actions cannot be completed and give the following error:

Run docker/login-action@v1
  with:
    ecr: auto
    logout: true
Error: Username and password required

I am not clear if I have to create an access token from Docker and change configuration somewhere.

Thank you

**Comment by rohandebsarkar** [comment]
Sorry for the inconvenience. This bug has been identified. It will be fixed by the PR #767.

**Note:** Though it is showing the error in the `Docker Image CI` script, it should not affect the `deploy` script, and therefore you should not have any problem in deploying the site.

**Comment by bttgcm** [comment]
You are right in the "Deploy"  there is no error but the page does not update (not sure if due to Docker CI actions not going through).

**Comment by pourmand1376** [comment]
PR is now merged. You can update your repo. But, I don't think that not updating the page is related to `Docker CI`.

**Comment by rohandebsarkar** [comment]
fixed in #767.
