### ISSUE TITLE
about header

### ISSUE THREAD

**Issue by aditisgh** [alshedivat/al-folio#77]
Hi,
For all the other pages, the title changes the page header but the title for the about page is my name. Hence, I cannot find a way of changing the "about" header. Any leads would be appreciated.
Thanks

**Comment by alshedivat** [comment]
This is set in the [`_includes/head.html`](https://github.com/alshedivat/al-folio/blob/master/_includes/head.html#L6). About is the root page, and by default, the page name is not appended to the title of the root page. Feel free to change that if necessary.
