### ISSUE TITLE
Changing the location of the news listed in about page

### ISSUE THREAD

**Issue by kaanaksit** [alshedivat/al-folio#771]
I am a happy user of your work. Thank you very much for releasing it online and allowing others to enjoy the ease of usage of this project on their web pages.

I am looking for a solution to change the location of the news section on the about page. I want to insert a news section between sections in `about.md` (e.g., `# section 0`, then news than `# section1`). Is there a way to make this happen?

Thanks!

**Comment by george-gca** [comment]
I believe this is pretty straightforward. Just create a copy of a page (like repositories) and start from there.
