### ISSUE TITLE
Cannot recognize my name when equal contribution

### ISSUE THREAD

**Issue by CryoSky** [alshedivat/al-folio#808]
Hi, I have a quick question. I have a paper that I was one of the co-first authors. If I add a star sign on my name in the paper.bib, then the underscore line cannot recognize my name because in the _config.yml I didn't put a star sign behind my last name. Does anyone know how to solve this problem then? Many thanks for your reply!

**Comment by avrohr** [comment]
This seems to be fixed with #770.

**Comment by gzwongkk** [comment]
#770 should have fixed the problem.

In the bib.html file, the following line
`{%- assign author_last_name = author.last | remove: "¶" | remove: "&" | remove: "*" | remove: "†" | remove: "^" -%}`
supports five special characters to indicate different authorship type. Its meaning is literal, i.e., remove these characters from the current author's last name. 

Let me know if the issue persists.

**Comment by CryoSky** [comment]
> #770 should have fixed the problem.
> 
> In the bib.html file, the following line
> `{%- assign author_last_name = author.last | remove: "¶" | remove: "&" | remove: "*" | remove: "†" | remove: "^" -%}`
> supports five special characters to indicate different authorship type. Its meaning is literal, i.e., remove these characters from the current author's last name. 
> 
> Let me know if the issue persists.

You are right. I have figured it out. Thank you very much!

**Comment by LarsDoorenbos** [comment]
With this I can indeed add star signs to the names of co-authors of a publication, but how do I add a footnote saying that the star stands for "equal contribution"?

**Comment by toggled** [comment]
@LarsDoorenbos You can add something like ` note={* = equal contribution} ` in papers.bib file inside the relevant BibTeX entry
