### ISSUE TITLE
White-space issue in layout if short "about" content

### ISSUE THREAD

**Issue by mjuarezm** [alshedivat/al-folio#810]
**Acknowledge the following**
- [ x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [ x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x ] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
When there is not much text in the about page content, the News section does not wrap around the profile picture float. That creates a whitespace between the content and the news page. I do not think this is intended.

**To Reproduce**
1. Use an empty about content.

**Expected behavior**
I expect sections following the 'about' content (e.g., news and selected publications) to wrap around the float.

**Screenshots**
Screenshot attached showing the whitespace in red.

**System (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Jekyll version: 3.8.7
- Ruby version: 2.6.5
![layout_issue](https://user-images.githubusercontent.com/2465450/183433236-2a717e49-d284-4f8d-80d6-783cce46370d.png)

**Comment by cmoralesmx** [comment]
I cannot reproduce the issue. This may have been fixed already as the current version running in docker produces the expected behavior.
![image](https://user-images.githubusercontent.com/1790200/194726793-6174334c-50da-4aca-8744-06fdb49c1fa7.png)
