### ISSUE TITLE
Project not building with "horizontal: true" in projects.md (see #677)

### ISSUE THREAD

**Issue by maurice-schleussinger** [alshedivat/al-folio#814]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
See https://github.com/alshedivat/al-folio/issues/677. Building from the repository and only changing `horizontal: true` in `projects.md` results in the project not building anymore (including deployment with Github Pages). 

**To Reproduce**
1. Set horizontal: true in projects.md
2. Build the project
3. See error

**Expected behavior**
Project should build without error.

**System (please complete the following information):**
Irrelevant (happens with Github Actions as well).

The fix described in https://github.com/alshedivat/al-folio/issues/677 involves removing 

```
{% responsive_image_block %}
            path: {{ project.img }}
            alt: "project thumbnail"
          {% endresponsive_image_block %}
```

from `projects_horizontal.html` (if I understood it correctly) and indeed fixes the immediate problem, but this results in no images being displayed in the project overview. Can somebody with more knowledge take a look and maybe provide a PR? Thanks!

**Comment by rohandebsarkar** [comment]
This issue should be fixed by commit c142853.
