### ISSUE TITLE
Double slash (...github.io//assets/...) in the url when use deploy

### ISSUE THREAD

**Issue by pranabdas** [alshedivat/al-folio#83]
When I use : `./bin/deploy`, it generating URLs with double slash after `...github.io//...` Can you please help pinpoint the issue? I know it's not a problem with the page loading. Thank you.

**Comment by thePranab** [comment]
Could it be because my base url is empty? 🤔 I have found a workaround by using `build` and manually `git push` _site/ to my GitHub pages.

**Comment by alshedivat** [comment]
Thanks for pointing this out. This might be a tiny bug somewhere in the code that requests assets. I plan to fix such minor bugs in the next release, but does this double slash affect anything now?

**Comment by pranabdas** [comment]
In terms of URL loading, there was no issue. Apparently, browser does not care whether there is single or double slash in the url string. Currently, I am building using `jekyll build` which does not generate double slash. Thank you.
