### ISSUE TITLE
Fetching external posts from medium.com: connection error

### ISSUE THREAD

**Issue by teddyand** [alshedivat/al-folio#834]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by teddyand** [comment]
#  - name: medium.com
#    rss_url: https://medium.com/@al-folio/feed
in _config.yml 
it's ok

**Comment by rohandebsarkar** [comment]
You can just comment out or remove the following lines from `_config.yml`:

https://github.com/alshedivat/al-folio/blob/30e51bc90005f8bf36a4e1d59423531b04b22c30/_config.yml#L120-L122
