### ISSUE TITLE
Writing equations centered on the page

### ISSUE THREAD

**Issue by santoshkumarradha** [alshedivat/al-folio#84]
Hi, Is it possible to center the equations ? 

Tried adding \begin{equations} inside $$ and also tried adding css, but nothing seems to work.

**Comment by pranabdas** [comment]
As a workaround you may use: 
```
<div style="text-align: center">
    <script type='math/tex; mode=display'>
        \lim_{x \rightarrow 0}\frac{\sin x}{x} = 1
    </script>
</div>
```

**Comment by f-t-s** [comment]
This can be changed by replacing 
```
$("script[type='math/tex; mode=display']").replaceWith(   
  function(){  
    var tex = $(this).text();  
    return "<div class=\"equation\">" +  
           katex.renderToString("\\displaystyle "+tex) +  
           "</div>";  
});

to 

```
$("script[type='math/tex; mode=display']").replaceWith(   
  function(){  
    var tex = $(this).text();  
    return "<div class=\"equation\">" +  
           katex.renderToString("\\displaystyle "+tex, {displayMode: true}) +  
           "</div>";  
});

in assets/js/katex.js
