### ISSUE TITLE
[SASS] MD blockquotes introduce one empty line below the quoted-paragraph

### ISSUE THREAD

**Issue by rosustefan** [alshedivat/al-folio#840]
**Acknowledge the following**
- [ x ] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [ x ] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [ x ] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
MD blockquotes introduce one empty line below the quoted-paragraph. When using HTML blockquotes this is not an issue, no empty line below the quoted-paragraph.

**To Reproduce**
1. Go to _posts
2. Create a new blog post
3. Use the MD blockquote ">" on any text
4. Jekyll Serve
5. Open that post in a browser
6. See how that quoted paragraph looks

**Expected behavior**
This behavior is not present when using the HTML "<blockquote></blockquote>" --> no empty line introduced below quoted text. Same behavior should be present when using the MD ">" to quote text.

**Workaround**
1. Edit _sass/_base.scss
2. Find the .post / .post-content / blockquote class
3. Change the padding from _8px_ to _0px 8px_

**Screenshots**
![padding_0px_8px](https://user-images.githubusercontent.com/44987333/186414185-028ad83f-822d-46a2-93ee-2d0221a38097.png)
![padding_8px](https://user-images.githubusercontent.com/44987333/186414194-0f52ab62-fcd4-4fc4-b900-a168d53728bb.png)
![_sass](https://user-images.githubusercontent.com/44987333/186414189-eed5006b-e963-41c2-8e13-2923974b7c1f.png)

**System (please complete the following information):**
- OS: Ubuntu 22.04 LTS (AWS VPS), Ubuntu 20.04 (WSL), Windows 10, Windows 11
- Browser: Google Chrome 104.0.5112.102 (Official Build) (64-bit)
- Jekyll version 4.2.2
- Ruby version 2.7.0p0

**Additional context**

**Comment by rohandebsarkar** [comment]
This feels less of a bug than a design choice. If you notice, there is also the same amount of space before the `blockquote`. So I would rather tag @alshedivat to make the design choice here.
