### ISSUE TITLE
[News][Table] The news titles are not left-aligned when the post uses "inline: false"

### ISSUE THREAD

**Issue by rosustefan** [alshedivat/al-folio#841]
**Acknowledge the following**
- [ x ] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [ x ] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [ x ] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
When the user adds any news post and sets the inline value to false, the news title is centered in the news table, faraway from the news-date. When the inline is true, the news title is left aligned, close to the news-date.

**To Reproduce**
1. Go to _news
2. Create a new announcement_x.md
3. Set inline: false
4. Jekyll Serve
5. Open the website in any browser
6. Observe the news table displayed at the bottom of the About page

**Expected behavior**
The news-title should always be left-aligned, close to the news-date, no matter if inline is true or false.

**Workaround**
The table in the news.html contains these classes:
table class="table table-sm table-borderless"
... and if removing the "table" class, the issue is solved:
table class="table-sm table-borderless"
... with no apparent downside.

**Screenshots**
![table_class_causing_the_issue](https://user-images.githubusercontent.com/44987333/186417664-c9cfaa84-b0aa-4fb2-bf77-83b1144f56ce.png)
![_news_inline_false_table_class_present_for_table](https://user-images.githubusercontent.com/44987333/186417672-0052895a-cc40-4003-85f7-5db2bd4d1133.png)
![_news_inline_false_table_class_removed_from_table](https://user-images.githubusercontent.com/44987333/186417669-4c281da1-bfc2-4444-be60-c24e35608ce4.png)

**System (please complete the following information):**
- OS: Ubuntu 22.04 LTS (AWS VPS), Ubuntu 20.04 (WSL), Windows 10, Windows 11
- Browser: Google Chrome 104.0.5112.102 (Official Build) (64-bit)
- Jekyll version 4.2.2
- Ruby version 2.7.0p0

**Additional context**

**Comment by rohandebsarkar** [comment]
Sorry, but I can not reproduce this. Looks like bootstrap puts `text-aliign: left` on the body element, which is inherited into the table.

![Screenshot from 2022-08-28 08-19-08](https://user-images.githubusercontent.com/50144004/187055339-72be1167-0395-4d10-8925-9c765a863a4e.png)

This also does not reflect in the demo site: https://alshedivat.github.io/al-folio/
