### ISSUE TITLE
Problems with Deployment

### ISSUE THREAD

**Issue by mendezVKI** [alshedivat/al-folio#86]
Hello,

First of all, thank you very much for such a nice template. I have a very naive question ( I started playing with Jekyll today) that has been puzzling me a lot in the last 2 hours :(

I have created my webpage and it works beautifully on local.
Once deployed with ./bin/deploy I get the message 'Deployed successfully!' and I see I have two branches on my repository. Yet, the page is not loaded (I get 404 error). In the Github page I see this error:

 Your site is having problems building: The tag bibliography on line 3 in _pages/publications.md is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.

in the Github page, it says it wants to build the page from the master branch and I can't put it on the gh page brunch.

Do you have any suggestions?

Thank you very much

**Comment by alshedivat** [comment]
For personal webpages, you would want to run `./bin/deploy --user`. See [installation notes](https://github.com/alshedivat/al-folio#installation).

**Comment by mendezVKI** [comment]
Thank you very much for your quick response. I missed this important detail. 
Now it's up and running and I am very happy with it: https://mendezvki.github.io/.

Of course, I left in the footer the link to your page. Please let me know if this is acknowledgement is sufficient or if I should add something else; I am not familiar with Github pages/jekyll and the proper way of crediting these beautiful pieces of work.

Miguel
