### ISSUE TITLE
Enabling the Github template option

### ISSUE THREAD

**Issue by kargaranamir** [alshedivat/al-folio#873]
**Is your feature request related to a problem? Please describe.**
The template option makes it easier for people to deploy their own [page](https://garywoodfine.com/how-to-use-github-repository-templates/).  You can make an existing repository a template, so you and others can generate new repositories with the same directory structure, branches, and files. Forks are used for contributions.

**Describe the solution you'd like**
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by rohandebsarkar** [comment]
We considered this in the past, but the main problems are:
- The fork counters are not updated for people using the template option, thus we can't keep track of the users using this theme.
- And more importantly, The commits are not migrated to the new repository, therefore in future if anyone wants to update the theme from the upstream, it will be difficult.

Said that, @alshedivat has updated the settings to use this repo as a template. But I would still recommend using the fork option in case we fix some bugs or add a new feature, and you would like to update from the upstream.

**Comment by kargaranamir** [comment]
Thank you for your response. It appears that this repo now follows the Template option as well.
