### ISSUE TITLE
Dropdown menu on the Mobile Phone not working

### ISSUE THREAD

**Issue by DoHaiSon** [alshedivat/al-folio#896]
**Describe the bug**
After upgraded from ver 5.0 to 7.0. The dropdown menu on the mobile phone was not working as you can see from the screenshot. Nothing happened when I clicked on the button.

**To Reproduce**
1. Go to: [https://dohaison.github.io/](https://dohaison.github.io/)
2. Click on: The dropdown menu icon on the right side of this page.
3. See error

**System (please complete the following information):**
 - Github Repo source code of my page: [https://github.com/DoHaiSon/dohaison.github.io/tree/source](https://github.com/DoHaiSon/dohaison.github.io/tree/source) 
 - OS: WSL Linux / Android 13
 - Browser (and its version): Chrome
 - Jekyll version: 4.2.2
 - Ruby version: 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

![com android chrome](https://user-images.githubusercontent.com/50046954/191462355-d6b7a9ac-b677-4357-91a0-17ec3260e65b.jpg)

**Comment by rohandebsarkar** [comment]
See #781, and try to fix it. If you are not able to resolve it, leave a comment on that discussion.

**Comment by DoHaiSon** [comment]
> See #781, and try to fix it. If you are not able to resolve it, leave a comment on that discussion.

Thx a lot. It's worked. 
I don't know why but just change sha256 of js to:
`js: "sha256-SyTu6CwrfOhaznYZPoolVw2rxoY7lKYKQvqbtqN93HI="`
