### ISSUE TITLE
font-awesome not showing in local build

### ISSUE THREAD

**Issue by christineymshen** [alshedivat/al-folio#90]
Somehow fa icons are not showing up in my local build. But when I deploy it on GitHub pages, they are shown correctly. I wonder why this happens... 

Here I enclose a screen shot for my local build.

Thanks!

![Screen Shot 2020-06-03 at 20 26 45](https://user-images.githubusercontent.com/28140445/83702562-08116500-a5db-11ea-8038-06c9415214a2.png)

**Comment by alshedivat** [comment]
Thanks for pointing this out. This is a known issue (see #54 for a solution). The problem is resolved in the upcoming `al-folio v0.3` (currently available in the `dev` branch).

**Comment by christineymshen** [comment]
Thanks for your prompt reply!
