### ISSUE TITLE
Light Font on Mobile view

### ISSUE THREAD

**Issue by bhatiasiddharth** [alshedivat/al-folio#91]
Can you please tell how to have a darker font when viewed on mobile? It appears very light as of now. Thanks.

**Comment by BonJovi1** [comment]
Hi @alshedivat 
Thank you for the awesome theme! I'm using an older version of your code, where the the font is really light and not very visible on mobile view. Could you please tell me where exactly did you make the changes in the css files? 
There have been lots of updates to the code, so I would have to make many changes for using the latest version. I would be grateful if you could let me know what exactly to change to fix this. 

Thank you,
Abhinav
