### ISSUE TITLE
Social media integration: Matrix + Mastodon

### ISSUE THREAD

**Issue by MarkWieczorek** [alshedivat/al-folio#918]
There are two social media integrations that are missing for me:

* Mastodon (i.e., open-source twitter....)
* matrix [m] / Element (an open source chat protocol/client).

Would it be possible to add these? And thanks for adding keybase!

**Comment by dxvidmr** [comment]
Yes! You can do that:

Add this in `_includes\social.html`:

```
{% if site.mastodon_username -%}
<a href="https://yourinstance/@{{ site.mastodon_username }}" title="Mastodon"><i class="fab fa-mastodon"></i></a>
{% endif %}
```
And this in `_config.yml` in the `# Social integration` section:
```
mastodon_username: yourusername #without the @
```

Hope that works for you too! (check it in my website: https://dxvidmr.github.io/)

**Comment by alshedivat** [comment]
mastodon was added in #974. not sure about matrix [m] / Element (whoever uses it is welcome to submit a PR).
