### ISSUE TITLE
Allow specifying different images for use with dark and light mode

### ISSUE THREAD

**Issue by MarkWieczorek** [alshedivat/al-folio#930]
I have a black and white image that I placed in the footer. Though the image is fine when displayed using the light theme, it is unreadable when displayed using dark mode.

I have tried the following which changes the image when changing the system theme in macos

```
<picture>
    <source
        srcset="/assets/dark.png"
        media="(prefers-color-scheme: dark)">
    <img align="right" width=280 vspace=25 style="padding-bottom: 10px;" src="/assets/light.png">
</picture>
```
However, this has no effect when clicking on the light/dark button on the al-folio web page.

As a feature request, I would like to be able to specify separate images when using light and dark themes.

**Comment by buerviper** [comment]
I second this wish.

Related: I upload a .svg which is b/w. If I switch to dark mode, I'd like also the colors to automatically reverse. Would that be possible? Alternatively, uploading a dark mode version of the file as suggested in the original comment would of course be a viable workaround.

**Comment by klasmodin** [comment]
I also think this would be a nice feature to have.

**Comment by arashgmn** [comment]
I managed to do this some time ago on a private deployment for`png` and `jpg`. I can take up this task if currently no one is already working on it.

**Comment by Grs257** [comment]
I think there was an error in JS , check it once🙂

**Comment by george-gca** [comment]
I believe no one is still working on this @arashgmn. Help would be much appreciated.

**Comment by arashgmn** [comment]
@george-gca Please check my PR out.

**Comment by DavidKrassnig** [comment]
> I second this wish.
> 
> Related: I upload a .svg which is b/w. If I switch to dark mode, I'd like also the colors to automatically reverse. Would that be possible? Alternatively, uploading a dark mode version of the file as suggested in the original comment would of course be a viable workaround.
> 
> EDIT: wait that seems to be possible; at least the social media icons switch from black to white when yous witch between light and dark mode.

@buerviper  I don't know if you know this by now,  but since nobody has mentioned this in the thread so far, SVGs are automatically affected by dark mode if you use `currentColor` for the SVG's colour value instead of regular black hex code `#000000` in the SVG file (you can search & replace inside the SVG file with any text editor). That's the standard way of handling this afaik

**Comment by DavidKrassnig** [comment]
> Thanks for the advice @DavidKrassnig, but I cannot get it to work. For instance, if I draw a circle with the fill = currentColor ...
> 
> ```
> <svg width="100" height="100">
>   <circle cx="50" cy="50" r="40" fill=currentColor/>
> </svg>
> ```
> 
> ... it changes to black in dark mode (but in bright mode, it show the correct value, I think).

@buerviper Hm, that's weird. It worked/works for [my SVG file](https://github.com/DavidKrassnig/al-folio-crasnicius/blob/main/assets/img/coa-krassnig.svg), which I created in Inkscape and then Search&Replaced the colour values of (you should be able to verify it working [here](https://david.krassnig.de/al-folio-crasnicius/)). Not immediately sure why it doesn't work in your case …

**Comment by buerviper** [comment]
@DavidKrassnig I found the error with the svg: It's the distill layout. If I enter 
```
<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" fill=currentColor/>
</svg>
```
into a normal blog post, it works and changes the color according to the color scheme. If I put it in a distill layout post, it's not using the color scheme and just stays black.

**Comment by PkleinRNA** [comment]
Hi, on something related anyone knows how I can have different profile image loaded when I switch modes (light vs dark)? Thanks so much

**Comment by kastnerp** [comment]
You can do it like this: 

I use an external markdown file like this: 
https://github.com/SustainableUrbanSystemsLab/.github/blob/7891c943cef784500eab053e263eb2d1ff9961fc/profile/README.md?plain=1#L1

Add these css changes: 
https://github.com/SustainableUrbanSystemsLab/SustainableUrbanSystemsLab.github.io/blob/678b012272106bebf5da58b6ecc2e025874af9fd/_sass/_themes.scss#L122

Result: https://sustainableurbansystems.com/

**Comment by george-gca** [comment]
@arashgmn sorry, somehow I missed your PR. Will check it later.
