### ISSUE TITLE
pages build and deploy Workflow error : github-pages 227 | Error:  Liquid syntax error (line 5): Unknown tag 'twitter'

### ISSUE THREAD

**Issue by abhinavbharadwajr** [alshedivat/al-folio#933]
I'm trying to build and customize this Template for my Personal Portfolio. 'deploy' workflow runs without throwing any error, but the workflow to build the page is throwing an error :

`github-pages 227 | Error:  Liquid syntax error (line 5): Unknown tag 'twitter'`

![image](https://user-images.githubusercontent.com/25419079/195014224-a48e77a2-e92f-4d8c-822a-2d2bd1f70509.png)

I did try some workaround as suggested in [jekyll-twitter-plugin](https://github.com/rob-murray/jekyll-twitter-plugin)

What could be the Problem? Can anyone help me?

**Comment by rohandebsarkar** [comment]
I think you are trying to build the GitHub Pages site from the master branch. You must choose the `gh-pages` branch in the GitHub pages settings. See #864.
