### ISSUE TITLE
Project page

### ISSUE THREAD

**Issue by christineymshen** [alshedivat/al-folio#94]
I'm building the project page and have got a few questions.

1. The general layout in my local build is different from the demo website (refer to attached screen caps). There are mainly two differences: 1) project name and descriptions are shown when mouse hover on the picture rather than at the bottom; 2) only part of the images are shown rather than a re-scalled full version. I noted from the other post that the demo website is built from slightly different codes. So I wonder whether the differences I'm currently seeing is also due to that~~?

2. It's weird that somehow for my local build, it's not able to link to imges which are in the assets folder. I got errors for example in project 1 page, saying it cannot find img/6.jpg and img/11.jpg while both are in the folder. Please refer to screen cap.

Many thanks!! 
<img width="782" alt="Screen Shot 2020-06-10 at 18 04 43" src="https://user-images.githubusercontent.com/28140445/84325105-10701f80-ab48-11ea-824c-3e1dbcadc207.png">
<img width="880" alt="Screen Shot 2020-06-10 at 18 26 24" src="https://user-images.githubusercontent.com/28140445/84325112-136b1000-ab48-11ea-9616-95e58a5ef0a2.png">

**Comment by jkmacc-LANL** [comment]
The demo web page is using the `dev` branch.  I liked it too, and it works just fine for me.  Give it a try!

**Comment by christineymshen** [comment]
> The demo web page is using the `dev` branch. I liked it too, and it works just fine for me. Give it a try!

I've been making some customizations here and there since I started working on it... I'm pretty new to this. So I'm a bit concerned that if I switch to `dev` branch version, I might mess things up...

**Comment by jkmacc-LANL** [comment]
I’d done the same thing.  I had to `git rebase <the branch you modified> dev`, and follow the instructions to fix several conflicts.  Git-rebase is always a bit gnarly, but it worked for me.

**Comment by christineymshen** [comment]
> I’d done the same thing. I had to `git rebase <the branch you modified> dev`, and follow the instructions to fix several conflicts. Git-rebase is always a bit gnarly, but it worked for me.

I'm actually wondering how I could adopt later versions of the theme once it's released... definitely should explore Git-rebases sometimes...

**Comment by jkmacc-LANL** [comment]
My thinking is that, once `dev` merges into `master, I can just rebase my modified branch onto `master` whenever there’s an update.  I wonder if I’ll constantly have to re-fix the same merge conflicts, though.  That gets a little above my understanding of git to predict 😁

**Comment by christineymshen** [comment]
@alshedivat I'm trying to decide whether to rebase to the dev branch. But I also like the grey-ish colored text in the current theme set up. I wonder whether there's any quick way to have the current text font if I change to the dev branch? Also I wonder whether you would recommend switching to dev branch now~? Many thanks!!

**Comment by jkmacc-LANL** [comment]
It sounded to me like @alshedivat was going to merge this into master soon-ish, but it depends on how long you’re willing to wait:-)  If you modify the font color back to the one you like after you rebase, you should be able to choose your color when you resolve conflicts during the next rebase and have it persist after that.

**Comment by christineymshen** [comment]
> It sounded to me like @alshedivat was going to merge this into master soon-ish, but it depends on how long you’re willing to wait:-) If you modify the font color back to the one you like after you rebase, you should be able to choose your color when you resolve conflicts during the next rebase and have it persist after that.

I actually just cloned dev branch into my local and played with it for a while. I explored a bit but didn't manage to change the font color to my current one... I'm not familiar with CSS and HTML so... I'm thinking not to rebase it for now~~~ I'm hoping to maintain this with minimal efforts on formatting... But I had a look at the codes of the dev branch, it seems the whole structure is more streamlined~~

**Comment by jkmacc-LANL** [comment]
Yeah, I have to learn more about CSS than I care to when I use Jekyll:-)
