### ISSUE TITLE
The tag bibliography on line 3 in _pages/publications.md is not a recognized Liquid tag

### ISSUE THREAD

**Issue by grjd** [alshedivat/al-folio#95]
I can build page locally but when I try to deploy at github I get this error:

Your site is having problems building: The tag bibliography on line 3 in _pages/publications.md is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.

On line 3 _pages/publications.md there is:
permalink: /publications/

**Comment by alshedivat** [comment]
The theme comes with a script for deploying to GitHub (see `bin/deploy`). Please follow instructions in [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide. If you have more related questions, please ask on [gitter chat](https://gitter.im/alshedivat/al-folio). Thanks.
