### ISSUE TITLE
Error at deploy website stage

### ISSUE THREAD

**Issue by EnriqueCerv** [alshedivat/al-folio#962]
I get 
**'Error: Process completed with exit code 1.'**
at the deployment stage when pushing the changes. Full error message at the bottom. 

Various changes from the original template:
Renamed deploy.yml to deploy-stage.yml as a linting program had issues with the properties of 'name', 'on', 'jobs' tasks in the original. Note the error at 'Deploy Website' stays the same regardless of the name deploy-stage.yml or deploy.yml.

I have tried fixes in #208 but they did not help.
Renaming the branches as per #209 messed up my branches and not sure why :/
Also looked at #321 but could not see if this was the issue. 

Im using ruby 3.1.2p20, jekyll 4.2.2, bundler 2.3.24. 
OS is Windows 11, chrome version 106.0.5249.119
 

Run yes | bash bin/deploy --verbose  --src master --deploy gh-pages
+shift
+[[ [4](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:5) > 0 ]]
+key=--src
+case $key in
+SRC_BRANCH=master
+shift
+shift
+[[ 2 > 0 ]]
+key=--deploy
+case $key in
+DEPLOY_BRANCH=gh-pages
+shift
+shift
+[[ 0 > 0 ]]
+set -e
+echo Deploying...
Deploying...
+echo 'Source branch: master'
Source branch: master
Deploy branch: gh-pages
+echo 'Deploy branch: gh-pages'
+read -r -p 'Do you want to proceed? [y/N] ' response
+[[ ! y =~ ^([yY][eE][sS]|[yY])+$ ]]
+git diff-index --quiet HEAD --
++ git ls-files --exclude-standard --others
+test -z ''
++ git branch
++ grep master
++ tr ' ' '\n'
++ tail -1
+'[' master ']'
+git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
++ grep gh-pages
++ git branch
+'[' ']'
+git checkout -b gh-pages
Switched to a new branch 'gh-pages'
+export JEKYLL_ENV=production
+JEKYLL_ENV=production
+bundle exec jekyll build
bundler: failed to load command: jekyll (/home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll)
/home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/gems/wdm-0.1.1/lib/wdm.rb:4:in `rescue in <top (required)>':     Can't load WDM! (LoadError)
    
    WDM is not supported on your system. For a cross-platform alternative,
    we recommend using Listen: http://github.com/guard/listen
	from /home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/gems/wdm-0.1.1/lib/wdm.rb:1:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:66:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:61:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:[5](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:6)0:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.2/x[6](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:7)4/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler.rb:1[7](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:8)4:in `require'
	from /home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	from /home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/exe/jekyll:11:in `<top (required)>'
	from /home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `load'
	from /home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli/exec.rb:2[8](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:9):in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli.rb:474:in `exec'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:3[9](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:10)2:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:49:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:37:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `<main>'
/home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/gems/wdm-0.1.1/lib/wdm.rb:2:in `require': cannot load such file -- wdm_ext (LoadError)
	from /home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/gems/wdm-0.1.1/lib/wdm.rb:2:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:66:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:61:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler.rb:174:in `require'
	from /home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	from /home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.1/exe/jekyll:[11](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:12):in `<top (required)>'
	from /home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `load'
	from /home/runner/work/EnriqueCerv.github.io/EnriqueCerv.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli.rb:474:in `exec'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:[12](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:13)7:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.[22](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:23)/libexec/bundle:49:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:37:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:[23](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:24):in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x[64](https://github.com/EnriqueCerv/EnriqueCerv.github.io/actions/runs/3334469303/jobs/5517460979#step:6:65)/bin/bundle:23:in `<main>'
yes: standard output: Broken pipe
Error: Process completed with exit code 1.

**Comment by JanPastorek** [comment]
I got this as well
