### ISSUE TITLE
Liquid Exception: Liquid syntax error Unknown tag 'bibliography' included  (Liquid::SyntaxError)

### ISSUE THREAD

**Issue by amirmohan** [alshedivat/al-folio#964]
Hi! i am really interested in this website. While the website works locally on my computer it does not work on github.io with the following error:

**Liquid Exception: Liquid syntax error (/github/workspace/_includes/selected_papers.html line 4): Unknown tag 'bibliography' included in /_layouts/about.html**
/usr/local/bundle/gems/liquid-4.0.3/lib/liquid/document.rb:23:in `unknown_tag': Liquid syntax error (/github/workspace/_includes/selected_papers.html line 4): Unknown tag 'bibliography' included  (Liquid::SyntaxError)

I am sure that the url and baseurl have the correct inputs (.github.io and blank respectively). Any help is appreciated.

**Comment by amirmohan** [comment]
solved using deploy!

**Comment by jonvis23** [comment]
how?
