### ISSUE TITLE
Liquid Exception: Stack Level Too Deep

### ISSUE THREAD

**Issue by electronsandstuff** [alshedivat/al-folio#965]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Hey folks, thanks for this project! Everything looks amazing and it fills a need I've had for a bit.

I am pretty new to Jekyll and to docker so I'm not sure if I'm just doing something wrong or if there's a bug out there. Anyways, my issue is that when I follow the instructions for local setup on windows using docker, Jekyll fails while building the site with the following error. I have cut out some of the error message for brevity. The line that says "stack level too deep" is repeated something like 50 times. I was able to successfully build the site by deleting the file `_posts/2021-07-04-diagrams.md`.

```
chris@DESKTOP-RHS7O0D:/mnt/c/Users/Chris/Dropbox/Website/personal-site$ ./bin/dockerhub_run.sh
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
"Fetching external posts from medium.com:"
"...fetching https://medium.com/@al-folio/displaying-external-posts-on-your-al-folio-blog-b60a1d241a0a?source=rss-17feae71c3c4------2"
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
       Jekyll Feed: Generating feed for posts
       Imagemagick: Searching files in /srv/jekyll/assets/img/
       Imagemagick: Adding static file /srv/jekyll/_site/assets/img/1-480.webp
       ...
       Imagemagick: Adding static file /srv/jekyll/_site/assets/img/publications-screenshot-1400.webp
       Imagemagick: Generated 0 file(s)
  Liquid Exception: stack level too deep in /srv/jekyll/_posts/2021-07-04-diagrams.md/#excerpt
  Liquid Exception: stack level too deep in /srv/jekyll/_posts/2021-07-04-diagrams.md/#excerpt
  Liquid Exception: stack level too deep in /srv/jekyll/_posts/2021-07-04-diagrams.md/#excerpt
  ...
  Liquid Exception: stack level too deep in /srv/jekyll/_posts/2021-07-04-diagrams.md/#excerpt
  Liquid Exception: stack level too deep in /srv/jekyll/_posts/2021-07-04-diagrams.md
                    ------------------------------------------------
      Jekyll 4.3.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/usr/gem/gems/jekyll-4.3.1/lib/jekyll/frontmatter_defaults.rb:63:in `find': stack level too deep (SystemStackError)
        from /usr/gem/gems/jekyll-4.3.1/lib/jekyll/document.rb:58:in `block in initialize'
        from /usr/gem/gems/jekyll-4.3.1/lib/jekyll/drops/excerpt_drop.rb:19:in `name'
        from /usr/gem/gems/jekyll-4.3.1/lib/jekyll/drops/drop.rb:128:in `public_send'
        from /usr/gem/gems/jekyll-4.3.1/lib/jekyll/drops/drop.rb:128:in `[]'
        from /usr/gem/gems/jekyll-4.3.1/lib/jekyll/drops/drop.rb:205:in `block in to_h'
        from /usr/gem/gems/jekyll-4.3.1/lib/jekyll/drops/drop.rb:204:in `each'
        from /usr/gem/gems/jekyll-4.3.1/lib/jekyll/drops/drop.rb:204:in `each_with_object'
        from /usr/gem/gems/jekyll-4.3.1/lib/jekyll/drops/drop.rb:204:in `to_h'
         ... 9391 levels...
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/exe/bundler:4:in `load'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.23/exe/bundler:4:in `<top (required)>'
        from /usr/local/bin/bundler:25:in `load'
        from /usr/local/bin/bundler:25:in `<main>'
```

**To Reproduce**
1. Clone the repo
2. Run bin/dockerhub_run.sh on windows subsystem for linux

**Expected behavior**
The website should build and be served locally.

**System (please complete the following information):**
 - OS: Windows 10
 - Browser (and its version) Chrome
 - Jekyll version 4.3.1
- Ruby version 3.1.0

**Comment by ztangent** [comment]
I also ran into this issue, which seems like it is due to Jekyll not being able to render diagrams correctly. I removed the following lines and it seems to work now:

https://github.com/alshedivat/al-folio/blob/7172df0877a30b12feea4b6c41adfdd9da7951c0/_posts/2021-07-04-diagrams.md?plain=1#L16-L43

**Comment by pourmand1376** [comment]
This is an odd issue. If I test this docker image in `github codespaces`, there would be no problem at all. But testing it with `Windows` causes this issue. 

This can be temporarily solved with removing this diagrams file but that's not a solution.
