### ISSUE TITLE
Bundle exec jekyll serve

### ISSUE THREAD

**Issue by bsflll** [alshedivat/al-folio#985]
**Acknowledge the following**
- [ ] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [ ] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [ ] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Browser (and its version) [e.g. chrome, safari]
 - Jekyll version [e.g. 3.8.7]
- Ruby version [e.g. 2.6.5]

**Additional context**

**Comment by bsflll** [comment]
(base) christina@christinadeMacBook-Pro bsflll.github.io % bundle install   
Using concurrent-ruby 1.1.10
Using i18n 1.12.0
Using minitest 5.16.3
Using tzinfo 2.0.5
Using activesupport 7.0.4
Using public_suffix 5.0.0
Using addressable 2.8.1
Using latex-decode 0.4.0
Using bibtex-ruby 6.0.0
Using bundler 2.3.7
Using namae 1.1.1
Using citeproc 1.0.10
Using rexml 3.2.5
Using csl 1.6.0
Using citeproc-ruby 1.1.14
Using colorator 1.1.0
Using crass 1.0.6
Using csl-styles 1.0.1.11
Using cssminify2 2.0.1
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using em-websocket 0.5.3
Using execjs 2.8.1
Using racc 1.6.0
Using nokogiri 1.13.9 (arm64-darwin)
Using loofah 2.19.0
Using sax-machine 1.3.2
Using feedjira 3.2.2
Using ffi 1.15.5
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Using html-pipeline 2.14.3
Using htmlcompressor 0.4.0
Using mime-types-data 3.2022.0105
Using mime-types 3.4.1
Using multi_xml 0.6.0
Using httparty 0.20.0
Using sassc 2.4.0
Using jekyll-sass-converter 2.2.0
Using rb-fsevent 0.11.2
Using rb-inotify 0.10.1
Using listen 3.7.1
Using jekyll-watch 2.2.1
Using kramdown 2.4.0
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.3
Using mercenary 0.4.0
Using pathutil 0.16.2
Using rouge 4.0.0
Using safe_yaml 1.0.5
Using unicode-display_width 2.3.0
Using terminal-table 3.0.2
Using webrick 1.7.0
Using jekyll 4.3.1
Using jekyll-archives 2.2.1
Using jekyll-diagrams 0.10.0
Using jekyll-email-protect 1.1.0
Using jekyll-feed 0.17.0
Using jekyll-imagemagick 1.4.0
Using json 2.6.2
Using json-minify 0.0.3
Using uglifier 4.2.0
Using jekyll-minifier 0.1.10
Using jekyll-paginate-v2 3.0.0
Using jekyll-scholar 7.1.1
Using jekyll-sitemap 1.4.0
Using jekyll-target-blank 2.0.0
Using jekyll-twitter-plugin 2.1.0
Using jemoji 0.12.0
Using libv8-node 16.10.0.0 (arm64-darwin)
Using mini_racer 0.6.3
Using unicode_utils 1.4.0
Bundle complete! 18 Gemfile dependencies, 72 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
(base) christina@christinadeMacBook-Pro bsflll.github.io % bundle exec jekyll serve
Configuration file: /Users/christina/Desktop/bsflll.github.io/_config.yml
            Source: /Users/christina/Desktop/bsflll.github.io
       Destination: /Users/christina/Desktop/bsflll.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
"Fetching external posts from medium.com:"
                    ------------------------------------------------
      Jekyll 4.3.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Failed to open TCP connection to medium.com:443 (No route to host - connect(2) for [2001::1f0d:490c]:443) (Errno::EHOSTUNREACH)
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:137:in `connect'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:227:in `each'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:227:in `foreach'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:632:in `tcp'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:998:in `connect'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:965:in `start'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:1530:in `request'
 from /Users/christina/.gem/ruby/3.1.2/gems/httparty-0.20.0/lib/httparty/request.rb:152:in `perform'
 from /Users/christina/.gem/ruby/3.1.2/gems/httparty-0.20.0/lib/httparty.rb:613:in `perform_request'
 from /Users/christina/.gem/ruby/3.1.2/gems/httparty-0.20.0/lib/httparty.rb:527:in `get'
 from /Users/christina/.gem/ruby/3.1.2/gems/httparty-0.20.0/lib/httparty.rb:646:in `get'
 from /Users/christina/Desktop/bsflll.github.io/_plugins/external-posts.rb:14:in `block in generate'
 from /Users/christina/Desktop/bsflll.github.io/_plugins/external-posts.rb:12:in `each'
 from /Users/christina/Desktop/bsflll.github.io/_plugins/external-posts.rb:12:in `generate'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/site.rb:193:in `block in generate'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/site.rb:191:in `each'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/site.rb:191:in `generate'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/site.rb:79:in `process'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
 from /Users/christina/.gem/ruby/3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
 from /Users/christina/.gem/ruby/3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
 from /Users/christina/.gem/ruby/3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
 from /Users/christina/.gem/ruby/3.1.2/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
 from /Users/christina/.gem/ruby/3.1.2/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
 from /Users/christina/.gem/ruby/3.1.2/bin/jekyll:25:in `load'
 from /Users/christina/.gem/ruby/3.1.2/bin/jekyll:25:in `<top (required)>'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:484:in `exec'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
 from /Users/christina/.gem/ruby/3.1.2/bin/bundle:25:in `load'
 from /Users/christina/.gem/ruby/3.1.2/bin/bundle:25:in `<main>'
/Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': No route to host - connect(2) for [2001::1f0d:490c]:443 (Errno::EHOSTUNREACH)
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:137:in `connect'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:227:in `each'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:227:in `foreach'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:632:in `tcp'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:998:in `connect'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:965:in `start'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:1530:in `request'
 from /Users/christina/.gem/ruby/3.1.2/gems/httparty-0.20.0/lib/httparty/request.rb:152:in `perform'
 from /Users/christina/.gem/ruby/3.1.2/gems/httparty-0.20.0/lib/httparty.rb:613:in `perform_request'
 from /Users/christina/.gem/ruby/3.1.2/gems/httparty-0.20.0/lib/httparty.rb:527:in `get'
 from /Users/christina/.gem/ruby/3.1.2/gems/httparty-0.20.0/lib/httparty.rb:646:in `get'
 from /Users/christina/Desktop/bsflll.github.io/_plugins/external-posts.rb:14:in `block in generate'
 from /Users/christina/Desktop/bsflll.github.io/_plugins/external-posts.rb:12:in `each'
 from /Users/christina/Desktop/bsflll.github.io/_plugins/external-posts.rb:12:in `generate'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/site.rb:193:in `block in generate'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/site.rb:191:in `each'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/site.rb:191:in `generate'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/site.rb:79:in `process'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
 from /Users/christina/.gem/ruby/3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
 from /Users/christina/.gem/ruby/3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
 from /Users/christina/.gem/ruby/3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
 from /Users/christina/.gem/ruby/3.1.2/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
 from /Users/christina/.gem/ruby/3.1.2/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
 from /Users/christina/.gem/ruby/3.1.2/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
 from /Users/christina/.gem/ruby/3.1.2/bin/jekyll:25:in `load'
 from /Users/christina/.gem/ruby/3.1.2/bin/jekyll:25:in `<top (required)>'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:484:in `exec'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
 from /Users/christina/.rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
 from /Users/christina/.gem/ruby/3.1.2/bin/bundle:25:in `load'
 from /Users/christina/.gem/ruby/3.1.2/bin/bundle:25:in `<main>'


when I wrote "bundle exec jekyll serve" in my terminal it does not work and the thing above came out.

**Comment by mxbuschi** [comment]
I am experiencing the same issue (Windows 10, and I followed the problem solving steps for another issue: https://github.com/alshedivat/al-folio/issues/691)

**Comment by pourmand1376** [comment]
For now, Just comment out these lines and your problem would be gone. 

https://github.com/alshedivat/al-folio/blob/69e013b9a0f0418af0a8a3c921d3a0f283a8bdb1/_config.yml#L149-L151

**Comment by scarlettmluis** [comment]
> For now, Just comment out these lines and your problem would be gone.
> 
> https://github.com/alshedivat/al-folio/blob/69e013b9a0f0418af0a8a3c921d3a0f283a8bdb1/_config.yml#L149-L151
> 
> I think we have to make it commented by default.

Thanks for the recommendation @pourmand1376. I still show this error on my command prompt. Do you know what is the solution for this error?
Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
       Imagemagick: Disabled in site.config
       Jekyll Feed: Generating feed for posts
  Liquid Exception: undefined method `tainted?' for "2015":String in C:/Users/scarl/scarlettmluis.github.io/_layouts/post.html
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?' for "2015":String (NoMethodError)

      return unless obj.tainted?
                       ^^^^^^^^^
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:89:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/tags/assign.rb:26:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:129:in `render_liquid'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:192:in `render_layout'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:161:in `place_in_layouts'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:93:in `render_document'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:63:in `run'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:578:in `render_regenerated'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:563:in `block (2 levels) in render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:562:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:562:in `block in render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:561:in `each_value'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:561:in `render_docs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:210:in `render'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:80:in `process'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby32-x64/bin/jekyll:32:in `load'
        from C:/Ruby32-x64/bin/jekyll:32:in `<main>'

**Comment by pourmand1376** [comment]
I do not know anything about that error. Can you also test the docker image to see if it has the same error?

**Comment by jonvis23** [comment]
I'm also getting same error as  @scarlettmluis

**Comment by Xiangyue-Zhang** [comment]
> 

I also have the same headache problem.Have you sloved it yet?It drives me crazy.

**Comment by Xiangyue-Zhang** [comment]
@scarlettmluis @mxbusch @jonvis23  I'm still stuck here, U got any idea?

**Comment by Xiangyue-Zhang** [comment]
> For now, Just comment out these lines and your problem would be gone.
> 
> https://github.com/alshedivat/al-folio/blob/69e013b9a0f0418af0a8a3c921d3a0f283a8bdb1/_config.yml#L149-L151
> 
> I think we have to make it commented by default.

Thanks for the tips,but I'm still stuck here.I got the same problem just like @scarlettmluis .Do you have any idea about the issue?

**Comment by pourmand1376** [comment]
> > For now, Just comment out these lines and your problem would be gone.
> > https://github.com/alshedivat/al-folio/blob/69e013b9a0f0418af0a8a3c921d3a0f283a8bdb1/_config.yml#L149-L151
> > 
> > I think we have to make it commented by default.
> 
> Thanks for the tips,but I'm still stuck here.I got the same problem just like @scarlettmluis .Do you have any idea about the issue?

Have you tested the docker image after removing the lines?

**Comment by Xiangyue-Zhang** [comment]
> > > For now, Just comment out these lines and your problem would be gone.
> > > https://github.com/alshedivat/al-folio/blob/69e013b9a0f0418af0a8a3c921d3a0f283a8bdb1/_config.yml#L149-L151
> > > 
> > > I think we have to make it commented by default.
> > 
> > Thanks for the tips,but I'm still stuck here.I got the same problem just like @scarlettmluis .Do you have any idea about the issue?
> 
> Have you tested the docker image after removing the lines?

I've tried on my Windows.but it didn't work.And it's kinda weird because it worked on Ubuntu system.But I'm still trying to fix it on Windows.Do u have any idea?

**Comment by adityajain93** [comment]
> I do not know anything about that error. Can you also test the docker image to see if it has the same error?

Hey, I'm using the docker image on Mac and getting the same errors

**Comment by li-yang23** [comment]
> 

i'm following the local setup on Mac and getting the same errors

**Comment by pourmand1376** [comment]
> > 
> 
> i'm following the local setup on Mac and getting the same errors

Are you using docker installation? Local setup can be buggy and frustrating. 

If you are using docker, please share your stack trace (bug details reported on your terminal).

**Comment by li-yang23** [comment]
> 



> > i'm following the local setup on Mac and getting the same errors
> 
> Are you using docker installation? Local setup can be buggy and frustrating.
> 
> If you are using docker, please share your stack trace (bug details reported on your terminal).

I comment out the external resources, problem solved

**Comment by pourmand1376** [comment]
Okay. Thanks.
