### ISSUE TITLE
Deployment failure on github

### ISSUE THREAD

**Issue by Toytiny** [alshedivat/al-folio#997]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Browser (and its version) [e.g. chrome, safari]
 - Jekyll version [e.g. 3.8.7]
- Ruby version [e.g. 2.6.5]

**Additional context**

I worked on setting up this project for the whole day but cannot make it.
I can successfully running the project on my local machine but when I comment and push my modification to Github, there is always something wrong in the 'Action'. As a result, I cannot deploy.

One example is: 

  Liquid Exception: Liquid syntax error (line 5): Unknown tag 'twitter' in /github/workspace/_posts/2020-09-28-twitter.md
/usr/local/bundle/gems/liquid-4.0.3/lib/liquid/document.rb:23:in `unknown_tag': Liquid syntax error (line 5): Unknown tag 'twitter' (Liquid::SyntaxError)
	from /usr/local/bundle/gems/liquid-4.0.3/lib/liquid/document.rb:11:in `block in parse'
	from /usr/local/bundle/gems/liquid-4.0.3/lib/liquid/block_body.rb:32:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.3/lib/liquid/document.rb:10:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.3/lib/liquid/document.rb:5:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.3/lib/liquid/template.rb:132:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.3/lib/liquid/template.rb:116:in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:121:in `render_liquid'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:79:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:463:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:463:in `block in render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:462:in `each_value'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:462:in `render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:191:in `render'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
Globbed Scope Path: assets/js/dark_mode.js
         Rendering: _posts/2020-09-28-twitter.md
  Pre-Render Hooks: _posts/2020-09-28-twitter.md
  Rendering Liquid: _posts/2020-09-28-twitter.md
github-pages 227 | Error:  Liquid syntax error (line 5): Unknown tag 'twitter'

Besides when I delete the 2020-09-29-twitter.md, there will be:

github-pages 227 | Error:  Liquid syntax error (/github/workspace/_includes/selected_papers.html line 4): Unknown tag 'bibliography' included.

I really want to know what's happening and how to fix them. I have tried both the docker and local machine way on my Windows system but both not work.

**Comment by qomhmd** [comment]
Per https://github.com/alshedivat/al-folio#deployment under the subtitle "To enable automatic deployment":
1. Go to your project > Settings > Pages
2. Under "Build and deployment" set `source` to `deploy from a branch` and `branch` to `gh-pages`

**Comment by panichem** [comment]
I am running into a very similar issue. 

The error I am running into is: Liquid syntax error (line 6): Unknown tag 'bibliography'

I don't think qomhmd's answer is relevant here, as this error occurs during the pages build workflow, which is a precondition for creating the gh-pages folder in the first place

**Comment by phvmous** [comment]
I am seeing this bug as well when deploying a fresh fork after configuring the _config.yml.

**Comment by NickvashKani** [comment]
I am running into the exact same issue. However, I am trying to deploy from the master branch instead of the gh-pages branch. What is the difference between the two?

**Comment by NickvashKani** [comment]
Ok so that was the issue. But I am still confused about the interaction between the master and gh-pages branch. In other jekyll websites I've built, this structure of one branch populating another didn't really exist. Can someone help me figure out how this works in ai-folio and why? 

PS. I love the template, and I'd really like to find out more about how it works and maybe contribute.

**Comment by lch32111** [comment]
In my case, I changed the SRC_BRANCH name from "master" to "main" on the 'bin/deploy' file. Then, it starts to deploy well.

@qomhmd 
I'd like to recommend the contributors adds this point on the deployment section, because the initial branch name of the repositories created nowadays is main.

**Comment by moha23** [comment]
Tried pretty much all the solutions posted here, deployment fails for fresh forks. The error for me is :

`github-pages 227 | Error:  Liquid syntax error (line 5): Unknown tag 'twitter'`

**Comment by josumsc** [comment]
Still the same issue with the unknown tag 'twitter' for me too

**Comment by rohandebsarkar** [comment]
Follow these steps: https://github.com/alshedivat/al-folio/discussions/864#discussioncomment-3543060

**Comment by moha23** [comment]
Does not work @rohandebsarkar, tried all the solutions I could find in the issues section. You can try it out with a fresh fork, something probably changed on github side.

**Comment by rohandebsarkar** [comment]
@moha23 Can you give a link to your repository?

**Comment by rohandebsarkar** [comment]
@josumsc go to your repository settings. In the actions tab under workflow permissions enable read and write permissions and save it. Push to your repo again to check if it works.

**Comment by josumsc** [comment]
@rohandebsarkar thank you very much that was the problem 👏🏼

**Comment by hkof** [comment]
As @rohandebsarkar mentioned, you need to enable read & write permission under Action -> General -> Workflow permissions. Wait for a few minutes and let the action complete, then in the Settings of your repository, in the Pages section, set the branch to gh-pages.

**Comment by SylvanSun** [comment]
@rohandebsarkar Thanks a lot, literally life saver !

**Comment by tanmayyb** [comment]
So I tried all these solutions but it was not working for me. I forked the repo again and followed the instructions in the manual + from these discussion posts. Eventually what worked for me was changing the name of my repository from <user name>.github.io to just portfolio. Everything just built from there.

**Comment by JohnDoRight** [comment]
Thank you, tanmayyb! Renaming to portfolio (I wonder if any other name would work too) worked. After successful build/deploy now I could change source branch to gh-pages, have read/write permissions actually work, and do actual updates!

**Comment by tanmayyb** [comment]
ofc! I think the issue is having the repo named to <your-user-name>.github.io. This causes issues with the URL, since the github page url is <your-user-name>.github.io/<your-repo's-name>. This should be made a little clearer in the README.md which asks you to name your repo in the following format: <your-user-name>.github.io

**Comment by gubazoltan** [comment]
It would be nice to create a comment where someone explicitly mentions all the required steps and not "the last step".

**Comment by eleonorerouault** [comment]
Agree with all previous comments, no solution found at this time
